Repository conan-io/conan-center-index, pull requests merged in 2020-05, with the labels that each got.

#1474 add nuklear/4.02.1
  recipes/nuklear/all/conandata.yml
  recipes/nuklear/config.yml
Labels: Bump version

#1465 meson 0.54.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#1286 Bump PEGTL version to 2.8.2
  recipes/taocpp-pegtl/all/conandata.yml
  recipes/taocpp-pegtl/config.yml
Labels: Bump version

#1569 Add sqlpp11 0.59
  recipes/sqlpp11/all/conandata.yml
  recipes/sqlpp11/config.yml
Labels: Bump version

#1590 adding fmt/6.2.1
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#1588 Add libpqxx/7.0.7
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#1486 feat: add ctest/1.0.0
  recipes/bvdberg-ctest/all/conandata.yml
  recipes/bvdberg-ctest/all/conanfile.py
  recipes/bvdberg-ctest/all/test_package/CMakeLists.txt
  recipes/bvdberg-ctest/all/test_package/conanfile.py
  recipes/bvdberg-ctest/all/test_package/test_package.c
  recipes/bvdberg-ctest/config.yml
Labels: infrastructure

#1646 meson 0.54.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#1523 Add abseil/20200225.2
  recipes/abseil/all/conandata.yml
  recipes/abseil/config.yml
Labels: Bump version

#1521 Add asio/1.16.1
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#1666 add packio/1.2.1
  recipes/packio/all/conandata.yml
  recipes/packio/config.yml
Labels: Bump version

#1671 Add libpqxx/7.1.1
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#1650 Add approvaltests.cpp 8.7.0
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#1665 libmbus: bump to latest master
  recipes/libmbus/all/conandata.yml
  recipes/libmbus/config.yml
Labels: Bump version

#1719 Add doctest/2.3.8
  recipes/doctest/2.x.x/conandata.yml
  recipes/doctest/config.yml
Labels: Bump version

#1712 giflib: add config.yml + msys2 as build requirements + minor fixes
  recipes/giflib/all/conandata.yml
  recipes/giflib/all/conanfile.py
  recipes/giflib/all/gif_lib.h
  recipes/giflib/all/test_package/CMakeLists.txt
  recipes/giflib/all/test_package/conanfile.py
  recipes/giflib/all/test_package/test_package.c
  recipes/giflib/all/unistd.h
  recipes/giflib/config.yml
Labels: Failed
