Repository conan-io/conan-center-index, pull requests merged in 2020-02, with the labels that each got.

#433 Add libffi/3.3
  recipes/libffi/3.2.x/conandata.yml
  recipes/libffi/3.2.x/conanfile.py
  recipes/libffi/3.2.x/test_package/CMakeLists.txt
  recipes/libffi/3.2.x/test_package/conanfile.py
  recipes/libffi/3.2.x/test_package/test_package.cpp
  recipes/libffi/3.3.x/conandata.yml
  recipes/libffi/3.3.x/conanfile.py
  recipes/libffi/3.3.x/test_package/CMakeLists.txt
  recipes/libffi/3.3.x/test_package/conanfile.py
  recipes/libffi/3.3.x/test_package/test_package.cpp
  recipes/libffi/config.yml
Labels: Failed

#777 Revert "Add libffi/3.3"
  recipes/libffi/3.3.x/conandata.yml
  recipes/libffi/3.3.x/conanfile.py
  recipes/libffi/3.3.x/test_package/CMakeLists.txt
  recipes/libffi/3.3.x/test_package/conanfile.py
  recipes/libffi/3.3.x/test_package/test_package.cpp
  recipes/libffi/all/conandata.yml
  recipes/libffi/all/conanfile.py
  recipes/libffi/all/test_package/CMakeLists.txt
  recipes/libffi/all/test_package/conanfile.py
  recipes/libffi/all/test_package/test_package.cpp
  recipes/libffi/config.yml
Labels: Failed, infrastructure

#779 [libffi] Fix hook
  recipes/libffi/all/conanfile.py
Labels: infrastructure
