Repository conan-io/conan-center-index, pull requests merged in 2020-11, with the labels that each got.

#3363 add fontconfig/2.13.92
  recipes/fontconfig/all/conandata.yml
  recipes/fontconfig/config.yml
Labels: Bump version

#3372 bump catch2/2.13.3
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#3371 add libmount/2.36
  recipes/libmount/all/conandata.yml
  recipes/libmount/config.yml
Labels: Bump version

#3370 add libalsa/1.2.4
  recipes/libalsa/all/conandata.yml
  recipes/libalsa/config.yml
Labels: Bump version

#3368 Add span-lite/0.8.0
  recipes/span-lite/all/conandata.yml
  recipes/span-lite/config.yml
Labels: Bump version

#3389 Bump eigen/3.3.8
  recipes/eigen/all/conandata.yml
  recipes/eigen/config.yml
Labels: Bump version

#3400 add cpp-peglib/0.1.13
  recipes/cpp-peglib/all/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#3399 add fmt/7.1.1
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#3398 add cpp-httplib/0.7.12
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#3396 add re2/20201101
  recipes/re2/all/conandata.yml
  recipes/re2/config.yml
Labels: Bump version

#3414 bump fmt/7.1.2
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#3406 Add SI 2.0.0
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#3407 Add span-lite/0.8.1
  recipes/span-lite/all/conandata.yml
  recipes/span-lite/config.yml
Labels: Bump version

#3418 Add approvaltests.cpp 10.5.0
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#3423 Remove email to request access to the EAP
  docs/how_to_add_packages.md
Labels: Docs

#3448 ctre: version bump to 3.3.2
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#3468 Add .gitattributes
  .gitattributes
Labels: Failed

#3460 add botan 2.17.1
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#3473 Change line endings to LF
  recipes/clipp/all/conandata.yml
  recipes/clipp/all/conanfile.py
  recipes/clipp/all/test_package/CMakeLists.txt
  recipes/clipp/all/test_package/conanfile.py
  recipes/clipp/all/test_package/test_package.cpp
  recipes/clipp/config.yml
  recipes/clipper/all/CMakeLists.txt
  recipes/clipper/all/conandata.yml
  recipes/clipper/all/test_package/CMakeLists.txt
  recipes/clipper/all/test_package/conanfile.py
  recipes/clipper/all/test_package/test_package.cpp
  recipes/clipper/config.yml
  recipes/irrxml/all/patches/1.2/irrtypes_debug_vs.patch
  recipes/libiberty/all/test_package/conanfile.py
  recipes/nanobench/config.yml
  recipes/pfr/config.yml
  recipes/quickfix/all/patches/0001-Fix-build-for-C-17-replace-throw-.-with-EXCEPT.patch
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
  recipes/xmlsec/all/test_package/rsakey.pem
  recipes/xmlsec/all/test_package/sign1-tmpl.xml
Labels: Failed

#3457 Add variant-lite/2.0.0
  recipes/variant-lite/all/conandata.yml
  recipes/variant-lite/config.yml
Labels: Bump version

#3471 add bitsery/5.2.0
  recipes/bitsery/all/conandata.yml
  recipes/bitsery/config.yml
Labels: Bump version

#3490 Add optional-lite/3.3.0
  recipes/optional-lite/all/conandata.yml
  recipes/optional-lite/config.yml
Labels: Bump version

#3484 bump librdkafka/1.5.2
  recipes/librdkafka/all/conandata.yml
  recipes/librdkafka/config.yml
Labels: Bump version

#3516 Bump openvr/1.14.15
  recipes/openvr/all/conandata.yml
  recipes/openvr/config.yml
Labels: Bump version

#3513 Bump ags/6.0
  recipes/ags/all/conandata.yml
  recipes/ags/config.yml
Labels: Bump version

#3525 libpq: add version 13.1
  recipes/libpq/all/conandata.yml
  recipes/libpq/config.yml
Labels: Bump version

#3568 add enet/1.3.17
  recipes/enet/all/conandata.yml
  recipes/enet/config.yml
Labels: Bump version

#3553 Add expected-lite/0.5.0
  recipes/expected-lite/all/conandata.yml
  recipes/expected-lite/config.yml
Labels: Bump version

#3572 packio: add version 2.0.1
  recipes/packio/all/conandata.yml
  recipes/packio/config.yml
Labels: Bump version

#3587 spirv-headers: add version 1.5.4
  recipes/spirv-headers/all/conandata.yml
  recipes/spirv-headers/config.yml
Labels: Bump version

#3586 h3: add version 3.7.1
  recipes/h3/all/conandata.yml
  recipes/h3/config.yml
Labels: Bump version

#3596 Update changelog with Conan 1.31
  docs/changelog.md
Labels: Docs

#3141 How to provide a good recipe
  docs/how_to_add_packages.md
Labels: Docs

#3600 [pybind11] update to pybind11 2.6.1
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#3598 Update changelog 18-November-2020 - 12:58 CEST
  docs/changelog.md
Labels: Docs

#3611 ixwebsocket: add version 10.4.0
  recipes/ixwebsocket/all/conandata.yml
  recipes/ixwebsocket/config.yml
Labels: Bump version

#3613 cmake: add 3.18.5 + 3.19.0
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#3635 bitsery: add version 5.2.1
  recipes/bitsery/all/conandata.yml
  recipes/bitsery/config.yml
Labels: Bump version

#3656 bump cgal/5.1.1
  recipes/cgal/all/conandata.yml
  recipes/cgal/config.yml
Labels: Bump version

#3655 bump openblas/0.3.12
  recipes/openblas/all/conandata.yml
  recipes/openblas/config.yml
Labels: Bump version

#3654 bump libmorton/0.2.6
  recipes/libmorton/all/conandata.yml
  recipes/libmorton/config.yml
Labels: Bump version

#3653 bump cpp-httplib/0.7.15
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#3648 Add optional-lite/3.4.0
  recipes/optional-lite/all/conandata.yml
  recipes/optional-lite/config.yml
Labels: Bump version

#3642 cpp-jwt: add version 1.3
  recipes/cpp-jwt/all/conandata.yml
  recipes/cpp-jwt/config.yml
Labels: Bump version

#3588 Libunwind/1.5.0
  recipes/libunwind/all/conandata.yml
  recipes/libunwind/config.yml
Labels: Bump version

#3677 xkbcommon: add version 1.0.3
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/config.yml
Labels: Bump version

#3673 outcome: add version 2.1.4
  recipes/outcome/all/conandata.yml
  recipes/outcome/config.yml
Labels: Bump version

#3672 opusfile: add version 0.12
  recipes/opusfile/all/conandata.yml
  recipes/opusfile/config.yml
Labels: Bump version

#3682 Add span-lite/0.9.0
  recipes/span-lite/all/conandata.yml
  recipes/span-lite/config.yml
Labels: Bump version

#3680 amqp-cpp: add version 4.3.10
  recipes/amqp-cpp/all/conandata.yml
  recipes/amqp-cpp/config.yml
Labels: Bump version

#3689 utf8proc: add version 2.6.0
  recipes/utf8proc/all/conandata.yml
  recipes/utf8proc/config.yml
Labels: Bump version

#3659 ixwebsocket: add version 11.0.4
  recipes/ixwebsocket/all/conandata.yml
  recipes/ixwebsocket/config.yml
Labels: Bump version

#3698 gcem: add version 1.13.1
  recipes/gcem/all/conandata.yml
  recipes/gcem/config.yml
Labels: Bump version

#3686 add cmake/3.19.1
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#3702 xmlsec: add version 1.2.31
  recipes/xmlsec/all/conandata.yml
  recipes/xmlsec/config.yml
Labels: Bump version

#3712 CI: new release
  docs/changelog.md
Labels: Docs

#3706 cwalk: add version 1.2.5
  recipes/cwalk/all/conandata.yml
  recipes/cwalk/config.yml
Labels: Bump version

#3722 Add any-lite/0.3.0
  recipes/any-lite/all/conandata.yml
  recipes/any-lite/config.yml
Labels: Bump version
