Repository conan-io/conan-center-index, pull requests merged in 2020-12, with the labels that each got.

#3734 tbb: add version 2020.3
  recipes/tbb/all/conandata.yml
  recipes/tbb/config.yml
Labels: Bump version

#3735 vulkan-headers: add version 1.2.162
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#3736 xsimd: add version 7.4.9
  recipes/xsimd/all/conandata.yml
  recipes/xsimd/config.yml
Labels: Bump version

#3703 add stalebot
  .github/stale.yml
Labels: Failed, infrastructure

#3741 add botan/2.17.0
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#3759 magic_enum: add version 0.7.1
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#3749 doctest: add version 2.4.1
  recipes/doctest/2.x.x/conandata.yml
  recipes/doctest/config.yml
Labels: Bump version

#3761 taywee-args: add version 6.2.4
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#3788 robin-hood-hashing: add version 3.9.1
  recipes/robin-hood-hashing/all/conandata.yml
  recipes/robin-hood-hashing/config.yml
Labels: Bump version

#3790 bullet3: add version 3.07
  recipes/bullet3/all/conandata.yml
  recipes/bullet3/config.yml
Labels: Bump version

#3792 structopt: add version 0.1.1
  recipes/structopt/all/conandata.yml
  recipes/structopt/config.yml
Labels: Bump version

#3793 libraw: add version 0.20.2
  recipes/libraw/all/conandata.yml
  recipes/libraw/config.yml
Labels: Bump version

#3796 Version bump for si to version 2.0.1
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#3797 Update quill to version 1.6.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#3798 libwebsockets: add version 4.1.6
  recipes/libwebsockets/all/conandata.yml
  recipes/libwebsockets/config.yml
Labels: Bump version

#3799 ctre: add version 3.3.4
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#3809 jasper: add version 2.0.22
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#3821 Add approvaltests.cpp 10.5.1
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#3819 bump simdjson/0.7.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#3751 sqlite 3.34.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#3827 bump cgltf/1.9
  recipes/cgltf/all/conandata.yml
  recipes/cgltf/config.yml
Labels: Bump version

#3438 Update matio to v1.5.19
  recipes/matio/all/conandata.yml
  recipes/matio/config.yml
Labels: Bump version

#3833 add openssl/1.1.1i
  recipes/openssl/1.x.x/conandata.yml
  recipes/openssl/config.yml
Labels: Bump version

#3838 cppcheck: add version 2.3
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#2097 Add component support to boost using boostdep
  recipes/boost/all/conanfile.py
  recipes/boost/all/dependencies/dependencies-1.69.0.yml
  recipes/boost/all/dependencies/dependencies-1.70.0.yml
  recipes/boost/all/dependencies/dependencies-1.71.0.yml
  recipes/boost/all/dependencies/dependencies-1.72.0.yml
  recipes/boost/all/dependencies/dependencies-1.73.0.yml
  recipes/boost/all/dependencies/dependencies-1.74.0.yml
  recipes/boost/all/rebuild-dependencies.py
  recipes/boost/all/test_package/CMakeLists.txt
  recipes/boost/all/test_package/conanfile.py
  recipes/boost/all/test_package/numpy.cpp
  recipes/boost/all/test_package/python.py
Labels: infrastructure

#3859 bump spdlog/1.8.2
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#3865 bump eigen/3.3.9
  recipes/eigen/all/conandata.yml
  recipes/eigen/config.yml
Labels: Bump version

#3906 Update changelog 14-December-2020
  docs/changelog.md
Labels: Docs

#3925 add protobuf/3.13.0
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#3914 wt: add version 4.5.0
  recipes/wt/all/conandata.yml
  recipes/wt/config.yml
Labels: Bump version

#3941 Add approvaltests.cpp 10.6.0
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#3942 Add libpqxx/7.3.0
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#3944 stlab: add version 1.5.4
  recipes/stlab/all/conandata.yml
  recipes/stlab/config.yml
Labels: Bump version

#3945 outcome: add version 2.1.5
  recipes/outcome/all/conandata.yml
  recipes/outcome/config.yml
Labels: Bump version

#3946 Version for 'si' to bump to 2.0.2
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#3919 add cmake/3.19.2
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#3960 bump zstd/1.4.8
  recipes/zstd/all/conandata.yml
  recipes/zstd/config.yml
Labels: Bump version

#3943 ezc3d: add version 1.3.8
  recipes/ezc3d/all/conandata.yml
  recipes/ezc3d/config.yml
Labels: Bump version

#3955 doctest: update to 2.4.3
  recipes/doctest/2.x.x/conandata.yml
  recipes/doctest/config.yml
Labels: Bump version

#3576 Let's add release notes
  docs/releases.md
Labels: Docs

#3958 nlohmann_json/3.2.0
  recipes/nlohmann_json/all/conandata.yml
  recipes/nlohmann_json/config.yml
Labels: Bump version

#3964 Bump TaoCpp PEGTL 3.1.0
  recipes/taocpp-pegtl/3.x.x/conandata.yml
  recipes/taocpp-pegtl/config.yml
Labels: Bump version

#3970 add botan/2.17.3
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#3980 bump opencv/4.5.1
  recipes/opencv/4.x/conandata.yml
  recipes/opencv/config.yml
Labels: Bump version

#4004 libepoxy: add version 1.5.5
  recipes/libepoxy/all/conandata.yml
  recipes/libepoxy/config.yml
Labels: Bump version

#4011 doctest: add 2.4.4
  recipes/doctest/2.x.x/conandata.yml
  recipes/doctest/config.yml
Labels: Bump version

#3902 [docs] Add sources policy
  docs/README.md
  docs/packaging_policy.md
Labels: Docs

#4015 tomlplusplus/2.3.0
  recipes/tomlplusplus/all/conandata.yml
  recipes/tomlplusplus/config.yml
Labels: Bump version

#4020 bump simdjson/0.7.1
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#4021 bump icu/68.2
  recipes/icu/all/conandata.yml
  recipes/icu/config.yml
Labels: Bump version

#4023 bump jasper/2.0.23
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#4037 Update changelog 29-December-2020
  docs/changelog.md
Labels: Docs

#4026 bump catch2/2.13.4
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#4025 bump magic_enum/0.7.2
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#4033 asio: add version 1.18.1
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#4038 Update changelog 30-December-2020
  docs/changelog.md
Labels: Docs
