Repository conan-io/conan-center-index, pull requests merged in 2020-08, with the labels that each got.

#2393 wt: add 4.4.0
  recipes/wt/all/conandata.yml
  recipes/wt/config.yml
Labels: Bump version

#2384 add re2/20200801
  recipes/re2/all/conandata.yml
  recipes/re2/config.yml
Labels: Bump version

#2409 update cmake , add version 3.18.1
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#2222 cmake: add version 3.16.8
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#2354 Add ms-gsl 3.1.0
  recipes/ms-gsl/all/conandata.yml
  recipes/ms-gsl/config.yml
Labels: Bump version

#2420 add cgltf/1.7
  recipes/cgltf/all/conandata.yml
  recipes/cgltf/config.yml
Labels: Bump version

#2424 add sofa/20200721
  recipes/sofa/all/conandata.yml
  recipes/sofa/config.yml
Labels: Bump version

#2422 add vulkan-headers/1.2.148.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#2429 Add approvaltests.cpp 10.2.0
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#2444 add asio 1.17.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#2435 nlohmann_json: add 3.9.1
  recipes/nlohmann_json/all/conandata.yml
  recipes/nlohmann_json/config.yml
Labels: Bump version

#2455 Add approvaltests.cpp 10.2.1
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#2470 Update changelog
  docs/changelog.md
Labels: Docs

#2425 Fix docs link
  docs/contributing.md
Labels: Docs

#2437 [docs] Virtual version must use cci. as prefix
  docs/faqs.md
Labels: Docs

#2352 Add bx 20200716
  recipes/bx/all/conandata.yml
  recipes/bx/config.yml
Labels: Bump version

#2465 adding fmt/7.0.3
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#2475 glib 2.65.1
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#2430 [documentation] Add info about header-only option behavior
  docs/supported_platforms_and_configurations.md
Labels: Docs

#2481 Update Github template to link to docs folder
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Failed

#2284 Add KB-H048 description
  docs/error_knowledge_base.md
Labels: Docs

#2483 Update changelog: 11-August-2020 - 14:19 CEST
  docs/changelog.md
Labels: Docs

#2484 Add info about VS 2015
  docs/supported_platforms_and_configurations.md
Labels: Docs

#2482 Add TOC to 'docs' folder
  README.md
  docs/README.md
  docs/changelog.md
  docs/code_of_conduct.md
  docs/contributing.md
  docs/error_knowledge_base.md
  docs/faqs.md
  docs/how_to_add_packages.md
  docs/supported_platforms_and_configurations.md
Labels: Docs

#2490 Update changelog: 12-August-2020 - 10:12 CEST
  docs/changelog.md
Labels: Docs

#2387 Add docs: Why not PDB files?
  docs/faqs.md
Labels: Docs

#2492 [docs] Fix link to issue
  docs/faqs.md
Labels: Docs

#2292 gsl-lite: add 0.37.0
  recipes/gsl-lite/all/conandata.yml
  recipes/gsl-lite/config.yml
Labels: Bump version

#2267 [gtest]: add support for components
  recipes/gtest/all/conanfile.py
  recipes/gtest/all/test_package/CMakeLists.txt
  recipes/gtest/all/test_package/conanfile.py
Labels: No Beta user

#2564 Update changelog (17-August-2020)
  docs/changelog.md
Labels: Docs

#2615 Add KB-H050 description
  docs/error_knowledge_base.md
Labels: Docs

#2593 Add KB-H049 to docs
  docs/error_knowledge_base.md
Labels: Docs

#2540 Update quill to version 1.4.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#2547 [blaze] Add recipe for Blaze 3.8
  recipes/blaze/all/conandata.yml
  recipes/blaze/config.yml
Labels: Bump version

#2627 adding restinio/0.6.10
  recipes/restinio/all/conandata.yml
  recipes/restinio/config.yml
Labels: Bump version

#2456 Fix .editorconfig file
  .editorconfig
Labels: Failed

#2640 - add doc for KB-H052
  docs/error_knowledge_base.md
Labels: Docs

#2253 Bump benchmark 1.5.1
  recipes/benchmark/all/conandata.yml
  recipes/benchmark/config.yml
Labels: Bump version
