Repository conan-io/conan-center-index, pull requests merged in 2020-07, with the labels that each got.

#2085 Add tomlplusplus/1.3.3
  recipes/tomlplusplus/all/conandata.yml
  recipes/tomlplusplus/config.yml
Labels: Bump version

#1961 vulkan-headers: add all sdk versions up to 1.2.141.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#2053 Add curl/7.71.0
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#2146 add fmt/7.0.0 + if header only: copy header files only and properly define import target
  recipes/fmt/all/conandata.yml
  recipes/fmt/all/conanfile.py
  recipes/fmt/all/test_package/CMakeLists.txt
  recipes/fmt/all/test_package/conanfile.py
  recipes/fmt/config.yml
Labels: infrastructure

#2141 adding catch2/2.12.4
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#2136 add cpp-peglib/0.1.12
  recipes/cpp-peglib/all/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#2185 libselinux/3.1
  recipes/libselinux/all/conandata.yml
  recipes/libselinux/config.yml
Labels: Bump version

#2186 Add approvaltests.cpp 10.1.2
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#2192 Add fruit 3.6.0
  recipes/fruit/all/conandata.yml
  recipes/fruit/all/patches/0002-remove-cmake-extra-target-3.5.0.patch
  recipes/fruit/all/patches/0002-remove-cmake-extra-target-3.6.0.patch
  recipes/fruit/config.yml
Labels: Bump version

#2193 adding catch2/2.13.0
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#2194 meson 0.55.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#2124 [WIKI] Why not x86
  docs/faqs.md
Labels: Docs

#1931 add spirv-tools/2020.3 + cmake components + pkg_config name + propagate C++ lib for C API
  recipes/spirv-tools/all/conandata.yml
  recipes/spirv-tools/all/conanfile.py
  recipes/spirv-tools/all/test_package/CMakeLists.txt
  recipes/spirv-tools/config.yml
Labels: blocked, infrastructure

#2238 adding toml++ v2.0.0
  recipes/tomlplusplus/all/conandata.yml
  recipes/tomlplusplus/config.yml
Labels: Bump version

#2269 Add Msys2 20200517
  recipes/msys2/all/conandata.yml
  recipes/msys2/config.yml
Labels: Bump version

#2265 Move Wiki to Docs
  README.md
  docs/changelog.md
  docs/contributing.md
  docs/error_knowledge_base.md
  docs/faqs.md
  docs/how_to_add_packages.md
  docs/supported_platforms_and_configurations.md
Labels: Docs

#2263 add nuklear/4.03.1
  recipes/nuklear/all/conandata.yml
  recipes/nuklear/all/test_package/test_package.c
  recipes/nuklear/config.yml
Labels: Bump version

#1360 add glslang/8.13.3559
  recipes/glslang/all/CMakeLists.txt
  recipes/glslang/all/conandata.yml
  recipes/glslang/all/conanfile.py
  recipes/glslang/all/patches/conanize-cmake-8.13.3559.patch
  recipes/glslang/all/test_package/CMakeLists.txt
  recipes/glslang/all/test_package/conanfile.py
  recipes/glslang/all/test_package/test_package.cpp
  recipes/glslang/all/test_package/test_package.vert
  recipes/glslang/config.yml
Labels: blocked

#2312 adding fmt/7.0.2
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version
