Repository conan-io/conan-center-index, pull requests merged in 2020-09, with the labels that each got.

#2747 meson 0.55.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#2811 Bump cpp-httplib to 0.7.6
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#2806 Update nng 1.3.1 and 1.3.2
  recipes/nng/all/conandata.yml
  recipes/nng/config.yml
Labels: Bump version

#2738 Add libcurl 7.72.0
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#2861 enet: add 1.3.16
  recipes/enet/all/conandata.yml
  recipes/enet/config.yml
Labels: Bump version

#2849 add entt/3.5.1
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#2843 wolfssl/4.5.0 : build package with wolfssl-4.5.0 version
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#2543 span-lite: fix cmake names
  recipes/span-lite/all/conandata.yml
  recipes/span-lite/all/conanfile.py
  recipes/span-lite/all/test_package/CMakeLists.txt
  recipes/span-lite/all/test_package/conanfile.py
  recipes/span-lite/all/test_package/test_package.cpp
  recipes/span-lite/config.yml
Labels: blocked

#2892 meson 0.55.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#2858 Bump cpp-httplib to 0.7.7
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#2855 bump catch2/2.13.1
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#2890 glib 2.66.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#2935 [docs] Document KB053: symlinks must be contained inside the package
  docs/error_knowledge_base.md
Labels: Docs

#2940 Add libpqxx/7.2.0
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#2946 Update changelog 17-September-2020 - 17:42 CEST
  docs/changelog.md
Labels: Docs

#2954 Update the number of generated packages
  docs/supported_platforms_and_configurations.md
Labels: Docs

#2959 Upgrade Conan to 1.29.1
  docs/changelog.md
Labels: Docs

#2960 Fix typo foler -> folder in README.md
  README.md
Labels: Docs

#2966 add toml11/3.6.0
  recipes/toml11/all/conandata.yml
  recipes/toml11/config.yml
Labels: Bump version

#2976 Update changelog 21-September-2020 - 17:59 CEST
  docs/changelog.md
Labels: Docs

#2989 add entt/3.5.2
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#2994 Update changelog 23-September-2020 - 15:48 CEST
  docs/changelog.md
Labels: Docs

#3017 add utfcpp/3.1.2
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#3046 Update changelog
  docs/changelog.md
Labels: Docs

#3035 Add cxxopts/2.2.1
  recipes/cxxopts/all/conandata.yml
  recipes/cxxopts/config.yml
Labels: Bump version

#3001 Fix builds for OpenSSL < 1.0.2d
  recipes/openssl/1.x.x/conanfile.py
Labels: infrastructure

#3055 adding spdlog/1.8.1
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#3056 add hana/1.7.0
  recipes/hana/all/conandata.yml
  recipes/hana/config.yml
Labels: Bump version
