Repository conan-io/conan-center-index, pull requests merged in 2021-03, with the labels that each got.

#4716 oatpp: add version 1.2.5
  recipes/oatpp/all/conandata.yml
  recipes/oatpp/config.yml
Labels: Bump version

#4718 taocpp-pegtl: add version 3.2.0
  recipes/taocpp-pegtl/3.x.x/conandata.yml
  recipes/taocpp-pegtl/config.yml
Labels: Bump version

#4704 Bump vulkan-loader/1.2.170.0
  recipes/vulkan-loader/all/conandata.yml
  recipes/vulkan-loader/config.yml
Labels: Bump version

#4746 glib: add version 2.67.5
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#4753 Bump fast_float/0.9.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#4754 Bump cpp-peglib/1.3.3
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#4778 Bump zstd/1.4.9
  recipes/zstd/all/conandata.yml
  recipes/zstd/config.yml
Labels: Bump version

#4781 xkbcommon: add version 1.1.0
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/config.yml
Labels: Bump version

#4785 bullet3: add version 3.09
  recipes/bullet3/all/conandata.yml
  recipes/bullet3/config.yml
Labels: Bump version

#4375 Add github action file, to update tables of contents automatically
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#4658 Added liburing recipe
  recipes/liburing/all/conandata.yml
  recipes/liburing/all/conanfile.py
  recipes/liburing/all/test_package/CMakeLists.txt
  recipes/liburing/all/test_package/conanfile.py
  recipes/liburing/all/test_package/test_package.c
  recipes/liburing/config.yml
Labels: infrastructure

#4794 Update changelog 05-March-2021
  docs/changelog.md
  docs/supported_platforms_and_configurations.md
Labels: Docs

#4825 [gh-action] Trigger the action only if there are changes in 'docs' folder
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#4847 glib: add version 2.67.6
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#4862 [docs] Add a link to conan-io/conan-docker-tools
  docs/supported_platforms_and_configurations.md
Labels: Docs

#4852 pango: add version 1.48.3
  recipes/pango/all/conandata.yml
  recipes/pango/config.yml
Labels: Bump version

#4873 Bump libwebp/1.2.0
  recipes/libwebp/all/conandata.yml
  recipes/libwebp/config.yml
Labels: Bump version

#4900 vulkan-headers: add version 1.2.172
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#4892 add newest cubicinterpolation version v0.1.4
  recipes/cubicinterpolation/all/conandata.yml
  recipes/cubicinterpolation/config.yml
Labels: Bump version

#4891 add cmake/3.19.7
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#4908 vulkan-headers 1.2.170
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#4911 Add libtins 4.3
  recipes/libtins/all/conandata.yml
  recipes/libtins/config.yml
Labels: Bump version

#4923 gobject-introspection: add version 1.67.1
  recipes/gobject-introspection/all/conandata.yml
  recipes/gobject-introspection/config.yml
Labels: Bump version

#4924 gstreamer: add version 1.18.4
  recipes/gstreamer/all/conandata.yml
  recipes/gstreamer/config.yml
Labels: Bump version

#4955 Try to improve README visibility
  README.md
Labels: Docs

#4948 volk: add version 1.2.170
  recipes/volk/all/conandata.yml
  recipes/volk/config.yml
Labels: Bump version

#4949 vulkan-loader: add version 1.2.172
  recipes/vulkan-loader/all/conandata.yml
  recipes/vulkan-loader/config.yml
Labels: Bump version

#4967 glib: add version 2.68.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#4977 add span-lite/0.9.2
  recipes/span-lite/all/conandata.yml
  recipes/span-lite/config.yml
Labels: Bump version

#4984 Bump uriparser/0.9.5
  recipes/uriparser/all/conandata.yml
  recipes/uriparser/config.yml
Labels: Bump version

#4986 at-spi2-core: add version 2.40.0
  recipes/at-spi2-core/all/conandata.yml
  recipes/at-spi2-core/config.yml
Labels: Bump version

#4987 Bump jasper/2.0.27
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#4988 Bump fast_float/1.0.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#4989 Bump cpp-peglib/1.3.5
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#4990 Bump cpp-httplib/0.8.5
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#4991 Bump hlslpp/3.0
  recipes/hlslpp/all/conandata.yml
  recipes/hlslpp/config.yml
Labels: Bump version

#4993 Bump sqlite3/3.35.2
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#4998 cppcheck: add version 2.4
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#4999 gobject-introspection: add version 1.68.0
  recipes/gobject-introspection/all/conandata.yml
  recipes/gobject-introspection/config.yml
Labels: Bump version

#5001 [docs] reviewing preferences: updating subfolder + note CMake
  docs/reviewing.md
Labels: Docs

#5002 KB-H007 Remove fPIC when building shared lib
  docs/error_knowledge_base.md
Labels: Docs

#4973 [cgal] Add 5.2.1, 5.1.2, and 5.1.3
  recipes/cgal/all/conandata.yml
  recipes/cgal/config.yml
Labels: Bump version

#5010 Bump ECM version
  recipes/extra-cmake-modules/all/conandata.yml
  recipes/extra-cmake-modules/config.yml
Labels: Bump version

#5021 add cmake/3.20.0
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#5028 Bump si to version 2.1.0
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#5046 add toml11/3.6.1
  recipes/toml11/all/conandata.yml
  recipes/toml11/config.yml
Labels: Bump version

#5049 uvw: add version 2.9.0
  recipes/uvw/all/conandata.yml
  recipes/uvw/config.yml
Labels: Bump version

#5070 Add imgui/1.82
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#5073 [matio] Update matio to v1.5.21
  recipes/matio/all/conandata.yml
  recipes/matio/config.yml
Labels: Bump version

#5029 add ixwebsocket 11.2.4, which is compatible with mingw and allows sha…
  recipes/ixwebsocket/all/conandata.yml
  recipes/ixwebsocket/config.yml
Labels: Bump version

#5044 add openssl/1.1.1k
  recipes/openssl/1.x.x/conandata.yml
  recipes/openssl/config.yml
Labels: Bump version

#5074 caf: add version 0.18.2
  recipes/caf/all/conandata.yml
  recipes/caf/config.yml
Labels: Bump version

#5077 cppcheck: add version 2.4.1
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#5084 [ci] [rfc] warmer welcome to PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub config

#5094 trompeloeil: add version 40
  recipes/trompeloeil/all/conandata.yml
  recipes/trompeloeil/config.yml
Labels: Bump version
