Repository conan-io/conan-center-index, pull requests merged in 2021-01, with the labels that each got.

#4050 Add any-lite 0.4.0
  recipes/any-lite/all/conandata.yml
  recipes/any-lite/config.yml
Labels: Bump version

#4077 libpcap: bump to 1.10.0
  recipes/libpcap/all/conandata.yml
  recipes/libpcap/config.yml
Labels: Bump version

#4089 glib 2.67.1
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#4090 libcap 2.46
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#4091 libsystemd 247.2
  recipes/libsystemd/all/conandata.yml
  recipes/libsystemd/config.yml
Labels: Bump version

#4083 pulseaudio 14.0
  recipes/pulseaudio/all/conandata.yml
  recipes/pulseaudio/config.yml
Labels: Bump version

#4153 ceres-solver/1.13.0
  recipes/ceres-solver/all/conandata.yml
  recipes/ceres-solver/config.yml
Labels: Bump version

#4194 bump entt/3.6.0
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#3614 [docs] Create reviewing.md
  docs/reviewing.md
Labels: Docs

#4180 mdns: add version 1.2
  recipes/mdns/all/conandata.yml
  recipes/mdns/config.yml
Labels: Bump version

#4213 meson: add version 0.56.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#4231 Quill update to 1.6.1
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#4244 add cmake/3.19.3
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#4276 Bump jasper/2.0.24
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#4279 Bump cpp-httplib/0.8.0
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#4280 at-spi2-core 2.39.1
  recipes/at-spi2-core/all/conandata.yml
  recipes/at-spi2-core/config.yml
Labels: Bump version

#4287 mosquitto: add version 2.0.5
  recipes/mosquitto/2.x/conandata.yml
  recipes/mosquitto/config.yml
Labels: Bump version

#4234 openssl: remove duplicate no_cast option
  recipes/openssl/1.x.x/conanfile.py
Labels: infrastructure

#4289 mbedtls: add version 2.25.0
  recipes/mbedtls/all/conandata.yml
  recipes/mbedtls/config.yml
Labels: Bump version

#4296 Add timsort/1.3.0 and timsort/2.1.0
  recipes/timsort/all/conandata.yml
  recipes/timsort/config.yml
Labels: Bump version

#4307 Bump vulkan-headers/1.2.162.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#4311 Bump abseil/20200923.3
  recipes/abseil/all/conandata.yml
  recipes/abseil/config.yml
Labels: Bump version

#4215 Add libpqxx/7.3.1
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/all/patches/fix-msvc-compilation-3.7.1.patch
  recipes/libpqxx/config.yml
Labels: infrastructure

#4343 Bump simdjson/0.8.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#4337 libgit2: Bump 1.1.0
  recipes/libgit2/all/conandata.yml
  recipes/libgit2/config.yml
Labels: Bump version

#4345 Version bump to 0.0.14
  recipes/bertrand/all/conandata.yml
  recipes/bertrand/config.yml
Labels: Bump version

#4348 nameof: Bump to 0.10.0
  recipes/nameof/all/conandata.yml
  recipes/nameof/config.yml
Labels: Bump version

#4340 Bump imgui/1.80
  recipes/imgui/all/conandata.yml
  recipes/imgui/all/conanfile.py
  recipes/imgui/config.yml
Labels: infrastructure

#4317 - add .am to .gitattributes
  .gitattributes
Labels: Failed

#4357 Add approvaltests.cpp 10.7.0
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#4361 Adding a curated list of community resources
  README.md
  docs/community_resources.md
Labels: Docs

#4368 Document how to update conan hooks
  docs/how_to_add_packages.md
Labels: Docs

#4350 update sqlite3 to 3.34.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#4378 Bump spirv-cross/20210115
  recipes/spirv-cross/all/conandata.yml
  recipes/spirv-cross/config.yml
Labels: Bump version

#4383 Update changelog 27-January-2021
  docs/changelog.md
Labels: Docs

#4382 Bump openexr/2.5.4
  recipes/openexr/2.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#1759 qt/5.15.2
  recipes/qt/5.x.x/conandata.yml
  recipes/qt/5.x.x/conanfile.py
  recipes/qt/5.x.x/patches/aa2a39dea5.diff
  recipes/qt/5.x.x/patches/c72097e.diff
  recipes/qt/5.x.x/qtmodules5.15.2.conf
  recipes/qt/5.x.x/test_package/CMakeLists.txt
  recipes/qt/5.x.x/test_package/conanfile.py
  recipes/qt/5.x.x/test_package/greeter.h
  recipes/qt/5.x.x/test_package/meson.build
  recipes/qt/5.x.x/test_package/test_package.cpp
  recipes/qt/5.x.x/test_package/test_package.pro
  recipes/qt/config.yml
Labels: infrastructure

#4395 mdns: add version 1.3
  recipes/mdns/all/conandata.yml
  recipes/mdns/config.yml
Labels: Bump version

#4406 add cmake/3.19.4
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#4405 Bump pcre2/10.36
  recipes/pcre2/all/conandata.yml
  recipes/pcre2/config.yml
Labels: Bump version

#4410 Bump nuklear/4.06.1
  recipes/nuklear/all/conandata.yml
  recipes/nuklear/config.yml
Labels: Bump version

#4409 Bump glew/2.2.0
  recipes/glew/all/conandata.yml
  recipes/glew/config.yml
Labels: Bump version

#4413 Bump spy/1.0.0
  recipes/spy/all/conandata.yml
  recipes/spy/config.yml
Labels: Bump version

#4417 imaGL: adding 0.1.1
  recipes/imagl/all/conandata.yml
  recipes/imagl/config.yml
Labels: Bump version

#4424 Version bump for si to 2.0.3
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#4433 Add meson/0.51.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version
