Repository conan-io/conan-center-index, pull requests merged in 2021-07, with the labels that each got.

#6106 pango: add version 1.48.6
  recipes/pango/all/conandata.yml
  recipes/pango/config.yml
Labels: Bump version

#6107 Update json_dto to 0.2.13
  recipes/json_dto/all/conandata.yml
  recipes/json_dto/config.yml
Labels: Bump version

#6109 Bump ezc3d/1.4.5
  recipes/ezc3d/all/conandata.yml
  recipes/ezc3d/config.yml
Labels: Bump version

#6113 at-spi2-core: add version 2.40.2
  recipes/at-spi2-core/all/conandata.yml
  recipes/at-spi2-core/config.yml
Labels: Bump version

#6114 hipony-enumerate: add version 2.4.0
  recipes/hipony-enumerate/all/conandata.yml
  recipes/hipony-enumerate/config.yml
Labels: Bump version

#6116 sqlite 3.36.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#6077 Update to vulkan-loader
  recipes/vulkan-loader/all/conandata.yml
  recipes/vulkan-loader/config.yml
Labels: Bump version

#6078 Updated spirv-headers to last known good commit before spirv-tools v2…
  recipes/spirv-headers/all/conandata.yml
  recipes/spirv-headers/config.yml
Labels: Bump version

#6129 Add sentry-crashpad/0.4.10
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#6139 Bump tcsbank-uri-template/1.1.4
  recipes/tcsbank-uri-template/all/conandata.yml
  recipes/tcsbank-uri-template/config.yml
Labels: Bump version

#6140 Bump tcsbank-uconfig/2.1.0
  recipes/tcsbank-uconfig/all/conandata.yml
  recipes/tcsbank-uconfig/config.yml
Labels: Bump version

#6136 [docs] Update Error Knowledge Base
  docs/error_knowledge_base.md
Labels: Docs

#6142 fmt: add version 8.0.1
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#6147 Bump bitmagic/7.4.0
  recipes/bitmagic/all/conandata.yml
  recipes/bitmagic/config.yml
Labels: Bump version

#6157 pango: add version 1.48.7
  recipes/pango/all/conandata.yml
  recipes/pango/config.yml
Labels: Bump version

#6169 mdns: add version 1.4.1
  recipes/mdns/all/conandata.yml
  recipes/mdns/config.yml
Labels: Bump version

#6079 add cmake/3.20.5
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#6224 libxcrypt: add version 4.4.23
  recipes/libxcrypt/all/conandata.yml
  recipes/libxcrypt/config.yml
Labels: Bump version

#6245 Add sentry-breakpad/0.4.10
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#6249 harfbuzz: add version 2.8.2
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#6240 sassc: add version 3.6.2
  recipes/sassc/all/conandata.yml
  recipes/sassc/config.yml
Labels: Bump version

#6256 Add ring-span-lite/0.5.0
  recipes/ring-span-lite/all/conandata.yml
  recipes/ring-span-lite/config.yml
Labels: Bump version

#6257 Add span-lite/0.10.0
  recipes/span-lite/all/conandata.yml
  recipes/span-lite/config.yml
Labels: Bump version

#6259 asio: add version 1.19.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#6264 taywee-args: add version 6.2.5
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#6265 vulkan-headers: add version 1.2.184
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#6260 at-spi2-core: add version 2.40.3
  recipes/at-spi2-core/all/conandata.yml
  recipes/at-spi2-core/config.yml
Labels: Bump version

#6263 libuv: add version 1.41.1
  recipes/libuv/all/conandata.yml
  recipes/libuv/config.yml
Labels: Bump version

#6283 Bump msdfgen/1.9.1
  recipes/msdfgen/all/conandata.yml
  recipes/msdfgen/config.yml
Labels: Bump version

#6297 sentry-breakpad/0.4.11
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#6340 add cmake/3.21.0
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#6289 sentry-crashpad/0.4.11
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#6374 mgs: add 0.1.4
  recipes/mgs/all/conandata.yml
  recipes/mgs/config.yml
Labels: Bump version

#6381 godot_headers: add 3.3.2
  recipes/godot_headers/all/conandata.yml
  recipes/godot_headers/config.yml
Labels: Bump version

#6406 Add ring-span-lite/0.6.0
  recipes/ring-span-lite/all/conandata.yml
  recipes/ring-span-lite/config.yml
Labels: Bump version

#6313 Bumped cppcommon version to 1.0.2.0
  recipes/cppcommon/all/conandata.yml
  recipes/cppcommon/config.yml
Labels: Bump version

#6298 sentry-native/0.4.11
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#6413 meson: add version 0.59.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#6437 Bump miniaudio version
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#6337 OpenSSL on Windows: multi-profile support
  recipes/openssl/1.x.x/conanfile.py
Labels: blocked

#6445 spdlog: add version 1.9.0
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#6477 Bump entt/3.8.0
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#6478 Bump cpp-httplib/0.9.2
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#6479 enkits: Bump version 1.10
  recipes/enkits/all/conandata.yml
  recipes/enkits/config.yml
Labels: Bump version

#6480 taywee-args: Bump version 6.2.6
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#6481 libgit2: add version 1.1.1
  recipes/libgit2/all/conandata.yml
  recipes/libgit2/config.yml
Labels: Bump version

#6482 libwebsockets: Bump version 4.2.1
  recipes/libwebsockets/all/conandata.yml
  recipes/libwebsockets/config.yml
Labels: Bump version

#6483 minizip-ng: Bump version 3.0.2
  recipes/minizip-ng/all/conandata.yml
  recipes/minizip-ng/config.yml
Labels: Bump version

#6495 Bump cpp-sort/1.11.0
  recipes/cpp-sort/all/conandata.yml
  recipes/cpp-sort/config.yml
Labels: Bump version

#6499 Bump spscqueue/1.1
  recipes/spscqueue/all/conandata.yml
  recipes/spscqueue/config.yml
Labels: Bump version

#6377 pybind11: version bump 2.7.0.
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#6517 aws-c-common: add version 0.6.8
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#6519 caf: add version 0.18.5
  recipes/caf/all/conandata.yml
  recipes/caf/config.yml
Labels: Bump version

#6503 Add protobuf version 3.16.0
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#6518 aws-c-compression: add version 0.2.14
  recipes/aws-c-compression/all/conandata.yml
  recipes/aws-c-compression/config.yml
Labels: Bump version

#6523 uwebsockets: add version 19.3.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#6524 tclap: add version 1.2.4
  recipes/tclap/all/conandata.yml
  recipes/tclap/config.yml
Labels: Bump version

#6525 tabulate: add version 1.4
  recipes/tabulate/all/conandata.yml
  recipes/tabulate/config.yml
Labels: Bump version

#6527 statslib: add version 3.1.2
  recipes/statslib/all/conandata.yml
  recipes/statslib/config.yml
Labels: Bump version

#6528 ssht: add version 1.4.0
  recipes/ssht/all/conandata.yml
  recipes/ssht/config.yml
Labels: Bump version

#6533 octomap: add version 1.9.7
  recipes/octomap/all/conandata.yml
  recipes/octomap/config.yml
Labels: Bump version

#6534 numcpp: add version 2.4.2
  recipes/numcpp/all/conandata.yml
  recipes/numcpp/config.yml
Labels: Bump version

#6532 openblas: add version 0.3.17
  recipes/openblas/all/conandata.yml
  recipes/openblas/config.yml
Labels: Bump version

#6526 structopt: add version 0.1.2
  recipes/structopt/all/conandata.yml
  recipes/structopt/config.yml
Labels: Bump version

#6531 readerwriterqueue: add version 1.0.5
  recipes/readerwriterqueue/all/conandata.yml
  recipes/readerwriterqueue/config.yml
Labels: Bump version

#6535 nanobench: add version 4.3.5
  recipes/nanobench/all/conandata.yml
  recipes/nanobench/config.yml
Labels: Bump version

#6529 robin-hood-hashing: add version 3.11.3
  recipes/robin-hood-hashing/all/conandata.yml
  recipes/robin-hood-hashing/config.yml
Labels: Bump version

#6530 sole: add version 1.0.2
  recipes/sole/all/conandata.yml
  recipes/sole/config.yml
Labels: Bump version

#6596 Update changelog from past deployments
  docs/changelog.md
Labels: Docs

#6582 spdlog: Bump to 1.9.1
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#6602 add cmake/3.21.1
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version
