Repository conan-io/conan-center-index, pull requests merged in 2021-04, with the labels that each got.

#5117 [sqlite3] new version 3.35.3
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#5020 How to deprecate a recipe option
  docs/faqs.md
Labels: Docs

#5138 gsl-lite-0.38.0 support added
  recipes/gsl-lite/all/conandata.yml
  recipes/gsl-lite/config.yml
Labels: Bump version

#5130 [sqlite3] version 3.35.4
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#5127 Feature/add protobuf 3.11.3 version
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#5142 Bump entt/3.7.0
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#5143 Bump cpp-httplib/0.8.6
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#5147 add cmake/3.19.8
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#5153 Add stale PR section on review process
  docs/review_process.md
Labels: Docs

#5159 New changes deployed to production
  docs/changelog.md
Labels: Docs

#5161 glib: add version 2.68.1
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#5162 b2: add version 4.5.0
  recipes/b2/config.yml
  recipes/b2/portable/conandata.yml
Labels: Bump version

#5163 glfw: add version 3.3.4
  recipes/glfw/all/conandata.yml
  recipes/glfw/config.yml
Labels: Bump version

#5164 jasper: add version 2.0.28
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#5057 add links about precompiled binaries in FAQ and how-to-add
  docs/faqs.md
  docs/how_to_add_packages.md
Labels: Docs

#5172 oatpp-libressl: add version 1.2.5
  recipes/oatpp-libressl/all/conandata.yml
  recipes/oatpp-libressl/config.yml
Labels: Bump version

#5173 oatpp-openssl: add version 1.2.5
  recipes/oatpp-openssl/all/conandata.yml
  recipes/oatpp-openssl/config.yml
Labels: Bump version

#5174 simdjson: add version 0.9.2
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#5176 graphene: add version 1.10.6
  recipes/graphene/all/conandata.yml
  recipes/graphene/config.yml
Labels: Bump version

#5181 libcpuid: add version 0.5.1
  recipes/libcpuid/all/conandata.yml
  recipes/libcpuid/config.yml
Labels: Bump version

#5187 meson: add version 0.57.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#5183 mosquitto: add version 2.0.10
  recipes/mosquitto/2.x/conandata.yml
  recipes/mosquitto/config.yml
Labels: Bump version

#5189 Update fakeit to version 2.0.8.
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#5199 add cmake/3.20.1
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#5148 add djinni-generator/0.3.2
  recipes/djinni-generator/all/conandata.yml
  recipes/djinni-generator/config.yml
Labels: Bump version

#5213 xtl: add version 0.7.2
  recipes/xtl/all/conandata.yml
  recipes/xtl/config.yml
Labels: Bump version

#5219 [miniaudio] Add v 0.10.33
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#5224 Bump xsimd/7.4.10
  recipes/xsimd/all/conandata.yml
  recipes/xsimd/config.yml
Labels: Bump version

#5225 New: Usr: Added opencv/4.5.2
  recipes/opencv/4.x/conandata.yml
  recipes/opencv/config.yml
Labels: Bump version

#5253 catch2: add catch2/2.16.6
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#5149 add the gamma and lepton propagator PROPOSAL
  recipes/proposal/all/CMakeLists.txt
  recipes/proposal/all/conandata.yml
  recipes/proposal/all/conanfile.py
  recipes/proposal/all/test_package/CMakeLists.txt
  recipes/proposal/all/test_package/conanfile.py
  recipes/proposal/all/test_package/test_package.cpp
  recipes/proposal/config.yml
Labels: infrastructure

#5276 sqlite3 3.35.5
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#5287 Add FAQ about Public Domain
  docs/faqs.md
Labels: Docs

#4286 [msys2] Bump version and support two profiles approach.
  recipes/msys2/all/conandata.yml
  recipes/msys2/all/conanfile.py
  recipes/msys2/all/test_package/conanfile.py
  recipes/msys2/config.yml
Labels: stale

#5306 Add libpqxx/7.5.0
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#5319 gsl-lite: add version 0.38.1
  recipes/gsl-lite/all/conandata.yml
  recipes/gsl-lite/config.yml
Labels: Bump version

#5320 jasper: add version 2.0.32
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#5331 Bump si to version 2.1.1
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#5337 add djinni-generator v0.4.0
  recipes/djinni-generator/all/conandata.yml
  recipes/djinni-generator/config.yml
Labels: Bump version

#5343 Bump miniaudio (0.10.35)
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#5360 add djinni-generator v0.5.0
  recipes/djinni-generator/all/conandata.yml
  recipes/djinni-generator/config.yml
Labels: Bump version

#5080 Provide examples for "how to" add components with varying complexity
  docs/how_to_add_packages.md
Labels: Docs
