Repository conan-io/conan-center-index, pull requests merged in 2021-05, with the labels that each got.

#5384 Add approvaltests.cpp 10.9.1
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#5398 [sentry-native] Adds 0.4.9
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#5399 meson: add version 0.58.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#5400 at-spi2-core: add version 2.40.1
  recipes/at-spi2-core/all/conandata.yml
  recipes/at-spi2-core/config.yml
Labels: Bump version

#5408 Bumped DataFrame version to 1.17.0
  recipes/dataframe/all/conandata.yml
  recipes/dataframe/config.yml
Labels: Bump version

#5427 Version bump si to 2.1.2
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#5431 Bump vulkan-headers 1.2.176 & 1.2.176.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#5435 opencl-headers: add version 2021.04.29
  recipes/opencl-headers/all/conandata.yml
  recipes/opencl-headers/config.yml
Labels: Bump version

#5439 opencl-icd-loader: add version 2021.04.29
  recipes/opencl-icd-loader/all/conandata.yml
  recipes/opencl-icd-loader/config.yml
Labels: Bump version

#5446 cgltf: Bump to 1.10
  recipes/cgltf/all/conandata.yml
  recipes/cgltf/config.yml
Labels: Bump version

#5447 meshoptimzer: Bump to 1.16
  recipes/meshoptimizer/all/conandata.yml
  recipes/meshoptimizer/config.yml
Labels: Bump version

#5448 inja: Bump to 3.2.0
  recipes/inja/all/conandata.yml
  recipes/inja/config.yml
Labels: Bump version

#5449 taskflow: Bump to 3.1.0
  recipes/taskflow/all/conandata.yml
  recipes/taskflow/config.yml
Labels: Bump version

#5426 harfbuzz: add version 2.8.1
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#5445 [rtm] Bump to 2.1.2
  recipes/rtm/all/conandata.yml
  recipes/rtm/config.yml
Labels: Bump version

#5457 add doctest/2.4.5
  recipes/doctest/2.x.x/conandata.yml
  recipes/doctest/config.yml
Labels: Bump version

#5146 Describe why check_min_cppstd is not enough
  docs/faqs.md
Labels: Docs

#5467 proposal: Bump to 7.0.4
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#5474 sjson-cpp: add version 0.8.1
  recipes/sjson-cpp/all/conandata.yml
  recipes/sjson-cpp/config.yml
Labels: Bump version

#5473 bullet3: add version 3.17
  recipes/bullet3/all/conandata.yml
  recipes/bullet3/config.yml
Labels: Bump version

#5478 robin-hood-hashing: add version 3.11.1
  recipes/robin-hood-hashing/all/conandata.yml
  recipes/robin-hood-hashing/config.yml
Labels: Bump version

#5425 How to build without build script
  docs/how_to_add_packages.md
Labels: Docs

#5475 update djinni-generator to v1.0.0
  recipes/djinni-generator/all/conandata.yml
  recipes/djinni-generator/config.yml
Labels: Bump version

#5480 Add libpqxx/7.5.1
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#5483 Add libpqxx/7.5.2
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#5220 Add FAQ for splitting projects
  docs/faqs.md
Labels: Docs

#5484 - add a clarification about recommended feature options names
  docs/reviewing.md
Labels: Docs

#5526 Update changelog 13-May-2021
  docs/changelog.md
Labels: Docs

#5529 Update SObjectizer to latest version (5.7.2.5)
  recipes/sobjectizer/all/conandata.yml
  recipes/sobjectizer/config.yml
Labels: Bump version

#5534 zstd: bump zstd/1.5.0
  recipes/zstd/all/conandata.yml
  recipes/zstd/config.yml
Labels: Bump version

#5537 ctre: add version 3.4.1
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#5574 Update json_dto to latest version (0.2.12)
  recipes/json_dto/all/conandata.yml
  recipes/json_dto/config.yml
Labels: Bump version

#5611 Add new version of expat 2.4.1.
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#5614 [changelog] Update changelog for new release
  docs/changelog.md
Labels: Docs

#5440 Add Qt integration to sentry
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/all/conanfile.py
  recipes/sentry-native/all/patches/find-conan-qt-0.4.7.patch
  recipes/sentry-native/all/patches/find-conan-qt-0.4.8.patch
  recipes/sentry-native/all/patches/find-conan-qt-0.4.9.patch
Labels: infrastructure

#5570 proposal: Bump to 7.0.5
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#5624 libepoxy: add version 1.5.8
  recipes/libepoxy/all/conandata.yml
  recipes/libepoxy/config.yml
Labels: Bump version

#5637 Add new community reviewer
  docs/review_process.md
Labels: Docs

#5644 how_to_add_packages.md: typo fix
  docs/how_to_add_packages.md
Labels: Docs

#5654 glib: add version 2.68.2
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#5656 paho-mqtt-c: add version 1.3.9
  recipes/paho-mqtt-c/all/conandata.yml
  recipes/paho-mqtt-c/config.yml
Labels: Bump version

#5658 toml11: add version 3.7.0
  recipes/toml11/all/conandata.yml
  recipes/toml11/config.yml
Labels: Bump version

#5664 libcurl: add version 7.76.0
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#5661 Bump pcre2/10.37
  recipes/pcre2/all/conandata.yml
  recipes/pcre2/config.yml
Labels: Bump version

#5655 mdns: add version 1.4
  recipes/mdns/all/conandata.yml
  recipes/mdns/config.yml
Labels: Bump version

#5665 nanodbc: Bump to 2.13.0
  recipes/nanodbc/all/conandata.yml
  recipes/nanodbc/config.yml
Labels: Bump version

#5669 imgui: add version 1.83
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#5667 pango: add version 1.48.5
  recipes/pango/all/conandata.yml
  recipes/pango/config.yml
Labels: Bump version

#5668 outcome: add version 2.2.0
  recipes/outcome/all/conandata.yml
  recipes/outcome/config.yml
Labels: Bump version

#5676 simdjson: add version 0.9.5
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#5687 botan: add version 2.18.1
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#5688 utfcpp: add version 3.2
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#5689 quill: add version 1.6.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version
