Repository conan-io/conan-center-index, pull requests merged in 2021-06, with the labels that each got.

#5701 Bump version Protobuf 3.17.1
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#5713 [changelog] New release (no new features)
  docs/changelog.md
Labels: Docs

#5719 Document policy for adding older package versions
  docs/faqs.md
Labels: Docs

#5770 libcap/2.50: bump version
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#5741 xkbcommon: add version 1.3.0
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/config.yml
Labels: Bump version

#5742 gstreamer: add version 1.19.1
  recipes/gstreamer/all/conandata.yml
  recipes/gstreamer/config.yml
Labels: Bump version

#5774 abseil: add version 20210324.2
  recipes/abseil/all/conandata.yml
  recipes/abseil/config.yml
Labels: Bump version

#5775 cpp-httplib: add version 0.8.9
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#5776 fakeit: add version 2.0.9
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#5777 libsass: add version 3.6.5
  recipes/libsass/all/conandata.yml
  recipes/libsass/config.yml
Labels: Bump version

#5778 libxcrypt: add version 4.4.22
  recipes/libxcrypt/all/conandata.yml
  recipes/libxcrypt/config.yml
Labels: Bump version

#5811 meson: add version 0.58.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#5834 Add QArchive/2.0.2
  recipes/qarchive/all/conandata.yml
  recipes/qarchive/config.yml
Labels: Bump version

#5880 glib: add version 2.68.3
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#5893 add cmake/3.20.4
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#5918 Update pffft to cci.20210511
  recipes/pffft/all/conandata.yml
  recipes/pffft/config.yml
Labels: Bump version

#5827 hazelcast-cpp-client: add v4.1.1
  recipes/hazelcast-cpp-client/all/conandata.yml
  recipes/hazelcast-cpp-client/config.yml
Labels: Bump version

#5941 trompeloeil: add version 41
  recipes/trompeloeil/all/conandata.yml
  recipes/trompeloeil/config.yml
Labels: Bump version

#5942 crowcpp-crow: add version 0.3
  recipes/crowcpp-crow/all/conandata.yml
  recipes/crowcpp-crow/config.yml
Labels: Bump version

#5950 Note recipes may lag behind best practices
  docs/how_to_add_packages.md
Labels: Docs

#5963 thrift: add version 0.14.2
  recipes/thrift/all/conandata.yml
  recipes/thrift/config.yml
Labels: Bump version

#5978 add djinni-generator v1.1.0
  recipes/djinni-generator/all/conandata.yml
  recipes/djinni-generator/config.yml
Labels: Bump version

#5992 mosquitto: add version 2.0.11
  recipes/mosquitto/2.x/conandata.yml
  recipes/mosquitto/config.yml
Labels: Bump version

#5993 utf8proc: add version 2.6.1
  recipes/utf8proc/all/conandata.yml
  recipes/utf8proc/config.yml
Labels: Bump version

#6016 fmt: add version 8.0.0
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#5606 ignore .devcontainer
  .gitignore
Labels: Failed

#6012 magic_enum: add version 0.7.3
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#6013 oatpp-websocket: add version 1.2.5
  recipes/oatpp-websocket/all/conandata.yml
  recipes/oatpp-websocket/config.yml
Labels: Bump version

#6014 nameof: add version 0.10.1
  recipes/nameof/all/conandata.yml
  recipes/nameof/config.yml
Labels: Bump version

#6017 fast_float: add version 1.1.2
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#6027 libpq: add libpq/13.3
  recipes/libpq/all/conandata.yml
  recipes/libpq/config.yml
Labels: Bump version

#6038 Bump vc/1.4.2
  recipes/vc/all/conandata.yml
  recipes/vc/config.yml
Labels: Bump version

#6041 Bump cpp-httplib/0.9.0
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#5962 Update how_to_add_packages.md
  docs/how_to_add_packages.md
Labels: Docs

#6087 Bump tiny-utf8/4.4.1
  recipes/tiny-utf8/all/conandata.yml
  recipes/tiny-utf8/config.yml
Labels: Bump version
