Repository conan-io/conan-center-index, pull requests merged in 2021-02, with the labels that each got.

#4448 Bump bertrand to version 0.0.15
  recipes/bertrand/all/conandata.yml
  recipes/bertrand/config.yml
Labels: Bump version

#4372 [docs] Add table of contents to most documentation pages (#4367)
  docs/community_resources.md
  docs/contributing.md
  docs/faqs.md
  docs/how_to_add_packages.md
  docs/reviewing.md
  docs/supported_platforms_and_configurations.md
Labels: Docs

#4430 Update reviewing.md
  docs/reviewing.md
Labels: Docs

#4466 bump cpprestsdk/2.10.18
  recipes/cpprestsdk/all/conandata.yml
  recipes/cpprestsdk/config.yml
Labels: Bump version

#4473 new version wolfssl 4.6.0
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#4460 [OpenSSL] remove explicit apple deployment target flag
  recipes/openssl/1.x.x/conanfile.py
Labels: infrastructure

#4490 [docs] Update changelog
  docs/changelog.md
Labels: Docs

#4504 Add pybind11 version 2.6.2.
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#4510 Fontconfig: Add version 2.13.93
  recipes/fontconfig/all/conandata.yml
  recipes/fontconfig/config.yml
Labels: Bump version

#4511 add jasper/2.0.25
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#4516 gstreamer: add version 1.18.3
  recipes/gstreamer/all/conandata.yml
  recipes/gstreamer/config.yml
Labels: Bump version

#4520 Bump prometheus-cpp to 0.12.1
  recipes/prometheus-cpp/all/conandata.yml
  recipes/prometheus-cpp/config.yml
Labels: Bump version

#4523 Add approvaltests.cpp 10.7.1
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#4531 Add rapidcheck/20210107
  recipes/rapidcheck/all/conandata.yml
  recipes/rapidcheck/config.yml
Labels: Bump version

#4522 audiofile: add version 1.0.9
  recipes/audiofile/all/conandata.yml
  recipes/audiofile/config.yml
Labels: Bump version

#4538 pango: add version 1.48.2
  recipes/pango/all/conandata.yml
  recipes/pango/config.yml
Labels: Bump version

#4543 add cmake/3.18.6
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#4548 Bump si to version 2.0.4
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#4527 Create review_process.md
  docs/review_process.md
Labels: Docs

#4565 libcap/2.48: bump version
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#4566 libsystemd/247.3: bump version
  recipes/libsystemd/all/conandata.yml
  recipes/libsystemd/config.yml
Labels: Bump version

#4575 meson: add version 0.57.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#4581 Add approvaltests.cpp 10.8.0
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#4583 packio: add version 2.2.0
  recipes/packio/all/conandata.yml
  recipes/packio/config.yml
Labels: Bump version

#4584 Add SPDX as source of license attribute content
  docs/reviewing.md
Labels: Docs

#4585 add cmake/3.19.5
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#4589 glib: add version 2.67.4
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#4593 Add support for OpenSSL version 1.1.1j
  recipes/openssl/1.x.x/conandata.yml
  recipes/openssl/config.yml
Labels: Bump version

#4601 Bump imgui/1.81
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#4603 Bump re2/20210202
  recipes/re2/all/conandata.yml
  recipes/re2/config.yml
Labels: Bump version

#4608 Add new community reviewer
  docs/review_process.md
Labels: Docs

#4622 gdbm: add version 1.19
  recipes/gdbm/all/conandata.yml
  recipes/gdbm/config.yml
Labels: Bump version

#4624 libpq: add missing versions
  recipes/libpq/all/conandata.yml
  recipes/libpq/config.yml
Labels: Bump version

#4636 [IMPORTANT] Updated changelog 22-February-2021
  docs/changelog.md
  docs/supported_platforms_and_configurations.md
Labels: Docs

#4637 meson: add version 0.57.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#4649 frozen: add 1.0.1
  recipes/frozen/all/conandata.yml
  recipes/frozen/config.yml
Labels: Bump version

#4598 [docs] Reviewing preference for subfolder properties
  docs/reviewing.md
Labels: Docs

#4650 Add new version of SObjectizer.
  recipes/sobjectizer/all/conandata.yml
  recipes/sobjectizer/config.yml
Labels: Bump version

#4661 nasm: use https url instead of http and download .xz archives
  recipes/nasm/all/conandata.yml
  recipes/nasm/config.yml
Labels: Bump version

#4678 bullet3: add version 3.08
  recipes/bullet3/all/conandata.yml
  recipes/bullet3/config.yml
Labels: Bump version

#4679 eastl: add 3.17.06
  recipes/eastl/all/conandata.yml
  recipes/eastl/config.yml
Labels: Bump version

#4669 Add libpqxx/7.4.1
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#4685 Remove email from EAP request
  docs/how_to_add_packages.md
Labels: Docs

#4690 Remove releases.md
  docs/releases.md
Labels: Failed

#4697 Bump vulkan-headers/1.2.170.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#4703 Bump odbc to 2.3.9
  recipes/odbc/all/conandata.yml
  recipes/odbc/config.yml
Labels: Bump version

#4709 add cmake/3.19.6
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#4713 Bump cpp-httplib/0.8.4
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version
