Repository conan-io/conan-center-index, pull requests merged in 2022-10, with the labels that each got.

#13248 c-blosc2: add version 2.4.2
  recipes/c-blosc2/all/conandata.yml
  recipes/c-blosc2/config.yml
Labels: Bump version

#13254 mosquitto: add version 2.0.15
  recipes/mosquitto/2.x/conandata.yml
  recipes/mosquitto/config.yml
Labels: Bump version

#13256 Bump parallel-hashmap version to 1.3.8
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#13257 Bump greg7mdp-gtl version to 1.1.5
  recipes/greg7mdp-gtl/all/conandata.yml
  recipes/greg7mdp-gtl/config.yml
Labels: Bump version

#13259 ctre: add version 3.7.1
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#13260 paho-mqtt-c: add version 1.3.11
  recipes/paho-mqtt-c/all/conandata.yml
  recipes/paho-mqtt-c/config.yml
Labels: Bump version

#13272 cpp-sort: add version 1.13.1
  recipes/cpp-sort/all/conandata.yml
  recipes/cpp-sort/config.yml
Labels: Bump version

#13209 docs: explain why no pdb is useful
  docs/faqs.md
Labels: Docs

#13281 unordered_dense: add version 1.4.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#13291 aws-c-sdkutils: add version 0.1.3
  recipes/aws-c-sdkutils/all/conandata.yml
  recipes/aws-c-sdkutils/config.yml
Labels: Bump version

#13295 aws-c-common: add version 0.8.2
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#13237 Update cmake template
  docs/package_templates/cmake_package/all/conanfile.py
Labels: Docs

#13300 aws-c-cal: update dependencies
  recipes/aws-c-cal/all/conanfile.py
Labels: Bump dependencies

#13310 freetype: bump libpng
  recipes/freetype/all/conanfile.py
Labels: Bump dependencies

#13314 gcem: add version 1.16.0
  recipes/gcem/all/conandata.yml
  recipes/gcem/config.yml
Labels: Bump version

#13316 meson: add version 0.63.3
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#13326 (#13323) Bump perfetto to v30.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#13331 [docs] Apply python black formatter over recipe templates
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/msbuild_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/test_package/conanfile.py
Labels: Docs

#13102 docs: Document working locally + Conan 2.0 commands
  CONTRIBUTING.md
  docs/README.md
  docs/consuming_recipes.md
  docs/developing_recipes_locally.md
  docs/how_to_add_packages.md
  docs/labels.md
  docs/linters.md
  docs/review_process.md
  docs/v2_linter.md
Labels: Docs

#13335 simdjson: add version 3.0.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#13348 Ignore CMakeUserPresets.json files
  .gitignore
Labels: GitHub config

#13360 aws-c-cal: add version 0.5.20
  recipes/aws-c-cal/all/conandata.yml
  recipes/aws-c-cal/config.yml
Labels: Bump version

#13374 cppzmq: add version v4.9.0
  recipes/cppzmq/all/conandata.yml
  recipes/cppzmq/config.yml
Labels: Bump version

#13376 Bump plf_list/2.52
  recipes/plf_list/all/conandata.yml
  recipes/plf_list/config.yml
Labels: Bump version

#13377 Bump plf_colony/7.03
  recipes/plf_colony/all/conandata.yml
  recipes/plf_colony/config.yml
Labels: Bump version

#13378 Bump plf_queue/1.21
  recipes/plf_queue/all/conandata.yml
  recipes/plf_queue/config.yml
Labels: Bump version

#13385 templates: Update cmake templates usage of cache variables
  docs/package_templates/cmake_package/all/conanfile.py
Labels: Docs

#13379 Bump plf_stack/1.63
  recipes/plf_stack/all/conandata.yml
  recipes/plf_stack/config.yml
Labels: Bump version

#13396 vulkan-headers: add version 1.3.224.1
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#13409 wayland-protocols: add 1.27
  recipes/wayland-protocols/all/conandata.yml
  recipes/wayland-protocols/config.yml
Labels: Bump version

#13410 cmake: add 3.24.2
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#13426 unordered_dense: add version 2.0.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#13438 fontconfig: bump expat
  recipes/fontconfig/all/conanfile.py
Labels: Bump dependencies

#13439 glib: bump libffi
  recipes/glib/all/conanfile.py
Labels: Bump dependencies

#13412 Bug/zlib/CVE 2022 37434
  recipes/zlib/all/conandata.yml
  recipes/zlib/all/conanfile.py
  recipes/zlib/all/patches/0004-Fix-a-bug-when-getting-a-gzip-header-extra-field-wit.patch
  recipes/zlib/all/patches/0005-Fix-extra-field-processing-bug-that-dereferences-NUL.patch
  recipes/zlib/all/test_package/conanfile.py
  recipes/zlib/all/test_v1_package/conanfile.py
Labels: Service Under Maintenance

#13405 docs: add a copy of the CLA for new contributors
  CONTRIBUTING.md
  docs/CONTRIBUTOR_LICENSE_AGREEMENT.md
  docs/how_to_add_packages.md
  docs/review_process.md
Labels: Docs

#13434 SDL: add v2.24.1
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#13455 daw_header_libraries: add version 2.71.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#13399 qt5: bump reqs
  recipes/qt/5.x.x/conanfile.py
Labels: Bump dependencies

#13471 (#13469) Protobuf: Add 3.19.6
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#13477 modern-cpp-kafka: add version 2022.10.12
  recipes/modern-cpp-kafka/all/conandata.yml
  recipes/modern-cpp-kafka/config.yml
Labels: Bump version

#13493 daw_json_link: add version 3.1.0
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#13528 minizip-ng: add version 3.0.7
  recipes/minizip-ng/all/conandata.yml
  recipes/minizip-ng/config.yml
Labels: Bump version

#13533 osmanip: add version 4.3.0
  recipes/osmanip/all/conandata.yml
  recipes/osmanip/config.yml
Labels: Bump version

#13536 [docs] Add Changelog October 17, 2022
  docs/changelog.md
Labels: Docs

#13461 Move myself to community
  .c3i/reviewers.yml
Labels: C3I config

#13544 bump github actions
  .github/workflows/linter-conan-v2.yml
  .github/workflows/linter-yaml.yml
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#13545 Create dependabot.yml
  .github/dependabot.yml
Labels: infrastructure, GitHub config

#13559 conan v2: ignore the files in `test_output/`
  .gitignore
Labels: GitHub config

#13580 [actions] Revert tj-actions/changed-file to version v20
  .github/workflows/linter-conan-v2.yml
  .github/workflows/linter-yaml.yml
Labels: GitHub config

#13579 Revert "Create dependabot.yml"
  .github/dependabot.yml
Labels: GitHub config

#13575 Add libde265/1.0.9 recipe
  recipes/libde265/all/conandata.yml
  recipes/libde265/all/test_v1_package/conanfile.py
  recipes/libde265/config.yml
Labels: blocked

#13598 opentdf-client: add version 1.3.2
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#13490 docs: v2 migration guidence for `conf_info`
  docs/v2_migration.md
Labels: Docs

#13603 [docs] Add Meson template
  docs/package_templates/README.md
  docs/package_templates/meson_package/all/conandata.yml
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/meson_package/all/test_package/conanfile.py
  docs/package_templates/meson_package/all/test_package/meson.build
  docs/package_templates/meson_package/all/test_package/test_package.cpp
  docs/package_templates/meson_package/all/test_v1_package/conanfile.py
  docs/package_templates/meson_package/config.yml
Labels: Docs

#13591 Add vulkan-headers 1.3.231
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#13610 docs: remove lines to make frameworkdirs and resdirs empty on header_only template
  docs/package_templates/header_only/all/conanfile.py
Labels: Docs

#13615 amqp-cpp: add version 4.3.18
  recipes/amqp-cpp/all/conandata.yml
  recipes/amqp-cpp/config.yml
Labels: Bump version

#13624 harfbuzz: add version 5.3.1
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#13629 meson-template: several improvements
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/meson_package/all/test_package/conanfile.py
  docs/package_templates/meson_package/all/test_v1_package/conanfile.py
Labels: Docs

#13654 daw_header_libraries: add version 2.72.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#13636 autotools template: several improvements
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/autotools_package/all/test_package/CMakeLists.txt
  docs/package_templates/autotools_package/all/test_package/conanfile.py
  docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt
Labels: Docs

#13644 header-only template: several improvements
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/header_only/all/test_package/CMakeLists.txt
  docs/package_templates/header_only/all/test_package/conanfile.py
  docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
Labels: Docs

#13656 [cmake-template] Simplify test_v1_package CMakeLists.txt
  docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
Labels: Docs

#13675 cli11: add version 2.3.0
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#13676 wolfssl: add version 5.5.1
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#13692 daw_json_link: add version 3.1.1
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#13701 c-blosc: update zlib
  recipes/c-blosc/all/conanfile.py
Labels: Bump dependencies

#13702 cpp-httplib: update zlib
  recipes/cpp-httplib/all/conanfile.py
Labels: Bump dependencies

#13681 taywee-args: conan v2 support
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/all/conanfile.py
  recipes/taywee-args/all/test_package/CMakeLists.txt
  recipes/taywee-args/all/test_package/conanfile.py
  recipes/taywee-args/all/test_v1_package/CMakeLists.txt
  recipes/taywee-args/all/test_v1_package/conanfile.py
Labels: checksum_mismatch

#13690 [doc] Fix tools_requires => tool_requires
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/test_package/conanfile.py
Labels: Docs

#13602 actions: upgrade changed-files version
  .github/workflows/linter-conan-v2.yml
  .github/workflows/linter-yaml.yml
Labels: GitHub config

#13274 linters: Add annotations for YAML lint + add schema verification for `config.yml` and `conandata.yml`
  .github/workflows/linter-yaml.yml
  docs/conandata_yml_format.md
  docs/developing_recipes_locally.md
  docs/linters.md
  docs/package_templates/autotools_package/all/conandata.yml
  docs/package_templates/cmake_package/all/conandata.yml
  docs/package_templates/header_only/all/conandata.yml
  docs/package_templates/meson_package/all/conandata.yml
  docs/package_templates/msbuild_package/all/conandata.yml
  linter/conandata_yaml_linter.py
  linter/config_yaml_linter.py
  linter/yaml_linting.py
  linter/yamllint_matcher.json
Labels: Docs, GitHub config

#13749 libslz: add version 1.2.1
  recipes/libslz/all/conandata.yml
  recipes/libslz/config.yml
Labels: Bump version

#13762 glaze: add version 0.1.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#13763 watcher: add version 0.3.2
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#13779 Fix conandata_yaml_linter
  linter/conandata_yaml_linter.py
Labels: GitHub config

#13780 function2: add version 4.2.2
  recipes/function2/all/conandata.yml
  recipes/function2/config.yml
Labels: Bump version

#13788 Bump vulkan-headers/1.3.231.1
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#13798 libtiff - bump dep version for zlib
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#13819 Bump draco/1.5.4
  recipes/draco/all/conandata.yml
  recipes/draco/config.yml
Labels: Bump version

#13824 watcher: add version 0.3.3
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#13823 quill: add version 2.3.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#13825 kuba-zip: add version 0.2.6
  recipes/kuba-zip/all/conandata.yml
  recipes/kuba-zip/config.yml
Labels: Bump version

#13810 [release] 27 October 2022
  docs/changelog.md
Labels: Docs

#13831 jenkins windows tag updated to windows20221024
  .c3i/config_v1.yml
Labels: C3I config

#13756 Bump volk/1.3.231.0
  recipes/volk/all/conandata.yml
  recipes/volk/config.yml
Labels: Bump version

#13840 jsonnet: add version 0.19.1
  recipes/jsonnet/all/conandata.yml
  recipes/jsonnet/config.yml
Labels: Bump version

#13842 highway: add version 1.0.2
  recipes/highway/all/conandata.yml
  recipes/highway/config.yml
Labels: Bump version

#13754 docs: remove workaround for info object in validate
  docs/package_templates/header_only/all/conanfile.py
Labels: Docs

#13836 [config] Update windows node labels for conan v2 config too
  .c3i/config_v2.yml
Labels: C3I config

#13832 [docs] Bump version label only accepts SEMVER and MAJOR.MINOR
  docs/labels.md
Labels: Docs

#13850 pcre: bump zlib
  recipes/pcre/all/conanfile.py
Labels: Bump dependencies

#13852 daw_header_libraries: add version 2.73.1
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#13856 daw_json_link: add version 3.3.0
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#13635 updated flatbuffers 22.9.24 and 22.9.29
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#13868 Bump draco/1.5.5
  recipes/draco/all/conandata.yml
  recipes/draco/config.yml
Labels: Bump version

#13871 daw_utf_range: update dependencies
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#13873 daw_json_link: update dependencies
  recipes/daw_json_link/all/conanfile.py
Labels: Bump dependencies

#13895 utf8proc: add version 2.8.0
  recipes/utf8proc/all/conandata.yml
  recipes/utf8proc/config.yml
Labels: Bump version

#13884 boost: update zlib
  recipes/boost/all/conanfile.py
Labels: Bump dependencies
