Repository conan-io/conan-center-index, pull requests merged in 2022-09, with the labels that each got.

#12688 github config: allow forks to manually run TOC generation
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#12798 emsdk version 3.1.20
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#12813 Bump cpp-peglib/1.8.0
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#12818 libsystemd/all: Bump dependencies
  recipes/libsystemd/all/conanfile.py
Labels: Bump dependencies

#12849 [docs] CMake package template
  docs/package_templates/cmake_package/all/conandata.yml
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/cmake_package/all/test_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/test_package/conanfile.py
  docs/package_templates/cmake_package/all/test_package/test_package.cpp
  docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/test_v1_package/conanfile.py
  docs/package_templates/cmake_package/config.yml
Labels: Docs

#12860 daw_json_link: add version 3.0.5
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#12851 [docs] header-only package template
  docs/package_templates/header_only/all/conandata.yml
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/header_only/all/test_package/CMakeLists.txt
  docs/package_templates/header_only/all/test_package/conanfile.py
  docs/package_templates/header_only/all/test_package/test_package.cpp
  docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
  docs/package_templates/header_only/all/test_v1_package/conanfile.py
  docs/package_templates/header_only/config.yml
Labels: Docs

#12857 Add restinio v0.6.17
  recipes/restinio/all/conandata.yml
  recipes/restinio/config.yml
Labels: Bump version

#12853 [docs] Add prebuilt package template
  docs/package_templates/prebuilt_tool_package/all/conandata.yml
  docs/package_templates/prebuilt_tool_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/test_package/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/test_v1_package/conanfile.py
  docs/package_templates/prebuilt_tool_package/config.yml
Labels: Docs

#12869 [docs] How to run linter locally
  docs/v2_linter.md
Labels: Docs

#12852 [docs] Add msbuild package template
  docs/package_templates/msbuild_package/all/conandata.yml
  docs/package_templates/msbuild_package/all/conanfile.py
  docs/package_templates/msbuild_package/all/test_package/CMakeLists.txt
  docs/package_templates/msbuild_package/all/test_package/conanfile.py
  docs/package_templates/msbuild_package/all/test_package/test_package.cpp
  docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/msbuild_package/all/test_v1_package/conanfile.py
  docs/package_templates/msbuild_package/config.yml
Labels: Docs

#12872 docs: how to alert consumers to problems
  docs/faqs.md
Labels: Docs

#12704 docs: update documentation for handling recipe changes
  docs/consuming_recipes.md
  docs/faqs.md
Labels: Docs

#12865 cpp-peglib: add version 1.8.1
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#12875 roaring: add version 0.7.1
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#12878 [docs] source subfolder is no longer used
  docs/package_templates/autotools_package/all/conandata.yml
  docs/package_templates/cmake_package/all/conandata.yml
  docs/package_templates/header_only/all/conandata.yml
  docs/package_templates/msbuild_package/all/conandata.yml
Labels: Docs

#12886 earcut: add version 2.2.4
  recipes/earcut/all/conandata.yml
  recipes/earcut/config.yml
Labels: Bump version

#12897 msgpack-cxx: add version 4.1.2
  recipes/msgpack-cxx/all/conandata.yml
  recipes/msgpack-cxx/config.yml
Labels: Bump version

#12905 [docs] `config.yml` file is mandatory
  docs/conandata_yml_format.md
  docs/faqs.md
  docs/how_to_add_packages.md
Labels: Docs

#12908 Use target_compile_features for package_templates/cmake_package/all/test_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
Labels: Docs

#12912 Add libltc/1.3.2 version
  recipes/libltc/all/conandata.yml
  recipes/libltc/config.yml
Labels: Bump version

#12913 [docs] Clarify Unexpected error restarting
  docs/labels.md
Labels: Docs

#12914 etl: add version 20.34.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#12934 docs: 2.0 migration guidance for subfolders
  docs/reviewing.md
  docs/v2_migration.md
Labels: Docs

#12936 [xnnpack] Add cci.20220801
  recipes/xnnpack/all/conandata.yml
  recipes/xnnpack/config.yml
Labels: Bump version

#12940 cpp-httplib: add version 0.11.2
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#12959 [linter] Convert import ConanFile from conans into an error
  linter/check_import_conanfile.py
Labels: C3I config

#12975 added new Version 7.85.0
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#12978 [docs] package_templates/cmake_package : fix `cache_variables.definitions` and add `configure`
  docs/package_templates/cmake_package/all/conanfile.py
Labels: Docs

#12982 magic_enum: add version 0.8.1
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#12984 libnghttp2: add version 1.49.0
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#12992 kuba-zip: add version 0.2.5
  recipes/kuba-zip/all/conandata.yml
  recipes/kuba-zip/config.yml
Labels: Bump version

#12994 statslib: add version 3.2.0
  recipes/statslib/all/conandata.yml
  recipes/statslib/config.yml
Labels: Bump version

#12998 at-spi2-core: add version 2.46.0
  recipes/at-spi2-core/config.yml
  recipes/at-spi2-core/new/conandata.yml
Labels: Bump version

#13003 thrift: add version 0.17.0
  recipes/thrift/all/conandata.yml
  recipes/thrift/config.yml
Labels: Bump version

#13005 update sqlite 3.39.3
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#12965 [docs] Safer autotools template
  docs/package_templates/autotools_package/all/conanfile.py
Labels: Docs

#12996 glib: add version 2.74.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#13014 [docs] Fix leftover dot for cache_variables
  docs/package_templates/cmake_package/all/conanfile.py
Labels: Docs

#13015 json-c: add version 0.16
  recipes/json-c/all/conandata.yml
  recipes/json-c/config.yml
Labels: Bump version

#13040 [config] Update conan version to 1.52.0
  .c3i/config_v1.yml
Labels: C3I config

#13046 opentdf-client: add version 1.1.6
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#12281 docs: capture our policy for the options `shared` and `fPIC`
  docs/faqs.md
  docs/packaging_policy.md
  docs/reviewing.md
Labels: Docs

#12931 [docs] How to add packages based on new templates
  docs/how_to_add_packages.md
  docs/package_templates/README.md
Labels: Docs

#12973 [docs] Enforce to ask more details when reporting a bug report
  .github/ISSUE_TEMPLATE/package_bug.yml
Labels: GitHub config

#12989 docs: using different build helpers with layouts
  docs/v2_migration.md
Labels: Docs

#13054 cpp-peglib: add version 1.8.2
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#13055 add expat version 2.4.9
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#13088 libglvnd/1.5.0
  recipes/libglvnd/all/conandata.yml
  recipes/libglvnd/config.yml
Labels: Bump version

#13089 freeglut/3.2.2
  recipes/freeglut/all/conandata.yml
  recipes/freeglut/config.yml
Labels: Bump version

#12979 Add libpng 1.6.38 to conandata and config
  recipes/libpng/all/conandata.yml
  recipes/libpng/config.yml
Labels: Bump version

#13078 xorg-proto 2022.2
  recipes/xorg-proto/all/conandata.yml
  recipes/xorg-proto/config.yml
Labels: Bump version

#13079 srawberryperl 5.32.1.1
  recipes/strawberryperl/all/conandata.yml
  recipes/strawberryperl/config.yml
Labels: Bump version

#13081 pkgconf/1.9.3
  recipes/pkgconf/all/conandata.yml
  recipes/pkgconf/all/patches/1.9.3-0003-PKG_CONF_PATH-allow-colon+semicolon-separator.patch
  recipes/pkgconf/config.yml
Labels: Bump version

#13083 nspr/4.35
  recipes/nspr/all/conandata.yml
  recipes/nspr/config.yml
Labels: Bump version

#13085 libpq/14.5
  recipes/libpq/all/conandata.yml
  recipes/libpq/config.yml
Labels: Bump version

#13087 libjpeg/9e
  recipes/libjpeg/all/conandata.yml
  recipes/libjpeg/all/patches/0001-9e-libjpeg-add-msvc-dll-support.patch
  recipes/libjpeg/config.yml
Labels: Bump version

#13100 unordered_dense: add version 1.3.2
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#13093 [templates] Use Conan 1.52.0 feature
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/msbuild_package/all/conanfile.py
Labels: Docs

#13103 docs: use export_conandata_patches
  docs/how_to_add_packages.md
  docs/reviewing.md
Labels: Docs

#13104 [parallel-hashmap] bump version to 1.36
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#13108 [greg7mdp-gtl] bump version to 1.1.3
  recipes/greg7mdp-gtl/all/conandata.yml
  recipes/greg7mdp-gtl/config.yml
Labels: Bump version

#12255 update diligent-core tag signature
  recipes/diligent-core/all/conandata.yml
  recipes/diligent-core/all/conanfile.py
Labels: checksum_mismatch

#13127 quill: add version 2.2.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#13140 add emsdk version 3.1.23
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#13146 unordered_dense: add version 1.3.3
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#13147 itlib: add version 1.6.3
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#13149 proposal: bump to 7.4.2
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#13150 greg7mdp-gtl: add version 1.1.4
  recipes/greg7mdp-gtl/all/conandata.yml
  recipes/greg7mdp-gtl/config.yml
Labels: Bump version

#13111 serd/0.30.16 version bump
  recipes/serd/all/conandata.yml
  recipes/serd/all/test_v1_package/conanfile.py
  recipes/serd/config.yml
Labels: Bump version

#13117 argparse: add version 2.9
  recipes/argparse/all/conandata.yml
  recipes/argparse/config.yml
Labels: Bump version

#13161 parallel-hashmap: add version 1.37
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#13166 poco: bump sqlite3 dependency version for MacOS
  recipes/poco/all/conanfile.py
Labels: Bump dependencies

#13172 odbc 2.3.11
  recipes/odbc/all/conandata.yml
  recipes/odbc/config.yml
Labels: Bump version

#13072 [docs] Templates documentation: Fix link for test package
  docs/how_to_add_packages.md
Labels: Docs

#13101 github_config: add an action to validate markdown links
  .github/workflows/marldown-links.yml
  .github/workflows/mlc_config.json
Labels: GitHub config

#13191 [docs] update the order of attributes
  docs/reviewing.md
Labels: Docs

#13193 [community] Add jwillikers as community reviewer
  .c3i/reviewers.yml
Labels: C3I config

#13200 opentdf-client: add version 1.2.0
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#13208 docs: add link to Twitter for more visibility
  docs/community_resources.md
Labels: Docs

#13210 docs: update list of reviewers
  docs/review_process.md
Labels: Docs

#13216 osmanip: add version 4.2.2
  recipes/osmanip/all/conandata.yml
  recipes/osmanip/config.yml
Labels: Bump version

#13217 libglvnd: generate gcc11 binaries
  recipes/libglvnd/all/conanfile.py
Labels: Bump dependencies

#13229 Add logr v0.5.1
  recipes/logr/all/conandata.yml
  recipes/logr/config.yml
Labels: Bump version

#13226 sqlite3: add version 3.39.4 and remove older versions
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/all/test_v1_package/conanfile.py
  recipes/sqlite3/config.yml
Labels: Bump version

#13230 docs: fix broken links
  docs/consuming_recipes.md
  docs/faqs.md
Labels: Docs

#12946 [docs] Add a brief explanation about linters
  docs/linters.md
Labels: Docs

#13246 [libyuv] Update libjpeg to 9e
  recipes/libyuv/all/conanfile.py
Labels: Bump dependencies
