Repository conan-io/conan-center-index, pull requests merged in 2022-12, with the labels that each got.

#14494 cpp-httplib: add version 0.11.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#14511 xsimd: add version 10.0.0
  recipes/xsimd/all/conandata.yml
  recipes/xsimd/config.yml
Labels: Bump version

#14522 [jfalcou-eve] upgrade to v2022.09.1
  recipes/jfalcou-eve/all/conandata.yml
  recipes/jfalcou-eve/config.yml
Labels: Bump version

#14473 [jwt-cpp] Bump openssl
  recipes/jwt-cpp/all/conanfile.py
Labels: Bump dependencies

#14520 [freetype] Bump libpng version
  recipes/freetype/all/conanfile.py
Labels: Bump dependencies

#14521 [fontconfig] Bump expat version
  recipes/fontconfig/meson/conanfile.py
Labels: Bump dependencies

#14523 docs: update Intel URLs
  docs/faqs.md
Labels: Docs

#14528 wayland: bump reqs
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#14467 bump version: metall v0.23.1
  recipes/metall/all/conandata.yml
  recipes/metall/all/test_v1_package/conanfile.py
  recipes/metall/config.yml
Labels: Bump version

#14491 Docs: split up reviewing into new file sections
  docs/adding_packages/README.md
  docs/adding_packages/conanfile_attributes.md
  docs/adding_packages/reviewing.md
  docs/adding_packages/sources_and_patches.md
  docs/adding_packages/test_packages.md
  docs/error_knowledge_base.md
  docs/faqs.md
Labels: Docs

#14533 xkbcommon: bump reqs
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#14549 md4qt: bump version to 2.0.3.
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#14551 daw_header_libraries: add version 2.76.3
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#14555 daw_utf_range: add version 2.2.3
  recipes/daw_utf_range/all/conandata.yml
  recipes/daw_utf_range/config.yml
Labels: Bump version

#14560 daw_json_link: add version 3.11.1
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#14557 Bump entt/3.11.1
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#14565 Bump reactiveplusplus/0.2.1
  recipes/reactiveplusplus/all/conandata.yml
  recipes/reactiveplusplus/config.yml
Labels: Bump version

#14568 daw_utf_range: update dependencies
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#14570 daw_json_link: update dependencies
  recipes/daw_json_link/all/conanfile.py
Labels: Bump dependencies

#14579 glibmm: bump reqs
  recipes/glibmm/all/conanfile.py
Labels: Bump dependencies

#14583 [config] Add Ruben as reviewer
  .c3i/authorized_users.yml
  .c3i/reviewers.yml
Labels: C3I config

#14617 pybind11_json: add version 0.2.13
  recipes/pybind11_json/all/conandata.yml
  recipes/pybind11_json/config.yml
Labels: Bump version

#14652 flatbuffers: add version 22.12.06
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#14654 nss 3.86
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#14655 etl: add version 20.35.5
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#14658 Update changelog 09-December-2022
  docs/changelog.md
Labels: Docs

#14664 sqlite_orm: add version 1.8
  recipes/sqlite_orm/all/conandata.yml
  recipes/sqlite_orm/config.yml
Labels: Bump version

#14673 fast_double_parser: add version 0.7.0
  recipes/fast_double_parser/all/conandata.yml
  recipes/fast_double_parser/config.yml
Labels: Bump version

#14672 luau: add version 0.556
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#14679 tgbot: add version 1.5
  recipes/tgbot/all/conandata.yml
  recipes/tgbot/config.yml
Labels: Bump version

#14684 imath: add version 3.1.6
  recipes/imath/all/conandata.yml
  recipes/imath/config.yml
Labels: Bump version

#14527 templates: bunch of small cleanups
  docs/package_templates/autotools_package/all/conandata.yml
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/cmake_package/all/conandata.yml
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/cmake_package/all/test_package/CMakeLists.txt
  docs/package_templates/header_only/all/conandata.yml
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/header_only/all/test_package/CMakeLists.txt
  docs/package_templates/meson_package/all/conandata.yml
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/msbuild_package/all/conandata.yml
  docs/package_templates/msbuild_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/test_package/conanfile.py
Labels: Docs

#14691 catch2: add version 3.2.1
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#14706 zpp_bits: add version 4.4.12
  recipes/zpp_bits/all/conandata.yml
  recipes/zpp_bits/config.yml
Labels: Bump version

#14716 (docs) Improve PR template experience
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub config

#14695 [fix] Run gh-action markdown link check only when changing md files
  .github/workflows/markdown-links.yml
  .github/workflows/marldown-links.yml
Labels: GitHub config

#14640 glaze: add version 0.2.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#14724 Bump vulkan-headers/1.3.236.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#14725 Bump spirv-headers/1.3.236.0
  recipes/spirv-headers/all/conandata.yml
  recipes/spirv-headers/config.yml
Labels: Bump version

#14738 [config] Add new windows nodes and bump conan v1 version
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#14743 Bump flecs/3.1.2
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version

#14745 wavelet_buffer: add version 0.5.0
  recipes/wavelet_buffer/all/conandata.yml
  recipes/wavelet_buffer/config.yml
Labels: Bump version

#14751 opentdf-client: add version 1.3.6
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#14746 simdutf: add version 2.0.8
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#14756 glaze: add version 0.2.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#14740 Bump spirv-tools/1.3.236.0
  recipes/spirv-tools/all/conandata.yml
  recipes/spirv-tools/all/dependencies/dependencies-1.3.236.0.yml
  recipes/spirv-tools/config.yml
Labels: Bump version

#14760 [docs] Update changelog 15-December-2022
  docs/changelog.md
Labels: Docs

#14763 glaze: add version 0.2.2, fix wrong url for 0.2.1, delete older versions
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#14771 simdutf: add version 2.0.9
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#14773 c-blosc2: add version 2.6.1
  recipes/c-blosc2/all/conandata.yml
  recipes/c-blosc2/config.yml
Labels: Bump version

#14741 Bump volk/1.3.236.0
  recipes/volk/all/conandata.yml
  recipes/volk/config.yml
Labels: Bump version

#14777 fakeit: add version 2.3.1
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#14783 daw_header_libraries: add version 2.79.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#14784 harfbuzz: add version 6.0.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#14786 daw_json_link: add version 3.12.0
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#14799 fakeit: add version 2.3.2
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#14805 s2n: add version 1.3.31
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#14808 netcdf - bump libcurl dep version
  recipes/netcdf/all/conanfile.py
Labels: Bump dependencies

#14726 Bump spirv-cross/1.3.236.0
  recipes/spirv-cross/all/conandata.yml
  recipes/spirv-cross/all/patches/1.3.236.0-0001-fix-gcc5.patch
  recipes/spirv-cross/config.yml
Labels: Bump version

#14675 linter: Add error when layouts are missing `src_folder` in recipe
  linter/check_layout_src_folder.py
  linter/conanv2_transition.py
Labels: GitHub config

#14833 docs: add working with dependencies to give a lot more guidance
  docs/adding_packages/README.md
  docs/adding_packages/dependencies.md
  docs/adding_packages/test_packages.md
  docs/error_knowledge_base.md
  docs/faqs.md
Labels: Docs

#14015 linter: improve conandata.yml linter output
  .github/workflows/linter-yaml.yml
  .github/workflows/markdown-links.yml
  linter/conandata_yaml_linter.py
Labels: GitHub config

#14842 etl: add version 20.35.7
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#14845 [Maintenance] Clarify docs around the settings attribute
  docs/adding_packages/conanfile_attributes.md
Labels: Docs

#14766 [config] Activate conan v2 pipeline feedback in github comments
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#13285 [jasper] Add version 3.0.6 and cross-support Conan v1 and v2
  recipes/jasper/all/CMakeLists.txt
  recipes/jasper/all/conandata.yml
  recipes/jasper/all/conanfile.py
  recipes/jasper/all/patches/2.0.33-0001-skip-rpath.patch
  recipes/jasper/all/patches/2.0.33-0002-find-libjpeg.patch
  recipes/jasper/all/patches/3.0.6-0001-skip-rpath.patch
  recipes/jasper/all/patches/3.0.6-0002-find-libjpeg.patch
  recipes/jasper/all/patches/3.0.6-0003-deterministic-libname.patch
  recipes/jasper/all/patches/fix-exported-symbols.patch
  recipes/jasper/all/test_package/CMakeLists.txt
  recipes/jasper/all/test_package/conanfile.py
  recipes/jasper/all/test_v1_package/CMakeLists.txt
  recipes/jasper/all/test_v1_package/conanfile.py
  recipes/jasper/config.yml
Labels: Failed

#14831 docs: how we handle rare build system
  docs/faqs.md
Labels: Docs

#14674 docs: Add "no individual boost libraries" to FAQ
  docs/faqs.md
Labels: Docs

#14856 docs: Move build system examples to new file
  docs/adding_packages/README.md
  docs/adding_packages/build_and_package.md
  docs/adding_packages/test_packages.md
  docs/error_knowledge_base.md
  docs/faqs.md
Labels: Docs

#14887 bitsery: add version 5.2.3
  recipes/bitsery/all/conandata.yml
  recipes/bitsery/config.yml
Labels: Bump version

#14896 docs: Improve language around folder layouts from hooks
  docs/error_knowledge_base.md
Labels: Docs

#14875 Improve the comments in the header-only template
  docs/package_templates/header_only/all/conanfile.py
Labels: Docs

#14888 boost: Add 1.81.0
  recipes/boost/all/conandata.yml
  recipes/boost/all/conanfile.py
  recipes/boost/all/dependencies/dependencies-1.81.0.yml
  recipes/boost/all/patches/1.81.0-locale-fail-on-missing-backend.patch
  recipes/boost/config.yml
Labels: Failed

#14890 jasper: add 4.0.0 + allow to disable jpeg or use mozjpeg
  recipes/jasper/all/conandata.yml
  recipes/jasper/all/conanfile.py
  recipes/jasper/all/patches/4.0.0-0001-skip-rpath.patch
  recipes/jasper/all/patches/4.0.0-0002-find-libjpeg.patch
  recipes/jasper/all/patches/4.0.0-0003-deterministic-libname.patch
  recipes/jasper/config.yml
Labels: Failed

#14955 User set_property in libunwind
  recipes/libunwind/all/conanfile.py
Labels: Failed

#13666 Update mold to 1.7.1
  recipes/mold/all/conandata.yml
  recipes/mold/all/conanfile.py
  recipes/mold/all/patches/0001-fix-install.patch
  recipes/mold/config.yml
Labels: Failed

#14966 [linter] Fix vs_layout has no folder param. Adds bazel_layout
  linter/check_layout_src_folder.py
Labels: GitHub config

#14969 libarchive: add version 3.6.2
  recipes/libarchive/all/conandata.yml
  recipes/libarchive/all/patches/0001-3.6.2-zlib-winapi.patch
  recipes/libarchive/all/patches/0003-3.6.2-cmake.patch
  recipes/libarchive/config.yml
Labels: Failed

#14973 docs: remove PEP8 formating request
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub config

#14984 etl: add version 20.35.8
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#14895 linter: reduce spam for notification from actions + lower error level
  .github/workflows/linter-yaml.yml
  linter/conandata_yaml_linter.py
Labels: GitHub config

#14963 glu/system conan v2 updates
  recipes/glu/all/conanfile.py
  recipes/glu/all/test_package/CMakeLists.txt
  recipes/glu/all/test_package/conanfile.py
  recipes/glu/all/test_v1_package/CMakeLists.txt
  recipes/glu/all/test_v1_package/conanfile.py
  recipes/glu/all/test_v1_package/test_package.c
Labels: Failed

#14633 catch2/2.x: use `self.info` in package id method
  recipes/catch2/2.x.x/conanfile.py
Labels: Failed

#14977 glib 2.75.1
  recipes/glib/all/conandata.yml
  recipes/glib/all/conanfile.py
  recipes/glib/all/patches/0001-2.74.0-clang-static-assert.patch
  recipes/glib/config.yml
Labels: Failed

#14990 docs: Adjust PR template to say current client version
  .github/PULL_REQUEST_TEMPLATE.md
  docs/adding_packages/README.md
Labels: Docs, GitHub config

#14992 Bump flecs/3.1.3
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version

#14994 itlib: add version 1.8.0
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#14995 tuplet: add version 2.1.0
  recipes/tuplet/all/conandata.yml
  recipes/tuplet/config.yml
Labels: Bump version

#14993 Docs: fix bad link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub config

#14975 libpciaccess 0.17
  recipes/libpciaccess/all/conandata.yml
  recipes/libpciaccess/all/test_v1_package/conanfile.py
  recipes/libpciaccess/config.yml
Labels: checksum_mismatch

#14976 libdrm 2.4.114
  recipes/libdrm/all/conandata.yml
  recipes/libdrm/all/conanfile.py
  recipes/libdrm/config.yml
Labels: Failed

#15015 taywee-args: add version 6.4.4
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#14776 boost: honor `tools.build:compiler_executables` config & env vars from `[buildenv]`
  recipes/boost/all/conanfile.py
Labels: Failed
