Repository conan-io/conan-center-index, pull requests merged in 2022-05, with the labels that each got.

#10568 tomlplusplus: add version 3.1.0
  recipes/tomlplusplus/all/conandata.yml
  recipes/tomlplusplus/config.yml
Labels: Bump version

#10606 sqlite3 updated to 3.38.3
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#10621 djinni-generator version update to v1.3.1
  recipes/djinni-generator/all/conandata.yml
  recipes/djinni-generator/config.yml
Labels: Bump version

#10619 sentry-native: Bump qt version to 5.15.3
  recipes/sentry-native/all/conanfile.py
Labels: Bump dependencies

#10622 djinni-support-lib version update to v1.2.1
  recipes/djinni-support-lib/1.x.x/conandata.yml
  recipes/djinni-support-lib/config.yml
Labels: Bump version

#10632 libressl: add 3.5.2
  recipes/libressl/all/conandata.yml
  recipes/libressl/config.yml
Labels: Bump version

#10651 Bump entt/3.10.1
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#10653 sqlite3 updated to 3.38.4
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#10639 docs: use relative links
  docs/error_knowledge_base.md
  docs/faqs.md
  docs/how_to_add_packages.md
Labels: Docs

#10654 Bump cpp-httplib/0.10.7
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#10655 Bump libmorton/0.2.10
  recipes/libmorton/all/conandata.yml
  recipes/libmorton/config.yml
Labels: Bump version

#10660 Bump spectra/1.0.1
  recipes/spectra/all/conandata.yml
  recipes/spectra/config.yml
Labels: Bump version

#10669 wasmtime-cpp: add version 0.36.0
  recipes/wasmtime-cpp/all/conandata.yml
  recipes/wasmtime-cpp/config.yml
Labels: Bump version

#10680 sqlite3 updated to 3.38.5
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#10580 add libcurl version 7.83.0
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#10681 arrow: update dependencies
  recipes/arrow/all/conanfile.py
Labels: Bump dependencies

#10719 magic_enum: add version 0.8.0
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#10731 Update changelog 28-April-2022
  docs/changelog.md
Labels: Docs

#10699 Add codeowners file
  .github/CODEOWNERS
Labels: GitHub config

#10735 doxygen 1.9.4 support added
  recipes/doxygen/all/conandata.yml
  recipes/doxygen/config.yml
Labels: Bump version

#10751 [doc] Draft next steps in our way to Conan v2
  README.md
  docs/README.md
  docs/v2_migration.md
  docs/v2_roadmap.md
Labels: Docs

#10748 libxml2: add 2.9.14
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#10667 elfutils: bump zlib version
  recipes/elfutils/all/conanfile.py
Labels: Bump dependencies

#10772 daw_header_libraries: add version 2.50.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#10783 opentelemetry-proto: add version 0.17.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#10789 st_tree: add version 1.2.2
  recipes/st_tree/all/conandata.yml
  recipes/st_tree/config.yml
Labels: Bump version

#9841 create a recipe template
  docs/package/all/CMakeLists.txt
  docs/package/all/conandata.yml
  docs/package/all/conanfile.py
  docs/package/all/test_package/CMakeLists.txt
  docs/package/all/test_package/conanfile.py
  docs/package/config.yml
Labels: Docs

#10809 [aws-c-common] add new versions
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#10823 Add SObjectizer v.5.7.4
  recipes/sobjectizer/all/conandata.yml
  recipes/sobjectizer/config.yml
Labels: Bump version

#10395 Create hooks-warnings.yml
  .github/workflows/hooks-warnings.yml
Labels: GitHub config

#10841 [doc] Fix typo
  docs/v2_roadmap.md
Labels: Docs

#10854 uncrustify: add version 0.75.1
  recipes/uncrustify/all/conandata.yml
  recipes/uncrustify/config.yml
Labels: Bump version

#10834 cmake: bump openssl
  recipes/cmake/3.x.x/conanfile.py
Labels: Bump dependencies

#10814 Add protobuf v3.15.8
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#10840 lockfiles: link issues in v1, add note around recommendation
  docs/faqs.md
Labels: Docs

#10853 hooks-warnings: ignore log download errors
  .github/workflows/hooks-warnings.yml
Labels: GitHub config

#10868 [docs] Update changelog 19-May-2022
  docs/changelog.md
Labels: Docs

#10882 blend2d: add version 0.0.18
  recipes/blend2d/all/conandata.yml
  recipes/blend2d/config.yml
Labels: Bump version

#10886 xkbcommon: add version 1.4.1
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/config.yml
Labels: Bump version

#10896 harfbuzz: add version 4.3.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#10898 enjincppsdk: add version `1.0.0-alpha.6`
  recipes/enjincppsdk/all/conandata.yml
  recipes/enjincppsdk/config.yml
Labels: Bump version

#10927 wayland - bump deps for libxml2 2.9.13 --> 2.9.14
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#10946 wolfssl: add version 5.3.0
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#10954 llvm-core: bump zlib
  recipes/llvm-core/all/conanfile.py
Labels: Bump dependencies

#10969 yyjson: add version 0.5.0
  recipes/yyjson/all/conandata.yml
  recipes/yyjson/config.yml
Labels: Bump version

#10970 libressl: add 3.5.3
  recipes/libressl/all/conandata.yml
  recipes/libressl/config.yml
Labels: Bump version

#10926 proj: bump dependency for sqlite3 and libcurl
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#10929 Qt bump xkbcommon, glib, harfbuzz, sqlite3
  recipes/qt/5.x.x/conanfile.py
  recipes/qt/6.x.x/conanfile.py
Labels: Bump dependencies

#10973 Add expected-lite/0.6.0
  recipes/expected-lite/all/conandata.yml
  recipes/expected-lite/config.yml
Labels: Bump version

#10981 etl: add version 20.28.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#10982 cwalk: add version 1.2.7
  recipes/cwalk/all/conandata.yml
  recipes/cwalk/config.yml
Labels: Bump version

#10985 daw_header_libraries: add version 2.53.3
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#10851 [package] netcdf/4.8.1: Upgrade to 4.8.1. Fix up patches for 4.7.4.
  recipes/netcdf/all/conandata.yml
  recipes/netcdf/all/conanfile.py
  recipes/netcdf/all/patches/0001-cmake-subproject.patch
  recipes/netcdf/all/patches/4.7.4-0001-cmake-subproject.patch
  recipes/netcdf/all/patches/4.7.4-0002-cmake-msvc.patch
  recipes/netcdf/all/patches/4.7.4-0003-cmake-HDF5-cmake-components-wrong.patch
  recipes/netcdf/all/patches/4.8.1-0001-fix-cmake.patch
  recipes/netcdf/config.yml
Labels: Service Under Maintenance

#10995 cpp-peglib: add version 1.4.1
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version
