Repository conan-io/conan-center-index, pull requests merged in 2022-04, with the labels that each got.

#10044 frozen: add 1.1.1
  recipes/frozen/all/conandata.yml
  recipes/frozen/config.yml
Labels: Bump version

#10092 cppcheck: add version 2.7.4
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#10078 ctre: add version 3.6
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#10076 benchmark: add version 1.6.1
  recipes/benchmark/all/conandata.yml
  recipes/benchmark/config.yml
Labels: Bump version

#10101 cli11: add version 2.2.0
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#10105 pcre: Bump requirement zlib/1.2.11 to zlib/1.2.12
  recipes/pcre/all/conanfile.py
Labels: Bump dependencies

#10054 opentdf-client: add version 0.6.3
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#10109 [spdlog] Bump version 1.10.0
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#10108 quill: update fmt to 8.1.1 on quill/1.6.3
  recipes/quill/all/conanfile.py
Labels: Bump dependencies

#10114 [gdbm] bump deps
  recipes/gdbm/all/conanfile.py
Labels: Bump dependencies

#10124 etl: add version 20.27.1
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#10120 bump dependencies of libxml2
  recipes/libxml2/all/conanfile.py
Labels: Bump dependencies

#10122 wolfssl: add version 5.2.0
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#10131 harfbuzz: bump glib
  recipes/harfbuzz/all/conanfile.py
Labels: Bump dependencies

#10149 tsl-robin-map: add version 1.0.1
  recipes/tsl-robin-map/all/conandata.yml
  recipes/tsl-robin-map/config.yml
Labels: Bump version

#10150 libunwind: Update to 1.6.2
  recipes/libunwind/all/conandata.yml
  recipes/libunwind/config.yml
Labels: Bump version

#10143 updated sentry-native dependencies
  recipes/sentry-native/all/conanfile.py
Labels: Bump dependencies

#10161 daw_header_libraries: add version 2.33.2
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#10142 update ffmpeg dependency
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#10145 bump dependencies of sentry-crashpad
  recipes/sentry-crashpad/all/conanfile.py
Labels: Bump dependencies

#10156 freetype: bump zlib
  recipes/freetype/all/conanfile.py
Labels: Bump dependencies

#10157 pcre2: bump zlib
  recipes/pcre2/all/conanfile.py
Labels: Bump dependencies

#10180 [hdf4] Bump dependencies
  recipes/hdf4/all/conanfile.py
Labels: Bump dependencies

#10144 bump dependency of libpq
  recipes/libpq/all/conanfile.py
Labels: Bump dependencies

#10095 [docs] Add more information to the review process
  docs/reviewing.md
Labels: Docs

#10141 update libcurl dependency
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#10189 aws-sdk-cpp: update dependencies
  recipes/aws-sdk-cpp/all/conanfile.py
Labels: Bump dependencies

#10196 cfitsio: bump zlib
  recipes/cfitsio/all/conanfile.py
Labels: Bump dependencies

#10195 libtiff: bump dependencies
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#10197 c-blosc: bump zlib
  recipes/c-blosc/all/conanfile.py
Labels: Bump dependencies

#10205 mongo-c-driver: bump dependencies
  recipes/mongo-c-driver/all/conanfile.py
Labels: Bump dependencies

#10208 ghc-filesystem: add version 1.5.12
  recipes/ghc-filesystem/all/conandata.yml
  recipes/ghc-filesystem/config.yml
Labels: Bump version

#10207 tree-sitter: add version 0.20.6
  recipes/tree-sitter/all/conandata.yml
  recipes/tree-sitter/config.yml
Labels: Bump version

#10212 [paho-mqtt-c] Update to v1.3.10
  recipes/paho-mqtt-c/all/conandata.yml
  recipes/paho-mqtt-c/config.yml
Labels: Bump version

#10206 protobuf: bump zlib
  recipes/protobuf/all/conanfile.py
Labels: Bump dependencies

#10219 zstr: bump zlib
  recipes/zstr/all/conanfile.py
Labels: Bump dependencies

#10220 libmysqlclient: bump dependencies
  recipes/libmysqlclient/all/conanfile.py
Labels: Bump dependencies

#10223 libnghttp2: add version 1.47.0
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#10209 boost: bump dependencies
  recipes/boost/all/conanfile.py
Labels: Bump dependencies

#10203 wt: bump dependencies
  recipes/wt/all/conanfile.py
Labels: Bump dependencies

#10226 mbedtls: bump zlib
  recipes/mbedtls/all/conanfile.py
Labels: Bump dependencies

#10228 pdal: bump dependencies
  recipes/pdal/all/conanfile.py
Labels: Bump dependencies

#10176 Remove superfluous line break
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub config

#10225 dcmtk: bump dependencies
  recipes/dcmtk/all/conanfile.py
Labels: Bump dependencies

#10227 openssl: bump zlib
  recipes/openssl/1.x.x/conanfile.py
  recipes/openssl/3.x.x/conanfile.py
Labels: Bump dependencies

#10234 Bump glfw/3.3.7
  recipes/glfw/all/conandata.yml
  recipes/glfw/config.yml
Labels: Bump version

#10236 Add SML 1.1.5
  recipes/sml/all/conandata.yml
  recipes/sml/config.yml
Labels: Bump version

#10239 log4cplus 2.0.6 + 2.0.7
  recipes/log4cplus/all/conandata.yml
  recipes/log4cplus/config.yml
Labels: Bump version

#10240 libarchive: bump dependencies
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#10244 vectorclass: add version 2.01.04
  recipes/vectorclass/all/conandata.yml
  recipes/vectorclass/config.yml
Labels: Bump version

#10247 libnghttp2: bump dependencies
  recipes/libnghttp2/all/conanfile.py
Labels: Bump dependencies

#10249 fltk: bump zlib
  recipes/fltk/all/conanfile.py
Labels: Bump dependencies

#10254 [libxlsxwriter] Bump dependencies
  recipes/libxlsxwriter/all/conanfile.py
Labels: Bump dependencies

#10264 sdl: bump libunwind
  recipes/sdl/all/conanfile.py
Labels: Bump dependencies

#10275 [wayland] Bump dependencies
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#10276 [cpprestsdk] Bump dependencies
  recipes/cpprestsdk/all/conanfile.py
Labels: Bump dependencies

#10279 fontconfig: bump reqs
  recipes/fontconfig/all/conanfile.py
Labels: Bump dependencies

#10285 Bump vulkan-headers/1.3.211
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#10294 opentelemetry-proto: add version 0.16.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#10311 cpp-httplib: bump openssl & zlib
  recipes/cpp-httplib/all/conanfile.py
Labels: Bump dependencies

#10299 quazip: bump zlib
  recipes/quazip/all/conanfile.py
Labels: Bump dependencies

#10301 qxlsx/1.4.3: Bump qt requirement
  recipes/qxlsx/all/conanfile.py
Labels: Bump dependencies

#10318 amqp-cpp: add version 4.3.16
  recipes/amqp-cpp/all/conandata.yml
  recipes/amqp-cpp/config.yml
Labels: Bump version

#10336 xsimd: add version 8.0.5
  recipes/xsimd/all/conandata.yml
  recipes/xsimd/config.yml
Labels: Bump version

#10342 arduinojson: add version 6.19.4
  recipes/arduinojson/all/conandata.yml
  recipes/arduinojson/config.yml
Labels: Bump version

#10351 catch2: add version 2.13.9
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#10340 add openexr/3.1.5
  recipes/openexr/3.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#10345 caf: add version 0.18.6
  recipes/caf/all/conandata.yml
  recipes/caf/config.yml
Labels: Bump version

#10346 cppcheck: add version 2.7.5
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#10359 opentdf-client: add version 0.9.0
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#10361 Bump vulkan-headers/1.3.211.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#10377 graphene: bump requirements
  recipes/graphene/all/conanfile.py
Labels: Bump dependencies

#10375 gstreamer: bump reqs
  recipes/gstreamer/all/conanfile.py
Labels: Bump dependencies

#10374 Bump vulkan-loader/1.3.211.0
  recipes/vulkan-loader/all/conandata.yml
  recipes/vulkan-loader/config.yml
Labels: Bump version

#10386 cmp: add version 20
  recipes/cmp/all/conandata.yml
  recipes/cmp/config.yml
Labels: Bump version

#10378 pango: bump reqs
  recipes/pango/all/conanfile.py
Labels: Bump dependencies

#10376 gst-plugins-base: bump reqs
  recipes/gst-plugins-base/all/conanfile.py
Labels: Bump dependencies

#10391 argh: add version 1.3.2
  recipes/argh/all/conandata.yml
  recipes/argh/config.yml
Labels: Bump version

#10396 Bump glslang/1.3.211.0
  recipes/glslang/all/conandata.yml
  recipes/glslang/config.yml
Labels: Bump version

#10379 [docs] Policy: remove old package versions
  docs/faqs.md
  docs/reviewing.md
Labels: Docs

#10419 meson: add version 0.62.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#10417 Update changelog 21-April-2022
  docs/changelog.md
  docs/review_process.md
Labels: Docs

#10061 tracy: add 0.8.1
  recipes/tracy/all/conandata.yml
  recipes/tracy/config.yml
Labels: Bump version

#10434 Bump bitmagic/7.11.2
  recipes/bitmagic/all/conandata.yml
  recipes/bitmagic/config.yml
Labels: Bump version

#10438 (#10437) Bump libusb to 1.0.26
  recipes/libusb/all/conandata.yml
  recipes/libusb/config.yml
Labels: Bump version

#10433 Bump cpp-httplib/0.10.6
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#10445 - [libmikmod] bump libalsa to 1.2.5.1
  recipes/libmikmod/all/conanfile.py
Labels: Bump dependencies

#10447 - [libmikmod] bump pulseaudio to 14.2
  recipes/libmikmod/all/conanfile.py
Labels: Bump dependencies

#10449 fakeit: add version 2.1.0
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#10458 Dbus: bump reqs
  recipes/dbus/1.x.x/conanfile.py
Labels: Bump dependencies

#10457 tng: bump zlib
  recipes/tng/all/conanfile.py
Labels: Bump dependencies

#10467 readosm: bump dependencies
  recipes/readosm/all/conanfile.py
Labels: Bump dependencies

#10469 add lcms/2.13.1
  recipes/lcms/all/conandata.yml
  recipes/lcms/config.yml
Labels: Bump version

#10472 meson: add version 0.62.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#10474 pango: add version 1.50.7
  recipes/pango/all/conandata.yml
  recipes/pango/config.yml
Labels: Bump version

#10473 glib: add version 2.72.1
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#10476 harfbuzz: add version 4.2.1
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#10475 wt: add version 4.7.1
  recipes/wt/all/conandata.yml
  recipes/wt/config.yml
Labels: Bump version

#10460 rocksdb: bump zlib
  recipes/rocksdb/all/conanfile.py
Labels: Bump dependencies

#10484 libspatialite: bump dependencies
  recipes/libspatialite/all/conanfile.py
Labels: Bump dependencies

#10485 librasterlite2: bump dependencies
  recipes/librasterlite2/all/conanfile.py
Labels: Bump dependencies

#10486 libzip: bump dependencies
  recipes/libzip/all/conanfile.py
Labels: Bump dependencies

#10521 proposal: bump to 7.3.1
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#10518 frugally-deep: add version 0.15.16-p0
  recipes/frugally-deep/all/conandata.yml
  recipes/frugally-deep/config.yml
Labels: Bump version

#9662 package/ignition-tools/[^1.0.0]
  recipes/ignition-tools/all/CMakeLists.txt
  recipes/ignition-tools/all/conandata.yml
  recipes/ignition-tools/all/conanfile.py
  recipes/ignition-tools/all/patches/0001-ign-tools-1.0.0-cmake-fixes.patch
  recipes/ignition-tools/all/patches/0002-ign-tools-1.2.0-cmake-fixes.patch
  recipes/ignition-tools/all/patches/0003-ign-tools-1.4.0-cmake-fixes.patch
  recipes/ignition-tools/all/test_package/CMakeLists.txt
  recipes/ignition-tools/all/test_package/conanfile.py
  recipes/ignition-tools/all/test_package/test_package.cpp
  recipes/ignition-tools/config.yml
Labels: blocked

#10510 [extra-cmake-modules] bump version
  recipes/extra-cmake-modules/all/conandata.yml
  recipes/extra-cmake-modules/config.yml
Labels: Bump version

#10535 [changelog] Deploy new version
  docs/changelog.md
  docs/review_process.md
Labels: Docs

#10544 miniaudio: add version 0.11.9
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#10540 aws-c-cal: add version 0.5.17
  recipes/aws-c-cal/all/conandata.yml
  recipes/aws-c-cal/config.yml
Labels: Bump version

#10399 Version bump zlib/1.2.12 in doxygen packages
  recipes/doxygen/all/conanfile.py
Labels: Bump dependencies

#10560 minizip-ng: add version 3.0.6
  recipes/minizip-ng/all/conandata.yml
  recipes/minizip-ng/config.yml
Labels: Bump version
