Repository conan-io/conan-center-index, pull requests merged in 2022-03, with the labels that each got.

#9527 Bump cista/0.10
  recipes/cista/all/conandata.yml
  recipes/cista/config.yml
Labels: Bump version

#9553 vulkan-headers: Add 1.3.204.1
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#9554 bump wayland dependency
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#9552 msgpack-cxx: add version 4.1.0
  recipes/msgpack-cxx/all/conandata.yml
  recipes/msgpack-cxx/config.yml
Labels: Bump version

#9561 [docs] Document new methods order
  docs/reviewing.md
Labels: Docs

#9398 [doc] Rewrite docs about recipes folders
  docs/how_to_add_packages.md
Labels: Docs

#9519 Update policy
  docs/packaging_policy.md
Labels: Docs

#9602 daw_header_libraries: add version 2.23.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#9622 daw_utf_range: update dependencies
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#9621 Bump wt/4.6.2
  recipes/wt/all/conandata.yml
  recipes/wt/config.yml
Labels: Bump version

#7212 nspr: bump + modernize + no tools.os_info in `build_requirements`
  recipes/nspr/all/conandata.yml
  recipes/nspr/all/conanfile.py
  recipes/nspr/all/test_package/CMakeLists.txt
  recipes/nspr/all/test_package/conanfile.py
  recipes/nspr/all/test_package/test_package.c
  recipes/nspr/all/test_package/test_package.cpp
  recipes/nspr/config.yml
Labels: infrastructure

#9646 - [google-cloud-cpp] bump abseil
  recipes/google-cloud-cpp/all/conanfile.py
Labels: Bump dependencies

#9642 wasmer: add version 2.2.0
  recipes/wasmer/all/conandata.yml
  recipes/wasmer/config.yml
Labels: Bump version

#9601 Bump version: parallel-hashmap 1.34
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#9660 glib: 2.71.3 and 2.70.4
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#9672 Update changelog 09-March-2022
  docs/changelog.md
Labels: Docs

#9661 Add read-excel library version 1.2.7.
  recipes/read-excel/all/conandata.yml
  recipes/read-excel/config.yml
Labels: Bump version

#9688 draco: add version 1.5.2
  recipes/draco/all/conandata.yml
  recipes/draco/config.yml
Labels: Bump version

#9689 minizip-ng: add version 3.0.5
  recipes/minizip-ng/all/conandata.yml
  recipes/minizip-ng/config.yml
Labels: Bump version

#9721 opentdf-client: add version 0.6.0
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#9742 libgeotiff: bump proj
  recipes/libgeotiff/all/conanfile.py
Labels: Bump dependencies

#9744 gdal: bump dependencies
  recipes/gdal/all/conanfile.py
Labels: Bump dependencies

#9570 [gh-action] TOC: use branch starting with `bot/`
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#9758 asio: add version 1.22.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#9759 b2: add version 4.8.0
  recipes/b2/config.yml
  recipes/b2/portable/conandata.yml
Labels: Bump version

#9761 cppcheck: add version 2.7.1
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#9762 meson: add version 0.61.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#9707 Add docs about no-review merges and labels
  docs/README.md
  docs/labels.md
  docs/review_process.md
Labels: Docs

#9648 Bump version of expat library to support 2.4.7
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#9749 etl: add version 20.25.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#9777 CI: Update used Actions
  .github/workflows/linters.yml
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#9778 sqlite3: add version 3.38.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#9782 qt6: bump reqs
  recipes/qt/6.x.x/conanfile.py
Labels: Bump dependencies

#9803 pybind11_json: add version 0.2.12
  recipes/pybind11_json/all/conandata.yml
  recipes/pybind11_json/config.yml
Labels: Bump version

#9802 embree3: add version 3.13.3
  recipes/embree3/all/conandata.yml
  recipes/embree3/config.yml
Labels: Bump version

#9813 xapian-core: Add 1.4.19
  recipes/xapian-core/all/conandata.yml
  recipes/xapian-core/config.yml
Labels: Bump version

#9817 Bump cpp-httplib/0.10.4
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#9830 [ci] Conan linter: match version running in CI
  .github/workflows/linters.yml
Labels: GitHub config

#9853 libepoxy: add version 1.5.10
  recipes/libepoxy/all/conandata.yml
  recipes/libepoxy/config.yml
Labels: Bump version

#9849 openssl: add 3.0.2
  recipes/openssl/3.x.x/conandata.yml
  recipes/openssl/config.yml
Labels: Bump version

#9863 [update] opene57/1.6.3
  recipes/opene57/all/conandata.yml
  recipes/opene57/config.yml
Labels: Bump version

#9548 Clarify importance of options when protecting from recipe changes
  docs/faqs.md
Labels: Docs

#9878 glib: add version 2.72.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#9880 sqlcipher: update dependent libraries
  recipes/sqlcipher/all/conanfile.py
Labels: Bump dependencies

#9883 proposal: bump to 7.3.0
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#9888 harfbuzz: add version 4.1.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#9892 aws-c-common: add version 0.6.19
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#9908 aws-c-compression: update dependencies
  recipes/aws-c-compression/all/conanfile.py
Labels: Bump dependencies

#9913 atk: add version 2.38.0
  recipes/atk/all/conandata.yml
  recipes/atk/config.yml
Labels: Bump version

#9918 asio: add version 1.22.1
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#9919 cppcheck: add version 2.7.3
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#9916 Update changelog 25-March-2022
  docs/changelog.md
Labels: Docs

#9921 graphene: add version 1.10.8
  recipes/graphene/all/conandata.yml
  recipes/graphene/config.yml
Labels: Bump version

#9922 outcome: add version 2.2.3
  recipes/outcome/all/conandata.yml
  recipes/outcome/config.yml
Labels: Bump version

#9920 emsdk: add version 3.1.7
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#9923 stlab: add version 1.6.2
  recipes/stlab/all/conandata.yml
  recipes/stlab/config.yml
Labels: Bump version

#9941 aws-checksums: update dependencies
  recipes/aws-checksums/all/conanfile.py
Labels: Bump dependencies

#9915 Fix bump dependencies link
  docs/labels.md
Labels: Docs

#9503 Update auto merge time to 20 minutes
  docs/review_process.md
Labels: Docs

#9982 dbus: bump expat
  recipes/dbus/1.x.x/conanfile.py
Labels: Bump dependencies

#9985 New version of expat, 2.4.8
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#9973 fix labels doc title
  docs/labels.md
Labels: Docs

#9989 nspr 4.33
  recipes/nspr/all/conandata.yml
  recipes/nspr/config.yml
Labels: Bump version

#10035 add imath/3.1.5
  recipes/imath/all/conandata.yml
  recipes/imath/config.yml
Labels: Bump version

#10026 cmake: bump openssl
  recipes/cmake/3.x.x/conanfile.py
Labels: Bump dependencies

#10042 harfbuzz: add version 4.2.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#10034 crowcpp-crow: add version 1.0+1
  recipes/crowcpp-crow/all/conandata.yml
  recipes/crowcpp-crow/config.yml
Labels: Bump version

#10045 Update changelog 31-March-2022: Conan client upgraded to 1.45.0
  docs/changelog.md
Labels: Docs

#10014 Add protobuf 3.18.1
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#10018 aws-c-event-stream: update dependencies
  recipes/aws-c-event-stream/all/conanfile.py
Labels: Bump dependencies

#10020 CI: upgrade pylint
  .github/workflows/linters.yml
Labels: GitHub config
