Repository conan-io/conan-center-index, pull requests merged in 2022-07, with the labels that each got.

#11455 parallel-hashmap: add version 1.35
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#11462 Add `prince-chrismc` as team member
  .c3i/reviewers.yml
Labels: C3I config

#11461 simdjson: add version 2.1.0 and remove old versions
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#11476 [symengine] Update boost requirement.
  recipes/symengine/all/conanfile.py
Labels: Bump dependencies

#11488 libgphoto2: update dependencies
  recipes/libgphoto2/all/conanfile.py
Labels: Bump dependencies

#11493 daw_header_libraries: add version 2.65.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#11500 daw_json_link: add version 3.0.1
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#11504 rtm: add version 2.1.4
  recipes/rtm/all/conandata.yml
  recipes/rtm/config.yml
Labels: Bump version

#11519 libcuckoo: add v0.3.1
  recipes/libcuckoo/all/conandata.yml
  recipes/libcuckoo/config.yml
Labels: Bump version

#11520 meson: add version 0.63.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#11411 Add latest frugally-deep version (0.15.18-p0)
  recipes/frugally-deep/all/conandata.yml
  recipes/frugally-deep/config.yml
Labels: Bump version

#11494 wayland: Add version 1.21.0
  recipes/wayland/all/conandata.yml
  recipes/wayland/config.yml
Labels: Bump version

#11487 highfive: add v2.4.1
  recipes/highfive/all/conandata.yml
  recipes/highfive/config.yml
Labels: Bump version

#11503 rapidcsv: add version 8.64
  recipes/rapidcsv/all/conandata.yml
  recipes/rapidcsv/config.yml
Labels: Bump version

#11486 openscenegraph: update dependencies
  recipes/openscenegraph/all/conanfile.py
Labels: Bump dependencies

#11541 (#11540) perfetto: Bump version to 27.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#11560 v2 - Do not notify via slack
  .c3i/config_v2.yml
Labels: C3I config

#11567 Add libpqxx/7.7.4
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#11565 doc: update links to point to github pages
  docs/community_resources.md
Labels: Docs

#11572 tracy: add version 0.8.2.1
  recipes/tracy/all/conandata.yml
  recipes/tracy/config.yml
Labels: Bump version

#11581 update: metall/0.21
  recipes/metall/all/conandata.yml
  recipes/metall/config.yml
Labels: Bump version

#11588 [docs] Why not build testing as a recipe option
  docs/faqs.md
  docs/packaging_policy.md
Labels: Docs

#11602 bump version: dice-template-library/0.2.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#11620 itlib: add version 1.5.2
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#11587 [changelog] New C3I release: July 2022
  docs/changelog.md
Labels: Docs

#11601 [docs] Packaging policy: fix missing info for package_id
  docs/packaging_policy.md
Labels: Docs

#11589 [config] New windows machines with more ram
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#11606 linter - Add linter for test_*/conanfile.py files
  .github/workflows/linter-conan-v2.yml
  linter/pylintrc_recipe
  linter/pylintrc_testpackage
Labels: GitHub config, C3I config

#11625 docs/faqs - wrong title level
  docs/faqs.md
Labels: Docs

#3951 [docs] Add policy about patching
  docs/README.md
  docs/policy_patching.md
Labels: Docs

#11465 config - Up Conan version
  .c3i/config_v1.yml
Labels: C3I config

#11647 Bump draco/1.5.3
  recipes/draco/all/conandata.yml
  recipes/draco/config.yml
Labels: Bump version

#11652 Add args-parser library version 6.3.2.
  recipes/args-parser/all/conandata.yml
  recipes/args-parser/config.yml
Labels: Bump version

#11649 cpp-httplib: bump openssl
  recipes/cpp-httplib/all/conanfile.py
Labels: Bump dependencies

#11657 rtm: add version 2.1.5
  recipes/rtm/all/conandata.yml
  recipes/rtm/config.yml
Labels: Bump version

#11661 [config] Update Conan version to 1.49.0
  .c3i/config_v1.yml
Labels: C3I config

#11627 linter - check ConanFile import and cross_building
  docs/v2_linter.md
  docs/v2_migration.md
  linter/check_import_conanfile.py
  linter/check_package_name.py
  linter/conanv2_transition.py
  linter/pylintrc_recipe
  linter/pylintrc_testpackage
  linter/transform_conanfile.py
  linter/transform_imports.py
Labels: Docs, C3I config

#11678 c-client - bump deps
  recipes/c-client/all/conanfile.py
Labels: Bump dependencies

#11677 brynet - bump deps
  recipes/brynet/all/conanfile.py
Labels: Bump dependencies

#11675 aws-c-cal - bump deps
  recipes/aws-c-cal/all/conanfile.py
Labels: Bump dependencies

#11671 arrow: update dependencies
  recipes/arrow/all/conanfile.py
Labels: Bump dependencies

#11680 cassandra-cpp-driver - bump deps
  recipes/cassandra-cpp-driver/all/conanfile.py
Labels: Bump dependencies

#11673 amqp-cpp - bump deps
  recipes/amqp-cpp/all/conanfile.py
Labels: Bump dependencies

#11682 certify - bump deps
  recipes/certify/all/conanfile.py
Labels: Bump dependencies

#11683 docs: add a link the list of reviewers
  docs/review_process.md
Labels: Docs

#11687 sqlite3: add version 3.39.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#11688 s2n: update openssl
  recipes/s2n/all/conanfile.py
Labels: Bump dependencies

#11693 pulseaudio: update dependencies
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#11701 usockets: update dependencies
  recipes/usockets/all/conanfile.py
Labels: Bump dependencies

#11704 libxslt: update dependencies
  recipes/libxslt/all/conanfile.py
Labels: Bump dependencies

#11723 wolfssl: add version 5.4.0
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#11711 [doc] How to disable linter for v1-only tests
  docs/how_to_add_packages.md
  docs/v2_linter.md
Labels: Docs

#11726 etl: add version 20.31.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#11732 trantor: add version 1.5.6
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#11734 trantor: update openssl/1.1.1q
  recipes/trantor/all/conanfile.py
Labels: Bump dependencies

#11768 cmake: update openssl
  recipes/cmake/3.x.x/conanfile.py
Labels: Bump dependencies

#11771 bump libxml2 dependencies
  recipes/libxml2/all/conanfile.py
Labels: Bump dependencies

#11792 tgbot: update dependencies
  recipes/tgbot/all/conanfile.py
Labels: Bump dependencies

#11804 srt: update openssl
  recipes/srt/all/conanfile.py
Labels: Bump dependencies

#11803 docs: required reviews changed from 3 to 2
  docs/review_process.md
Labels: Docs

#11812 simple-websocket-server: update dependencies
  recipes/simple-websocket-server/all/conanfile.py
Labels: Bump dependencies

#11829 lightgbm: bump fmt
  recipes/lightgbm/all/conanfile.py
Labels: Bump dependencies

#11838 libxft: bump freetype
  recipes/libxft/all/conanfile.py
Labels: Bump dependencies

#11837 libselinux: bump reqs
  recipes/libselinux/all/conanfile.py
Labels: Bump dependencies

#11835 libarchive: bump reqs
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#11844 sqlite3: add version 3.39.2
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#11848 mcap: add version 0.1.2, revert addition of 0.2.2
  recipes/mcap/all/conandata.yml
  recipes/mcap/config.yml
Labels: Bump version

#11859 Update changelog 22-July-2022
  docs/changelog.md
Labels: Docs

#11856 libgettext: bump reqs
  recipes/libgettext/all/conanfile.py
Labels: Bump dependencies

#11867 poppler-data/0.4.11
  recipes/poppler-data/all/conandata.yml
  recipes/poppler-data/config.yml
Labels: Bump version

#11870 daw_header_libraries: add version 2.68.1
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#11871 daw_utf_range: update dependencies
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#11875 dataframe: add version 1.21.0
  recipes/dataframe/all/conandata.yml
  recipes/dataframe/config.yml
Labels: Bump version

#11883 cyrus-sasl: update dependencies
  recipes/cyrus-sasl/all/conanfile.py
Labels: Bump dependencies

#11885 lunasvg: add version 2.3.2
  recipes/lunasvg/all/conandata.yml
  recipes/lunasvg/config.yml
Labels: Bump version

#11887 numcpp: add version 2.8.0
  recipes/numcpp/all/conandata.yml
  recipes/numcpp/config.yml
Labels: Bump version

#11888 rabbitmq-c: update openssl
  recipes/rabbitmq-c/all/conanfile.py
Labels: Bump dependencies

#11890 resiprocate: update dependencies
  recipes/resiprocate/all/conanfile.py
Labels: Bump dependencies

#11895 podofo: update dependencies
  recipes/podofo/all/conanfile.py
Labels: Bump dependencies

#11896 pistache: update openssl
  recipes/pistache/all/conanfile.py
Labels: Bump dependencies

#11898 paho-mqtt-c: update openssl
  recipes/paho-mqtt-c/all/conanfile.py
Labels: Bump dependencies

#11899 opusfile: update openssl
  recipes/opusfile/all/conanfile.py
Labels: Bump dependencies

#11902 nanoflann: add version 1.4.3
  recipes/nanoflann/all/conandata.yml
  recipes/nanoflann/config.yml
Labels: Bump version

#11901 minizip-ng: update dependencies
  recipes/minizip-ng/all/conanfile.py
Labels: Bump dependencies

#11868 Add frugally-deep version 0.15.19-p0
  recipes/frugally-deep/all/conandata.yml
  recipes/frugally-deep/config.yml
Labels: Bump version

#11886 luau: add version 0.537
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#11894 valijson: add version 0.7
  recipes/valijson/all/conandata.yml
  recipes/valijson/config.yml
Labels: Bump version

#11900 openldap: update openssl
  recipes/openldap/all/conanfile.py
Labels: Bump dependencies

#11797 Latest tclap version
  recipes/tclap/all/conandata.yml
  recipes/tclap/config.yml
Labels: Bump version

#11910 arrow: add version 8.0.1
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#11911 [poppler/xxx] Bump dependencies
  recipes/poppler/all/conanfile.py
Labels: Bump dependencies

#11914 mailio: update dependencies
  recipes/mailio/all/conanfile.py
Labels: Bump dependencies

#11915 libzip: update dependencies
  recipes/libzip/all/conanfile.py
Labels: Bump dependencies

#11916 libxlsxwriter: update openssl
  recipes/libxlsxwriter/all/conanfile.py
Labels: Bump dependencies

#11917 libucl: update dependencies
  recipes/libucl/all/conanfile.py
Labels: Bump dependencies

#11918 libtorrent: update dependencies
  recipes/libtorrent/all/conanfile.py
Labels: Bump dependencies

#11909 wasmtime: add version 0.39.1
  recipes/wasmtime/all/conandata.yml
  recipes/wasmtime/config.yml
Labels: Bump version

#11919 libtins: update dependencies
  recipes/libtins/all/conanfile.py
Labels: Bump dependencies

#11921 libssh2: update openssl
  recipes/libssh2/all/conanfile.py
Labels: Bump dependencies

#11925 [docs] Review access-request section on contributing packages
  docs/how_to_add_packages.md
Labels: Docs

#11929 libsrtp: update openssl
  recipes/libsrtp/all/conanfile.py
Labels: Bump dependencies

#11934 librhash: update openssl
  recipes/librhash/all/conanfile.py
Labels: Bump dependencies

#11713 [patching] Add conadata format and new patch fields
  docs/conandata_yml_format.md
  docs/policy_patching.md
Labels: Docs

#11942 etl: add version 20.31.3
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#11824 bump ffmpeg dependencies
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#11943 libnghttp2: update dependencies
  recipes/libnghttp2/all/conanfile.py
Labels: Bump dependencies

#11935 libpq: update openssl
  recipes/libpq/all/conanfile.py
Labels: Bump dependencies

#11963 libcoap: update dependencies
  recipes/libcoap/all/conanfile.py
Labels: Bump dependencies

#11964 simdjson: add version 2.2.2
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#11966 jwt-cpp: update openssl
  recipes/jwt-cpp/all/conanfile.py
Labels: Bump dependencies

#11969 ixwebsocket: update dependencies
  recipes/ixwebsocket/all/conanfile.py
Labels: Bump dependencies

#11976 etl: add version 20.32.1
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#11978 cpp-httplib: add version 0.11.0
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#11984 hiredis: update openssl
  recipes/hiredis/all/conanfile.py
Labels: Bump dependencies
