Repository conan-io/conan-center-index, pull requests merged in 2022-02, with the labels that each got.

#7749 run yaml-lint and pylint as github action
  .github/recipe_linter.json
  .github/runlint.py
  .github/workflows/linters.yml
  .github/yaml_linter.json
Labels: GitHub config

#9204 add sentry-crashpad/0.4.14
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#9074 double-conversion: add version 3.2.0
  recipes/double-conversion/all/conandata.yml
  recipes/double-conversion/config.yml
Labels: Bump version

#9210 linter: various fixes
  .github/runlint.py
  .github/workflows/linters.yml
Labels: GitHub config

#9211 proposal: bump to 7.2.1
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#9217 zlib-ng: add version 2.0.6
  recipes/zlib-ng/all/conandata.yml
  recipes/zlib-ng/config.yml
Labels: Bump version

#9218 elfio: Add version 3.9
  recipes/elfio/all/conandata.yml
  recipes/elfio/config.yml
Labels: Bump version

#9075 gsl-lite: add version 0.40.0
  recipes/gsl-lite/all/conandata.yml
  recipes/gsl-lite/config.yml
Labels: Bump version

#9201 opencl-headers: Add version 2022.01.04
  recipes/opencl-headers/all/conandata.yml
  recipes/opencl-headers/config.yml
Labels: Bump version

#9250 [pybind11/2.9.1] Add latest version
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#9226 libgettext 0.21
  recipes/libgettext/all/DEPRECATED
  recipes/libgettext/all/conandata.yml
  recipes/libgettext/config.yml
Labels: Bump version

#9259 opencl-headers: modernize
  recipes/opencl-headers/all/conanfile.py
  recipes/opencl-headers/all/test_package/conanfile.py
Labels: infrastructure

#9140 [docs] Better description for why version ranges are not allowed
  docs/faqs.md
Labels: Docs

#9251 Update changelog with latest changes
  docs/changelog.md
Labels: Docs

#9294 elfio: Add version 3.10
  recipes/elfio/all/conandata.yml
  recipes/elfio/config.yml
Labels: Bump version

#9313 [fp16] fp16 cci.20210320
  recipes/fp16/all/conandata.yml
  recipes/fp16/config.yml
Labels: Bump version

#9317 emscripten update
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#9340 implot: add version 0.13
  recipes/implot/all/conandata.yml
  recipes/implot/config.yml
Labels: Bump version

#9334 opencv: update libwebp 1.2.1 -> 1.2.2
  recipes/opencv/3.x/conanfile.py
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#9360 wasmtime: add version 0.34.0
  recipes/wasmtime/all/conandata.yml
  recipes/wasmtime/config.yml
Labels: Bump version

#9366 [pulseaudio] Bump deps
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#9373 cimg: add version 3.0.2
  recipes/cimg/all/conandata.yml
  recipes/cimg/config.yml
Labels: Bump version

#9378 Update si to version 2.4.1
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#9347 DOCS: Add an example of cmake_build_modules property to migration guide
  docs/preparing_recipes_for_conan2.md
Labels: Docs

#9247 linters: Don't annotate TODOs and FIXMEs
  .github/recipe_linter.json
  .github/runlint.py
  .github/workflows/linters.yml
Labels: GitHub config

#9368 mdns: add version 1.4.2
  recipes/mdns/all/conandata.yml
  recipes/mdns/config.yml
Labels: Bump version

#9300 [doc] Entries about settings and options (and shared libraries)
  docs/faqs.md
  docs/packaging_policy.md
Labels: Docs

#9384 Add args-parser library version 6.3.1.
  recipes/args-parser/all/conandata.yml
  recipes/args-parser/config.yml
Labels: Bump version

#9387 Bump vulkan-headers/1.3.204.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#9380 linters: don't crash on invalid versions
  .github/runlint.py
Labels: GitHub config

#9063 simple-yaml: add compatibility for older compilers
  recipes/simple-yaml/all/conandata.yml
  recipes/simple-yaml/all/conanfile.py
  recipes/simple-yaml/config.yml
Labels: infrastructure

#9402 Bump spirv-headers/1.3.204.0
  recipes/spirv-headers/all/conandata.yml
  recipes/spirv-headers/config.yml
Labels: Bump version

#9427 Add new version 2.4.5 for expat library to fix several CVEs.
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#9437 bump sentry-crashpad
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#9439 etl: add version 20.24.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#9442 bitmagic: add version 7.10.3
  recipes/bitmagic/all/conandata.yml
  recipes/bitmagic/config.yml
Labels: Bump version

#9327 - [gst-plugins-base] bump libalsa to libalsa/1.2.5.1
  recipes/gst-plugins-base/all/conanfile.py
Labels: Bump dependencies

#9456 - [openimageio] bump deps
  recipes/openimageio/all/conanfile.py
Labels: Bump dependencies

#9470 xkbcommon: add version 1.4.0
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/config.yml
Labels: Bump version

#9475 Update changelog with latest changes
  docs/changelog.md
Labels: Docs

#9493 emsdk: update version list
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#9477 etl: add version 20.24.1
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#9480 Add json_dto 0.3.1
  recipes/json_dto/all/conandata.yml
  recipes/json_dto/config.yml
Labels: Bump version

#8843 crowcpp-crow: add version 0.3+4
  recipes/crowcpp-crow/all/conandata.yml
  recipes/crowcpp-crow/config.yml
Labels: Bump version

#9393 Added kangaru version 4.3.0
  recipes/kangaru/all/conandata.yml
  recipes/kangaru/config.yml
Labels: Bump version

#9408 - add KB-H065 & KB-H066, clarify some points and add relevant links for newcomers
  docs/error_knowledge_base.md
Labels: Docs

#9448 bump sentry-breakpad
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#9500 Changelog update 24-February-2022
  docs/changelog.md
Labels: Docs

#9516 Add approvaltests.cpp 10.12.2
  recipes/approvaltests.cpp/all/conandata.yml
  recipes/approvaltests.cpp/config.yml
Labels: Bump version

#9520 libdeflate: add version 1.10
  recipes/libdeflate/all/conandata.yml
  recipes/libdeflate/config.yml
Labels: Bump version

#9526 Bump cpp-httplib/0.10.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#9530 Bump cpp-peglib/1.3.9
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#9529 Bump re2/20220201
  recipes/re2/all/conandata.yml
  recipes/re2/config.yml
Labels: Bump version

#9541 [docs] Remove italics, they break the autogenerated link in TOC
  docs/faqs.md
Labels: Docs

#9514 sqlite3: add version 3.38.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version
