Repository conan-io/conan-center-index, pull requests merged in 2022-06, with the labels that each got.

#11004 quill: add version 2.0.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#11043 [cairo]: bump requirements
  recipes/cairo/meson/conanfile.py
Labels: Bump dependencies

#11046 [harfbuzz]: bump dependencies
  recipes/harfbuzz/all/conanfile.py
Labels: Bump dependencies

#11047 opentdf-client: add version 1.0.0
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#11048 [pango]: bump dependencies
  recipes/pango/all/conanfile.py
Labels: Bump dependencies

#11066 libalsa 1.2.7
  recipes/libalsa/all/conandata.yml
  recipes/libalsa/config.yml
Labels: Bump version

#11067 at-spi2-core 2.44.1
  recipes/at-spi2-core/all/conandata.yml
  recipes/at-spi2-core/config.yml
Labels: Bump version

#11079 restinio: add version 0.6.15
  recipes/restinio/all/conandata.yml
  recipes/restinio/config.yml
Labels: Bump version

#11083 cereal: add version 1.3.2
  recipes/cereal/all/conandata.yml
  recipes/cereal/config.yml
Labels: Bump version

#11096 cpp-httplib: add version 0.10.8
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#11089 aws-c-io: add version 0.11.2
  recipes/aws-c-io/all/conandata.yml
  recipes/aws-c-io/config.yml
Labels: Bump version

#11097 cpp-peglib: add version 1.4.2
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#11133 automake: add automake/1.16.5
  recipes/automake/all/conandata.yml
  recipes/automake/config.yml
Labels: Bump version

#11134 libtool: bump automake + gnu-config version
  recipes/libtool/all/conanfile.py
Labels: Bump dependencies

#11142 fakeit: add version 2.3.0
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#11143 nanobench: add version 4.3.7
  recipes/nanobench/all/conandata.yml
  recipes/nanobench/config.yml
Labels: Bump version

#11141 cargs: add version 1.0.3
  recipes/cargs/all/conandata.yml
  recipes/cargs/config.yml
Labels: Bump version

#11140 botan: add version 2.19.2
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#11128 xbyak: add version 6.60
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#11125 Issue report: use a form
  .github/ISSUE_TEMPLATE/package_bug.md
  .github/ISSUE_TEMPLATE/package_bug.yml
Labels: GitHub config

#11147 [linter] Linter for v2 migration
  .github/runlint.py
  .github/workflows/linter-conan-v2.yml
  .github/workflows/linters.yml
  linter/.pylintrc
  linter/__init__.py
  linter/conanv2_transition.py
  linter/package_name.py
  linter/recipe_linter.json
Labels: GitHub config, C3I config

#11117 [config] Add configuration files to index repository
  .c3i/Jenkinsfile
  .c3i/authorized_users.yml
  .c3i/c3i.yml
  .c3i/reviewers.yml
Labels: C3I config

#11149 [linter] Basic YAML linting
  .github/workflows/linter-yaml.yml
  .github/yaml_linter.json
  linter/yamllint_rules.yml
Labels: GitHub config, C3I config

#11167 [fontconfig]: bump dependencies
  recipes/fontconfig/all/conanfile.py
Labels: Bump dependencies

#11193 kuba-zip: add version 0.2.3
  recipes/kuba-zip/all/conandata.yml
  recipes/kuba-zip/config.yml
Labels: Bump version

#11203 Bump vulkan-headers/1.3.216.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#11204 Bump spirv-headers/1.3.216.0
  recipes/spirv-headers/all/conandata.yml
  recipes/spirv-headers/config.yml
Labels: Bump version

#11205 Bump spirv-cross/1.3.216.0
  recipes/spirv-cross/all/conandata.yml
  recipes/spirv-cross/config.yml
Labels: Bump version

#11199 scons: add version 4.3.0
  recipes/scons/all/conandata.yml
  recipes/scons/config.yml
Labels: Bump version

#11214 - update FAQ about Python support
  docs/faqs.md
Labels: Docs

#11225 Bump vulkan-loader/1.3.216.0
  recipes/vulkan-loader/all/conandata.yml
  recipes/vulkan-loader/config.yml
Labels: Bump version

#11229 Bump geos/3.10.3
  recipes/geos/all/conandata.yml
  recipes/geos/config.yml
Labels: Bump version

#11243 vulkan-memory-allocator: bump vulkan-headers
  recipes/vulkan-memory-allocator/all/conanfile.py
Labels: Bump dependencies

#11246 Bump vulkan-memory-allocator/3.0.1
  recipes/vulkan-memory-allocator/all/conandata.yml
  recipes/vulkan-memory-allocator/config.yml
Labels: Bump version

#11245 Bump calceph/3.5.1
  recipes/calceph/all/conandata.yml
  recipes/calceph/config.yml
Labels: Bump version

#11247 Bump vulkan-loader in glfw for static build
  recipes/glfw/all/conanfile.py
Labels: Bump dependencies

#11162 [linter] Transform `ConanFile` class to match actual one
  .github/workflows/linter-conan-v2.yml
  linter/.pylintrc
  linter/conanfile_transform.py
  linter/recipe_linter.json
Labels: GitHub config, C3I config

#11242 Bump glslang/1.3.216.0
  recipes/glslang/all/conandata.yml
  recipes/glslang/config.yml
Labels: Bump version

#11244 Bump volk/1.3.216.0
  recipes/volk/all/conandata.yml
  recipes/volk/config.yml
Labels: Bump version

#11250 gdal: update dependencies
  recipes/gdal/pre_3.5.0/conanfile.py
Labels: Bump dependencies

#11271 msgpack-cxx: add version 4.1.1
  recipes/msgpack-cxx/all/conandata.yml
  recipes/msgpack-cxx/config.yml
Labels: Bump version

#11272 hidapi: add version 0.12.0
  recipes/hidapi/all/conandata.yml
  recipes/hidapi/config.yml
Labels: Bump version

#11274 s2n: add version 1.3.15
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#11276 nsync: add version 1.25.0
  recipes/nsync/all/conandata.yml
  recipes/nsync/config.yml
Labels: Bump version

#10817 [pybind11/2.9.2] Add pybind11 2.9.2
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#11281 rmlui 3.3: Upgrade CMake to support VS2022
  recipes/rmlui/3.3/conanfile.py
Labels: Bump dependencies

#11290 sentry-breakpad/0.4.18
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#11291 sentry-crashpad/0.4.18
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#11293 sentry-native/0.4.18
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#11302 qr-code-generator: add version 1.8.0
  recipes/qr-code-generator/all/conandata.yml
  recipes/qr-code-generator/config.yml
Labels: Bump version

#11227 Update README.md
  docs/README.md
Labels: Docs

#11318 range-v3 0.12.0
  recipes/range-v3/all/conandata.yml
  recipes/range-v3/config.yml
Labels: Bump version

#11334 websocketpp: bump to boost/1.79.0 and openssl/1.1.1o
  recipes/websocketpp/all/conanfile.py
Labels: Bump dependencies

#11355 itlib: add version 1.5.1
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#11367 veque: add version 1.3.6
  recipes/veque/all/conandata.yml
  recipes/veque/config.yml
Labels: Bump version

#11366 taywee-args: add version 6.4.1
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#11371 Add so5extra v1.5.2
  recipes/so5extra/all/conandata.yml
  recipes/so5extra/config.yml
Labels: Bump version

#11361 opentelemetry-cpp: add version 1.4.1
  recipes/opentelemetry-cpp/all/conandata.yml
  recipes/opentelemetry-cpp/config.yml
Labels: Bump version

#11384 pbtools: add version 0.45.2
  recipes/pbtools/all/conandata.yml
  recipes/pbtools/config.yml
Labels: Bump version

#11377 argparse: add version 2.6
  recipes/argparse/all/conandata.yml
  recipes/argparse/config.yml
Labels: Bump version

#11396 etl: add version 20.29.3
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#11385 Add expected-lite/0.6.1 - fixes version number contained in files
  recipes/expected-lite/all/conandata.yml
  recipes/expected-lite/config.yml
Labels: Bump version

#11397 effolkronium-random: add version 1.4.1
  recipes/effolkronium-random/all/conandata.yml
  recipes/effolkronium-random/config.yml
Labels: Bump version

#11410 [config] Add Conan v2 configuration files and update v1
  .c3i/authorized_users.yml
  .c3i/config_v1.yml
  .c3i/config_v2.yml
  .c3i/v1.jenkins
  .c3i/v2.jenkins
Labels: C3I config

#11418 [docs] Update changelog 27-June-2022
  docs/changelog.md
Labels: Docs

#11426 Fix formatting of some header in v2 Roadmap
  docs/v2_roadmap.md
Labels: Docs

#11443 daw_utf_range: update dependencies
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#11444 config - execute (and report) v2 export
  .c3i/config_v1.yml
Labels: C3I config

#11445 [taocpp-pegtl] Bump version 3.2.6
  recipes/taocpp-pegtl/3.x.x/conandata.yml
  recipes/taocpp-pegtl/config.yml
Labels: Bump version

#11447 README.md: Fix broken link to contribution guide
  docs/README.md
Labels: Docs
