Repository conan-io/conan-center-index, pull requests merged in 2022-11, with the labels that each got.

#13905 openexr: bump zlib
  recipes/openexr/2.x/conanfile.py
  recipes/openexr/3.x/conanfile.py
Labels: Bump dependencies

#13911 etl: add version 20.35.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#13909 thrift: update dependencies
  recipes/thrift/all/conanfile.py
Labels: Bump dependencies

#13915 glaze: add version 0.1.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#13814 [docs] Document inactive users process
  docs/faqs.md
  docs/how_to_add_packages.md
Labels: Docs

#13926 bzip3: add version 1.2.0
  recipes/bzip3/all/conandata.yml
  recipes/bzip3/config.yml
Labels: Bump version

#13927 lcms: add version 2.14
  recipes/lcms/all/conandata.yml
  recipes/lcms/config.yml
Labels: Bump version

#13936 hdrhistogram-c: bump zlib
  recipes/hdrhistogram-c/all/conanfile.py
Labels: Bump dependencies

#13944 objectbox: add version 0.18.0
  recipes/objectbox/all/conandata.yml
  recipes/objectbox/config.yml
Labels: Bump version

#13945 leptonica: bump zlib & pkgconf
  recipes/leptonica/all/conanfile.py
Labels: Bump dependencies

#13950 glaze: add version 0.1.3
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#13848 docs: Use new Conan 1.53 features
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/msbuild_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/conanfile.py
  docs/packaging_policy.md
Labels: Docs

#13753 [config] Update conan version to 1.53.0
  .c3i/config_v1.yml
Labels: C3I config

#13954 cmake: bump openssl
  recipes/cmake/3.x.x/conanfile.py
Labels: Bump dependencies

#13957 libxlsxwriter: bump minizip & openssl
  recipes/libxlsxwriter/all/conanfile.py
Labels: Bump dependencies

#13841 wasmtime-cpp: add version 2.0.0
  recipes/wasmtime-cpp/all/conandata.yml
  recipes/wasmtime-cpp/all/conanfile.py
  recipes/wasmtime-cpp/config.yml
Labels: Failed

#13958 cpp-httplib: update openssl
  recipes/cpp-httplib/all/conanfile.py
Labels: Bump dependencies

#13960 aws-c-cal: update openssl
  recipes/aws-c-cal/all/conanfile.py
Labels: Bump dependencies

#13974 ignore test_package's output at all levels
  .gitignore
Labels: GitHub config

#13984 [templates] Keep same pattern for cmake and min_cppstd
  docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
  docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt
Labels: Docs

#13987 glaze: add version 0.1.4
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#13995 cli11: add v2.3.1
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#13996 pugixml: add version 1.13
  recipes/pugixml/all/conandata.yml
  recipes/pugixml/config.yml
Labels: Bump version

#14000 usockets: update dependencies
  recipes/usockets/all/conanfile.py
Labels: Bump dependencies

#14021 fast_float: add version 3.6.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#14022 [docs] Remove sha256 for patches in conandata.yml
  docs/conandata_yml_format.md
Labels: Docs

#14023 glaze: update fast_float
  recipes/glaze/all/conanfile.py
Labels: Bump dependencies

#14026 c4core: update fast_float
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#14051 daw_json_link: add version 3.4.1
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#14067 daw_header_libraries: add version 2.74.2
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#14078 daw_utf_range: update dependencies
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#14082 meson: add version 0.64.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#14031 [docs] remove src_folder from keyword args for vs_layout
  docs/package_templates/msbuild_package/all/conanfile.py
Labels: Docs

#14075 Fixed psyinf-gmtl cmake setup
  recipes/psyinf-gmtl/all/conandata.yml
  recipes/psyinf-gmtl/all/conanfile.py
  recipes/psyinf-gmtl/all/test_package/CMakeLists.txt
  recipes/psyinf-gmtl/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#14091 [release] Add changelog november 7th, 2022
  docs/changelog.md
Labels: Docs

#14092 utfcpp: add version 3.2.2
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#14112 daw_json_link: update daw_header_libraries
  recipes/daw_json_link/all/conanfile.py
Labels: Bump dependencies

#14099 Import vs_layout from conan.tools.microsoft
  docs/package_templates/msbuild_package/all/conanfile.py
Labels: Docs

#14087 Mingw-builds 12.2.0
  recipes/mingw-builds/all/conandata.yml
  recipes/mingw-builds/config.yml
Labels: Bump version

#14096 docs: rename patch field "backport" to "bugfix" to avoid confusion
  docs/conandata_yml_format.md
  linter/conandata_yaml_linter.py
Labels: Docs, GitHub config

#14133 glib 2.75.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#14142 daw_json_link: add version 3.5.0, remove older versions
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#13906 ffmpeg: bump dependencies
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#14081 config: Update list of reviewers
  .c3i/reviewers.yml
Labels: C3I config

#14134 [config] Add access request users
  .c3i/authorized_users.yml
Labels: C3I config

#14164 flatbuffers: add version 22.10.26
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#14165 roaring: add version 0.7.3
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#13861 onetbb: add version 2021.7.0
  recipes/onetbb/all/conandata.yml
  recipes/onetbb/config.yml
Labels: Bump version

#14184 nss 3.85
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#13864 Update .gitignore for vim
  .gitignore
Labels: GitHub config

#13736 docs: Create a subfolder for "adding packages"
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/adding_packages/README.md
  docs/adding_packages/conandata_yml_format.md
  docs/adding_packages/packaging_policy.md
  docs/adding_packages/policy_patching.md
  docs/adding_packages/reviewing.md
  docs/developing_recipes_locally.md
  docs/error_knowledge_base.md
  docs/faqs.md
  docs/v2_migration.md
Labels: Docs

#14192 [boost] Update icu reference in boost to use the latest.
  recipes/boost/all/conanfile.py
Labels: Bump dependencies

#14214 fast_float: add version 3.7.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#14222 trantor: add version 1.5.8
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#14213 updated link in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/developing_recipes_locally.md
  docs/faqs.md
Labels: Docs, GitHub config

#14230 feat: Add units library version 2.3.3
  recipes/units/all/conandata.yml
  recipes/units/config.yml
Labels: Bump version

#14208 msgpack-cxx: add version 4.1.3
  recipes/msgpack-cxx/all/conandata.yml
  recipes/msgpack-cxx/config.yml
Labels: Bump version

#14232 c4core: update fast_float/3.7.0
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#14247 sqlite3: add version 3.40.0, remove older versions
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#14253 roaring: add version 0.8.0
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#14255 quill: add version 2.3.3
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#14221 [config] Use larger resources to build cppfront packages
  .c3i/config_v1.yml
Labels: C3I config

#14265 catch2: add version 3.2.0
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#14269 civetweb: bump openssl
  recipes/civetweb/all/conanfile.py
Labels: Bump dependencies

#14288 libnghttp2: add version 1.51.0
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#14297 quill: add version 2.3.4
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#14296 libevent: Update dependencies
  recipes/libevent/all/conanfile.py
Labels: Bump dependencies

#14308 trantor: update openssl
  recipes/trantor/all/conanfile.py
Labels: Bump dependencies

#14314 drogon: update dependencies
  recipes/drogon/all/conanfile.py
Labels: Bump dependencies

#14338 unordered_dense: add version 2.0.1
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#14337 libpng: add version 1.6.39
  recipes/libpng/all/conandata.yml
  recipes/libpng/config.yml
Labels: Bump version

#14341 quill: add version 2.4.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#13971 docs: when to use CMakeToolchain's variable choices
  docs/v2_migration.md
Labels: Docs

#14363 bump version: dice-template-library/0.3.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#14378 taywee-args: add version 6.4.2
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#14382 meson 0.64.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#13748 github actions: don't use tj-actions/changed-files
  .github/actions/pr_changed_files/action.yml
  .github/workflows/linter-conan-v2.yml
  .github/workflows/linter-yaml.yml
Labels: GitHub config

#14388 opentdf-client: add version 1.3.4
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#14385 [docs] New hook kb-h075: Override is not allowed
  docs/error_knowledge_base.md
Labels: Docs

#14393 fix conandata lint
  .github/actions/pr_changed_files/action.yml
Labels: GitHub config

#14394 Version bump for si to 2.5.1
  recipes/si/all/conandata.yml
  recipes/si/config.yml
Labels: Bump version

#14391 sdl: add version 2.26.0
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#14411 fast_float: add version 3.8.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#14409 [protobuf] Add protobuf 3.21.9
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/config.yml
Labels: Bump version

#14416 glaze: update fast_float
  recipes/glaze/all/conanfile.py
Labels: Bump dependencies

#14419 immer: add version 0.8.0
  recipes/immer/all/conandata.yml
  recipes/immer/config.yml
Labels: Bump version

#14412 simdjson: add version 3.0.1
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#14417 c4core: update fast_float
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#14418 scnlib: update fast_float
  recipes/scnlib/all/conanfile.py
Labels: Bump dependencies

#14377 docs: update picking sources and unify with patching rules
  docs/adding_packages/conandata_yml_format.md
  docs/adding_packages/policy_patching.md
  docs/adding_packages/reviewing.md
  docs/adding_packages/sources_and_patches.md
  docs/developing_recipes_locally.md
  docs/faqs.md
Labels: Docs

#14425 botan: add version 2.19.3
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#14436 quill: add version 2.5.1
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#14438 protopuf: add version 2.2.1
  recipes/protopuf/all/conandata.yml
  recipes/protopuf/config.yml
Labels: Bump version

#14370 linter: dont allow backport as patch type (to match docs)
  linter/conandata_yaml_linter.py
Labels: GitHub config

#14442 wasmtime-cpp: add version 3.0.0
  recipes/wasmtime-cpp/all/conandata.yml
  recipes/wasmtime-cpp/config.yml
Labels: Bump version

#14443 flatbuffers: add version 22.11.23
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#14448 confu_json: add version 0.0.10
  recipes/confu_json/all/conandata.yml
  recipes/confu_json/config.yml
Labels: Bump version

#14449 fast_float: add v2.8.1
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#14454 glaze: update fast_float
  recipes/glaze/all/conanfile.py
Labels: Bump dependencies

#14483 daw_json_link: add version 3.10.0
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#14484 md4qt: bump version to 2.0.1.
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#14455 c4core: update fast_float
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#14456 scnlib: update fast_float
  recipes/scnlib/all/conanfile.py
Labels: Bump dependencies

#14469 blend2d: update asmjit
  recipes/blend2d/all/conanfile.py
Labels: Bump dependencies
