Repository conan-io/conan-center-index, pull requests merged in 2022-08, with the labels that each got.

#11983 luau: add version 0.538
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump dependencies

#11948 [linter] Add more checks to migrate import for tools
  docs/v2_linter.md
  linter/transform_imports.py
Labels: Docs, C3I config

#11989 typo: import from conan
  docs/v2_linter.md
Labels: Docs

#11991 nlohmann_json: Add version 3.11.0
  recipes/nlohmann_json/all/conandata.yml
  recipes/nlohmann_json/config.yml
Labels: Bump version

#12004 nlohmann_json: Add version 3.11.1
  recipes/nlohmann_json/all/conandata.yml
  recipes/nlohmann_json/config.yml
Labels: Bump version

#11982 docs: encourage export only the patches used
  docs/reviewing.md
Labels: Docs

#11974 fix sdl deps
  recipes/sdl/all/conanfile.py
Labels: Bump dependencies

#12016 libmikmod bump deps
  recipes/libmikmod/all/conanfile.py
Labels: Bump dependencies

#12017 pulseaudio update deps
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#12019 emsdk update for 3.1.18
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#12018 sdl update deps
  recipes/sdl/all/conanfile.py
Labels: Bump dependencies

#12009 [ffmpeg/xxx] Bump dependencies
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#12026 [sentry-crashpad/0.5.0] Add version
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#12027 [sentry-breakpad/0.5.0]
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#12035 cpp-httplib: add version 0.11.1
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#12032 [sentry-native/0.5.0] Add version
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#11656 Documented missing errors from knowledge base
  docs/error_knowledge_base.md
Labels: Docs

#12052 [linter] Fix enabled/disabled items for test_package
  linter/pylintrc_testpackage
Labels: C3I config

#12060 fast_float: add version 3.5.1
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#12046 [libx264/20220602] Add version
  recipes/libx264/all/conandata.yml
  recipes/libx264/config.yml
Labels: Bump version

#12061 daw_header_libraries: add version 2.68.3
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#12065 [docs] Update changelog 8-August-2022
  docs/changelog.md
Labels: Docs

#12077 nameof: add version 0.10.2
  recipes/nameof/all/conandata.yml
  recipes/nameof/config.yml
Labels: Bump version

#12088 opentelemetry-proto: add version 0.19.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#12091 at-spi2-core: add version 2.45.90
  recipes/at-spi2-core/config.yml
  recipes/at-spi2-core/new/conandata.yml
Labels: Bump version

#12092 aws-c-common: add version 0.7.5
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#12095 Add expected-lite/0.6.2
  recipes/expected-lite/all/conandata.yml
  recipes/expected-lite/config.yml
Labels: Bump version

#12097 tree-sitter-c: add version 0.20.2
  recipes/tree-sitter-c/all/conandata.yml
  recipes/tree-sitter-c/config.yml
Labels: Bump version

#12096 stc: add version 3.9
  recipes/stc/all/conandata.yml
  recipes/stc/config.yml
Labels: Bump version

#12103 fast-cdr 1.0.24 support
  recipes/fast-cdr/all/conandata.yml
  recipes/fast-cdr/config.yml
Labels: Bump version

#12100 luau: add version 0.539
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#12115 sjson-cpp: add version 0.8.3
  recipes/sjson-cpp/all/conandata.yml
  recipes/sjson-cpp/config.yml
Labels: Bump version

#12116 highway: add version 1.0.0
  recipes/highway/all/conandata.yml
  recipes/highway/config.yml
Labels: Bump version

#12138 Add string-view-lite/1.7.0
  recipes/string-view-lite/all/conandata.yml
  recipes/string-view-lite/config.yml
Labels: Bump version

#12136 [linter] Do not promote migration of `Version` class (yet)
  docs/v2_linter.md
  linter/transform_imports.py
Labels: Docs, C3I config

#12127 docs: fix markup for automatic table of contents
  docs/conandata_yml_format.md
  docs/consuming_recipes.md
  docs/policy_patching.md
  docs/v2_migration.md
  docs/v2_roadmap.md
Labels: Docs

#12141 vectorclass: add 2.02.00
  recipes/vectorclass/all/conandata.yml
  recipes/vectorclass/config.yml
Labels: Bump version

#12142 Add @jcar87 to reviewers list (as a team member)
  .c3i/reviewers.yml
Labels: C3I config

#12150 modern-cpp-kafka: add version 2022.08.01
  recipes/modern-cpp-kafka/all/conandata.yml
  recipes/modern-cpp-kafka/config.yml
Labels: Bump version

#12172 nlohmann_json: Add version 3.11.2
  recipes/nlohmann_json/all/conandata.yml
  recipes/nlohmann_json/config.yml
Labels: Bump version

#12194 meson: add version 0.63.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#12235 xbyak: add version 6.61.2
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#12170 YML linter - Add more rules
  linter/yamllint_rules.yml
Labels: C3I config

#12202 luau: add version 0.540
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#12250 grpc-proto - bump deps
  recipes/grpc-proto/all/conanfile.py
Labels: Bump dependencies

#12163 Up Conan version + recover linter for Version
  .c3i/config_v1.yml
  docs/v2_linter.md
  linter/transform_imports.py
Labels: Docs, C3I config

#12261 libwebp: add version 1.2.4
  recipes/libwebp/all/conandata.yml
  recipes/libwebp/config.yml
Labels: Bump version

#12157 bubmpup grpc protobuf dependency to 3.21.4
  recipes/grpc/all/conanfile.py
Labels: Bump dependencies

#12289 libjpeg-turbo: add version 2.1.4
  recipes/libjpeg-turbo/all/conandata.yml
  recipes/libjpeg-turbo/config.yml
Labels: Bump version

#12254 linter v2 - Request migration of `conans.errors` to `conan.errors`
  docs/v2_linter.md
  linter/transform_imports.py
Labels: Docs, C3I config

#12251 grpc - bump deps
  recipes/grpc/all/conanfile.py
Labels: Bump dependencies

#12307 proposal: bump to 7.4.0
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#12330 linter - fix regex matching messages
  linter/check_import_errors.py
  linter/conanv2_test_transition.py
  linter/conanv2_transition.py
  linter/recipe_linter.json
  linter/transform_imports.py
Labels: C3I config

#12280 docs: update instruction for conandata format and patching
  docs/how_to_add_packages.md
  docs/package/all/conandata.yml
  docs/package/all/conanfile.py
  docs/reviewing.md
Labels: Docs

#12298 [linter] Fix linter v2 running on test_v1_package conanfiles
  .github/workflows/linter-conan-v2.yml
  docs/v2_linter.md
Labels: Docs, GitHub config

#12347 [config] Add franramirez688 as team reviewer
  .c3i/reviewers.yml
Labels: C3I config

#12381 luau: add version 0.541
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#10888 prometheus-cpp: Bump to 1.0.1
  recipes/prometheus-cpp/all/conandata.yml
  recipes/prometheus-cpp/config.yml
Labels: Bump version

#12436 Update changelog
  docs/changelog.md
Labels: Docs

#12441 [docs] Conan v2 Linter: Required Conan version
  docs/v2_linter.md
Labels: Docs

#12460 cpp-peglib: add version 1.6.1
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#12437 [config] Upgrade Conan version
  .c3i/config_v1.yml
Labels: C3I config

#12463 proposal: bump to 7.4.1
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#11468 [config] Remove old jenkinsfile and start using new configuration
  .c3i/reviewers.yml
  .jenkins/Jenkinsfile
Labels: C3I config

#12540 [docs] consuming recipes: add link to base lockiles & lockfile bundles docs
  docs/consuming_recipes.md
Labels: Docs

#12575 [docs] Update the template package to use V1 & V2 support
  docs/package/all/CMakeLists.txt
  docs/package/all/conanfile.py
  docs/package/all/test_package/CMakeLists.txt
  docs/package/all/test_package/conanfile.py
  docs/package/all/test_package/test_package.cpp
  docs/package/all/test_v1_package/CMakeLists.txt
  docs/package/all/test_v1_package/conanfile.py
Labels: Docs

#12625 artery-font-format: add version 1.0.1
  recipes/artery-font-format/all/conandata.yml
  recipes/artery-font-format/config.yml
Labels: Bump version

#12291 clipper: update checksum for v4.10.0
  recipes/clipper/all/conandata.yml
Labels: checksum_mismatch

#12633 libatomic_ops: add version 7.6.14
  recipes/libatomic_ops/all/conandata.yml
  recipes/libatomic_ops/config.yml
Labels: Bump version

#12687 docs: spelling and formatting
  docs/changelog.md
  docs/code_of_conduct.md
  docs/community_resources.md
  docs/consuming_recipes.md
  docs/error_knowledge_base.md
  docs/faqs.md
  docs/labels.md
  docs/review_process.md
  docs/v2_linter.md
  docs/v2_migration.md
  docs/v2_roadmap.md
Labels: Docs

#12694 [community] Add paulocoutinhox as community reviewer
  .c3i/reviewers.yml
Labels: C3I config

#12714 [docs] Add ConanCenter remote
  README.md
Labels: Docs

#12724 Bump flecs/3.0.4
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version
