Repository conan-io/conan-center-index, pull requests merged in 2023-07, with the labels that each got.

#18222 quill: add version 3.1.0, remove older versions
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#18269 libuv: add version 1.46.0
  recipes/libuv/all/conandata.yml
  recipes/libuv/config.yml
Labels: Bump version

#18282 glaze: add version 1.3.0, remove older versions
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#18320 libunwind: bump dep xz_utils
  recipes/libunwind/all/conanfile.py
Labels: Bump dependencies

#18319 sdl_image: bump dep sdl to latest patch
  recipes/sdl_image/all/conanfile.py
Labels: Bump dependencies

#18326 cjson: add version 1.7.16
  recipes/cjson/all/conandata.yml
  recipes/cjson/config.yml
Labels: Bump version

#18327 benchmark: add version 1.8.1
  recipes/benchmark/all/conandata.yml
  recipes/benchmark/config.yml
Labels: Bump version

#18331 libtiff/all: bump deps
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#18334 nanoflann: add version 1.5.0
  recipes/nanoflann/all/conandata.yml
  recipes/nanoflann/config.yml
Labels: Bump version

#18337 opencv: bump libwebp version
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#18339 imgui: add version 1.89.7, 1.89.7-docking
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#18329 Bump/libcurl/all
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#18358 freetype: bump dep libpng
  recipes/freetype/all/conanfile.py
Labels: Bump dependencies

#18370 nlohmann_json: add version 3.5.0
  recipes/nlohmann_json/all/conandata.yml
  recipes/nlohmann_json/config.yml
Labels: Bump version

#18374 libpng: add version 1.6.32
  recipes/libpng/all/conandata.yml
  recipes/libpng/config.yml
Labels: Bump version

#18276 flatbush: add release v1.2.0
  recipes/flatbush/all/conandata.yml
  recipes/flatbush/config.yml
Labels: Bump version

#18383 hwloc 2.9.2
  recipes/hwloc/all/conandata.yml
  recipes/hwloc/config.yml
Labels: Bump version

#18378 benchmark: add version 1.8.2
  recipes/benchmark/all/conandata.yml
  recipes/benchmark/config.yml
Labels: Bump version

#18393 simdjson: add version 3.2.1, remove older versions
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#18394 glib: add version 2.77.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#18397 infra: add Visual Studio 2022 configuration to Conan 2.0 checks (msvc 193)
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#18396 Add MartinDelille as reviewer for snowhouse
  .github/workflows/alert-community.yml
Labels: GitHub config

#18407 etl: add version 20.37.0, remove older versions
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#18003 [sentry-native] Add version 0.6.3
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#18412 cyclonedds: Bump version to 0.10.3
  recipes/cyclonedds/all/conandata.yml
  recipes/cyclonedds/config.yml
Labels: Bump version

#18420 libharu: bump deps
  recipes/libharu/all/conanfile.py
Labels: Bump dependencies

#18424 jsoncons: add version 0.171.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#18426 commata: add version 0.2.5
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#18422 uni-algo: add version 1.0.0
  recipes/uni-algo/all/conandata.yml
  recipes/uni-algo/config.yml
Labels: Bump version

#18427 harfbuzz: add version 8.0.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#18435 [sentry-crashpad/0.6.5] Add version
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#18432 freeimage/all: bump deps
  recipes/freeimage/all/conanfile.py
Labels: Bump dependencies

#18440 cairo/meson: bump deps
  recipes/cairo/meson/conanfile.py
Labels: Bump dependencies

#18439 opencv/2.x: bump deps
  recipes/opencv/2.x/conanfile.py
Labels: Bump dependencies

#18448 sqlpp11: add version 0.63
  recipes/sqlpp11/all/conandata.yml
  recipes/sqlpp11/config.yml
Labels: Bump version

#18446 spdlog: add version 1.12.0
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#18442 libraw/all: bump deps
  recipes/libraw/all/conanfile.py
Labels: Bump dependencies

#18454 sail/all: bump deps
  recipes/sail/all/conanfile.py
Labels: Bump dependencies

#18450 opencv/3.x: bump deps
  recipes/opencv/3.x/conanfile.py
Labels: Bump dependencies

#18455 leptonica/all: bump deps
  recipes/leptonica/all/conanfile.py
Labels: Bump dependencies

#18451 opencv/4.x: bump deps
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#18460 wavelet_buffer/all: bump deps
  recipes/wavelet_buffer/all/conanfile.py
Labels: Bump dependencies

#18281 Add flecs version 3.2.4
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version

#18406 zug: add version 0.1.0
  recipes/zug/all/conandata.yml
  recipes/zug/config.yml
Labels: Bump version

#18436 proj/all: bump deps
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#18482 glaze: add version 1.3.1, remove older versions
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#18484 b2: add version 4.10.1
  recipes/b2/config.yml
  recipes/b2/portable/conandata.yml
Labels: Bump version

#18447 [GMP] change the data source
  recipes/gmp/all/conandata.yml
Labels: checksum_mismatch

#18485 libspatialite/all: bump deps
  recipes/libspatialite/all/conanfile.py
Labels: Bump dependencies

#18488 librasterlite/all: bump deps
  recipes/librasterlite/all/conanfile.py
Labels: Bump dependencies

#18504 harfbuzz: add version 8.0.1
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#18480 Docs: remove some duplicated migration entries
  docs/v2_migration.md
Labels: Docs

#18510 screen_capture_lite: add version 17.1.1327
  recipes/screen_capture_lite/all/conandata.yml
  recipes/screen_capture_lite/config.yml
Labels: Bump version

#18503 openscenegraph/all: bump deps
  recipes/openscenegraph/all/conanfile.py
Labels: Bump dependencies

#18516 tl-optional: add version 1.1.0
  recipes/tl-optional/all/conandata.yml
  recipes/tl-optional/config.yml
Labels: Bump version

#18513 adds range of openssl libs to have wider compatibility
  recipes/jwt-cpp/all/conanfile.py
Labels: Bump dependencies

#18431 openimageio/all: bump deps
  recipes/openimageio/all/conanfile.py
Labels: Bump dependencies

#18538 etl: add version 20.37.1
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#18537 glaze: add version 1.3.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#18536 catch2: add version 3.4.0
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#18541 [config] Add pcl reference to the extra-large pod size list
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#18481 clarify public domaing licenses
  docs/adding_packages/conanfile_attributes.md
Labels: Docs

#18565 daw_json_link: add version 3.19.0, remove older versions
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Bump version

#18562 libnghttp2: add version 1.55.1
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#18576 effolkronium-random: add version 1.5.0
  recipes/effolkronium-random/all/conandata.yml
  recipes/effolkronium-random/config.yml
Labels: Bump version

#18581 meson: add version 1.2.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#18599 spdlog_setup: bump dependencies
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#18591 [config] Update conan v2 to 2.0.8
  .c3i/config_v2.yml
Labels: C3I config

#18605 restinio: bump dependencies
  recipes/restinio/all/conanfile.py
Labels: Bump dependencies

#18609 at-spi2-core 2.49.1
  recipes/at-spi2-core/config.yml
  recipes/at-spi2-core/new/conandata.yml
  recipes/at-spi2-core/new/patches/93.patch
Labels: Bump version

#18612 dbus/1.x.x: bump deps
  recipes/dbus/1.x.x/conanfile.py
Labels: Bump dependencies

#18617 qt/5.x.x: bump deps
  recipes/qt/5.x.x/conanfile.py
Labels: Bump dependencies

#18627 ada: add version 2.5.1
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#18614 qt/6.x.x: bump deps
  recipes/qt/6.x.x/conanfile.py
Labels: Bump dependencies

#18630 Bump opencv requirements
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#18364 ffmpeg: bump libwebp version
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#18645 [changelog] C3I Jenkins Release - 19 July 2013
  docs/changelog.md
Labels: Docs

#18713 highway: add version 1.0.5
  recipes/highway/all/conandata.yml
  recipes/highway/config.yml
Labels: Bump version

#18762 Add dav1d/1.2.1
  recipes/dav1d/all/conandata.yml
  recipes/dav1d/config.yml
Labels: Bump version

#18763 Add libaom-av1 release 3.6.1
  recipes/libaom-av1/all/conandata.yml
  recipes/libaom-av1/config.yml
Labels: Bump version

#18773 aeron: add version 1.41.4
  recipes/aeron/all/conandata.yml
  recipes/aeron/config.yml
Labels: Bump version

#18805 cairo/all: bump deps
  recipes/cairo/all/conanfile.py
Labels: Bump dependencies

#18566 docs: Improve license attribute guidelines
  docs/adding_packages/conanfile_attributes.md
  docs/faqs.md
Labels: Docs

#18856 xtr: bump to 2.1.0
  recipes/xtr/all/conandata.yml
  recipes/xtr/config.yml
Labels: Bump version
