Repository conan-io/conan-center-index, pull requests merged in 2023-12, with the labels that each got.

#21538 glog: Bump deps to fix conflicts
  recipes/glog/all/conanfile.py
Labels: Bump dependencies

#21540 libtiff: Bump deps to fix conflicts
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#21516 pcl/all: bump deps
  recipes/pcl/all/conanfile.py
Labels: Bump dependencies

#21548 glaze: add version 1.8.3
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#21528 simdjson: add version 3.6.1
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#21551 tinydir: add version 1.2.6
  recipes/tinydir/all/conandata.yml
  recipes/tinydir/config.yml
Labels: Bump version

#21537 re2: Bump deps to fix conflicts
  recipes/re2/all/conanfile.py
Labels: Bump dependencies

#21559 skyr-url: update nlohmann_json
  recipes/skyr-url/all/conanfile.py
Labels: Bump dependencies

#21578 minizip-ng: Update xz_utils requirements
  recipes/minizip-ng/all/conanfile.py
Labels: Bump dependencies

#21497 libcurl/all: bump deps
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#21579 ffmpeg: Update xz_utils requirements
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#21460 libbigwig: update dependencies
  recipes/libbigwig/all/conanfile.py
Labels: Bump dependencies

#21366 sqlpp11-connector-sqlite3: bump sqlite3
  recipes/sqlpp11-connector-sqlite3/all/conanfile.py
Labels: Bump dependencies

#21580 opencolorio: bump deps
  recipes/opencolorio/all/conanfile.py
Labels: Bump dependencies

#21583 xerces-c: bump icu
  recipes/xerces-c/all/conanfile.py
Labels: Bump dependencies

#21582 libmysqlclient: bump libunwind
  recipes/libmysqlclient/all/conanfile.py
Labels: Bump dependencies

#21584 libsigcpp: bump pkgconf
  recipes/libsigcpp/2.x.x/test_v1_package/conanfile.py
Labels: Bump dependencies

#21586 proj/all: bump deps
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#21587 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21590 etl: add version 20.38.7
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#21598 cpp-httplib: add version 0.14.2
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#21603 [docs] Add changelog 05-December-2023
  docs/changelog.md
Labels: Docs

#21600 cpprestsdk: add version 2.10.19
  recipes/cpprestsdk/all/conandata.yml
  recipes/cpprestsdk/config.yml
Labels: Bump version

#21607 sdl/all: bump deps
  recipes/sdl/all/conanfile.py
Labels: Bump dependencies

#21609 aravis: add version 0.8.30
  recipes/aravis/all/conandata.yml
  recipes/aravis/config.yml
Labels: Bump version

#21619 perfetto: Bump version: 40.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#21623 libtins: bump libpcap
  recipes/libtins/all/conanfile.py
Labels: Bump dependencies

#21634 xbyak: add version 7.00
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#21636 libbpf: add version 1.3.0
  recipes/libbpf/all/conandata.yml
  recipes/libbpf/config.yml
Labels: Bump version

#21618 [emsdk] bump to 3.1.50
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#21638 evmc: add version 11.0.0
  recipes/evmc/all/conandata.yml
  recipes/evmc/config.yml
Labels: Bump version

#21673 glib: add version 2.78.3
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#21691 r8brain-free-src: add version 6.5
  recipes/r8brain-free-src/all/conandata.yml
  recipes/r8brain-free-src/config.yml
Labels: Bump version

#21696 xsimd: add version 12.1.0
  recipes/xsimd/all/conandata.yml
  recipes/xsimd/config.yml
Labels: Bump version

#21702 quill: add version 3.5.1
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#21703 zxing-cpp: add version 2.2.1
  recipes/zxing-cpp/all/conandata.yml
  recipes/zxing-cpp/config.yml
Labels: Bump version

#21705 readline/all: bump ncurses to v6.4
  recipes/readline/all/conanfile.py
Labels: Bump dependencies

#21716 recipes/libbpf: bump elfutils to v0.190
  recipes/libbpf/all/conanfile.py
Labels: Bump dependencies

#21723 rtm: add version 2.2.0
  recipes/rtm/all/conandata.yml
  recipes/rtm/config.yml
Labels: Bump version

#21655 wolfssl: add version 5.6.4
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#21678 g3log: add version 2.4
  recipes/g3log/all/conandata.yml
  recipes/g3log/config.yml
Labels: Bump version

#21711 libarchive/all: bump deps
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#21718 catch2: add version 3.5.0
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#21727 xmlsec: bump libxslt
  recipes/xmlsec/all/conanfile.py
Labels: Bump dependencies

#21732 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21706 readline: add version 8.2
  recipes/readline/all/conandata.yml
  recipes/readline/config.yml
Labels: Bump version

#21733 etl: add version 20.38.10
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#21654 mbedtls: add version 3.5.1
  recipes/mbedtls/all/conandata.yml
  recipes/mbedtls/config.yml
Labels: Bump version

#21778 fast_float: add version 6.0.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#21779 valijson: add version 1.0.2
  recipes/valijson/all/conandata.yml
  recipes/valijson/config.yml
Labels: Bump version

#21793 objectbox: add version 0.20.0
  recipes/objectbox/all/conandata.yml
  recipes/objectbox/config.yml
Labels: Bump version

#21794 scnlib: update fast_float/6.0.0
  recipes/scnlib/all/conanfile.py
Labels: Bump dependencies

#21773 wayland/all: bump deps
  recipes/wayland/all/conanfile.py
  recipes/wayland/all/test_package/conanfile.py
Labels: Bump dependencies

#21777 libdrm/all: bump deps
  recipes/libdrm/all/conanfile.py
Labels: Bump dependencies

#21797 rtm: add version 2.2.1
  recipes/rtm/all/conandata.yml
  recipes/rtm/config.yml
Labels: Bump version

#21774 wayland-protocols/all: bump deps
  recipes/wayland-protocols/all/conanfile.py
  recipes/wayland-protocols/all/test_package/conanfile.py
Labels: Bump dependencies

#21801 ssp: update fast_float/6.0.0
  recipes/ssp/all/conanfile.py
Labels: Bump dependencies

#21800 highfive: update hdf5/1.14.3
  recipes/highfive/all/conanfile.py
Labels: Bump dependencies

#21799 c4core: update fast_float/6.0.0
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#21780 jsoncons: add version 0.173.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#21701 asio: add version 1.29.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#21802 hictk: update dependencies
  recipes/hictk/all/conanfile.py
Labels: Bump dependencies

#21786 roaring: add version 2.1.0
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#21677 bzip3: add version 1.4.0
  recipes/bzip3/all/conandata.yml
  recipes/bzip3/config.yml
Labels: Bump version

#21809 quill: add version 3.6.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#21811 unordered_dense: add version 4.3.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#21567 tinygltf: update dependencies
  recipes/tinygltf/all/conanfile.py
Labels: Bump dependencies

#21693 plf_colony: add version 7.39
  recipes/plf_colony/all/conandata.yml
  recipes/plf_colony/config.yml
Labels: Bump version

#21690 kuba-zip: add version 0.3.0
  recipes/kuba-zip/all/conandata.yml
  recipes/kuba-zip/config.yml
Labels: Bump version

#21814 xtl: add version 0.7.6
  recipes/xtl/all/conandata.yml
  recipes/xtl/config.yml
Labels: Bump version

#21768 uni-algo: add version 1.2.0
  recipes/uni-algo/all/conandata.yml
  recipes/uni-algo/config.yml
Labels: Bump version

#21813 arrow: add version 14.0.2
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#21789 uwebsockets: add version 20.49.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#21769 s2n: add version 1.4.0
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#21821 xkbcommon: partial bump
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#21826 [config] Change configurations to amrv8 arch for Macos build profiles
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#21824 xkbcommon: bump deps
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#21839 Add restinio v0.7.1
  recipes/restinio/config.yml
  recipes/restinio/v0.7/conandata.yml
Labels: Bump version

#21844 bdwgc/all: bump deps
  recipes/bdwgc/all/conanfile.py
Labels: Bump dependencies

#21785 opencv/3.x add version 3.4.20
  recipes/opencv/3.x/conandata.yml
  recipes/opencv/config.yml
Labels: Bump version

#21661 openblas: add v0.3.25
  recipes/openblas/all/conandata.yml
  recipes/openblas/config.yml
Labels: Bump version

#21663 raylib: add v5.0
  recipes/raylib/all/conandata.yml
  recipes/raylib/config.yml
Labels: Bump version

#21847 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21864 libnl: add v3.9.0
  recipes/libnl/all/conandata.yml
  recipes/libnl/config.yml
Labels: Bump version

#21849 7bitdi: add v2.0.0
  recipes/7bitdi/all/conandata.yml
  recipes/7bitdi/config.yml
Labels: Bump version

#21851 libde265: add v1.0.15
  recipes/libde265/all/conandata.yml
  recipes/libde265/config.yml
Labels: Bump version

#21850 lightgbm: add v4.2.0
  recipes/lightgbm/all/conandata.yml
  recipes/lightgbm/config.yml
Labels: Bump version

#21854 libraw: add v0.21.2
  recipes/libraw/all/conandata.yml
  recipes/libraw/config.yml
Labels: Bump version

#21859 zfp: add version 1.0.1
  recipes/zfp/all/conandata.yml
  recipes/zfp/config.yml
Labels: Bump version

#21866 libwebsockets: add version 4.3.3
  recipes/libwebsockets/all/conandata.yml
  recipes/libwebsockets/config.yml
Labels: Bump version

#21828 unordered_dense: add version 4.3.1
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#21867 cpp-httplib: add version 0.14.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#21868 uwebsockets: add version 20.51.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#21871 [openapi-generator] Add version 7.2.0
  recipes/openapi-generator/all/conandata.yml
  recipes/openapi-generator/config.yml
Labels: Bump version

#21882 commata: add version 0.2.8
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#21885 unordered_dense: add version 4.4.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#21887 libavif: add version 1.0.3
  recipes/libavif/all/conandata.yml
  recipes/libavif/config.yml
Labels: Bump version

#21891 libxslt: add version 1.1.39
  recipes/libxslt/all/conandata.yml
  recipes/libxslt/config.yml
Labels: Bump version

#21895 uwebsockets: add version 20.53.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#21863 tinygltf: add v2.8.19
  recipes/tinygltf/all/conandata.yml
  recipes/tinygltf/config.yml
Labels: Bump version

#21898 libgphoto2: bump deps
  recipes/libgphoto2/all/conanfile.py
Labels: Bump dependencies

#21897 aravis: bump deps
  recipes/aravis/all/conanfile.py
Labels: Bump dependencies

#21902 norm: bump deps
  recipes/norm/all/conanfile.py
Labels: Bump dependencies

#21899 libnghttp2: bump deps
  recipes/libnghttp2/all/conanfile.py
Labels: Bump dependencies

#21908 linux-syscall-support: add v2022.10.12
  recipes/linux-syscall-support/all/conandata.yml
  recipes/linux-syscall-support/config.yml
Labels: Bump version

#21906 nettle: add v3.9.1
  recipes/nettle/all/conandata.yml
  recipes/nettle/config.yml
Labels: Bump version

#21918 extra-cmake-modules: add v5.113.0
  recipes/extra-cmake-modules/all/conandata.yml
  recipes/extra-cmake-modules/config.yml
Labels: Bump version

#21913 drflac: add v0.12.42
  recipes/drflac/all/conandata.yml
  recipes/drflac/config.yml
Labels: Bump version

#21920 cfitsio: add v4.3.1
  recipes/cfitsio/all/conandata.yml
  recipes/cfitsio/config.yml
Labels: Bump version

#21909 lmdb: add v0.9.31
  recipes/lmdb/all/conandata.yml
  recipes/lmdb/config.yml
Labels: Bump version

#21925 aaplus: add v2.53
  recipes/aaplus/all/conandata.yml
  recipes/aaplus/config.yml
Labels: Bump version

#21928 blaze: add v3.8.2
  recipes/blaze/all/conandata.yml
  recipes/blaze/config.yml
Labels: Bump version

#21931 plf_stack: add v2.0.1
  recipes/plf_stack/all/conandata.yml
  recipes/plf_stack/config.yml
Labels: Bump version

#21932 plf_queue: add v2.0.2
  recipes/plf_queue/all/conandata.yml
  recipes/plf_queue/config.yml
Labels: Bump version

#21934 plf_indiesort: add v1.41
  recipes/plf_indiesort/all/conandata.yml
  recipes/plf_indiesort/config.yml
Labels: Bump version

#21900 hwloc: bump deps
  recipes/hwloc/all/conanfile.py
Labels: Bump dependencies

#21886 Add cppcheck 2.13
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#21901 libmetalink: bump deps
  recipes/libmetalink/all/conanfile.py
Labels: Bump dependencies

#21935 dav1d: add v1.3.0
  recipes/dav1d/all/conandata.yml
  recipes/dav1d/config.yml
Labels: Bump version

#21936 cimg: add v3.3.2
  recipes/cimg/all/conandata.yml
  recipes/cimg/config.yml
Labels: Bump version

#21487 aws-c-auth: add version 0.7.8
  recipes/aws-c-auth/all/conandata.yml
  recipes/aws-c-auth/config.yml
Labels: Bump version

#21940 mozilla-build: add v4.0.2
  recipes/mozilla-build/all/conandata.yml
  recipes/mozilla-build/config.yml
Labels: Bump version

#21941 mujs: add v1.3.4
  recipes/mujs/all/conandata.yml
  recipes/mujs/config.yml
Labels: Bump version

#21946 rapidfuzz: add version 3.0.0
  recipes/rapidfuzz/all/conandata.yml
  recipes/rapidfuzz/config.yml
Labels: Bump version

#21955 libunistring: add v1.1
  recipes/libunistring/all/conandata.yml
  recipes/libunistring/config.yml
Labels: Bump version

#21958 libgpg-error: add v1.47
  recipes/libgpg-error/all/conandata.yml
  recipes/libgpg-error/config.yml
Labels: Bump version

#21960 meson: add version 1.3.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#21964 functionalplus: add version 0.2.22
  recipes/functionalplus/all/conandata.yml
  recipes/functionalplus/config.yml
Labels: Bump version

#21963 cjson: add version 1.7.17
  recipes/cjson/all/conandata.yml
  recipes/cjson/config.yml
Labels: Bump version

#21965 frugally-deep: add version 0.15.29
  recipes/frugally-deep/all/conandata.yml
  recipes/frugally-deep/config.yml
Labels: Bump version

#21966 xkbcommon/all: bump deps
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#21944 libxml2: bump deps
  recipes/libxml2/all/conanfile.py
Labels: Bump dependencies

#21974 libxml2: add 2.12.3
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#21976 libxml2: add version 2.11.6
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#21970 libnetfilter_conntrack: add v1.0.9
  recipes/libnetfilter_conntrack/all/conandata.yml
  recipes/libnetfilter_conntrack/config.yml
Labels: Bump version

#21977 wayland: bump deps
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#21978 norm: bump deps
  recipes/norm/all/conanfile.py
Labels: Bump dependencies

#21921 cista: add v0.14
  recipes/cista/all/conandata.yml
  recipes/cista/config.yml
Labels: Bump version

#21979 libnghttp2: bump deps
  recipes/libnghttp2/all/conanfile.py
Labels: Bump dependencies

#21980 libmetalink: bump deps
  recipes/libmetalink/all/conanfile.py
Labels: Bump dependencies

#21981 libgphoto2: bump deps
  recipes/libgphoto2/all/conanfile.py
Labels: Bump dependencies

#21982 libarchive: bump deps
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#21983 hwloc: bump deps
  recipes/hwloc/all/conanfile.py
Labels: Bump dependencies

#21984 aravis: bump deps
  recipes/aravis/all/conanfile.py
Labels: Bump dependencies

#21992 libdc1394: add v2.2.7
  recipes/libdc1394/all/conandata.yml
  recipes/libdc1394/config.yml
Labels: Bump version

#21993 libdrm: add v2.4.119
  recipes/libdrm/all/conandata.yml
  recipes/libdrm/config.yml
Labels: Bump version

#21994 libfdk_aac: add v2.0.3
  recipes/libfdk_aac/all/conandata.yml
  recipes/libfdk_aac/config.yml
Labels: Bump version

#21998 fontconfig: add v2.15.0
  recipes/fontconfig/config.yml
  recipes/fontconfig/meson/conandata.yml
Labels: Bump version

#21999 gdcm: add v3.0.22
  recipes/gdcm/all/conandata.yml
  recipes/gdcm/config.yml
Labels: Bump version

#22001 scons: add v4.6.0
  recipes/scons/all/conandata.yml
  recipes/scons/config.yml
Labels: Bump version
