Repository conan-io/conan-center-index, pull requests merged in 2023-02, with the labels that each got.

#15500 linter workflow: fix linter change test on test_package
  .github/workflows/linter-conan-v2.yml
Labels: GitHub config

#15531 modern-cpp-kafka: add version 2023.01.05
  recipes/modern-cpp-kafka/all/conandata.yml
  recipes/modern-cpp-kafka/config.yml
Labels: Bump version

#15554 [service] fix community alerts
  .github/actions/alert-community/action.yml
  .github/workflows/alert-community.yml
Labels: GitHub config

#15561 Bump vulkan-headers/1.3.239.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#15578 zstd: get source code from official release tarballs
  recipes/zstd/all/conandata.yml
Labels: checksum_mismatch

#15579 fmt: download official release tarballs + modernize more
  recipes/fmt/all/conandata.yml
  recipes/fmt/all/conanfile.py
  recipes/fmt/all/test_package/conanfile.py
Labels: checksum_mismatch

#15584 xkbcommon: download official tarballs & bump wayland-protocols
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/all/conanfile.py
Labels: checksum_mismatch

#15587 jasper: download official tarballs
  recipes/jasper/all/conandata.yml
Labels: checksum_mismatch

#15597 libnghttp2: download official tarballs + modernize more
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/all/conanfile.py
Labels: checksum_mismatch

#15606 action: pr_changed_files: exclude removed files
  .github/actions/pr_changed_files/action.yml
Labels: GitHub config

#15593 lcms: download official tarballs
  recipes/lcms/all/conandata.yml
Labels: checksum_mismatch

#15689 glaze: add version 0.3.6
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#15592 geos: download official tarball + modernize more
  recipes/geos/all/conandata.yml
  recipes/geos/all/conanfile.py
Labels: checksum_mismatch

#15509 imgui: add version cci.20230105+1.89.2.docking
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#15586 libjpeg-turbo: add 2.1.5 + download official tarballs + no manual injection of CMAKE_SYSTEM_PROCESSOR
  recipes/libjpeg-turbo/all/CMakeLists.txt
  recipes/libjpeg-turbo/all/conandata.yml
  recipes/libjpeg-turbo/all/conanfile.py
  recipes/libjpeg-turbo/all/patches/2.1.3-0001-fix-cmake.patch
  recipes/libjpeg-turbo/config.yml
Labels: checksum_mismatch

#15588 libgeotiff: download official tarballs + bump proj
  recipes/libgeotiff/all/conandata.yml
  recipes/libgeotiff/all/conanfile.py
  recipes/libgeotiff/all/patches/fix-cmake-1.5.1.patch
  recipes/libgeotiff/all/patches/fix-cmake-1.6.0.patch
  recipes/libgeotiff/all/patches/fix-cmake-1.7.1.patch
  recipes/libgeotiff/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15591 glm: download official tarballs + modernize more
  recipes/glm/all/conandata.yml
  recipes/glm/all/conanfile.py
  recipes/glm/all/test_package/conanfile.py
  recipes/glm/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15658 (#15657) Perfetto: Bump to v32.1
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#15667 unordered_dense: add version 3.1.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#15671 Bump vulkan-loader/1.3.239.0
  recipes/vulkan-loader/all/conandata.yml
  recipes/vulkan-loader/config.yml
Labels: Bump version

#15684 cs_libguarded: add version 1.4.0
  recipes/cs_libguarded/all/conandata.yml
  recipes/cs_libguarded/config.yml
Labels: Bump version

#15690 android-ndk: add r25c
  recipes/android-ndk/all/conandata.yml
  recipes/android-ndk/config.yml
Labels: Bump version

#15577 [catch2] adds Catch2 v3.3.1
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#15691 libharu: bump dependency version: libpng
  recipes/libharu/all/conanfile.py
Labels: Bump dependencies

#15692 netcdf: bump dependency version: libcurl
  recipes/netcdf/all/conanfile.py
Labels: Bump dependencies

#15696 arrow: add version 10.0.1
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#15701 [docs] Update changelog 03-February-2023
  docs/changelog.md
Labels: Docs

#15718 cmake: add version 3.25.2
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#15722 taywee-args: add version 6.4.6
  recipes/taywee-args/all/conandata.yml
  recipes/taywee-args/config.yml
Labels: Bump version

#15567 Add MartinDelille watched recipes
  .github/workflows/alert-community.yml
Labels: GitHub config

#15608 gdcm: use official tarballs
  recipes/gdcm/all/conandata.yml
  recipes/gdcm/all/conanfile.py
Labels: checksum_mismatch

#15719 emsdk: add version 3.1.31
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#15720 flecs: add version 3.1.4
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version

#15751 glm: Add new release (pick latest version from master)
  recipes/glm/all/conandata.yml
  recipes/glm/config.yml
Labels: Bump version

#15797 Add Hopobcn to watched recipes
  .github/workflows/alert-community.yml
Labels: GitHub config

#15492 [sentry-native/0.5.4] Bump version
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#15811 config: limit alerts to on CCI
  .github/workflows/alert-community.yml
Labels: GitHub config

#15737 apr: fix url of source code tarball + modernize more
  recipes/apr/all/conandata.yml
  recipes/apr/all/conanfile.py
Labels: checksum_mismatch

#15595 Add watched recipes for jwillikers
  .github/workflows/alert-community.yml
Labels: GitHub config

#15820 [service] fix alert community workflow
  .github/workflows/alert-community.yml
Labels: GitHub config

#15604 pugixml: use official tarballs + modernize more
  recipes/pugixml/all/conandata.yml
  recipes/pugixml/all/conanfile.py
  recipes/pugixml/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15590 openal: deprecate in favor of openal-soft + download official tarballs + modernize more
  recipes/openal/all/conandata.yml
  recipes/openal/all/conanfile.py
  recipes/openal/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15594 libwebp: download official tarball + fix homepage
  recipes/libwebp/all/conandata.yml
  recipes/libwebp/all/conanfile.py
Labels: checksum_mismatch

#14911 yamllinter: raise if a version has patches but no sources
  linter/conandata_yaml_linter.py
Labels: GitHub config

#15859 nss 3.88.1
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#15843 CI: add Croydon to some alerts
  .github/workflows/alert-community.yml
Labels: GitHub config

#15670 czmq: use official tarball + fix dependencies handling
  recipes/czmq/all/conandata.yml
  recipes/czmq/all/conanfile.py
  recipes/czmq/all/patches/4.2.0-0001-fix-cmake.patch
  recipes/czmq/all/patches/4.2.1-0001-fix-cmake.patch
  recipes/czmq/all/test_package/CMakeLists.txt
  recipes/czmq/all/test_package/conanfile.py
  recipes/czmq/all/test_package/test_package.c
  recipes/czmq/all/test_v1_package/conanfile.py
Labels: checksum_mismatch

#15767 libspatialindex: use official tarball + modernize more for conan v2
  recipes/libspatialindex/all/conandata.yml
  recipes/libspatialindex/all/conanfile.py
  recipes/libspatialindex/all/test_package/conanfile.py
  recipes/libspatialindex/all/test_v1_package/CMakeLists.txt
  recipes/libspatialindex/all/test_v1_package/conanfile.py
Labels: checksum_mismatch

#15926 crc_cpp: Update to v1.2.0
  recipes/crc_cpp/all/conandata.yml
  recipes/crc_cpp/config.yml
Labels: Bump version

#15938 simdjson: add version 3.1.1
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#15727 Add Eric's pr Status page
  docs/community_resources.md
Labels: Docs

#15864 cmake: switch to official release tarballs again + openssl update
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/3.x.x/conanfile.py
  recipes/cmake/config.yml
Labels: checksum_mismatch

#15706 xmlsec: use official tarballs + conan v2 support
  recipes/xmlsec/all/conandata.yml
  recipes/xmlsec/all/conanfile.py
  recipes/xmlsec/all/test_package/CMakeLists.txt
  recipes/xmlsec/all/test_package/conanfile.py
  recipes/xmlsec/all/test_v1_package/CMakeLists.txt
  recipes/xmlsec/all/test_v1_package/conanfile.py
Labels: checksum_mismatch

#15895 chipmunk2d: use official tarball + modernize more
  recipes/chipmunk2d/all/conandata.yml
  recipes/chipmunk2d/all/conanfile.py
  recipes/chipmunk2d/all/test_package/conanfile.py
  recipes/chipmunk2d/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15951 jansson: use official tarballs + modernize more for conan v2
  recipes/jansson/all/conandata.yml
  recipes/jansson/all/conanfile.py
  recipes/jansson/all/test_package/conanfile.py
  recipes/jansson/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15937 exiv2: use official tarballs + modernize more for conan v2
  recipes/exiv2/all/conandata.yml
  recipes/exiv2/all/conanfile.py
  recipes/exiv2/all/test_package/conanfile.py
  recipes/exiv2/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#15993 glib 2.75.3
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#16011 [docs] Update changelog 14-February-2023 - 15:32 CET
  docs/changelog.md
Labels: Docs

#16036 remove MesonDeps from template
  docs/package_templates/meson_package/all/conanfile.py
Labels: Docs

#15934 enet: modernize more for conan v2
  recipes/enet/all/conandata.yml
  recipes/enet/all/conanfile.py
  recipes/enet/all/test_package/conanfile.py
  recipes/enet/all/test_v1_package/CMakeLists.txt
Labels: checksum_mismatch

#16055 [grpc-proto] bump required googleapis version
  recipes/grpc-proto/all/conanfile.py
Labels: Bump dependencies

#16063 kmod: use official tarballs + modernize more for conan v2
  recipes/kmod/all/conandata.yml
  recipes/kmod/all/conanfile.py
Labels: checksum_mismatch

#16068 benchmark: bump version of cmake tool requirement
  recipes/benchmark/all/conanfile.py
Labels: Bump dependencies

#16087 service: set python version for alert-community action
  .github/workflows/alert-community.yml
Labels: GitHub config

#16100 libmysqlclient: bump reqs
  recipes/libmysqlclient/all/conanfile.py
Labels: Bump dependencies

#16111 roaring: add version 0.9.8
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#16138 [openapi-generator] bump to 6.4.0 and remove old versions
  recipes/openapi-generator/all/conandata.yml
  recipes/openapi-generator/config.yml
Labels: Bump version

#16145 abseil: add version 20230125.1
  recipes/abseil/all/conandata.yml
  recipes/abseil/config.yml
Labels: Bump version

#15994 config: Adding new community reviewers to the list
  .c3i/reviewers.yml
Labels: C3I config

#16203 Add new changelog - Feb 2023
  docs/changelog.md
Labels: Docs

#16223 [docs] Update changelog 21-2-2023
  docs/changelog.md
Labels: Docs

#16258 [config] Use Conan 2.0.0 in v2 pipeline and add new conditional status check
  .c3i/conan_v2_ready_references.yml
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#16265 [config v2] Add intermediate epochs from config v1
  .c3i/config_v2.yml
Labels: C3I config

#16316 [access request] Add user tannerbitz to allow merging its PR
  .c3i/authorized_users.yml
Labels: C3I config

#16018 [faqs] Can use full_package_mode over my dependencies
  docs/faqs.md
Labels: Docs

#16260 zstd: don't require CMake 3.18 or later
  recipes/zstd/all/conandata.yml
  recipes/zstd/all/conanfile.py
  recipes/zstd/all/patches/1.5.4-decrease-min-cmake-version.patch
Labels: Unexpected Error
