Repository conan-io/conan-center-index, pull requests merged in 2023-10, with the labels that each got.

#20209 glaze: add version 1.5.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#20228 dlib/all: bump deps
  recipes/dlib/all/conanfile.py
Labels: Bump dependencies

#20227 freeimage/all: bump deps
  recipes/freeimage/all/conanfile.py
Labels: Bump dependencies

#20229 sail/all: bump deps
  recipes/sail/all/conanfile.py
Labels: Bump dependencies

#20230 leptonica/all: bump deps
  recipes/leptonica/all/conanfile.py
Labels: Bump dependencies

#19692 harfbuzz: add version 8.2.1
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#20238 [highs] bump version to 1.6.0
  recipes/highs/all/conandata.yml
  recipes/highs/config.yml
Labels: Bump version

#20240 cpp-httplib: add version 0.14.1
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#20000 serd: bump meson
  recipes/serd/all/conanfile.py
Labels: Bump dependencies

#20246 clickhouse-cpp: add version 2.5.1
  recipes/clickhouse-cpp/all/conandata.yml
  recipes/clickhouse-cpp/config.yml
Labels: Bump version

#20294 [config] Remove old profile configurations
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#19998 Move prince-chrismc back to a community reviewer
  .c3i/reviewers.yml
  .github/workflows/alert-community.yml
Labels: GitHub config, C3I config

#20243 qpdf/all: bump deps
  recipes/qpdf/all/conanfile.py
Labels: Bump dependencies

#20244 libgd/all: bump deps
  recipes/libgd/all/conanfile.py
Labels: Bump dependencies

#20251 pugixml: add version 1.14
  recipes/pugixml/all/conandata.yml
  recipes/pugixml/config.yml
Labels: Bump version

#20252 fontconfig/meson: bump deps
  recipes/fontconfig/meson/conanfile.py
Labels: Bump dependencies

#20303 picobench: add version 2.05
  recipes/picobench/all/conandata.yml
  recipes/picobench/config.yml
Labels: Bump version

#20307 libmorton: add version 0.2.12
  recipes/libmorton/all/conandata.yml
  recipes/libmorton/config.yml
Labels: Bump version

#20337 glaze: add version 1.5.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#20264 cyrus-sasl: bump libpq to 14.9
  recipes/cyrus-sasl/all/conanfile.py
Labels: Bump dependencies

#20364 harfbuzz: bump dependencies
  recipes/harfbuzz/all/conanfile.py
Labels: Bump dependencies

#20382 libgphoto2: bump deps
  recipes/libgphoto2/all/conanfile.py
Labels: Bump dependencies

#20386 netcdf/all: bump deps
  recipes/netcdf/all/conanfile.py
Labels: Bump dependencies

#20263 Poco: bump libpq to 14.9
  recipes/poco/all/conanfile.py
Labels: Bump dependencies

#20387 libxslt/all: bump deps
  recipes/libxslt/all/conanfile.py
Labels: Bump dependencies

#20384 cfitsio/all: bump deps
  recipes/cfitsio/all/conanfile.py
Labels: Bump dependencies

#20254 Bump libwebp in opencv to 1.3.2
  recipes/opencv/3.x/conanfile.py
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#20389 Add llvm to larger timeout list
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#20395 prometheus-cpp/all: bump libcurl
  recipes/prometheus-cpp/all/conanfile.py
Labels: Bump dependencies

#20409 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#20402 mariadb-connector-c/all: bump libcurl
  recipes/mariadb-connector-c/all/conanfile.py
Labels: Bump dependencies

#20404 libbigwig/all: bump libcurl
  recipes/libbigwig/all/conanfile.py
Labels: Bump dependencies

#20403 libmediainfo/all: bump libcurl
  recipes/libmediainfo/all/conanfile.py
Labels: Bump dependencies

#20407 czmq/all: bump libcurl
  recipes/czmq/all/conanfile.py
Labels: Bump dependencies

#20408 imutils-cpp/all: bump libcurl
  recipes/imutils-cpp/all/conanfile.py
Labels: Bump dependencies

#20406 sentry-crashpad/all: bump libcurl
  recipes/sentry-crashpad/all/conanfile.py
Labels: Bump dependencies

#20428 emio: add version 0.5.0
  recipes/emio/all/conandata.yml
  recipes/emio/config.yml
Labels: Bump version

#20424 tmx/all: bump deps
  recipes/tmx/all/conanfile.py
Labels: Bump dependencies

#20427 norm/all: bump libxml2
  recipes/norm/all/conanfile.py
Labels: Bump dependencies

#20432 civetweb/all: bump OpenSSL
  recipes/civetweb/all/conanfile.py
Labels: Bump dependencies

#20433 libmysqlclient/all: bump deps
  recipes/libmysqlclient/all/conanfile.py
Labels: Bump dependencies

#20429 libwebsockets/all: bump OpenSSL
  recipes/libwebsockets/all/conanfile.py
Labels: Bump dependencies

#20434 libpq/all: bump OpenSSL
  recipes/libpq/all/conanfile.py
Labels: Bump dependencies

#20457 [changelog] New C3I Release: 2023-Oct-06
  docs/changelog.md
Labels: Docs

#20422 hwloc/all: bump libxml2
  recipes/hwloc/all/conanfile.py
Labels: Bump dependencies

#20393 bump dependencies of pkgconf
  recipes/pkgconf/all/conanfile.py
Labels: Bump dependencies

#19949 opentdf-client release 1.5.3 & 1.5.4
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#20455 xkbcommon 1.6.0
  recipes/xkbcommon/all/conandata.yml
  recipes/xkbcommon/config.yml
Labels: Bump version

#20212 ffmpeg: add versions 4.4.4, 5.0.3 & 5.1.3
  recipes/ffmpeg/all/conandata.yml
  recipes/ffmpeg/config.yml
Labels: Bump version

#20397 sentry-native/all: bump deps
  recipes/sentry-native/all/conanfile.py
Labels: Bump dependencies

#20405 libsixel/all: bump deps
  recipes/libsixel/all/conanfile.py
Labels: Bump dependencies

#20425 libmetalink/all: bump deps
  recipes/libmetalink/all/conanfile.py
Labels: Bump dependencies

#20466 c-ares: add version 1.20.1
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#20468 commata: add version 0.2.6
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#20479 xorg-gccmakedep/all: bump deps
  recipes/xorg-gccmakedep/all/conanfile.py
Labels: Bump dependencies

#20480 xorg-makedepend/all: bump deps
  recipes/xorg-makedepend/all/conanfile.py
Labels: Bump dependencies

#20481 simde/all: bump deps
  recipes/simde/all/conanfile.py
Labels: Bump dependencies

#20498 [config] Update conan version to 2.0.12 and 1.61.0
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#20482 wayland-protocols/all: bump deps
  recipes/wayland-protocols/all/conanfile.py
  recipes/wayland-protocols/all/test_package/conanfile.py
Labels: Bump dependencies

#20490 xorg-proto/all: bump deps
  recipes/xorg-proto/all/conanfile.py
Labels: Bump dependencies

#20517 [config] Uses CCI Bot as ower of Conan 1.x scheduled export results
  .c3i/config_v1.yml
Labels: C3I config

#20518 [docs] Add changelog for new conan versions
  docs/changelog.md
Labels: Docs

#20491 sdbus-cpp/all: bump deps
  recipes/sdbus-cpp/all/conanfile.py
Labels: Bump dependencies

#20500 sqlite3: add version 3.43.2
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#20501 libnghttp2: add version 1.57.0 (fix CVE-2023-44487)
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#20503 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#20224 sdl_image/all: bump deps
  recipes/sdl_image/all/conanfile.py
Labels: Bump dependencies

#20522 bump glib dependencies
  recipes/glib/all/conanfile.py
Labels: Bump dependencies

#20527 onnxruntime: add version 1.16.1
  recipes/onnxruntime/all/conandata.yml
  recipes/onnxruntime/config.yml
Labels: Bump version

#20515 wayland-protocols: add version 1.32
  recipes/wayland-protocols/all/conandata.yml
  recipes/wayland-protocols/config.yml
Labels: Bump version

#20525 ada: add version 2.7.0
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#20539 watcher: add version 0.9.5
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#20313 nuklear: add version 4.10.6
  recipes/nuklear/all/conandata.yml
  recipes/nuklear/config.yml
Labels: Bump version

#20418 libxml2: add version 2.11.5
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#20301 utfcpp: add version 3.2.5
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#20310 dbg-macro: add version 0.5.1
  recipes/dbg-macro/all/conandata.yml
  recipes/dbg-macro/config.yml
Labels: Bump version

#20298 cpp-peglib: add version 1.8.5
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#20549 android-ndk: add r26b
  recipes/android-ndk/all/conandata.yml
  recipes/android-ndk/config.yml
Labels: Bump version

#20299 lerc: add version 4.0.1
  recipes/lerc/all/conandata.yml
  recipes/lerc/config.yml
Labels: Bump version

#20309 kangaru: add version 4.3.1
  recipes/kangaru/all/conandata.yml
  recipes/kangaru/config.yml
Labels: Bump version

#20302 libsvtav1: add version 1.7.0
  recipes/libsvtav1/all/conandata.yml
  recipes/libsvtav1/config.yml
Labels: Bump version

#20308 reactiveplusplus: add version 0.2.3
  recipes/reactiveplusplus/all/conandata.yml
  recipes/reactiveplusplus/config.yml
Labels: Bump version

#20042 gcem: add version 1.17.0
  recipes/gcem/all/conandata.yml
  recipes/gcem/config.yml
Labels: Bump version

#20030 plog: add version 1.1.10
  recipes/plog/all/conandata.yml
  recipes/plog/config.yml
Labels: Bump version

#20020 vc: add version 1.4.3
  recipes/vc/all/conandata.yml
  recipes/vc/config.yml
Labels: Bump version

#20023 ezc3d: add version 1.5.4
  recipes/ezc3d/all/conandata.yml
  recipes/ezc3d/config.yml
Labels: Bump version

#20038 libharu: add version 2.4.4
  recipes/libharu/all/conandata.yml
  recipes/libharu/config.yml
Labels: Bump version

#20559 luau: add version 0.598
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#20523 libmount: Add version 2.39.2
  recipes/libmount/all/conandata.yml
  recipes/libmount/config.yml
Labels: Bump version

#20567 emio: add version 0.6.0
  recipes/emio/all/conandata.yml
  recipes/emio/config.yml
Labels: Bump version

#20047 cgif: add version 0.3.2
  recipes/cgif/all/conandata.yml
  recipes/cgif/config.yml
Labels: Bump version

#20563 opencv/4.x: bump deps
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#20570 ctre: add version 3.8.1
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#20014 pupnp: add version 1.14.18
  recipes/pupnp/all/conandata.yml
  recipes/pupnp/config.yml
Labels: Bump version

#20576 mbedtls: add version 3.5.0
  recipes/mbedtls/all/conandata.yml
  recipes/mbedtls/config.yml
Labels: Bump version

#20577 oniguruma: add version 6.9.9
  recipes/oniguruma/all/conandata.yml
  recipes/oniguruma/config.yml
Labels: Bump version

#20583 sqlpp11: add version 0.64
  recipes/sqlpp11/all/conandata.yml
  recipes/sqlpp11/config.yml
Labels: Bump version

#20585 tomlplusplus: add version 3.4.0
  recipes/tomlplusplus/all/conandata.yml
  recipes/tomlplusplus/config.yml
Labels: Bump version

#20597 kmod/all: bump deps
  recipes/kmod/all/conanfile.py
Labels: Bump dependencies

#18872 amqp-cpp: add version 4.3.26
  recipes/amqp-cpp/all/conandata.yml
  recipes/amqp-cpp/config.yml
Labels: Bump version

#20325 s2n: add version 1.3.52
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#20599 nettle/all: bump deps
  recipes/nettle/all/conanfile.py
Labels: Bump dependencies

#20596 gnutls/all: bump deps
  recipes/gnutls/all/conanfile.py
Labels: Bump dependencies

#20598 mongo-c-driver/all: bump deps
  recipes/mongo-c-driver/all/conanfile.py
Labels: Bump dependencies

#20641 SObjectizer: add version 5.8.1
  recipes/sobjectizer/all/conandata.yml
  recipes/sobjectizer/config.yml
Labels: Bump version

#20636 harfbuzz: add version 8.2.2
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#20603 xmlsec/all: bump deps
  recipes/xmlsec/all/conanfile.py
  recipes/xmlsec/all/test_package/conanfile.py
Labels: Bump dependencies

#20604 pdf-writer: add version 4.6.1
  recipes/pdf-writer/all/conandata.yml
  recipes/pdf-writer/config.yml
Labels: Bump version

#20609 rapidfuzz: add version 2.1.1
  recipes/rapidfuzz/all/conandata.yml
  recipes/rapidfuzz/config.yml
Labels: Bump version

#20645 Update meson test package
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/meson_package/all/test_package/conanfile.py
Labels: Docs

#20613 vulkan-loader/all: bump deps
  recipes/vulkan-loader/all/conanfile.py
Labels: Bump dependencies

#20614 libuvc/all: bump deps
  recipes/libuvc/all/conanfile.py
Labels: Bump dependencies

#20617 libgeotiff/all: bump deps
  recipes/libgeotiff/all/conanfile.py
Labels: Bump dependencies

#20624 tracy: add version 0.10
  recipes/tracy/all/conandata.yml
  recipes/tracy/config.yml
Labels: Bump version

#20626 glaze: add version 1.5.3
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#20646 [config] Enable merge labels for Conan 1.x
  .c3i/config_v1.yml
Labels: C3I config

#20688 Update meson template package
  docs/package_templates/meson_package/all/conanfile.py
Labels: Docs

#20644 coin-osi/all: bump deps
  recipes/coin-osi/all/conanfile.py
  recipes/coin-osi/all/test_package/conanfile.py
Labels: Bump dependencies

#20647 etl: add version 20.38.4
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#20682 numcpp: add version 2.12.1, support apple-clang again
  recipes/numcpp/all/conandata.yml
  recipes/numcpp/config.yml
Labels: Bump version

#20691 hwloc: added 2.9.3
  recipes/hwloc/all/conandata.yml
  recipes/hwloc/config.yml
Labels: Bump version

#20697 zlib-ng: add version 2.1.4
  recipes/zlib-ng/all/conandata.yml
  recipes/zlib-ng/config.yml
Labels: Bump version

#20684 proj/all: bump deps
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#20702 onetbb: bump hwloc dependency
  recipes/onetbb/all/conanfile.py
Labels: Bump dependencies

#20713 meson: Add version 1.2.3
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#20717 librttopo/all: bump deps
  recipes/librttopo/all/conanfile.py
Labels: Bump dependencies

#20724 libtiff/all: bump deps
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#20726 opencv/2.x: bump deps
  recipes/opencv/2.x/conanfile.py
Labels: Bump dependencies

#20733 coin-clp/all: bump deps
  recipes/coin-clp/all/conanfile.py
Labels: Bump dependencies

#20742 utfcpp: add version 4.0.0
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#20745 coin-cgl/all: bump deps
  recipes/coin-cgl/all/conanfile.py
  recipes/coin-cgl/all/test_package/conanfile.py
Labels: Bump dependencies

#20765 [config] Add configuration for job relauncher
  .c3i/config_v1.yml
Labels: C3I config

#20767 linux-headers-generic: add version 6.5.9, 5.19.5
  recipes/linux-headers-generic/all/conandata.yml
  recipes/linux-headers-generic/config.yml
Labels: Bump version

#20766 libmikmod: bump libalsa
  recipes/libmikmod/all/conanfile.py
Labels: Bump dependencies

#20761 fast-dds: add version 2.11.2
  recipes/fast-dds/all/conandata.yml
  recipes/fast-dds/config.yml
Labels: Bump version

#20044 coin-cgl: add version 0.60.7
  recipes/coin-cgl/all/conandata.yml
  recipes/coin-cgl/config.yml
Labels: Bump version

#20778 [changelog] New C3I Jenkins version: release 2023.10.26
  docs/changelog.md
Labels: Docs

#20763 [docs] Add license change explanation
  docs/adding_packages/conanfile_attributes.md
Labels: Docs

#20032 libglvnd: add version 1.7.0
  recipes/libglvnd/all/conandata.yml
  recipes/libglvnd/config.yml
Labels: Bump version

#20797 libxft/all: bump deps
  recipes/libxft/all/conanfile.py
Labels: Bump dependencies

#20801 c-ares: add version 1.21.0
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#20809 simdjson: add version 3.5.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#20808 highfive: update xtensor/0.24.6
  recipes/highfive/all/conanfile.py
Labels: Bump dependencies

#20814 ada: add version 2.7.2
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#20815 etl: add version 20.38.6
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#20818 utfcpp: add version 4.0.1
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#20820 jsoncons: add version 0.171.1
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#20821 miniaudio: add version 0.11.18
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#20822 s2n: add version 1.3.55
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#20829 asio: add version 1.28.2
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version
