Repository conan-io/conan-center-index, pull requests merged in 2023-01, with the labels that each got.

#15030 usockets: update dependencies
  recipes/usockets/all/conanfile.py
Labels: Bump dependencies

#15031 sdl: add v2.26.1
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#15036 libcap/2.66: bump version
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#15045 Fix libjpeg/9e sha256 signature failed
  recipes/libjpeg/all/conandata.yml
Labels: Failed, checksum_mismatch

#14988 sqlite3: add version 3.40.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#15074 simdutf: add version 2.1.0
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#15075 libcbor: add version 0.10.1
  recipes/libcbor/all/conandata.yml
  recipes/libcbor/config.yml
Labels: Bump version

#14851 protobuf: Update to new CMake integrations
  recipes/protobuf/all/CMakeLists.txt
  recipes/protobuf/all/conandata.yml
  recipes/protobuf/all/conanfile.py
  recipes/protobuf/all/patches/upstream-pr-9437-msvc-runtime.patch
  recipes/protobuf/all/test_package/CMakeLists.txt
  recipes/protobuf/all/test_package/conanfile.py
  recipes/protobuf/all/test_v1_package/CMakeLists.txt
  recipes/protobuf/all/test_v1_package/conanfile.py
  recipes/protobuf/config.yml
Labels: Failed

#15086 openh264: fix tools legacy
  recipes/openh264/all/conanfile.py
Labels: Failed

#14953 Revert "[config] Use larger resources to build cppfront packages"
  .c3i/config_v1.yml
Labels: C3I config

#14874 faac: conan v2 support
  recipes/faac/all/conandata.yml
  recipes/faac/all/conanfile.py
  recipes/faac/all/test_package/CMakeLists.txt
  recipes/faac/all/test_package/conanfile.py
  recipes/faac/all/test_v1_package/CMakeLists.txt
  recipes/faac/all/test_v1_package/conanfile.py
Labels: Failed

#14903 arrow: remove patch for CMake
  recipes/arrow/all/conandata.yml
  recipes/arrow/all/conanfile.py
  recipes/arrow/all/patches/10.0.0-0002-fix-cmake.patch
Labels: Unexpected Error

#14974 libxshmfence: generate gcc11 binaries
  recipes/libxshmfence/all/conanfile.py
Labels: Failed

#15056 qt5: Apple OSs don't require CROSS_COMPILE option
  recipes/qt/5.x.x/conandata.yml
  recipes/qt/5.x.x/conanfile.py
  recipes/qt/5.x.x/patches/337f28c9ab-5.15.5.patch
  recipes/qt/5.x.x/patches/337f28c9ab.patch
Labels: Failed

#15088 Make openexr v2 compatible
  recipes/openexr/2.x/conanfile.py
  recipes/openexr/3.x/conanfile.py
Labels: Failed

#15122 m4: use positional arguments when calling self.run()
  recipes/m4/all/test_package/conanfile.py
Labels: Failed

#14982 rapidyaml: add version 0.5.0
  recipes/rapidyaml/all/conandata.yml
  recipes/rapidyaml/all/conanfile.py
  recipes/rapidyaml/all/patches/0.5.0-001-remove-internal-c4core.patch
  recipes/rapidyaml/all/test_v1_package/CMakeLists.txt
  recipes/rapidyaml/config.yml
Labels: Failed

#14103 gmp: conan v2 support
  recipes/gmp/all/conandata.yml
  recipes/gmp/all/conanfile.py
  recipes/gmp/all/test_package/CMakeLists.txt
  recipes/gmp/all/test_package/conanfile.py
  recipes/gmp/all/test_v1_package/CMakeLists.txt
  recipes/gmp/all/test_v1_package/conanfile.py
Labels: Failed

#15123 faac: add Visual Studio support + drop 1.28
  recipes/faac/all/conandata.yml
  recipes/faac/all/conanfile.py
  recipes/faac/all/patches/1.30-0001-fix-out-of-root-build.patch
  recipes/faac/all/patches/1.30-0002-dont-hardcode-x86.patch
  recipes/faac/all/patches/1.30-0003-relax-windows-sdk.patch
  recipes/faac/config.yml
Labels: Failed

#15093 [libjpeg] Update sha256 for 9e
  recipes/libjpeg/all/conandata.yml
Labels: Unexpected Error, Failed, checksum_mismatch

#14902 libcurl: add CMakeDeps generator
  recipes/libcurl/all/conanfile.py
Labels: Failed

#15068 [Mold] Use the official libexecdir now that the CCI hooks allow it
  recipes/mold/all/conandata.yml
  recipes/mold/all/conanfile.py
  recipes/mold/all/patches/0001-fix-install.patch
  recipes/mold/config.yml
Labels: Failed

#14978 moltenvk: add 1.2.1 + define new env var `VK_DRIVER_FILES` listened by Vulkan-Loader
  recipes/moltenvk/all/conandata.yml
  recipes/moltenvk/all/conanfile.py
  recipes/moltenvk/all/dependencies/dependencies-1.2.1.yml
  recipes/moltenvk/config.yml
Labels: Failed

#15105 [boost] Fix issues building with Conan 2 and with python
  recipes/boost/all/conanfile.py
  recipes/boost/all/test_package/CMakeLists.txt
  recipes/boost/all/test_package/conanfile.py
  recipes/boost/all/test_v1_package/CMakeLists.txt
  recipes/boost/all/test_v1_package/conanfile.py
Labels: Failed

#15005 linter: limit how many recipes are used to test changes
  .github/workflows/linter-conan-v2.yml
Labels: GitHub config

#14968 xz_utils: add v5.2.10 and v5.4.0
  recipes/xz_utils/all/conandata.yml
  recipes/xz_utils/config.yml
Labels: Failed, Bump version

#15050 libmicrohttpd: several fixes & more conan v2 stuff
  recipes/libmicrohttpd/all/conandata.yml
  recipes/libmicrohttpd/all/conanfile.py
  recipes/libmicrohttpd/all/patches/0.9.75-0001-allow-release-with-debug-runtime.patch
  recipes/libmicrohttpd/all/patches/0.9.75-0001-msbuild-RuntimeLibrary.patch
  recipes/libmicrohttpd/all/test_package/conanfile.py
  recipes/libmicrohttpd/all/test_v1_package/CMakeLists.txt
Labels: Failed

#15103 [qxlsx/1.4.5] Bump version
  recipes/qxlsx/all/conandata.yml
  recipes/qxlsx/all/conanfile.py
  recipes/qxlsx/all/patches/1.4.3/0001-allow-shared.patch
  recipes/qxlsx/all/patches/1.4.3/0002-add-install-target.patch
  recipes/qxlsx/config.yml
Labels: Failed

#15129 imgui: add version 1.89.2
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#15131 nss 3.87
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#15136 md4qt: bump version to 2.0.4.
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#15140 charls: add version 2.4.1
  recipes/charls/all/conandata.yml
  recipes/charls/config.yml
Labels: Bump version

#15118 continuable: Add version 4.2.1
  recipes/continuable/all/conandata.yml
  recipes/continuable/config.yml
Labels: Bump version

#14877 packio: add version 2.3.0
  recipes/packio/all/conandata.yml
  recipes/packio/config.yml
Labels: Bump version

#14897 sentry-breakpad: add version 0.5.3
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#14921 add meson/1.0.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#14945 brynet: add version 1.12.2
  recipes/brynet/all/conandata.yml
  recipes/brynet/config.yml
Labels: Bump version

#15038 libsystemd/252.4: bump version
  recipes/libsystemd/all/conandata.yml
  recipes/libsystemd/config.yml
Labels: Bump version

#15073 usockets: add version 0.8.5
  recipes/usockets/all/conandata.yml
  recipes/usockets/config.yml
Labels: Bump version

#14503 [Doc] Adapt some build rules to conan v2
  docs/adding_packages/build_and_package.md
Labels: Docs

#15112 foonathan-lexy: add version 2022.12.1
  recipes/foonathan-lexy/all/conandata.yml
  recipes/foonathan-lexy/config.yml
Labels: Bump version

#15141 roaring: add version 0.8.1
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#14971 libarchive: bump deps
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#15037 libmysqlclient: add version 8.0.31
  recipes/libmysqlclient/all/conandata.yml
  recipes/libmysqlclient/config.yml
Labels: Bump version

#15143 cli11: add v2.3.2
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#15167 libcurl: add version 7.87.0
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Failed, Bump version

#15180 minizip: add transitive_headers trait to dependencies (v2)
  recipes/minizip/all/conanfile.py
Labels: Failed

#15181 vorbis: add dependency trait and fix removal of fPIC options when on Windows
  recipes/vorbis/all/conanfile.py
Labels: Failed

#15079 cmake/3.25.1
  recipes/cmake/3.x.x/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#15155 Bump emsdk/3.1.29
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#15173 wayland/*: Bump Meson version to 1.0.0
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#15174 wayland-protocols: Bump Meson version to 1.0.0
  recipes/wayland-protocols/all/conanfile.py
  recipes/wayland-protocols/all/test_package/conanfile.py
  recipes/wayland-protocols/all/test_v1_package/conanfile.py
Labels: Bump dependencies

#15175 dbus: Bump Meson, libsystemd, and glib versions
  recipes/dbus/1.x.x/conanfile.py
Labels: Bump dependencies

#15176 xkbcommon: Bump Meson to version 1.0.0
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#15154 boost: handle spaces in path to C++ compiler
  recipes/boost/all/conanfile.py
Labels: Failed

#15178 libffi: Use rm_safe to delete options in the configure method
  recipes/libffi/all/conanfile.py
Labels: Unexpected Error, Failed

#15203 Maintenance: temporarily disable message reports from Conan v2 pipeline
  .c3i/config_v1.yml
Labels: C3I config

#15192 capnproto: add version 0.10.3 (for CVE-2022-46149)
  recipes/capnproto/all/conandata.yml
  recipes/capnproto/config.yml
Labels: Bump version

#15205 [docs] Update changelog 10-January-2023
  docs/changelog.md
Labels: Docs

#15152 unordered_dense: add version 3.0.2
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#15216 Update qcustomplot to version 2.1.1
  recipes/qcustomplot/all/conandata.yml
  recipes/qcustomplot/config.yml
Labels: Bump version

#15204 [config] Update conan version to 1.55.0
  .c3i/config_v1.yml
Labels: C3I config

#15222 [config] Update conan v1 to 1.56.0 and conan v2 to beta 7
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#13234 libsvt1: conan v2 package
  recipes/libsvtav1/all/conandata.yml
  recipes/libsvtav1/all/conanfile.py
  recipes/libsvtav1/all/test_package/CMakeLists.txt
  recipes/libsvtav1/all/test_package/conanfile.py
  recipes/libsvtav1/all/test_package/test_package.cpp
  recipes/libsvtav1/all/test_v1_package/CMakeLists.txt
  recipes/libsvtav1/all/test_v1_package/conanfile.py
  recipes/libsvtav1/config.yml
Labels: Failed

#15246 [sentry-native/0.5.3] Bump version
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#15261 coin-utils : added 2.11.6
  recipes/coin-utils/all/conandata.yml
  recipes/coin-utils/config.yml
Labels: Bump version

#15264 xtensor: bump deps
  recipes/xtensor/all/conanfile.py
Labels: Bump dependencies

#15269 simdutf: add version 3.0.0
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#15273 watcher: add version 0.5.5
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#15281 itlib: add versoin 1.8.1
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#15288 wayland-protocols: add version 1.31
  recipes/wayland-protocols/all/conandata.yml
  recipes/wayland-protocols/config.yml
Labels: Bump version

#15291 cppcheck: add version 2.9.3
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#15289 qarchive: add version 2.2.4
  recipes/qarchive/all/conandata.yml
  recipes/qarchive/config.yml
Labels: Bump version

#15290 emsdk: add version 3.1.30
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#15299 [docs] Update changelog 12-January-2023
  docs/changelog.md
Labels: Docs

#15310 foonathan-memory: add version 0.7.3
  recipes/foonathan-memory/all/conandata.yml
  recipes/foonathan-memory/config.yml
Labels: Bump version

#15313 cimg: add version 3.2.0
  recipes/cimg/all/conandata.yml
  recipes/cimg/config.yml
Labels: Bump version

#15329 taskflow: add version 3.5.0
  recipes/taskflow/all/conandata.yml
  recipes/taskflow/config.yml
Labels: Bump version

#15334 highfive: bump deps
  recipes/highfive/all/conanfile.py
Labels: Bump dependencies

#15320 Update changelog 16-January-2023
  docs/changelog.md
Labels: Docs

#15380 [docs] Update changelog 16-January-2023
  docs/changelog.md
Labels: Docs

#15004 docs: split out files and folders and the last few attributes
  docs/adding_packages/README.md
  docs/adding_packages/conanfile_attributes.md
  docs/adding_packages/folders_and_files.md
  docs/error_knowledge_base.md
  docs/faqs.md
Labels: Docs

#15382 [docs] Add hooks description for KB-H076 and KB-H077
  docs/error_knowledge_base.md
Labels: Docs

#15417 catch2: add version 3.3.0
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#15251 daw_utf_range: update daw_header_libraries
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#15333 config: Community Alerts System
  .github/CODEOWNERS
  .github/actions/alert-community/action.yml
  .github/workflows/alert-community.yml
Labels: GitHub config

#15494 Revise modular boost policy and clarify options which do no impact `package_id`
  docs/adding_packages/conanfile_attributes.md
  docs/faqs.md
Labels: Docs
