Repository conan-io/conan-center-index, pull requests merged in 2023-04, with the labels that each got.

#16840 [alert] Add community alert for armadillo, gcc and geotrans for samuel-emrys
  .github/workflows/alert-community.yml
Labels: GitHub config

#16759 docs: clarify everything should use CMake 3.15 to match Conan 2.0
  docs/error_knowledge_base.md
  docs/package_templates/autotools_package/all/test_package/CMakeLists.txt
  docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/test_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/header_only/all/test_package/CMakeLists.txt
  docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
  docs/package_templates/msbuild_package/all/test_package/CMakeLists.txt
  docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt
Labels: Docs

#16852 Restinio: bump version 0.6.18
  recipes/restinio/all/conandata.yml
  recipes/restinio/config.yml
Labels: Bump version

#15988 [linter] Do not accept version attribute on regular recipes
  docs/linters.md
  linter/check_version_attribute.py
  linter/conanv2_transition.py
  linter/pylintrc_recipe
Labels: Docs, GitHub config

#16814 Bump spirv-headers/1.3.243.0
  recipes/spirv-headers/all/conandata.yml
  recipes/spirv-headers/config.yml
Labels: Bump version

#16383 simdjson: add version 3.1.5
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#16853 [openapi-generator/6.5.0] Add version and remove 6.2.1
  recipes/openapi-generator/all/conandata.yml
  recipes/openapi-generator/config.yml
Labels: Bump version

#16864 [docs] Add changelog 03-April-2023
  docs/changelog.md
Labels: Docs

#16869 [c3i-config] Update conan v2 ready references
  .c3i/conan_v2_ready_references.yml
Labels: C3I config

#16730 bzip3: add version 1.2.3, use official tarballs
  recipes/bzip3/all/conandata.yml
  recipes/bzip3/all/conanfile.py
  recipes/bzip3/config.yml
Labels: checksum_mismatch

#16753 [sentry-native] Update to 0.6.1
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#16896 nanorange: add version cci.20200505
  recipes/nanorange/all/conandata.yml
  recipes/nanorange/config.yml
Labels: Bump version

#16903 fast_float: add v4.0.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#16904 Add gstreamer to large pod
  .c3i/config_v1.yml
Labels: C3I config

#16907 zstd: add version 1.5.5
  recipes/zstd/all/conandata.yml
  recipes/zstd/config.yml
Labels: Bump version

#16909 meson: add version 1.0.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#16912 netcdf: bump deps
  recipes/netcdf/all/conanfile.py
Labels: Bump dependencies

#16914 cgns: bump deps
  recipes/cgns/all/conanfile.py
Labels: Bump dependencies

#16501 patchelf: conan v2
  recipes/patchelf/all/conanfile.py
  recipes/patchelf/all/test_package/conanfile.py
  recipes/patchelf/all/test_v1_package/conanfile.py
Labels: Failed

#16919 libmysqlclient: bump deps
  recipes/libmysqlclient/all/conanfile.py
Labels: Bump dependencies

#16925 highfive: add v2.7.1
  recipes/highfive/all/conandata.yml
  recipes/highfive/config.yml
Labels: Bump version

#16916 fontconfig: bump deps
  recipes/fontconfig/meson/conanfile.py
Labels: Bump dependencies

#16924 xz_utils: add v5.4.2
  recipes/xz_utils/all/conandata.yml
  recipes/xz_utils/config.yml
Labels: Bump version

#16917 Fontconfig 2.14
  recipes/fontconfig/config.yml
  recipes/fontconfig/meson/conandata.yml
Labels: Bump version

#16911 proj: bump dependencies
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#16933 bzip3: add version 1.3.0
  recipes/bzip3/all/conandata.yml
  recipes/bzip3/config.yml
Labels: Bump version

#16937 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#16940 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#16948 safeint: add version 3.0.28
  recipes/safeint/all/conandata.yml
  recipes/safeint/config.yml
Labels: Bump version

#16949 simdjson: add version 3.1.7
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#16951 unordered_dense: add version 4.0.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#16947 re2: add version 20230301
  recipes/re2/all/conandata.yml
  recipes/re2/config.yml
Labels: Bump version

#16968 [config] Drop some Conan v1 pipeline configurations
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#16970 Revert "Add gstreamer to large pod"
  .c3i/config_v1.yml
Labels: C3I config

#16926 Ignore more test_package build dir patterns
  .gitignore
Labels: GitHub config

#16982 Bump draco/1.5.6
  recipes/draco/all/conandata.yml
  recipes/draco/config.yml
Labels: Bump version

#16005 harfbuzz: add version 7.0.1, use official tarballs
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/all/conanfile.py
  recipes/harfbuzz/all/test_v1_package/CMakeLists.txt
  recipes/harfbuzz/config.yml
Labels: checksum_mismatch

#16915 qt: bump deps
  recipes/qt/5.x.x/conanfile.py
  recipes/qt/5.x.x/test_package/conanfile.py
  recipes/qt/6.x.x/conanfile.py
  recipes/qt/6.x.x/test_package/conanfile.py
Labels: Bump dependencies

#16985 dav1d: add 1.1.0 + use official tarballs + add package_type
  recipes/dav1d/all/conandata.yml
  recipes/dav1d/all/conanfile.py
  recipes/dav1d/config.yml
Labels: checksum_mismatch

#16665 libcurl: update to 8.0.1
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#16988 docs: Access build folder using the improved syntax from 1.53
  docs/package_templates/autotools_package/all/test_package/conanfile.py
  docs/package_templates/cmake_package/all/test_package/conanfile.py
  docs/package_templates/header_only/all/test_package/conanfile.py
  docs/package_templates/meson_package/all/test_package/conanfile.py
  docs/package_templates/msbuild_package/all/test_package/conanfile.py
Labels: Docs

#16993 libxml2: add 2.10.4
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#16994 [changelog] New CCI release
  docs/changelog.md
Labels: Docs

#16995 roaring: add version 1.1.0
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#17023 glaze: add version 1.2.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#17039 cairo: bump dependencies
  recipes/cairo/all/conanfile.py
  recipes/cairo/meson/conanfile.py
Labels: Bump dependencies

#17038 doctest: Add version 2.4.11.
  recipes/doctest/2.x.x/conandata.yml
  recipes/doctest/config.yml
Labels: Bump version

#17020 config: remove alert with empty reviewers
  .github/workflows/alert-community.yml
Labels: GitHub config

#16979 Fix example in the docs
  docs/package_templates/meson_package/all/conandata.yml
Labels: Docs

#17071 cyrus-sasl: bump dependencies
  recipes/cyrus-sasl/all/conanfile.py
Labels: Bump dependencies

#17066 pulseaudio: bump dependencies
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#17070 gdcm: bump openssl
  recipes/gdcm/all/conanfile.py
Labels: Bump dependencies

#17069 s2n: bump openssl
  recipes/s2n/all/conanfile.py
Labels: Bump dependencies

#17068 libcurl: bump openssl & zstd
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#17083 mariadb-connector-c: bump openssl & libcurl
  recipes/mariadb-connector-c/all/conanfile.py
Labels: Bump dependencies

#17081 nuraft: bump openssl & asio
  recipes/nuraft/all/conanfile.py
Labels: Bump dependencies

#17082 mongo-c-driver: bump openssl & zstd
  recipes/mongo-c-driver/all/conanfile.py
Labels: Bump dependencies

#17089 minizip-ng: bump dependencies
  recipes/minizip-ng/all/conanfile.py
Labels: Bump dependencies

#17099 caf: bump openssl
  recipes/caf/all/conanfile.py
Labels: Bump dependencies

#17075 [config] Add regression message for Conan v2 builds
  .c3i/config_v2.yml
Labels: C3I config

#15115 [linter] reduce pylint to just one command
  linter/check_no_test_package_name.py
  linter/check_package_name.py
  linter/conanv2_test_transition.py
  linter/pylintrc_testpackage
Labels: GitHub config

#17103 linter: pylintrc_testpackage should not run layout checks
  linter/pylintrc_testpackage
Labels: GitHub config

#17130 fakeit: add version 2.4.0
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#17137 [config] Fix build log paths
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#17163 date: bump libcurl version
  recipes/date/all/conanfile.py
Labels: Bump dependencies

#17172 itlib: add version 1.9.1
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#17174 ada: add version 2.2.0
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#17192 Docs: update policy on version ranges
  docs/adding_packages/dependencies.md
  docs/faqs.md
Labels: Docs

#17199 docs: removed v2_roadmap (updated steps in v2_migration)
  docs/consuming_recipes.md
  docs/v2_linter.md
  docs/v2_migration.md
Labels: Docs

#17208 pulseaudio: use version range for openssl
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#17211 cyrus-sasl: use version range for openssl
  recipes/cyrus-sasl/all/conanfile.py
Labels: Bump dependencies

#17213 kmod: use version range for openssl
  recipes/kmod/all/conanfile.py
Labels: Bump dependencies

#17216 mariadb-connector-c: use version range for openssl
  recipes/mariadb-connector-c/all/conanfile.py
Labels: Bump dependencies

#17215 nuraft: use version range for openssl
  recipes/nuraft/all/conanfile.py
Labels: Bump dependencies

#17218 capnproto: use version range for openssl
  recipes/capnproto/all/conanfile.py
Labels: Bump dependencies

#17212 gdcm: use version range for openssl
  recipes/gdcm/all/conanfile.py
Labels: Bump dependencies

#17214 mongo-c-driver: use version range for openssl
  recipes/mongo-c-driver/all/conanfile.py
Labels: Bump dependencies

#17238 glaze: add version 1.2.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#17240 rapidcsv: Add version 8.75.
  recipes/rapidcsv/all/conandata.yml
  recipes/rapidcsv/config.yml
Labels: Bump version

#17241 roaring: Add version 1.1.2.
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#17239 nanobench: Add version 4.3.11.
  recipes/nanobench/all/conandata.yml
  recipes/nanobench/config.yml
Labels: Bump version

#17223 libarchive: bump deps
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#17209 libcurl: use version range for openssl
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#17248 caf: use version range for openssl
  recipes/caf/all/conanfile.py
Labels: Bump dependencies

#17253 update sqlite3 to version 3.41.2
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#17252 g3log: add version 2.3
  recipes/g3log/all/conandata.yml
  recipes/g3log/config.yml
Labels: Bump version

#17255 oatpp-openssl: use version range for openssl
  recipes/oatpp-openssl/all/conanfile.py
Labels: Bump dependencies

#17258 hiredis: use version range for openssl
  recipes/hiredis/all/conanfile.py
Labels: Bump dependencies

#17249 minizip-ng: use version range for openssl
  recipes/minizip-ng/all/conanfile.py
Labels: Bump dependencies

#17190 grpc: use newer openssl
  recipes/grpc/all/conanfile.py
Labels: Bump dependencies

#17256 trantor: use version range for openssl
  recipes/trantor/all/conanfile.py
Labels: Bump dependencies

#17279 cppserver: use version range for openssl & bump asio
  recipes/cppserver/all/conanfile.py
Labels: Bump dependencies

#17287 duckdb: use version range for openssl
  recipes/duckdb/all/conanfile.py
Labels: Bump dependencies

#17291 [parallel-hashmap] Update version to 1.3.11
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#17259 cpp-httplib: use version range for openssl
  recipes/cpp-httplib/all/conanfile.py
Labels: Bump dependencies

#17290 libtiff: bump dependencies
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#17266 restinio: bump dependencies
  recipes/restinio/all/conanfile.py
Labels: Bump dependencies

#17265 expected-lite: add version 0.6.3
  recipes/expected-lite/all/conandata.yml
  recipes/expected-lite/config.yml
Labels: Bump version

#17301 glib: bump deps
  recipes/glib/all/conanfile.py
Labels: Bump dependencies

#17310 libcap/2.68: Bump version
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#17319 cpp-httplib: add version 0.12.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version
