Repository conan-io/conan-center-index, pull requests merged in 2023-06, with the labels that each got.

#17780 conan V2 windows machine label updated
  .c3i/config_v2.yml
Labels: C3I config

#17783 conan V1 windows machine label updated
  .c3i/config_v1.yml
Labels: C3I config

#17789 magic_enum: Bump to 0.9.1
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#17794 miniaudio: add version 0.11.17
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#17804 daw_header_libraries: add version 2.93.1
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#17803 Update SObjectizer v.5.7.4
  recipes/sobjectizer/all/conandata.yml
  recipes/sobjectizer/config.yml
Labels: Bump version

#17807 svector: add version 1.0.3
  recipes/svector/all/conandata.yml
  recipes/svector/config.yml
Labels: Bump version

#17808 octo-logger-cpp: add version 1.4.0
  recipes/octo-logger-cpp/all/conandata.yml
  recipes/octo-logger-cpp/config.yml
Labels: Bump version

#17815 flatbuffers: add version 23.5.26
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#17816 uni-algo: add version 0.8.1
  recipes/uni-algo/all/conandata.yml
  recipes/uni-algo/config.yml
Labels: Bump version

#17819 add mbits-diags/0.9.5
  recipes/mbits-diags/all/conandata.yml
  recipes/mbits-diags/config.yml
Labels: Bump version

#17821 daw_utf_range: update daw_header_libraries
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#17833 quill: add version 2.9.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#17839 libxcrypt: add version 4.4.34
  recipes/libxcrypt/all/conandata.yml
  recipes/libxcrypt/config.yml
Labels: Bump version

#17840 nsync: add version 1.26.0
  recipes/nsync/all/conandata.yml
  recipes/nsync/config.yml
Labels: Bump version

#17842 sbepp: add 1.1.0 version
  recipes/sbepp/all/conandata.yml
  recipes/sbepp/config.yml
Labels: Bump version

#17845 lief: add version 0.13.1
  recipes/lief/all/conandata.yml
  recipes/lief/config.yml
Labels: Bump version

#17853 mongo-c-driver: add version 1.23.5
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#17861 opentelemetry-proto: add version 0.20.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#17862 imath: add version 3.1.9
  recipes/imath/all/conandata.yml
  recipes/imath/config.yml
Labels: Bump version

#17870 add mbits-diags/0.9.6
  recipes/mbits-diags/all/conandata.yml
  recipes/mbits-diags/config.yml
Labels: Bump version

#17860 libnghttp2: add version 1.54.0
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#17885 fast_float: add version 5.1.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#17884 cpp-httplib: add version 0.12.5
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#17883 libcurl: update libnghttp2 1.54.0
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#17887 hdf5: add v1.14.1
  recipes/hdf5/all/conandata.yml
  recipes/hdf5/config.yml
Labels: Bump version

#17889 libxcrypt: add version 4.4.35
  recipes/libxcrypt/all/conandata.yml
  recipes/libxcrypt/config.yml
Labels: Bump version

#17893 magic_enum: add version 0.9.2
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#17896 proposal: add version 7.6.0
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#17898 fast_float: add version 5.2.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#17918 roaring: add version 1.3.0
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#17826 Add support for SDL 2.26.5
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#17922 proposal: add version 7.6.1
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#17928 scnlib: update fast_float 5.2.0
  recipes/scnlib/all/conanfile.py
Labels: Bump dependencies

#17935 Bump/at spi2 core/new
  recipes/at-spi2-core/new/conanfile.py
Labels: Bump dependencies

#17952 proposal: add version 7.6.2
  recipes/proposal/all/conandata.yml
  recipes/proposal/config.yml
Labels: Bump version

#17955 simdjson: add version 3.2.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#17958 quill: add version 3.0.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#17960 charls: add version 2.4.2
  recipes/charls/all/conandata.yml
  recipes/charls/config.yml
Labels: Bump version

#17964 watcher: add version 0.8.8
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#17568 leaf-1.82.0
  recipes/boost-leaf/all/conandata.yml
  recipes/boost-leaf/config.yml
Labels: Bump version

#17371 [sentry-native] Add version 0.6.2
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#18015 libmount 2.39
  recipes/libmount/all/conandata.yml
  recipes/libmount/config.yml
Labels: Bump version

#18033 magic_enum: add version 0.9.3
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#18002 [sentry-breakpad/0.6.3] Add version
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#18036 wayland: add version 1.22.0
  recipes/wayland/all/conandata.yml
  recipes/wayland/config.yml
Labels: Bump version

#17751 [qt/6.5.1] Add version
  recipes/qt/6.x.x/conandata.yml
  recipes/qt/6.x.x/qtmodules6.5.1.conf
  recipes/qt/config.yml
Labels: Service Under Maintenance

#17351 imgui: add version 1.89.5
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#18043 (18044) Bump perfetto to v35.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#18042 wayland-protocols/all: bump deps
  recipes/wayland-protocols/all/conanfile.py
  recipes/wayland-protocols/all/test_package/conanfile.py
Labels: Bump dependencies

#18041 tlx: add version 0.6.1
  recipes/tlx/all/conandata.yml
  recipes/tlx/config.yml
Labels: Bump version

#18023 uni-algo: add version 0.8.2
  recipes/uni-algo/all/conandata.yml
  recipes/uni-algo/config.yml
Labels: Bump version

#18019 libsystemd/all: bump deps
  recipes/libsystemd/all/conanfile.py
Labels: Bump dependencies

#18035 at-spi2-core: add version 2.48.3
  recipes/at-spi2-core/config.yml
  recipes/at-spi2-core/new/conandata.yml
Labels: Bump version

#18050 luau: add version 0.582
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#18075 [sentry-crashpad] Update to 0.6.4
  recipes/sentry-crashpad/all/conandata.yml
  recipes/sentry-crashpad/config.yml
Labels: Bump version

#18074 [sentry-breakpad] Update to 0.6.4
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#18136 zlib-ng: add version 2.1.3
  recipes/zlib-ng/all/conandata.yml
  recipes/zlib-ng/config.yml
Labels: Bump version

#18146 libbigwig: bump deps
  recipes/libbigwig/all/conanfile.py
Labels: Bump dependencies

#18150 libunwind: Add version 1.7.0.
  recipes/libunwind/all/conandata.yml
  recipes/libunwind/config.yml
Labels: Bump version

#18157 nss 3.91
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#18217 Add outcome-2.2.4
  recipes/outcome/all/conandata.yml
  recipes/outcome/config.yml
Labels: Bump version
