Repository conan-io/conan-center-index, pull requests merged in 2023-08, with the labels that each got.

#18966 cpp-httplib: add version 0.13.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#18325 opentelemetry-proto: add version 1.0.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#18975 asio: add version 1.28.1
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#19035 [config] Update Conan client version: 1.60.2 and 2.0.9
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#19040 emsdk: add version 3.1.44
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#19043 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19025 harfbuzz: add version 8.1.1
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#19011 msgpack-c/3.3.0: Added version 3.3.0
  recipes/msgpack-c/all/conandata.yml
  recipes/msgpack-c/config.yml
Labels: Bump version

#18974 libunwind: add version 1.7.2
  recipes/libunwind/all/conandata.yml
  recipes/libunwind/config.yml
Labels: Bump version

#19052 cairo/meson: bump deps
  recipes/cairo/meson/conanfile.py
Labels: Bump dependencies

#19053 simdjson: add version 3.2.2
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#18973 aws-c-common: add version 0.9.0
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/all/test_v1_package/CMakeLists.txt
  recipes/aws-c-common/all/test_v1_package/conanfile.py
  recipes/aws-c-common/config.yml
Labels: Bump version

#18972 glib: add version 2.77.1
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#18953 [cgal] add cgal/5.5.3
  recipes/cgal/all/conandata.yml
  recipes/cgal/config.yml
Labels: Bump version

#19042 [docs] Add changelog 2023-Aug-04
  docs/changelog.md
Labels: Docs

#18284 BugFix: Update assimp's Draco version from 1.5.5 to 1.5.6 to resolve build error
  recipes/assimp/5.x/conanfile.py
Labels: Bump dependencies

#19068 zpp_bits: add version 4.4.18
  recipes/zpp_bits/all/conandata.yml
  recipes/zpp_bits/config.yml
Labels: Bump version

#19072 libuvc: update libjpeg-turbo/3.0.0
  recipes/libuvc/all/conanfile.py
Labels: Bump dependencies

#18932 nss 3.92
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#19079 libtiff: update libjpeg-turbo
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#18909 wt: add version 4.10.0
  recipes/wt/all/conandata.yml
  recipes/wt/config.yml
Labels: Bump version

#19080 jasper: update libjpeg-turbo
  recipes/jasper/all/conanfile.py
Labels: Bump dependencies

#19086 function2: add version 4.2.3
  recipes/function2/all/conandata.yml
  recipes/function2/config.yml
Labels: Bump version

#19087 mongo-c-driver: add version 1.24.3
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#19088 libyuv: update libjpeg-turbo/3.0.0
  recipes/libyuv/all/conanfile.py
Labels: Bump dependencies

#19015 Fix: sha256 sum of data for dice-template-library v1.0.0
  recipes/dice-template-library/all/conandata.yml
Labels: checksum_mismatch

#19093 [proj] Bump libcurl version
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#19091 [sentry-breakpad] bump libcurl to 8.2.0
  recipes/sentry-crashpad/all/conanfile.py
Labels: Bump dependencies

#19105 meson: add version 1.2.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#19106 libgeotiff: bump deps
  recipes/libgeotiff/all/conanfile.py
Labels: Bump dependencies

#19102 Add libsvtav1/1.6.0
  recipes/libsvtav1/all/conandata.yml
  recipes/libsvtav1/config.yml
Labels: Bump version

#18910 libmysqlclient: add version 8.0.34
  recipes/libmysqlclient/all/conandata.yml
  recipes/libmysqlclient/all/conanfile.py
  recipes/libmysqlclient/config.yml
Labels: Unexpected Error

#18923 libcurl: add version 8.2.1
  recipes/libcurl/all/conandata.yml
  recipes/libcurl/config.yml
Labels: Bump version

#18769 Add capnproto/0.10.4
  recipes/capnproto/all/conandata.yml
  recipes/capnproto/config.yml
Labels: Bump version

#19019 sqlitecpp: bump sqlite3 3.42.0
  recipes/sqlitecpp/all/conanfile.py
Labels: Bump dependencies

#18937 poco: sqlite3 bump 3.42.0
  recipes/poco/all/conanfile.py
Labels: Bump dependencies

#19132 etl: add version 20.37.3
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#18082 Add backup sources config
  .c3i/config_v2.yml
Labels: C3I config

#19136 Fix documentation typo
  docs/adding_packages/folders_and_files.md
Labels: Docs

#19143 [freetype] Bump requirements for libpng and zlib
  recipes/freetype/all/conanfile.py
Labels: Bump dependencies

#19183 args-parser: bump version
  recipes/args-parser/all/conandata.yml
  recipes/args-parser/config.yml
Labels: Bump version

#19169 fmt: add version 10.1.0
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#19188 quill: update fmt/10.1.0
  recipes/quill/all/conanfile.py
Labels: Bump dependencies

#19162 date: update libcurl
  recipes/date/all/conanfile.py
Labels: Bump dependencies

#19189 mppp: update dependencies
  recipes/mppp/all/conanfile.py
Labels: Bump dependencies

#19195 pngpp: update libpng
  recipes/pngpp/all/conanfile.py
Labels: Bump dependencies

#19197 blend2d: add version 0.10.4
  recipes/blend2d/all/conandata.yml
  recipes/blend2d/config.yml
Labels: Bump version

#19198 fmtlog: update fmt/10.1.0
  recipes/fmtlog/all/conanfile.py
Labels: Bump dependencies

#19199 jinja2cpp: update fmt/10.1.0
  recipes/jinja2cpp/all/conanfile.py
Labels: Bump dependencies

#19207 screen_capture_lite: add version 17.1.1369
  recipes/screen_capture_lite/all/conandata.yml
  recipes/screen_capture_lite/config.yml
Labels: Bump version

#19208 r8brain-free-src: add version 6.4
  recipes/r8brain-free-src/all/conandata.yml
  recipes/r8brain-free-src/config.yml
Labels: Bump version

#19216 maven: add version 3.9.4
  recipes/maven/all/conandata.yml
  recipes/maven/config.yml
Labels: Bump version

#19214 cppcommon: update fmt/10.1.0
  recipes/cppcommon/all/conanfile.py
Labels: Bump dependencies

#19185 Update wording on patch policy
  docs/adding_packages/sources_and_patches.md
Labels: Docs

#19220 jwt-cpp: update version range for OpenSSL
  recipes/jwt-cpp/all/conanfile.py
Labels: Bump dependencies

#19225 utfcpp: add 3.2.4
  recipes/utfcpp/all/conandata.yml
  recipes/utfcpp/config.yml
Labels: Bump version

#19236 json-c: add version 0.17
  recipes/json-c/all/conandata.yml
  recipes/json-c/config.yml
Labels: Bump version

#19244 [docs] Add changelog 17-Aug-2023
  docs/changelog.md
Labels: Docs

#19258 plusaes: add version 1.0.0
  recipes/plusaes/all/conandata.yml
  recipes/plusaes/config.yml
Labels: Bump version

#19255 s2n: add version 1.3.49
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#19250 [package] angelscript/2.36.1 (Update)
  recipes/angelscript/all/conandata.yml
  recipes/angelscript/config.yml
Labels: Bump version

#19265 [arsenalgear] Bump dependencies: Boost 1.82.0
  recipes/arsenalgear/all/conanfile.py
Labels: Bump dependencies

#19203 [libsnd] Update to 1.2.2
  recipes/libsndfile/all/conandata.yml
  recipes/libsndfile/config.yml
Labels: Bump version

#19276 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19282 nudb: update boost/1.83.0
  recipes/nudb/all/conanfile.py
Labels: Bump dependencies

#19287 restinio: bump boost & asio deps
  recipes/restinio/all/conanfile.py
Labels: Bump dependencies

#19288 asio-grpc: update boost/1.83.0
  recipes/asio-grpc/all/conanfile.py
Labels: Bump dependencies

#19289 asyncly: update dependencies
  recipes/asyncly/all/conanfile.py
Labels: Bump dependencies

#19293 tcl: add version 8.6.13
  recipes/tcl/all/conandata.yml
  recipes/tcl/config.yml
Labels: Bump version

#19295 boost-leaf: add version 1.83.0
  recipes/boost-leaf/all/conandata.yml
  recipes/boost-leaf/config.yml
Labels: Bump version

#19299 libpqxx: add version 7.8.1
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#19300 ftxui: add version 5.0.0
  recipes/ftxui/all/conandata.yml
  recipes/ftxui/config.yml
Labels: Bump version

#19303 docopt.cpp: update boost/1.83.0
  recipes/docopt.cpp/all/conanfile.py
Labels: Bump dependencies

#19302 numcpp: update boost/1.83.0
  recipes/numcpp/all/conanfile.py
Labels: Bump dependencies

#19304 wt: update dependencies
  recipes/wt/all/conanfile.py
Labels: Bump dependencies

#19308 proj: bump libcurl to v8.2.1
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#19314 unordered_dense: add version 4.1.0
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#19315 daw_utf_range: update daw_header_libraries
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#19317 mp-units: update dependencies
  recipes/mp-units/0.8.0/conanfile.py
Labels: Bump dependencies

#19319 mbits-diags: update fmt/10.1.0
  recipes/mbits-diags/all/conanfile.py
Labels: Bump dependencies

#19321 mbits-lngs: update fmt/10.1.0
  recipes/mbits-lngs/all/conanfile.py
Labels: Bump dependencies

#19124 [cgal] add cgal/5.6
  recipes/cgal/all/conandata.yml
  recipes/cgal/config.yml
Labels: Bump version

#19233 rtmidi: fix sha256 of 6.0.0
  recipes/rtmidi/all/conandata.yml
Labels: checksum_mismatch

#19316 svgwrite: update fmt/10.1.0
  recipes/svgwrite/all/conanfile.py
Labels: Bump dependencies

#19337 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19343 Added SDL version 2.28.2
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#19353 glaze: add version 1.3.6
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#19354 trantor: add version 1.5.13
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#19357 simdjson: add version 3.2.3
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#19358 cpp-httplib: add version 0.14.0
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#19359 drogon: update trantor/1.5.13
  recipes/drogon/all/conanfile.py
Labels: Bump dependencies

#19362 dbus 1.15.8
  recipes/dbus/1.x.x/conandata.yml
  recipes/dbus/config.yml
Labels: Bump version

#19364 glib: add version 2.77.2
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#19376 lexbor: add version 2.3.0
  recipes/lexbor/all/conandata.yml
  recipes/lexbor/config.yml
Labels: Bump version

#19383 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19396 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19395 sqlite3: add version 3.43.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#19388 libsecret/all: bump deps
  recipes/libsecret/all/conanfile.py
Labels: Bump dependencies

#19403 libselinux/all: bump deps
  recipes/libselinux/all/conanfile.py
Labels: Bump dependencies

#19390 glibmm/all: bump deps
  recipes/glibmm/all/conanfile.py
Labels: Bump dependencies

#19392 pulseaudio/alll: bump deps
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#19409 gperftools: add version 2.12.0
  recipes/gperftools/all/conandata.yml
  recipes/gperftools/config.yml
Labels: Bump version

#19387 keychain/all: bump deps
  recipes/keychain/all/conanfile.py
Labels: Bump dependencies

#19389 libverto/all: bump deps
  recipes/libverto/all/conanfile.py
Labels: Bump dependencies

#19414 xmlsec: bump libxml2 to 2.11.4
  recipes/xmlsec/all/conanfile.py
  recipes/xmlsec/all/test_package/conanfile.py
Labels: Bump dependencies

#19422 simple-yaml: update dependencies
  recipes/simple-yaml/all/conanfile.py
Labels: Bump dependencies

#19425 serdepp: update dependencies
  recipes/serdepp/all/conanfile.py
Labels: Bump dependencies

#19424 s2n: add version 1.3.50
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#19427 onnx: add version 1.14.1
  recipes/onnx/all/conandata.yml
  recipes/onnx/config.yml
Labels: Bump version

#19433 ada: add version 2.6.2
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#19435 gegles-spdlog_setup: update fmt/10.1.0
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#19436 seadex-essentials: update dependencies
  recipes/seadex-essentials/all/conanfile.py
Labels: Bump dependencies

#19431 aws-c-io: update s2n/1.3.50
  recipes/aws-c-io/all/conanfile.py
Labels: Bump dependencies

#19440 etl: add version 20.38.0
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#19442 implot: add version 0.16
  recipes/implot/all/conandata.yml
  recipes/implot/config.yml
Labels: Bump version

#19444 gsl-lite: add version 0.41.0
  recipes/gsl-lite/all/conandata.yml
  recipes/gsl-lite/config.yml
Labels: Bump version

#19446 cassandra-cpp-driver: add version 2.17.0
  recipes/cassandra-cpp-driver/all/conandata.yml
  recipes/cassandra-cpp-driver/config.yml
Labels: Bump version

#19450 maddy: add version 1.3.0
  recipes/maddy/all/conandata.yml
  recipes/maddy/config.yml
Labels: Bump version

#19451 capnproto: add version 1.0.1
  recipes/capnproto/all/conandata.yml
  recipes/capnproto/config.yml
Labels: Bump version

#19416 [openapi-generator] Add version 7.0.0
  recipes/openapi-generator/all/conandata.yml
  recipes/openapi-generator/config.yml
Labels: Bump version

#19467 fmt: add version 10.1.1
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#19471 ada: add version 2.6.4
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#19465 arrow: bump version of boost dependency
  recipes/arrow/all/conanfile.py
Labels: Bump dependencies

#19484 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19481 libheif: add version 1.16.2, update dependencies
  recipes/libheif/all/conandata.yml
  recipes/libheif/all/conanfile.py
  recipes/libheif/all/patches/0001-cmake_1.16.2.patch
  recipes/libheif/config.yml
Labels: Failed

#19492 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19507 libcap/2.69: Bump version
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#19503 ccache: add version 4.8.3
  recipes/ccache/all/conandata.yml
  recipes/ccache/config.yml
Labels: Bump version

#19513 nss 3.93
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#19525 onetbb: added 2021.10.0 version
  recipes/onetbb/all/conandata.yml
  recipes/onetbb/config.yml
Labels: Bump version

#19537 sdbus-cpp/1.3.0: Bump version
  recipes/sdbus-cpp/all/conandata.yml
  recipes/sdbus-cpp/config.yml
Labels: Bump version
