Repository conan-io/conan-center-index, pull requests merged in 2023-03, with the labels that each got.

#16403 [c3i] Update conan v2 ready references
  .c3i/conan_v2_ready_references.yml
Labels: C3I config

#16195 Document bumping version
  docs/README.md
  docs/bump_version.md
Labels: Docs

#16279 [doc] use `self.output.warning` in documentation instead of `self.output.warn` (invalid with conan v2 client)
  docs/faqs.md
Labels: Docs

#16420 Update conan_v2_ready_references.yml
  .c3i/conan_v2_ready_references.yml
Labels: C3I config

#16333 catch2: add version 3.3.2
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#16363 CI: Add Croydon for docs/ alerts
  .github/workflows/alert-community.yml
Labels: GitHub config

#16405 [readme] Add status page to the readme
  README.md
Labels: Docs

#16244 sigslot: add version 1.2.2
  recipes/sigslot/all/conandata.yml
  recipes/sigslot/config.yml
Labels: Bump version

#16502 glib 2.76.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#16512 opentdf-client: add version 1.3.10
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#16360 [changelog] Release 2023-03-03
  docs/changelog.md
Labels: Docs

#16515 simdutf: add version 3.2.2
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#16522 md4qt: bump version to 2.0.5.
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#16532 cpp-httplib: add version 0.12.1
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#16547 sqlite3: add version 3.41.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#16513 docs: make sure package type is set
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/msbuild_package/all/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/conanfile.py
Labels: Docs

#16425 config: add ceres-solver to large pod
  .c3i/config_v1.yml
Labels: C3I config

#16371 [docs] Document label c3i-conan2-ready
  docs/labels.md
Labels: Docs

#16562 nss 3.89
  recipes/nss/all/conandata.yml
  recipes/nss/config.yml
Labels: Bump version

#16561 roaring: add version 0.9.9
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#16585 catch2: add v2.13.10
  recipes/catch2/2.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#16597 websocketpp: Updated openssl dependency to 1.1.1t
  recipes/websocketpp/all/conanfile.py
Labels: Bump dependencies

#16510 config: drop openssl from v2 ready since it does not work for 3.x version
  .c3i/conan_v2_ready_references.yml
Labels: C3I config

#16616 libcbor: add version 0.10.2
  recipes/libcbor/all/conandata.yml
  recipes/libcbor/config.yml
Labels: Bump version

#16614 imath: add version 3.1.7
  recipes/imath/all/conandata.yml
  recipes/imath/config.yml
Labels: Bump version

#16609 imgui: add version 1.89.4
  recipes/imgui/all/conandata.yml
  recipes/imgui/config.yml
Labels: Bump version

#16635 Add David to team reviewers
  .c3i/reviewers.yml
Labels: C3I config

#16656 cpr: add version 1.10.1
  recipes/cpr/all/conandata.yml
  recipes/cpr/config.yml
Labels: Bump version

#16657 Bump Conan 2 to 2.0.2
  .c3i/config_v2.yml
Labels: C3I config

#16663 glib: add version 2.76.1
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#16593 docs: clarify what's support with Conan 2.0
  docs/developing_recipes_locally.md
Labels: Docs

#16199 Update documentation URLs to use Conan v1 dedicated address
  docs/adding_packages/README.md
  docs/adding_packages/build_and_package.md
  docs/adding_packages/conandata_yml_format.md
  docs/adding_packages/conanfile_attributes.md
  docs/adding_packages/dependencies.md
  docs/adding_packages/folders_and_files.md
  docs/adding_packages/sources_and_patches.md
  docs/adding_packages/test_packages.md
  docs/consuming_recipes.md
  docs/developing_recipes_locally.md
  docs/error_knowledge_base.md
  docs/faqs.md
  docs/linters.md
  docs/v2_linter.md
  docs/v2_migration.md
Labels: Docs

#16637 hazelcast-cpp-client: add version 5.2.0
  recipes/hazelcast-cpp-client/all/conandata.yml
  recipes/hazelcast-cpp-client/config.yml
Labels: Bump version

#16638 Improve and update ArduinoJson
  recipes/arduinojson/all/conandata.yml
  recipes/arduinojson/all/conanfile.py
  recipes/arduinojson/all/test_package/test_package.cpp
  recipes/arduinojson/config.yml
Labels: checksum_mismatch

#16682 [docs] Add changelog March 23 2023
  docs/changelog.md
Labels: Docs

#16643 asio: Add versions 1.26.0 and 1.27.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#16641 trantor: add version 1.5.11
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#16684 Add fast-cdr version 1.0.26
  recipes/fast-cdr/all/conandata.yml
  recipes/fast-cdr/config.yml
Labels: Bump version

#16677 wayland-protocols: fix source references
  recipes/wayland-protocols/all/conandata.yml
Labels: checksum_mismatch

#16468 daw_header_libraries: add version 2.88.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#16217 libx265: conan v2 support
  recipes/libx265/all/CMakeLists.txt
  recipes/libx265/all/conandata.yml
  recipes/libx265/all/conanfile.py
  recipes/libx265/all/patches/3.2.1-0001-remove_register_classifier.patch
  recipes/libx265/all/patches/3.2.1-0002-cmake-min-required.patch
  recipes/libx265/all/patches/3.4-0001-numa.patch
  recipes/libx265/all/test_package/CMakeLists.txt
  recipes/libx265/all/test_package/conanfile.py
  recipes/libx265/all/test_package/test_library.c
  recipes/libx265/all/test_v1_package/CMakeLists.txt
  recipes/libx265/all/test_v1_package/conanfile.py
Labels: checksum_mismatch

#16752 [sentry-breakpad] Update to 0.6.1
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#16783 fast_float: add version 3.11.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#16800 config: remove eric from gtk alerts
  .github/workflows/alert-community.yml
Labels: GitHub config

#16786 [config] Add values for cppstds for conan v2 pipeline
  .c3i/config_v2.yml
Labels: C3I config

#16810 md4qt: bump version.
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version
