Repository conan-io/conan-center-index, pull requests merged in 2023-09, with the labels that each got.

#19542 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#19550 highway: add version 1.0.7
  recipes/highway/all/conandata.yml
  recipes/highway/config.yml
Labels: Bump version

#19527 pkgconf 2.0.2
  recipes/pkgconf/all/conandata.yml
  recipes/pkgconf/config.yml
Labels: Bump version

#19543 graphene/all: bump deps
  recipes/graphene/all/conanfile.py
Labels: Bump dependencies

#19528 glib 2.77.3
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#19555 Add changelog 01 Sep 2023
  docs/changelog.md
Labels: Docs

#19559 c-blosc: add version 1.21.5
  recipes/c-blosc/all/conandata.yml
  recipes/c-blosc/config.yml
Labels: Bump version

#19522 [docs] Change conan v2 feedback message
  .c3i/config_v2.yml
Labels: C3I config

#19459 [docs] Add section about Docker images used by CCI
  docs/developing_recipes_locally.md
Labels: Docs

#19562 mppp: update dependencies
  recipes/mppp/all/conanfile.py
Labels: Bump dependencies

#19564 arsenalgear: update boost/1.8.30
  recipes/arsenalgear/all/conanfile.py
Labels: Bump dependencies

#19567 jinja2cpp: update dependencies
  recipes/jinja2cpp/all/conanfile.py
Labels: Bump dependencies

#19569 websocketpp: update dependencies
  recipes/websocketpp/all/conanfile.py
Labels: Bump dependencies

#19572 cpprestsdk: update boost/1.83.0
  recipes/cpprestsdk/all/conanfile.py
Labels: Bump dependencies

#19575 fakeit: update dependencies
  recipes/fakeit/all/conanfile.py
Labels: Bump dependencies

#19514 [onetbb] Bump dependencies
  recipes/onetbb/all/conanfile.py
Labels: Bump dependencies

#19410 wt: update dependencies
  recipes/wt/all/conanfile.py
Labels: Bump dependencies

#19523 [config] Conan v2 ready references is no longer required
  .c3i/config_v1.yml
Labels: C3I config

#19531 benchmark: add version 1.8.3
  recipes/benchmark/all/conandata.yml
  recipes/benchmark/config.yml
Labels: Bump version

#19597 [changelog] Add changelog 31-August-2023
  docs/changelog.md
Labels: Docs

#19588 [docs] Add `zlib` and `libcurl` to the list of allowed version ranges
  docs/adding_packages/dependencies.md
Labels: Docs

#19614 [imagl] Migrate to Conan 2.x and fix JSON error in CI
  recipes/imagl/all/CMakeLists.txt
  recipes/imagl/all/conandata.yml
  recipes/imagl/all/conanfile.py
  recipes/imagl/all/test_package/CMakeLists.txt
  recipes/imagl/all/test_package/conanfile.py
  recipes/imagl/all/test_v1_package/CMakeLists.txt
  recipes/imagl/all/test_v1_package/conanfile.py
Labels: checksum_mismatch

#19493 linux-headers-generic: add version 5.15.128
  recipes/linux-headers-generic/all/conandata.yml
  recipes/linux-headers-generic/config.yml
Labels: Bump version

#19495 xmlsec: add version 1.2.33
  recipes/xmlsec/all/conandata.yml
  recipes/xmlsec/config.yml
Labels: Bump version

#19622 daw_header_libraries: add version 2.96.1
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#19645 fontconfig/meson: bump deps
  recipes/fontconfig/meson/conanfile.py
Labels: Bump dependencies

#19680 zpp_bits: add version 4.4.19
  recipes/zpp_bits/all/conandata.yml
  recipes/zpp_bits/config.yml
Labels: Bump version

#19701 quill: update fmt/10.1.1
  recipes/quill/all/conanfile.py
Labels: Bump dependencies

#19699 soci: update dependencies
  recipes/soci/all/conanfile.py
Labels: Bump dependencies

#19705 visit_struct: update boost/1.83.0
  recipes/visit_struct/all/conanfile.py
Labels: Bump dependencies

#19707 samurai: add version 0.6.0
  recipes/samurai/all/conandata.yml
  recipes/samurai/config.yml
Labels: Bump version

#19708 restinio: update fmt/10.1.1
  recipes/restinio/all/conanfile.py
Labels: Bump dependencies

#19706 usockets: update boost/1.83.0
  recipes/usockets/all/conanfile.py
Labels: Bump dependencies

#19710 seadex-genesis: update fmt/10.1.0
  recipes/seadex-genesis/all/conanfile.py
Labels: Bump dependencies

#19711 highfive: update dependencies
  recipes/highfive/all/conanfile.py
Labels: Bump dependencies

#19712 xtensor: update dependencies
  recipes/xtensor/all/conanfile.py
Labels: Bump dependencies

#19715 daw_utf_range: update daw_header_libraries/2.96.1
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#19719 xz_utils: add v5.4.4
  recipes/xz_utils/all/conandata.yml
  recipes/xz_utils/config.yml
Labels: Bump version

#19723 libavif: bump deps
  recipes/libavif/all/conanfile.py
Labels: Bump dependencies

#19720 samurai: update dependencies
  recipes/samurai/all/conanfile.py
Labels: Bump dependencies

#19730 glib: add version 2.78.0
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#19731 hictk: add v0.0.2
  recipes/hictk/all/conandata.yml
  recipes/hictk/config.yml
Labels: Bump version

#19407 sqlite_orm: update sqlite3/3.43.0
  recipes/sqlite_orm/all/conanfile.py
Labels: Bump dependencies

#19737 pkgconf: add version 2.0.3
  recipes/pkgconf/all/conandata.yml
  recipes/pkgconf/config.yml
Labels: Bump version

#19740 sqlite3: add version 3.43.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#19755 gperftools: add version 2.13.0
  recipes/gperftools/all/conandata.yml
  recipes/gperftools/config.yml
Labels: Bump version

#19760 dirent: add version 1.24
  recipes/dirent/all/conandata.yml
  recipes/dirent/config.yml
Labels: Bump version

#19777 sml: add version 1.1.9
  recipes/sml/all/conandata.yml
  recipes/sml/config.yml
Labels: Bump version

#19778 add make/4.4
  recipes/make/all/conandata.yml
  recipes/make/config.yml
Labels: Bump version

#19792 Add drwav 0.13.12
  recipes/drwav/all/conandata.yml
  recipes/drwav/config.yml
Labels: Bump version

#19806 libsodium 1.0.19
  recipes/libsodium/all/conandata.yml
  recipes/libsodium/config.yml
Labels: Bump version

#19819 libwebp: add version 1.3.2
  recipes/libwebp/all/conandata.yml
  recipes/libwebp/config.yml
Labels: Bump version

#19821 libtiff: add version 4.6.0
  recipes/libtiff/all/conandata.yml
  recipes/libtiff/config.yml
Labels: Bump version

#19826 antlr4-cppruntime: Add version 4.13.1.
  recipes/antlr4-cppruntime/all/conandata.yml
  recipes/antlr4-cppruntime/config.yml
Labels: Bump version

#19875 gegles-spdlog_setup: bump fmt
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#19885 yyjson: add version 0.8.0
  recipes/yyjson/all/conandata.yml
  recipes/yyjson/config.yml
Labels: Bump version

#19886 cpu_features: add version 0.9.0
  recipes/cpu_features/all/conandata.yml
  recipes/cpu_features/config.yml
Labels: Bump version

#19889 uni-algo: add version 1.1.0
  recipes/uni-algo/all/conandata.yml
  recipes/uni-algo/config.yml
Labels: Bump version

#19893 platform.hashing: update cpu_features/0.9.0
  recipes/platform.hashing/all/conanfile.py
Labels: Bump dependencies

#19895 implot: update imgui/1.89.9
  recipes/implot/all/conanfile.py
Labels: Bump dependencies

#19898 emio: add version 0.4.0
  recipes/emio/all/conandata.yml
  recipes/emio/config.yml
Labels: Bump version

#19905 libdeflate: add version 1.19
  recipes/libdeflate/all/conandata.yml
  recipes/libdeflate/config.yml
Labels: Bump version

#19924 libalsa: add version 1.2.10
  recipes/libalsa/all/conandata.yml
  recipes/libalsa/config.yml
Labels: Bump version

#19913 [doc] fix msvc version in header-only template
  docs/package_templates/header_only/all/conanfile.py
Labels: Docs

#19817 xtensor: add version 0.24.6
  recipes/xtensor/all/conandata.yml
  recipes/xtensor/config.yml
Labels: Bump version

#19937 libselinux/all: bump deps
  recipes/libselinux/all/conanfile.py
Labels: Bump dependencies

#20062 Bump xz_utils for ffmpeg
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#20106 [docs] Add changelog September, 25 2023
  docs/changelog.md
Labels: Docs

#19962 stringzilla: add version 1.2.2
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#19967 glaze: add version 1.5.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#19968 cgif: bump meson
  recipes/cgif/all/conanfile.py
Labels: Bump dependencies

#19969 dav1d: bump meson
  recipes/dav1d/all/conanfile.py
Labels: Bump dependencies

#19970 fribidi: bump meson
  recipes/fribidi/all/conanfile.py
Labels: Bump dependencies

#20052 libunwind: update xz_utils/5.4.4
  recipes/libunwind/all/conanfile.py
Labels: Bump dependencies

#19974 inih: bump meson
  recipes/inih/all/conanfile.py
Labels: Bump dependencies

#19975 lcms: bump meson
  recipes/lcms/all/conanfile.py
Labels: Bump dependencies

#19977 libepoxy: bump meson
  recipes/libepoxy/all/conanfile.py
Labels: Bump dependencies

#19984 Bump/pulseaudio/all
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#19986 wayland/all: bump deps
  recipes/wayland/all/conanfile.py
  recipes/wayland/all/test_package/conanfile.py
Labels: Bump dependencies

#19992 mpg123/all: bump deps
  recipes/mpg123/all/conanfile.py
Labels: Bump dependencies

#19993 libsndfile/all: bump deps
  recipes/libsndfile/all/conanfile.py
Labels: Bump dependencies

#19997 cuda-api-wrappers: add version 0.7
  recipes/cuda-api-wrappers/all/conandata.yml
  recipes/cuda-api-wrappers/config.yml
Labels: Bump version

#19999 pixman: bump meson
  recipes/pixman/all/conanfile.py
Labels: Bump dependencies

#20004 libpsl: bump icu, meson & pkgconf
  recipes/libpsl/all/conanfile.py
Labels: Bump dependencies

#20005 vsg: add version 1.0.9
  recipes/vsg/all/conandata.yml
  recipes/vsg/config.yml
Labels: Bump version

#20006 caf: add version 0.19.3
  recipes/caf/all/conandata.yml
  recipes/caf/config.yml
Labels: Bump version

#20007 nvtx: add version 3.1.0
  recipes/nvtx/all/conandata.yml
  recipes/nvtx/config.yml
Labels: Bump version

#20011 libtiff/all: bump libwebp
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#20012 platform.exceptions: add version 0.5.0
  recipes/platform.exceptions/all/conandata.yml
  recipes/platform.exceptions/config.yml
Labels: Bump version

#20013 platform.converters: add version 0.4.0
  recipes/platform.converters/all/conandata.yml
  recipes/platform.converters/config.yml
Labels: Bump version

#20016 proj: add version 9.3.0
  recipes/proj/all/conandata.yml
  recipes/proj/config.yml
Labels: Bump version

#20018 stc: add version 4.2
  recipes/stc/all/conandata.yml
  recipes/stc/config.yml
Labels: Bump version

#20019 librdkafka: add version 2.2.0
  recipes/librdkafka/all/conandata.yml
  recipes/librdkafka/config.yml
Labels: Bump version

#20021 outcome: add version 2.2.7
  recipes/outcome/all/conandata.yml
  recipes/outcome/config.yml
Labels: Bump version

#20024 redboltz-mqtt_cpp: add version 13.2.1
  recipes/redboltz-mqtt_cpp/all/conandata.yml
  recipes/redboltz-mqtt_cpp/config.yml
Labels: Bump version

#20026 openddl-parser: add version 0.5.1
  recipes/openddl-parser/all/conandata.yml
  recipes/openddl-parser/config.yml
Labels: Bump version

#20028 mcap: add version 1.2.1
  recipes/mcap/all/conandata.yml
  recipes/mcap/config.yml
Labels: Bump version

#20029 seasocks: add version 1.4.6
  recipes/seasocks/all/conandata.yml
  recipes/seasocks/config.yml
Labels: Bump version

#20033 easyloggingpp: add version 9.97.1
  recipes/easyloggingpp/all/conandata.yml
  recipes/easyloggingpp/config.yml
Labels: Bump version

#20034 libipt: add version 2.0.6
  recipes/libipt/all/conandata.yml
  recipes/libipt/config.yml
Labels: Bump version

#20039 zpp_throwing: add version 1.0.1
  recipes/zpp_throwing/all/conandata.yml
  recipes/zpp_throwing/config.yml
Labels: Bump version

#20040 cyclonedds: add version 0.10.4
  recipes/cyclonedds/all/conandata.yml
  recipes/cyclonedds/config.yml
Labels: Bump version

#20045 libfreenect: add version 0.7.0
  recipes/libfreenect/all/conandata.yml
  recipes/libfreenect/config.yml
Labels: Bump version

#20046 hffix: add version 1.3.0
  recipes/hffix/all/conandata.yml
  recipes/hffix/config.yml
Labels: Bump version

#20048 tinyexr: add version 1.0.7
  recipes/tinyexr/all/conandata.yml
  recipes/tinyexr/config.yml
Labels: Bump version

#20049 godot_headers: add version 3.5.2
  recipes/godot_headers/all/conandata.yml
  recipes/godot_headers/config.yml
Labels: Bump version

#20053 Add cppcheck 2.12.1
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#20086 rapidcsv: add version 8.80
  recipes/rapidcsv/all/conandata.yml
  recipes/rapidcsv/config.yml
Labels: Bump version

#20087 unordered_dense: add version 4.1.2
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#20100 yaml linter: remove warning about base_path
  linter/conandata_yaml_linter.py
Labels: GitHub config

#20168 etl: add version 20.38.2
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#20205 meson: add version 1.2.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#20041 fribidi: add version 1.0.13
  recipes/fribidi/all/conandata.yml
  recipes/fribidi/config.yml
Labels: Bump version

#20207 md4qt: bump version.
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version
