Repository conan-io/conan-center-index, pull requests merged in 2023-05, with the labels that each got.

#17331 sdbus-cpp/all: Bump dependencies
  recipes/sdbus-cpp/all/conanfile.py
  recipes/sdbus-cpp/all/test_pkgconf/conanfile.py
  recipes/sdbus-cpp/all/test_v1_pkgconf/conanfile.py
Labels: Bump dependencies

#17333 Added ittapi 3.24.0
  recipes/ittapi/all/conandata.yml
  recipes/ittapi/config.yml
Labels: Bump version

#17362 glib: add version 2.76.2
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#17370 [sentry-breakpad] Add version 0.6.2
  recipes/sentry-breakpad/all/conandata.yml
  recipes/sentry-breakpad/config.yml
Labels: Bump version

#17225 [config] Update conan v2 version
  .c3i/config_v2.yml
Labels: Service Under Maintenance

#17065 ffmpeg: use version range for openssl
  recipes/ffmpeg/all/conanfile.py
Labels: Bump dependencies

#17401 [config] Add values for cppstds for conan v2 pipeline
  .c3i/config_v2.yml
Labels: C3I config

#17402 [docs] Update changelog 04-May-2023
  docs/changelog.md
Labels: Docs

#17421 onnx: add version 1.14.0
  recipes/onnx/all/conandata.yml
  recipes/onnx/config.yml
Labels: Bump version

#17432 daw_json_link: update daw_header_libraries
  recipes/daw_json_link/all/conanfile.py
Labels: Bump dependencies

#17438 onetbb: bump to 2021.9.0
  recipes/onetbb/all/conandata.yml
  recipes/onetbb/config.yml
Labels: Bump version

#17454 Update abseil to 20230125.3
  recipes/abseil/all/conandata.yml
  recipes/abseil/config.yml
Labels: Bump version

#17377 docs: using openssl version range with 1.x clients
  docs/adding_packages/dependencies.md
Labels: Docs

#17462 (#17461) Perfetto: Bump v34.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#17469 glaze: add version 1.2.3
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#17483 libxft/all/: bump deps
  recipes/libxft/all/conanfile.py
Labels: Bump dependencies

#17477 fontconfig/all/: bump deps
  recipes/fontconfig/all/conanfile.py
Labels: Bump dependencies

#17479 nss/all/: bump deps
  recipes/nss/all/conanfile.py
Labels: Bump dependencies

#17481 xkbcommon/all/: bump deps
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#17475 Bump eigen in opencv
  recipes/opencv/4.x/conanfile.py
Labels: Bump dependencies

#17494 fast-cdr: Bump version to 1.0.27
  recipes/fast-cdr/all/conandata.yml
  recipes/fast-cdr/config.yml
Labels: Bump version

#17492 at-spi2-core: add version 2.48.0
  recipes/at-spi2-core/config.yml
  recipes/at-spi2-core/new/conandata.yml
Labels: Bump version

#17530 Add mold 1.11.0
  recipes/mold/all/conandata.yml
  recipes/mold/config.yml
Labels: Bump version

#17458 arrow: add version 11.0.0
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#17537 (#17536) openexr: Add version 3.1.7
  recipes/openexr/3.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#17549 bshoshany-thread-pool: add version 3.4.0
  recipes/bshoshany-thread-pool/all/conandata.yml
  recipes/bshoshany-thread-pool/config.yml
Labels: Bump version

#17550 quill: add version 2.9.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#17551 asio: add version 1.28.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#17556 ada: add version 2.4.0
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#17558 packio: add version 2.5.0
  recipes/packio/all/conandata.yml
  recipes/packio/config.yml
Labels: Bump version

#17563 pfr: add version 2.1.0
  recipes/pfr/all/conandata.yml
  recipes/pfr/config.yml
Labels: Bump version

#17571 [openapi-generator] bump to 6.6.0
  recipes/openapi-generator/all/conandata.yml
  recipes/openapi-generator/config.yml
Labels: Bump version

#17576 benchmark: add version 1.8.0
  recipes/benchmark/all/conandata.yml
  recipes/benchmark/config.yml
Labels: Bump version

#17588 [grpc] prepare for google-cloud-cpp-v2.10.1
  recipes/grpc/all/conanfile.py
Labels: Bump dependencies

#17613 ghc-filesystem: add version 1.5.14
  recipes/ghc-filesystem/all/conandata.yml
  recipes/ghc-filesystem/config.yml
Labels: Bump version

#17616 ada: add version 2.4.1
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#17625 libxml2: add version 2.11.4
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#17622 double-conversion: add version 3.3.0
  recipes/double-conversion/all/conandata.yml
  recipes/double-conversion/config.yml
Labels: Bump version

#17601 update sqlite3 to version 3.42.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#17635 ada: add version 2.4.2
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#17374 docs: add standing convention for naming forks of projects
  docs/adding_packages/conanfile_attributes.md
  docs/faqs.md
Labels: Docs

#16976 Verilator: add version 5.008
  recipes/verilator/all/conandata.yml
  recipes/verilator/config.yml
Labels: Bump version

#17641 luau: add version 0.577
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#17642 ccache: add version 4.8.1
  recipes/ccache/all/conandata.yml
  recipes/ccache/config.yml
Labels: Bump version

#17643 daw_header_libraries: add version 2.92.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#17644 daw_utf_range: update daw_header_libraries
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#17631 wayland: bump deps
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#17632 xkbcommon: bump deps
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#17653 c-ares: add version 1.19.1
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#17654 unordered_dense: add version 4.0.1
  recipes/unordered_dense/all/conandata.yml
  recipes/unordered_dense/config.yml
Labels: Bump version

#17659 graphene: Bump glib and Meson versions
  recipes/graphene/all/conanfile.py
Labels: Bump dependencies

#17621 valijson: bump version 1.0.1
  recipes/valijson/all/conandata.yml
  recipes/valijson/config.yml
Labels: Bump version

#17677 glib: add version 2.76.3
  recipes/glib/all/conandata.yml
  recipes/glib/config.yml
Labels: Bump version

#17689 upgrade sqlitecpp to version 3.3.0
  recipes/sqlitecpp/all/conandata.yml
  recipes/sqlitecpp/config.yml
Labels: Bump version

#17688 harfbuzz: add version 7.3.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#17673 update samurai to release 0.3.0
  recipes/samurai/all/conandata.yml
  recipes/samurai/config.yml
Labels: Bump version

#17705 docs: remove mention of the migration test_v1_package
  docs/adding_packages/test_packages.md
  docs/error_knowledge_base.md
  docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/autotools_package/all/test_v1_package/conanfile.py
  docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/cmake_package/all/test_v1_package/conanfile.py
  docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
  docs/package_templates/header_only/all/test_v1_package/conanfile.py
  docs/package_templates/meson_package/all/test_v1_package/conanfile.py
  docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt
  docs/package_templates/msbuild_package/all/test_v1_package/conanfile.py
  docs/package_templates/prebuilt_tool_package/all/test_v1_package/conanfile.py
Labels: Docs

#17709 meson: add version 1.1.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#17713 pixman: generate V2 package
  recipes/pixman/all/conanfile.py
Labels: Bump dependencies

#17718 libpcap: add version 1.10.4
  recipes/libpcap/all/conandata.yml
  recipes/libpcap/config.yml
Labels: Bump version

#17720 ada: add version 2.5.0
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#17726 cpp-httplib: add version 0.12.4
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#17727 liblsl: add version 1.16.2
  recipes/liblsl/all/conandata.yml
  recipes/liblsl/config.yml
Labels: Bump version

#17729 di: add version 1.3.0
  recipes/di/all/conandata.yml
  recipes/di/config.yml
Labels: Bump version

#17730 imath: add version 3.1.8
  recipes/imath/all/conandata.yml
  recipes/imath/config.yml
Labels: Bump version

#17328 cmake: add `conanbuildinfo.cmake` to `.gitignore`
  .gitignore
Labels: GitHub config

#17747 roaring: add version 1.1.5
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#17766 scnlib: update fast_float
  recipes/scnlib/all/conanfile.py
Labels: Bump dependencies
