Repository conan-io/conan-center-index, pull requests merged in 2023-11, with the labels that each got.

#20867 cpp-ipc: add version 1.3.0
  recipes/cpp-ipc/all/conandata.yml
  recipes/cpp-ipc/config.yml
Labels: Bump version

#20863 libzip: bump deps
  recipes/libzip/all/conanfile.py
Labels: Bump dependencies

#20874 sqlite3: add version 3.44.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#20882 opentdf-client: add version 1.5.6
  recipes/opentdf-client/all/conandata.yml
  recipes/opentdf-client/config.yml
Labels: Bump version

#20873 Add support for ICU version 74.1
  recipes/icu/all/conandata.yml
  recipes/icu/config.yml
Labels: Bump version

#20633 openjpeg: Prefer SPDX identifier
  recipes/openjpeg/all/conanfile.py
Labels: User-approval pending

#20050 h5pp: add version 1.11.0.1
  recipes/h5pp/all/conandata.yml
  recipes/h5pp/config.yml
Labels: Bump version

#20862 re2: add version 20231101
  recipes/re2/all/conandata.yml
  recipes/re2/config.yml
Labels: Bump version

#20893 [yoga] bumb version to 2.0.1
  recipes/yoga/all/conandata.yml
  recipes/yoga/config.yml
Labels: Bump version

#20895 bump dependencies of libgcrypt
  recipes/libgcrypt/all/conanfile.py
Labels: Bump dependencies

#20914 glaze: add version 1.5.7
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#20917 aws-c-common: add version 0.9.6
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#20926 aws-c-sdkutils: update aws-c-common/0.9.6
  recipes/aws-c-sdkutils/all/conanfile.py
Labels: Bump dependencies

#20928 cs_libguarded: add version 1.4.1
  recipes/cs_libguarded/all/conandata.yml
  recipes/cs_libguarded/config.yml
Labels: Bump version

#20927 aws-c-compression: update aws-c-common/0.9.6
  recipes/aws-c-compression/all/conanfile.py
Labels: Bump dependencies

#20939 zpp_bits: add version 4.4.20
  recipes/zpp_bits/all/conandata.yml
  recipes/zpp_bits/config.yml
Labels: Bump version

#20940 rapidfuzz: add version 2.2.3
  recipes/rapidfuzz/all/conandata.yml
  recipes/rapidfuzz/config.yml
Labels: Bump version

#20941 hwdata: add version 0.376
  recipes/hwdata/all/conandata.yml
  recipes/hwdata/config.yml
Labels: Bump version

#20946 paho-mqtt-c: add version 1.3.13
  recipes/paho-mqtt-c/all/conandata.yml
  recipes/paho-mqtt-c/config.yml
Labels: Bump version

#20925 aws-c-cal: update aws-c-common/0.9.6
  recipes/aws-c-cal/all/conanfile.py
Labels: Bump dependencies

#20949 quill: add version 3.4.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#20856 Minor clean up of template packages
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/cmake_package/all/conanfile.py
  docs/package_templates/cmake_package/all/test_package/CMakeLists.txt
  docs/package_templates/header_only/all/conanfile.py
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/meson_package/all/test_package/conanfile.py
  docs/package_templates/msbuild_package/all/conanfile.py
  docs/package_templates/msbuild_package/all/test_package/CMakeLists.txt
  docs/package_templates/prebuilt_tool_package/all/conanfile.py
Labels: Docs

#20951 function2: add version 4.2.4
  recipes/function2/all/conandata.yml
  recipes/function2/config.yml
Labels: Bump version

#20974 microservice-essentials/all: bump deps
  recipes/microservice-essentials/all/conanfile.py
Labels: Bump dependencies

#20971 czmq/all: bump deps
  recipes/czmq/all/conanfile.py
Labels: Bump dependencies

#20982 octo-logger-cpp: add version 1.5.0
  recipes/octo-logger-cpp/all/conandata.yml
  recipes/octo-logger-cpp/config.yml
Labels: Bump version

#20980 arrow: add version 14.0.0
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#20989 emio: add version 0.6.1
  recipes/emio/all/conandata.yml
  recipes/emio/config.yml
Labels: Bump version

#20972 fakeit/all: bump deps
  recipes/fakeit/all/conanfile.py
Labels: Bump dependencies

#20978 aws-c-io: update dependencies
  recipes/aws-c-io/all/conanfile.py
Labels: Bump dependencies

#20990 aws-c-common: re-add 0.8.2
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#21010 continuable: update funciton2/4.2.4
  recipes/continuable/all/conanfile.py
Labels: Bump dependencies

#21008 asyncly: update function2/4.2.4
  recipes/asyncly/all/conanfile.py
Labels: Bump dependencies

#21013 base64: add version 0.5.1
  recipes/base64/all/conandata.yml
  recipes/base64/config.yml
Labels: Bump version

#21011 cimg: update openexr/3.2.1
  recipes/cimg/all/conanfile.py
Labels: Bump dependencies

#21009 aws-c-io: add version 0.13.35
  recipes/aws-c-io/all/conandata.yml
  recipes/aws-c-io/config.yml
Labels: Bump version

#21017 aws-checksums: update aws-c-common/0.9.6
  recipes/aws-checksums/all/conanfile.py
Labels: Bump dependencies

#21033 aws-c-event-stream: update dependencies
  recipes/aws-c-event-stream/all/conanfile.py
Labels: Bump dependencies

#21035 ada: add version 2.7.3
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#20994 [config v2] Add longer timeout to build gstreamer
  .c3i/config_v2.yml
Labels: C3I config

#21038 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21039 libpciaccess: bump pkgconf
  recipes/libpciaccess/all/conanfile.py
Labels: Bump dependencies

#21045 aws-kvs-pic: bump pkgconf
  recipes/aws-kvs-pic/all/test_package/conanfile.py
  recipes/aws-kvs-pic/all/test_v1_package/conanfile.py
Labels: Bump dependencies

#20959 argparse: add version 3.0
  recipes/argparse/all/conandata.yml
  recipes/argparse/config.yml
Labels: Bump version

#21054 emsdk: new versions
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#21065 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21041 libcap: bump pkgconf
  recipes/libcap/all/test_package/conanfile.py
  recipes/libcap/all/test_v1_package/conanfile.py
Labels: Bump dependencies

#21047 sdbus-cpp: bump pkgconf
  recipes/sdbus-cpp/all/test_pkgconf/conanfile.py
Labels: Bump dependencies

#21044 coin-cgl: bump pkgconf
  recipes/coin-cgl/all/test_v1_package/conanfile.py
Labels: Bump dependencies

#21063 libmaxminddb: add version 1.8.0
  recipes/libmaxminddb/all/conandata.yml
  recipes/libmaxminddb/config.yml
Labels: Bump version

#21043 sentry-breakpad: bump pkgconf
  recipes/sentry-breakpad/all/test_package/conanfile.py
Labels: Bump dependencies

#21053 coin-utils: bump pkgconf
  recipes/coin-utils/all/test_package/conanfile.py
  recipes/coin-utils/all/test_v1_package/conanfile.py
Labels: Bump dependencies

#21057 arrow: add version 14.0.1
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#21072 onnxruntime: add version 1.16.2
  recipes/onnxruntime/all/conandata.yml
  recipes/onnxruntime/config.yml
Labels: Bump version

#21062 uwebsockets: add version 20.48.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#21056 xsimd: add version 11.2.0
  recipes/xsimd/all/conandata.yml
  recipes/xsimd/config.yml
Labels: Bump version

#21074 c-blosc2: add version 2.11.2
  recipes/c-blosc2/all/conandata.yml
  recipes/c-blosc2/config.yml
Labels: Bump version

#21075 luau: add version 0.603
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#21076 sjson-cpp: add version 0.9.0
  recipes/sjson-cpp/all/conandata.yml
  recipes/sjson-cpp/config.yml
Labels: Bump version

#21084 roaring: add 2.0.4
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#21082 flecs: add 3.2.8
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version

#21081 Bump libjpeg-turbo/3.0.1
  recipes/libjpeg-turbo/all/conandata.yml
  recipes/libjpeg-turbo/config.yml
Labels: Bump version

#21083 ezc3d: add 1.5.5
  recipes/ezc3d/all/conandata.yml
  recipes/ezc3d/config.yml
Labels: Bump version

#21051 zbar: bump pkgconf
  recipes/zbar/all/conanfile.py
Labels: Bump dependencies

#21087 harfbuzz: add version 8.3.0
  recipes/harfbuzz/all/conandata.yml
  recipes/harfbuzz/config.yml
Labels: Bump version

#21015 Upgrade SDL 'requires' in sdl_ttf
  recipes/sdl_ttf/all/conanfile.py
Labels: Bump dependencies

#21027 commata: add version 0.2.6-bug1
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#21050 linter: fix name detection
  linter/check_package_name.py
Labels: GitHub config

#21078 wil: add version 1.0.231028.1
  recipes/wil/all/conandata.yml
  recipes/wil/config.yml
Labels: Bump version

#21089 libdc1394: bump pkgconf
  recipes/libdc1394/all/conanfile.py
Labels: Bump dependencies

#21091 mozjpeg/all: bump deps
  recipes/mozjpeg/all/conanfile.py
Labels: Bump dependencies

#21096 very-simple-smtps/all: bump deps
  recipes/very-simple-smtps/all/conanfile.py
  recipes/very-simple-smtps/all/test_package/conanfile.py
Labels: Bump dependencies

#21099 elfutils: bump deps
  recipes/elfutils/all/conanfile.py
Labels: Bump dependencies

#21101 cpr: update libcurl/8.4.0
  recipes/cpr/all/conanfile.py
Labels: Bump dependencies

#21104 minizip-ng: add version 4.0.3
  recipes/minizip-ng/all/conandata.yml
  recipes/minizip-ng/config.yml
Labels: Bump version

#21105 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21117 libsecret/all: bump deps
  recipes/libsecret/all/conanfile.py
Labels: Bump dependencies

#21118 libnetfilter queue/all: bump deps
  recipes/libnetfilter_queue/all/conanfile.py
Labels: Bump dependencies

#21121 avahi/all: bump deps
  recipes/avahi/all/conanfile.py
Labels: Bump dependencies

#21122 libverto/all: bump deps
  recipes/libverto/all/conanfile.py
Labels: Bump dependencies

#21124 libxshmfence/all: bump deps
  recipes/libxshmfence/all/conanfile.py
Labels: Bump dependencies

#21128 coin-osi: bump deps
  recipes/coin-osi/all/test_v1_package/conanfile.py
Labels: Bump dependencies

#21120 libnice/all:bump deps
  recipes/libnice/all/conanfile.py
Labels: Bump dependencies

#21129 sdbus-cpp: bump deps
  recipes/sdbus-cpp/all/test_v1_pkgconf/conanfile.py
Labels: Bump dependencies

#21125 pupnp/all: bump deps
  recipes/pupnp/all/conanfile.py
Labels: Bump dependencies

#21106 ffmpeg: Add version 6.0.1
  recipes/ffmpeg/all/conandata.yml
  recipes/ffmpeg/config.yml
Labels: Bump version

#21114 keychain/all: bump deps
  recipes/keychain/all/conanfile.py
Labels: Bump dependencies

#21136 cpr: add version 1.10.5
  recipes/cpr/all/conandata.yml
  recipes/cpr/config.yml
Labels: Bump version

#21134 c4core: update fast_float/5.3.0
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#20849 thrust: bump onetbb
  recipes/thrust/all/conanfile.py
Labels: Bump dependencies

#21143 ffmpeg: added 6.1 version
  recipes/ffmpeg/all/conandata.yml
  recipes/ffmpeg/config.yml
Labels: Bump version

#21155 ssp: update fast_float/5.3.0
  recipes/ssp/all/conanfile.py
Labels: Bump dependencies

#21154 dacap-clip: add version 1.7
  recipes/dacap-clip/all/conandata.yml
  recipes/dacap-clip/config.yml
Labels: Bump version

#21156 c-ares: add version 1.22.0
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#21133 scnlib: update fast_float/5.3.0
  recipes/scnlib/all/conanfile.py
Labels: Bump dependencies

#21166 Remove missing users from authorized_users.yml
  .c3i/authorized_users.yml
Labels: C3I config

#21160 fast-cdr: add version 2.1.0
  recipes/fast-cdr/all/conandata.yml
  recipes/fast-cdr/config.yml
Labels: Bump version

#21168 glaze: add version 1.6.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#21171 iowow: add version 1.4.17
  recipes/iowow/all/conandata.yml
  recipes/iowow/config.yml
Labels: Bump version

#21172 magic_enum: add version 0.9.5
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version

#21169 coin-utils: add v2.11.10
  recipes/coin-utils/all/conandata.yml
  recipes/coin-utils/config.yml
Labels: Bump version

#21175 cityhash: add version 1.0.1
  recipes/cityhash/all/conandata.yml
  recipes/cityhash/config.yml
Labels: Bump version

#21187 wavelet_buffer/all: bump deps
  recipes/wavelet_buffer/all/conanfile.py
Labels: Bump dependencies

#21192 certify/all: bump deps
  recipes/certify/all/conanfile.py
Labels: Bump dependencies

#21203 soci: bump sqlite3
  recipes/soci/all/conanfile.py
Labels: Bump dependencies

#21205 libwebsockets: bump deps
  recipes/libwebsockets/all/conanfile.py
Labels: Bump dependencies

#21206 sqlitecpp: bump sqlite3
  recipes/sqlitecpp/all/conanfile.py
Labels: Bump dependencies

#21211 samurai: add version 0.9.0
  recipes/samurai/all/conandata.yml
  recipes/samurai/config.yml
Labels: Bump version

#21210 mcap: add version 1.3.0
  recipes/mcap/all/conandata.yml
  recipes/mcap/config.yml
Labels: Bump version

#21212 simdutf: add version 4.0.4
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#21214 [uncrustify] Add version 0.78.0
  recipes/uncrustify/all/conandata.yml
  recipes/uncrustify/config.yml
Labels: Bump version

#21215 shield: add version 0.5
  recipes/shield/all/conandata.yml
  recipes/shield/config.yml
Labels: Bump version

#21216 hictk: update dependencies
  recipes/hictk/all/conanfile.py
Labels: Bump dependencies

#21201 perfetto: Bump version: 39.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#21224 rtmidi: bump libalsa
  recipes/rtmidi/all/conanfile.py
Labels: Bump dependencies

#21225 openal-soft: bump libalsa
  recipes/openal-soft/all/conanfile.py
Labels: Bump dependencies

#21232 s2n: add version 1.3.56
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#21234 fontconfig: bump dependencies
  recipes/fontconfig/all/conanfile.py
  recipes/fontconfig/meson/conanfile.py
Labels: Bump dependencies

#21243 stringzilla: add version 2.0.3
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#21236 harfbuzz: bump dependencies
  recipes/harfbuzz/all/conanfile.py
Labels: Bump dependencies

#21237 proj: bump sqlite3 dependency
  recipes/proj/all/conanfile.py
Labels: Bump dependencies

#21244 miniaudio: add version 0.11.21
  recipes/miniaudio/all/conandata.yml
  recipes/miniaudio/config.yml
Labels: Bump version

#21251 aggeom-agg: update freetype/2.13.2
  recipes/aggeom-agg/all/conanfile.py
Labels: Bump dependencies

#21250 pdfuim: update freetype/2.13.2
  recipes/pdfium/all/conanfile.py
Labels: Bump dependencies

#21254 sfml: update freetype/2.13.2
  recipes/sfml/all/conanfile.py
Labels: Bump dependencies

#21240 wayland: bump dependencies
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#21258 meson 1.3.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#21248 Add kammce as reviewer for libhal recipe
  .github/workflows/alert-community.yml
Labels: GitHub config

#21269 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#21266 wayland/all: bump deps
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#21265 xkbcommon: bump libxml2
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#21287 cairo: update dependencies
  recipes/cairo/meson/conanfile.py
Labels: Bump dependencies

#21289 ada: add version 2.7.4
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#21294 c-ares: add version 1.22.1
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#21300 [emsdk] bump to 3.1.49
  recipes/emsdk/all/conandata.yml
  recipes/emsdk/config.yml
Labels: Bump version

#21301 ktx: update lodepng
  recipes/ktx/all/conanfile.py
Labels: Bump dependencies

#21307 implot: update imgui/1.90
  recipes/implot/all/conanfile.py
Labels: Bump dependencies

#21319 [config] Add parallel strategy for BuildSingleReference
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#21218 aws-lambda-cpp: add version 0.2.10
  recipes/aws-lambda-cpp/all/conandata.yml
  recipes/aws-lambda-cpp/config.yml
Labels: Bump version

#21219 aws-c-event-stream: add version 0.3.2
  recipes/aws-c-event-stream/all/conandata.yml
  recipes/aws-c-event-stream/config.yml
Labels: Bump version

#21317 sqlite3: add version 3.44.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#21318 glaze: add version 1.6.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#21220 libavif: add version 1.0.2
  recipes/libavif/all/conandata.yml
  recipes/libavif/config.yml
Labels: Bump version

#21329 pfr: Bump to v2.2.0
  recipes/pfr/all/conandata.yml
  recipes/pfr/config.yml
Labels: Bump version

#21330 xz_utils: add 5.4.5
  recipes/xz_utils/all/conandata.yml
  recipes/xz_utils/config.yml
Labels: Bump version

#21335 metall: add version 0.27
  recipes/metall/all/conandata.yml
  recipes/metall/config.yml
Labels: Bump version

#21348 [docs] Use official windows PS for sha256sum
  docs/adding_packages/conandata_yml_format.md
Labels: Docs

#21356 glaze: add version 1.7.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#21359 sqlite3: add version 3.44.2
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#21361 simdutf: add version 4.0.5
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version
