Repository conan-io/conan-center-index, pull requests merged in 2024-06, with the labels that each got.

#24195 wiringpi: add version 3.6
  recipes/wiringpi/all/conandata.yml
  recipes/wiringpi/config.yml
Labels: Bump version

#24196 ipaddress: add version 1.1.0
  recipes/ipaddress/all/conandata.yml
  recipes/ipaddress/config.yml
Labels: Bump version

#24178 etl: add version 20.38.16
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#24190 minizip-ng: add version 4.0.6
  recipes/minizip-ng/all/conandata.yml
  recipes/minizip-ng/config.yml
Labels: Bump version

#24198 thorvg: add version 0.13.6
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24184 pdf-writer: add version 4.6.4
  recipes/pdf-writer/all/conandata.yml
  recipes/pdf-writer/config.yml
Labels: Bump version

#24212 cpp-dump: add version 0.6.0
  recipes/cpp-dump/all/conandata.yml
  recipes/cpp-dump/config.yml
Labels: Bump version

#24213 libxml2: add latest releases libxml2/2.11.8 libxml2/2.12.7 (changes for CVE-2024-34459)
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#24225 sfl: add version 1.6.0
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#24226 mongo-c-driver: add version 1.27.2
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#23852 ouster_sdk: add version 0.11.0
  recipes/ouster_sdk/all/conandata.yml
  recipes/ouster_sdk/config.yml
Labels: Bump version

#19411 Kdbindings fix
  recipes/kdbindings/all/conanfile.py
Labels: bug

#23656 kdbindings: add version 1.0.5
  recipes/kdbindings/all/conandata.yml
  recipes/kdbindings/config.yml
Labels: Bump version

#24254 thorvg: add version 0.13.7
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#23221 mold: add version 2.31.0
  recipes/mold/all/conandata.yml
  recipes/mold/config.yml
Labels: Bump version

#24259 expected-lite: add version 0.8.0
  recipes/expected-lite/all/conandata.yml
  recipes/expected-lite/config.yml
Labels: Bump version

#24260 tree-sitter: add version 0.22.6
  recipes/tree-sitter/all/conandata.yml
  recipes/tree-sitter/config.yml
Labels: Bump version

#24069 shield: add version 0.6
  recipes/shield/all/conandata.yml
  recipes/shield/config.yml
Labels: Bump version

#24193 qt: use upstream package folder architecture
  recipes/qt/5.x.x/conanfile.py
  recipes/qt/5.x.x/test_package/conanfile.py
  recipes/qt/5.x.x/test_v1_package/conanfile.py
  recipes/qt/6.x.x/conanfile.py
  recipes/qt/6.x.x/test_package/conanfile.py
  recipes/qt/6.x.x/test_v1_package/conanfile.py
Labels: Unexpected Error, Failed

#24284 Bumped fmt to latest version avoiding conflicts
  recipes/mp-units/0.8.0/conanfile.py
  recipes/mp-units/2.0.0/conanfile.py
Labels: Bump dependencies

#24286 remove objectbox, not open source
  recipes/objectbox/all/conandata.yml
  recipes/objectbox/all/conanfile.py
  recipes/objectbox/all/patches/0.17.0-0001-fix-cmake.patch
  recipes/objectbox/all/patches/0.21.0-0001-fix-cmake.patch
  recipes/objectbox/all/test_package/CMakeLists.txt
  recipes/objectbox/all/test_package/conanfile.py
  recipes/objectbox/all/test_package/test_package.c
  recipes/objectbox/all/test_v1_package/CMakeLists.txt
  recipes/objectbox/all/test_v1_package/conanfile.py
  recipes/objectbox/config.yml
Labels: Failed

#24257 Add libuv to list of supported version range libraries
  docs/adding_packages/dependencies.md
Labels: Docs

#24263 libpqxx: add version 7.9.1
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#24266 glog: add version 0.7.1
  recipes/glog/all/conandata.yml
  recipes/glog/config.yml
Labels: Bump version

#24269 reflect: add version 0.11.0
  recipes/reflect-cpp/all/conandata.yml
  recipes/reflect-cpp/config.yml
Labels: Bump version

#24270 flecs: add 3.2.11
  recipes/flecs/all/conandata.yml
  recipes/flecs/config.yml
Labels: Bump version

#20438 cmake/3.x.x: bump OpenSSL
  recipes/cmake/3.x.x/conanfile.py
Labels: Service Under Maintenance

#24280 log4cxx: use version range for qt5
  recipes/log4cxx/all/conanfile.py
Labels: Bump dependencies

#24283 mocknetworkaccessmanager: use version range for qt
  recipes/mocknetworkaccessmanager/all/conanfile.py
Labels: Bump dependencies

#24281 qarchive: use version range for qt 5.15
  recipes/qarchive/all/conanfile.py
Labels: Bump dependencies

#24296 cpp-httplib: add version 0.16.0
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#24297 glaze: add version 2.8.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24307 libftp: add version 0.5.1
  recipes/libftp/all/conandata.yml
  recipes/libftp/config.yml
Labels: Bump version

#24309 glaze: add version 2.8.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24311 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub config

#24300 octo-logger-cpp: bumped fmt dependency
  recipes/octo-keygen-cpp/all/conanfile.py
Labels: Bump dependencies

#24318 glaze: add version 2.8.4
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24316 jsoncons: add version 0.176.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#24323 pcre2: add version 10.44
  recipes/pcre2/all/conandata.yml
  recipes/pcre2/config.yml
Labels: Bump version

#24338 luau: add version 0.630
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#24340 xbyak: add version 7.07
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#24347 Update to SQLite3 Multiple Ciphers 1.8.6
  recipes/sqlite3mc/all/conandata.yml
  recipes/sqlite3mc/config.yml
Labels: Bump version

#24339 thorvg: add version 0.13.8, fix homepage
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24355 rocksdb: add version 9.2.1
  recipes/rocksdb/all/conandata.yml
  recipes/rocksdb/config.yml
Labels: Bump version

#24356 mathter: add version 1.1.1
  recipes/mathter/all/conandata.yml
  recipes/mathter/config.yml
Labels: Bump version

#24326 [config] Enable github status checks for conan v2 profiles
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#24370 sdl: add version 2.30.4
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#24372 quill: add version 4.4.1
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#24374 [simd] Large container
  .c3i/config_v1.yml
Labels: C3I config

#23626 xmlsec: use version range for libxml2
  recipes/xmlsec/all/conanfile.py
Labels: Bump dependencies

#24388 Add ErniGH as team reviewer in config
  .c3i/reviewers.yml
Labels: C3I config

#24402 c-blosc2: add version 2.15.0
  recipes/c-blosc2/all/conandata.yml
  recipes/c-blosc2/config.yml
Labels: Bump version

#24378 [config] Relax yaml linters (valid yaml is valid)
  .c3i/config_v1.yml
  linter/conandata_yaml_linter.py
  linter/yamllint_rules.yml
Labels: GitHub config, C3I config

#20857 Fix typo and grammar errors
  CONTRIBUTING.md
  README.md
  docs/consuming_recipes.md
  docs/developing_recipes_locally.md
Labels: Docs

#24410 clove-unit: add version 2.4.5
  recipes/clove-unit/all/conandata.yml
  recipes/clove-unit/config.yml
Labels: Bump version

#24415 cargs: add version 1.2.0
  recipes/cargs/all/conandata.yml
  recipes/cargs/config.yml
Labels: Bump version

#24416 uwebsockets: add version 20.63.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#24291 Etl 20.38.17
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#24418 sfl: add version 1.7.0
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#24419 cpp-sort: add version 1.16.0
  recipes/cpp-sort/all/conandata.yml
  recipes/cpp-sort/config.yml
Labels: Bump version

#24424 gcem: Add version 1.18.0
  recipes/gcem/all/conandata.yml
  recipes/gcem/config.yml
Labels: Bump version

#24420 libdisplay-info: add version 0.2.0
  recipes/libdisplay-info/all/conandata.yml
  recipes/libdisplay-info/config.yml
Labels: Bump version

#24421 rapidcsv: add version 8.83
  recipes/rapidcsv/all/conandata.yml
  recipes/rapidcsv/config.yml
Labels: Bump version

#24422 s2n: add version 1.4.16
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#24433 nsync: add version 1.29.1
  recipes/nsync/all/conandata.yml
  recipes/nsync/config.yml
Labels: Bump version

#24439 lua: add version 5.4.7
  recipes/lua/all/conandata.yml
  recipes/lua/config.yml
Labels: Bump version

#24454 mold: add version 2.32.1
  recipes/mold/all/conandata.yml
  recipes/mold/config.yml
Labels: Bump version

#24446 quill: add version 4.5.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#24461 mongo-c-driver: add version 1.27.3
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#24474 magic_enum: add version 0.9.6
  recipes/magic_enum/all/conandata.yml
  recipes/magic_enum/config.yml
Labels: Bump version
