Repository conan-io/conan-center-index, pull requests merged in 2024-11, with the labels that each got.

#25660 opencolorio: Bump lcms requirement to 2.16
  recipes/opencolorio/all/conanfile.py
Labels: Bump dependencies

#25812 msgpack-cxx: add version 7.0.0
  recipes/msgpack-cxx/all/conandata.yml
  recipes/msgpack-cxx/config.yml
Labels: Bump version

#25316 daw_json_link: add version 3.28.3
  recipes/daw_json_link/all/conandata.yml
  recipes/daw_json_link/config.yml
Labels: Failed

#25813 msgpack-c: add version 6.1.0
  recipes/msgpack-c/all/conandata.yml
  recipes/msgpack-c/config.yml
Labels: Bump version

#23131 libsixel: use libpng version range, bump deps
  recipes/libsixel/all/conanfile.py
Labels: Waiting for CI

#25816 lunasvg: add version 3.0.1
  recipes/lunasvg/all/conandata.yml
  recipes/lunasvg/config.yml
Labels: Bump version

#25801 thorvg: add version 0.15.3
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#25791 rocksdb: add version 9.7.4
  recipes/rocksdb/all/conandata.yml
  recipes/rocksdb/config.yml
Labels: Bump version

#25785 xbyak: add version 7.21
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#25172 Bump zstd for libdwarf
  recipes/libdwarf/all/conanfile.py
Labels: Waiting for CI

#25715 libxlsxwriter: add new version 1.1.9
  recipes/libxlsxwriter/all/conandata.yml
  recipes/libxlsxwriter/all/conanfile.py
  recipes/libxlsxwriter/all/patches/1.1.9-0001-fix-cmake.patch
  recipes/libxlsxwriter/config.yml
Labels: Failed

#25579 mongo-c-driver: add version 1.28.1
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#25806 sail: Enable jpegxl
  recipes/sail/all/conanfile.py
Labels: Failed

#25804 s2n: add version 1.5.7
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#25814 scnlib: add version 4.0.1, 3.0.2
  recipes/scnlib/all/conandata.yml
  recipes/scnlib/all/conanfile.py
  recipes/scnlib/all/patches/1.0-0001-install-dll-windows.patch
  recipes/scnlib/all/patches/1.0-0002-remove-header-only-target.patch
  recipes/scnlib/all/patches/1.0-0003-use-conan-package.patch
  recipes/scnlib/all/patches/1.1.2-0001-install-dll-windows.patch
  recipes/scnlib/all/patches/1.1.2-0002-remove-header-only-target.patch
  recipes/scnlib/all/patches/1.1.2-0003-fix-link-keyword.patch
  recipes/scnlib/all/patches/1.1.3-0001-install-dll-windows.patch
  recipes/scnlib/all/patches/1.1.3-0002-remove-header-only-target.patch
  recipes/scnlib/all/patches/1.1.3-0003-fix-link-keyword.patch
  recipes/scnlib/all/patches/2.0.0-0001-remove-re2-version.patch
  recipes/scnlib/config.yml
Labels: Bump version

#25789 Boost: correct address model for "s390x" architecture
  recipes/boost/all/conanfile.py
Labels: User-approval pending

#21417 byte-lite: add package_type
  recipes/byte-lite/all/conanfile.py
  recipes/byte-lite/all/test_package/test_package.cpp
  recipes/byte-lite/all/test_v1_package/CMakeLists.txt
  recipes/byte-lite/all/test_v1_package/conanfile.py
Labels: Failed

#25783 libheif: add version 1.19.0
  recipes/libheif/all/conandata.yml
  recipes/libheif/all/conanfile.py
  recipes/libheif/all/test_package/CMakeLists.txt
  recipes/libheif/config.yml
Labels: Failed

#25419 cryptopp: Add use_openmp option
  recipes/cryptopp/all/conandata.yml
  recipes/cryptopp/all/conanfile.py
  recipes/cryptopp/all/test_package/test_package.cpp
  recipes/cryptopp/config.yml
Labels: User-approval pending

#24217 avcpp: add version 2.4.0
  recipes/avcpp/all/conandata.yml
  recipes/avcpp/config.yml
Labels: Failed, Bump version

#22120 mbtis-lngs: update fmt/10.2.0
  recipes/mbits-lngs/all/conanfile.py
Labels: Waiting for CI

#25669 leptonica: add new version 1.85.0
  recipes/leptonica/all/conandata.yml
  recipes/leptonica/all/conanfile.py
  recipes/leptonica/config.yml
Labels: Failed

#23138 freeimage: use libpng version range, bump deps
  recipes/freeimage/all/conanfile.py
Labels: Waiting for CI

#22828 New package: libq
  recipes/libq/all/conandata.yml
  recipes/libq/all/conanfile.py
  recipes/libq/all/patches/0001-cmake-remove-hardcoded-flags.patch
  recipes/libq/all/test_package/CMakeLists.txt
  recipes/libq/all/test_package/conanfile.py
  recipes/libq/all/test_package/test_package.cpp
  recipes/libq/config.yml
Labels: Failed

#23122 openimageio: use libpng version range
  recipes/openimageio/all/conanfile.py
Labels: Waiting for CI

#25520 glaze: add version 4.0.1, 3.6.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22516 Bump timsort to 3.0.0
  recipes/timsort/all/conandata.yml
  recipes/timsort/all/conanfile.py
  recipes/timsort/all/test_package/CMakeLists.txt
  recipes/timsort/all/test_v1_package/CMakeLists.txt
  recipes/timsort/all/test_v1_package/conanfile.py
  recipes/timsort/config.yml
Labels: Failed

#25720 DevIL: add new recipe
  recipes/devil/all/conandata.yml
  recipes/devil/all/conanfile.py
  recipes/devil/all/patches/1.8.0-avoid-methoddef-dllimport-error.patch
  recipes/devil/all/patches/1.8.0-install-ilut-config-h.patch
  recipes/devil/all/patches/1.8.0-jp2_fix.patch
  recipes/devil/all/patches/1.8.0-jpeg_fix.patch
  recipes/devil/all/patches/1.8.0-remove_register_keyword.patch
  recipes/devil/all/test_package/CMakeLists.txt
  recipes/devil/all/test_package/conanfile.py
  recipes/devil/all/test_package/test_package.cpp
  recipes/devil/config.yml
Labels: Failed

#23217 bump libtiff dependencies
  recipes/libtiff/all/conanfile.py
Labels: Waiting for CI

#25038 libsvtav1: add new version 2.2.1
  recipes/libsvtav1/all/conandata.yml
  recipes/libsvtav1/all/conanfile.py
  recipes/libsvtav1/config.yml
Labels: Failed

#25335 json_struct receipt
  recipes/json_struct/all/conandata.yml
  recipes/json_struct/all/conanfile.py
  recipes/json_struct/all/test_package/CMakeLists.txt
  recipes/json_struct/all/test_package/conanfile.py
  recipes/json_struct/all/test_package/main.cpp
  recipes/json_struct/config.yml
Labels: Failed

#23030 glib: Bump libmount to 2.39.2 to avoid conflicts with libsystemd
  recipes/glib/all/conanfile.py
  recipes/glib/all/test_v1_package/CMakeLists.txt
  recipes/glib/all/test_v1_package/conanfile.py
Labels: Bump dependencies
