Repository conan-io/conan-center-index, pull requests merged in 2024-02, with the labels that each got.

#22244 openvino: added 2023.3.0 version
  recipes/openvino/all/conandata.yml
  recipes/openvino/all/dependencies/dependencies-2023.3.0.yml
  recipes/openvino/config.yml
Labels: Unexpected Error

#22605 [config] Add bump deps entry
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#22622 Upgrading C++ DataFrame to version 3.0.0
  recipes/dataframe/all/conandata.yml
  recipes/dataframe/config.yml
Labels: Bump version

#22631 libtiff: bump libjpeg-turbo
  recipes/libtiff/all/conanfile.py
Labels: Bump dependencies

#22626 jsoncons: add version 0.173.3
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#22623 thrift: bump boost
  recipes/thrift/all/conanfile.py
Labels: Bump dependencies

#22630 freetype: bump libpng
  recipes/freetype/all/conanfile.py
Labels: Bump dependencies

#22642 restinio: add version `0.7.2`
  recipes/restinio/config.yml
  recipes/restinio/v0.7/conandata.yml
Labels: Bump version

#22640 yder: update orcania/2.3.3
  recipes/yder/all/conanfile.py
Labels: Bump dependencies

#22648 cpp-httplib: add version 0.15.2
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#22651 yder: add version 1.4.20
  recipes/yder/all/conandata.yml
  recipes/yder/config.yml
Labels: Bump version

#22656 nameof: add version 0.10.4
  recipes/nameof/all/conandata.yml
  recipes/nameof/config.yml
Labels: Bump version

#22660 ssp: update fast_float/6.1.0
  recipes/ssp/all/conanfile.py
Labels: Bump dependencies

#22594 stale: migrate from bot to action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: GitHub config

#22664 actions: bump peter-evans/create-pull-request
  .github/workflows/on-push-do-doco.yml
Labels: GitHub config

#22685 stale bot: fix permissions and line endings
  .github/workflows/stale.yml
Labels: GitHub config

#22607 Bump/graphene/all
  recipes/graphene/all/conanfile.py
Labels: Bump dependencies

#22678 cli11: add version 2.4.0
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#22686 cpp-httplib: add version 0.15.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#22683 As reported in issue #22654, qt depends on freetype/2.13.2 which depe…
  recipes/qt/6.x.x/conanfile.py
Labels: Bump dependencies

#22552 aws-c-http: update dependencies
  recipes/aws-c-http/all/conanfile.py
Labels: Bump dependencies

#22699 Add cppcheck 2.13.3
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#22668 [config] Add waitaing list for users in authorized users
  .c3i/authorized_users.yml
  .c3i/config_v1.yml
  .c3i/config_v2.yml
  .c3i/waitlist_users.yml
  docs/faqs.md
Labels: Docs, C3I config

#22705 [c-blosc2] Revert checksum
  recipes/c-blosc2/all/conandata.yml
  recipes/c-blosc2/all/conanfile.py
Labels: checksum_mismatch

#22694 [expat] Add expat version 2.6.0
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#22722 cli11: add version 2.4.1
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#22726 7bitdi: add version 2.1.0
  recipes/7bitdi/all/conandata.yml
  recipes/7bitdi/config.yml
Labels: Bump version

#22721 glaze: add version 2.0.7
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22725 wise_enum: add version 3.1.0
  recipes/wise_enum/all/conandata.yml
  recipes/wise_enum/config.yml
Labels: Bump version

#22717 [openapi-generator] Add version 7.3.0
  recipes/openapi-generator/all/conandata.yml
  recipes/openapi-generator/config.yml
Labels: Bump version

#22703 Add gc/8.2.6 recipe
  recipes/bdwgc/all/conandata.yml
  recipes/bdwgc/all/patches/update-cmake-8_2_6.patch
  recipes/bdwgc/config.yml
Labels: Bump version

#22728 stale: process older PRs first
  .github/workflows/stale.yml
Labels: GitHub config

#22736 poco: add version 1.13.1
  recipes/poco/all/conandata.yml
  recipes/poco/config.yml
Labels: Bump version

#22742 libnfs: add version 5.0.3
  recipes/libnfs/all/conandata.yml
  recipes/libnfs/config.yml
Labels: Bump version

#22745 nanomsg: add version 1.2.1
  recipes/nanomsg/all/conandata.yml
  recipes/nanomsg/config.yml
Labels: Bump version

#22741 glaze: add version 2.0.9
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22756 leveldb: update snappy/1.1.10
  recipes/leveldb/all/conanfile.py
Labels: Bump dependencies

#22709 aws-c-auth: update dependencies
  recipes/aws-c-auth/all/conanfile.py
Labels: Bump dependencies

#22760 glaze: add version 2.1.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22716 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22762 md4qt: bump version to 2.7.2
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22767 Update to h5pp/1.11.2
  recipes/h5pp/all/conandata.yml
  recipes/h5pp/config.yml
Labels: Bump version

#22773 scnlib: add version 2.0.1
  recipes/scnlib/all/conandata.yml
  recipes/scnlib/config.yml
Labels: Bump version

#22774 cxxopts: add version 3.2.0
  recipes/cxxopts/all/conandata.yml
  recipes/cxxopts/config.yml
Labels: Bump version

#22783 ccache: add version 4.9.1
  recipes/ccache/all/conandata.yml
  recipes/ccache/config.yml
Labels: Bump version

#22798 ssp: add version 1.6.2
  recipes/ssp/all/conandata.yml
  recipes/ssp/config.yml
Labels: Bump version

#22800 rtm: add version 2.3.0
  recipes/rtm/all/conandata.yml
  recipes/rtm/config.yml
Labels: Bump version

#22777 aws-c-mqtt: update dependencies
  recipes/aws-c-mqtt/all/conanfile.py
Labels: Bump dependencies

#22813 emio: add version 0.7.0
  recipes/emio/all/conandata.yml
  recipes/emio/all/conanfile.py
  recipes/emio/config.yml
Labels: Bump version

#22799 sfl: add version 1.2.4
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#22825 daw_header_libraries: add version 2.101.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#22814 libpqxx: add version 7.9.0
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#22815 highway: add version 1.1.0
  recipes/highway/all/conandata.yml
  recipes/highway/config.yml
Labels: Bump version

#22826 scnlib: add version 2.0.2
  recipes/scnlib/all/conandata.yml
  recipes/scnlib/config.yml
Labels: Bump version

#22812 [nmos-cpp] Bump dependencies to match upstream
  recipes/nmos-cpp/all/conanfile.py
Labels: Bump dependencies

#22836 botan: add version 2.19.4
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#22845 perfetto: add version 42.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#22846 functionalplus: add version 0.2.23
  recipes/functionalplus/all/conandata.yml
  recipes/functionalplus/config.yml
Labels: Bump version

#22858 meson: add version 1.3.2
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#22859 md4qt: bump version to 2.7.4
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22868 libhal: add version 2.2.0
  recipes/libhal/all/conandata.yml
  recipes/libhal/config.yml
Labels: Bump version

#22870 [config] Fix validate infrastructure entry name
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#22893 hictk: add v0.0.9
  recipes/hictk/all/conandata.yml
  recipes/hictk/config.yml
Labels: Bump version

#22880 glfw: add version 3.4
  recipes/glfw/all/conandata.yml
  recipes/glfw/config.yml
Labels: Bump version

#22882 c-ares: add version 1.27.0
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#22884 libpng: add version 1.6.43
  recipes/libpng/all/conandata.yml
  recipes/libpng/config.yml
Labels: Bump version

#22879 simdjson: add version 3.7.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#22902 libglvnd: Bump build requirements to support Python 3.12
  recipes/libglvnd/all/conanfile.py
Labels: Bump dependencies

#22888 poco: add version 1.13.2
  recipes/poco/all/conandata.yml
  recipes/poco/config.yml
Labels: Bump version

#22915 OpenEXR add version 3.2.2
  recipes/openexr/3.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#21950 aws-c-s3: add version 0.4.5
  recipes/aws-c-s3/all/conandata.yml
  recipes/aws-c-s3/config.yml
Labels: Bump version

#22852 nmos-cpp/cci.20240223: new release
  recipes/nmos-cpp/all/conandata.yml
  recipes/nmos-cpp/all/conanfile.py
  recipes/nmos-cpp/config.yml
Labels: Bump version

#22914 c4core: update fast_float/6.1.0
  recipes/c4core/all/conanfile.py
Labels: Bump dependencies

#22918 Add me for community alerts on packages I'm working on
  .github/workflows/alert-community.yml
Labels: GitHub config
