Repository conan-io/conan-center-index, pull requests merged in 2024-03, with the labels that each got.

#22929 qt: Bump expat to 2.6.0 to avoid conflicts in xkbcommon and wayland
  recipes/qt/5.x.x/conanfile.py
  recipes/qt/6.x.x/conanfile.py
Labels: Failed

#22949 Update alert-community.yml
  .github/workflows/alert-community.yml
Labels: GitHub config

#22935 ssp: add version 1.7.2
  recipes/ssp/all/conandata.yml
  recipes/ssp/config.yml
Labels: Bump version

#22940 glaze: add version 2.1.9
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22948 Bump minizip to 1.3.1
  recipes/minizip/all/conandata.yml
  recipes/minizip/config.yml
Labels: Bump version

#22963 expat: add version 2.6.1
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#22916 Add OpenColorIO version 2.3.2
  recipes/opencolorio/all/conandata.yml
  recipes/opencolorio/config.yml
Labels: Bump version

#22978 [config] Remove Conan v2 migration check as mandatory
  .c3i/config_v1.yml
Labels: C3I config

#22979 linter: handle test_requires
  linter/transform_conanfile.py
Labels: GitHub config

#22975 hictk: add v0.0.10
  recipes/hictk/all/conandata.yml
  recipes/hictk/config.yml
Labels: Bump version

#22988 openjpeg: add version 2.5.2
  recipes/openjpeg/all/conandata.yml
  recipes/openjpeg/config.yml
Labels: Bump version

#22972 md4qt: bump version to 2.8.0
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22992 libxml2: add 2.12.5 and 2.11.7
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#23002 perfetto: add version 43.1
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#22919 xkbcommon: Bump wayland-protocols and Meson
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#22922 glfw: Bump wayland-protocols
  recipes/glfw/all/conanfile.py
Labels: Bump dependencies

#23016 Update range list to add libpng (And mention libxml)
  docs/adding_packages/dependencies.md
Labels: Docs

#23006 tensorflow-lite: resolve conflicts
  recipes/tensorflow-lite/all/conanfile.py
Labels: Bump dependencies

#22895 stale workflow: don't remove stale label twice
  .github/workflows/stale.yml
Labels: GitHub config

#23022 neargye-semver: add version 0.3.1
  recipes/neargye-semver/all/conandata.yml
  recipes/neargye-semver/config.yml
Labels: Bump version

#23027 xbyak: add version 7.06
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#23041 OpenEXR: Add 3.2.3
  recipes/openexr/3.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#23032 luau: add version 0.615
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#23026 glaze: add version 2.2.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23035 ada: add version 2.7.7
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#23046 add orc/2.0.0
  recipes/orc/all/conandata.yml
  recipes/orc/config.yml
Labels: Bump version

#23049 libavif: add version 1.0.4
  recipes/libavif/all/conandata.yml
  recipes/libavif/config.yml
Labels: Bump version

#23061 tree-sitter: add version 0.22.1
  recipes/tree-sitter/all/conandata.yml
  recipes/tree-sitter/config.yml
Labels: Bump version

#23064 uwebsockets: add version 20.62.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#23067 xz_utils: add version 5.6.1
  recipes/xz_utils/cmake/conandata.yml
  recipes/xz_utils/config.yml
Labels: Bump version

#23081 [docs] Changelog March 13th, 2024
  docs/changelog.md
Labels: Docs

#23074 sqlite3: add version 3.45.2
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#23121 sfl: add version 1.3.0
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#23161 flatbuffers: add version 24.3.7
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#23107 libvips: add v8.15.2
  recipes/libvips/all/conandata.yml
  recipes/libvips/config.yml
Labels: Bump version

#23063 glaze: add version 2.3.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23103 simde: add version 0.8.0
  recipes/simde/all/conandata.yml
  recipes/simde/config.yml
Labels: Bump version

#23116 unity: add version 2.6.0
  recipes/unity/all/conandata.yml
  recipes/unity/config.yml
Labels: Bump version

#23167 quilll: add version 3.7.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#23159 dnet: add version 1.18.0
  recipes/dnet/all/conandata.yml
  recipes/dnet/config.yml
Labels: Bump version

#23160 fast_float: add version 6.1.1
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#23169 simdutf: add version 5.0.0
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#23183 [changelog] Deployment March 20, 2023
  docs/changelog.md
Labels: Docs

#23177 meson: add version 1.4.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#23174 Add tree-gen 1.0.7.
  recipes/tree-gen/all/conandata.yml
  recipes/tree-gen/config.yml
Labels: Bump version

#23176 tsl-robin-map: add version 1.2.2
  recipes/tsl-robin-map/all/conandata.yml
  recipes/tsl-robin-map/config.yml
Labels: Bump version

#23190 glaze: add version 2.3.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23187 roaring: add version 3.0.0
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#23204 libunwind: Bump xz_utils to avoid a dependency conflict in cpython
  recipes/libunwind/all/conanfile.py
Labels: Bump dependencies

#22695 zint: use version range for libpng
  recipes/zint/all/conanfile.py
Labels: Bump dependencies

#23208 sfl: add version 1.3.1
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#22136 opencv: add version 4.9.0
  recipes/opencv/4.x/conandata.yml
  recipes/opencv/4.x/conanfile.py
  recipes/opencv/config.yml
Labels: look into

#22920 dbus: Bump expat and glib dependencies to minimize conflicts
  recipes/dbus/1.x.x/conanfile.py
Labels: Bump dependencies

#23211 glaze: add version 2.3.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#21448 [docs] Allow boost namespace for non official projects
  docs/faqs.md
Labels: Docs

#23284 cmake: add version `3.29.0`
  recipes/cmake/binary/conandata.yml
  recipes/cmake/config.yml
Labels: Bump version

#23239 Alembic: bump imath to 3.1.10 - Avoid conflict with Openvdb 11.0.0
  recipes/alembic/all/conanfile.py
Labels: Bump dependencies

#23264 [avahi] Bump expat and glib
  recipes/avahi/all/conanfile.py
Labels: Bump dependencies
