Repository conan-io/conan-center-index, pull requests merged in 2024-04, with the labels that each got.

#23290 Bump ReactivePlusPlus v2.1.1
  recipes/reactiveplusplus/all/conandata.yml
  recipes/reactiveplusplus/config.yml
Labels: Bump version

#23314 7bitdi: add version 3.0.0
  recipes/7bitdi/all/conandata.yml
  recipes/7bitdi/config.yml
Labels: Bump version

#23316 c-ares: add version 1.28.1
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#23178 z3: add version 4.13.0
  recipes/z3/all/conandata.yml
  recipes/z3/config.yml
Labels: Bump version

#23262 rapidcsv: add version 8.82
  recipes/rapidcsv/all/conandata.yml
  recipes/rapidcsv/config.yml
Labels: Bump version

#23283 glaze: add version 2.4.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23292 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#23298 cpp-peglib: add version 1.8.7
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#23299 pybind: add v2.12.0
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#23302 kuba-zip: add version 0.3.2
  recipes/kuba-zip/all/conandata.yml
  recipes/kuba-zip/config.yml
Labels: Bump version

#23324 commata: add version 0.2.9
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#23344 cpp-peglib: add version 1.8.8
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#23352 [config] Update conan versions to 2.2.2 and 1.63.0
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#23357 [docs] Update changelog 2024-04-03
  docs/changelog.md
Labels: Docs

#23225 octo-logger-cpp: add version 1.6.1
  recipes/octo-logger-cpp/all/conandata.yml
  recipes/octo-logger-cpp/config.yml
Labels: Bump version

#23345 sdl: add version 2.30.2
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#23355 [sentry-native] Bump 0.7.2 version
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#23348 OpenEXR: Add version 3.2.4
  recipes/openexr/3.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#23332 simdutf: add version 5.2.2
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#23354 vincentlaucsb-csv-parser: add version 2.2.0
  recipes/vincentlaucsb-csv-parser/all/conandata.yml
  recipes/vincentlaucsb-csv-parser/config.yml
Labels: Bump version

#23372 libnghttp2: add version 1.61.0
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#23377 poco: add version 1.13.3
  recipes/poco/all/conandata.yml
  recipes/poco/config.yml
Labels: Bump version

#23389 cista: add version 0.15
  recipes/cista/all/conandata.yml
  recipes/cista/config.yml
Labels: Bump version

#23408 poco: fix poco 1.13.3 sha256
  recipes/poco/all/conandata.yml
Labels: checksum_mismatch

#23399 Add community alert for mocknetworkaccessmanager and qtawesome
  .github/workflows/alert-community.yml
Labels: GitHub config

#23403 add mbits-utfconv/1.0.4
  recipes/mbits-utfconv/all/conandata.yml
  recipes/mbits-utfconv/config.yml
Labels: Bump version

#23406 7bitdi: add version 3.1.0
  recipes/7bitdi/all/conandata.yml
  recipes/7bitdi/config.yml
Labels: Bump version

#21648 libpq: add 15.5
  recipes/libpq/all/conandata.yml
  recipes/libpq/config.yml
Labels: Bump version

#23378 simdjson: add version 3.9.1
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#23423 rapidfuzz: add version 3.0.4
  recipes/rapidfuzz/all/conandata.yml
  recipes/rapidfuzz/config.yml
Labels: Bump version

#23424 opentelemetry-proto: add version 1.2.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#23425 asio: add version 1.30.1
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#23426 botan: add version 3.4.0
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#23430 [config] Update conan version to 1.64.0
  .c3i/config_v1.yml
Labels: C3I config

#23219 bshoshany-thread-pool: add version 4.1.0
  recipes/bshoshany-thread-pool/all/conandata.yml
  recipes/bshoshany-thread-pool/config.yml
Labels: Bump version

#23220 dice-template-library: add version 1.5.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#23457 flatbuffers: add version 24.3.25
  recipes/flatbuffers/all/conandata.yml
  recipes/flatbuffers/config.yml
Labels: Bump version

#23473 catch2: add version 3.5.4
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#23470 mcap: add version 1.4.0
  recipes/mcap/all/conandata.yml
  recipes/mcap/config.yml
Labels: Bump version

#23488 ada: add version 2.7.8
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#23581 sqlite3: add version 3.45.3
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#23522 fix template conan doesn't pass the linter
  docs/package_templates/autotools_package/all/conanfile.py
Labels: Docs

#23514 sdbus-cpp: security, bump expat
  recipes/sdbus-cpp/all/conanfile.py
Labels: Bump dependencies

#23515 wayland: security, bump deps
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#23504 gdcm: security, conflicts, bump deps
  recipes/gdcm/all/conanfile.py
Labels: Bump dependencies

#23511 cairo: security, bump expat
  recipes/cairo/meson/conanfile.py
Labels: Bump dependencies

#23184 libcurl: update to c-ares/1.27.0
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#23525 harfbuzz: Bump glib to 2.78.3 to avoid conflicts
  recipes/harfbuzz/all/conanfile.py
Labels: Bump dependencies

#23584 sfl: add version 1.4.0
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#23588 abseil: add version 20240116.2
  recipes/abseil/all/conandata.yml
  recipes/abseil/config.yml
Labels: Bump version

#23600 [sail] Bump version to 0.9.4
  recipes/sail/all/conandata.yml
  recipes/sail/config.yml
Labels: Bump version

#23637 wayland: fix conflict with xkbcommon
  recipes/wayland/all/conanfile.py
Labels: Bump dependencies

#23605 proxy: add version 2.3.1
  recipes/proxy/all/conandata.yml
  recipes/proxy/config.yml
Labels: Bump version

#23604 asio: add version 1.30.2
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#23610 aaf: use expat version range
  recipes/aaf/all/conanfile.py
Labels: Bump dependencies

#23608 exiv2: use expat version range
  recipes/exiv2/all/conanfile.py
Labels: Bump dependencies

#23609 jsbsim: use expat version range
  recipes/jsbsim/all/conanfile.py
Labels: Bump dependencies

#23611 apr-util: use expat version range
  recipes/apr-util/all/conanfile.py
Labels: Bump dependencies

#23613 libmetalink: use version range for expat & libxml2
  recipes/libmetalink/all/conanfile.py
Labels: Bump dependencies

#23617 xlsxio: use version range for expat
  recipes/xlsxio/all/conanfile.py
Labels: Bump dependencies

#23623 libarchive: use version range for libxml2
  recipes/libarchive/all/conanfile.py
Labels: Bump dependencies

#23627 hwloc: use version range for libxml2
  recipes/hwloc/all/conanfile.py
Labels: Bump dependencies

#23628 norm: use version range for libxml2
  recipes/norm/all/conanfile.py
Labels: Bump dependencies

#23636 xkbcommon: fix conflict with wayland
  recipes/xkbcommon/all/conanfile.py
Labels: Bump dependencies

#23615 openfx: use version range for expat
  recipes/openfx/all/conanfile.py
Labels: Bump dependencies

#23616 readosm: use version range for expat
  recipes/readosm/all/conanfile.py
Labels: Bump dependencies

#23618 libstudxml: use version range for expat
  recipes/libstudxml/1.1.x/conanfile.py
Labels: Bump dependencies

#23633 libxslt: bump libxml2 to v2.12.6
  recipes/libxslt/all/conanfile.py
Labels: Bump dependencies

#23025 libliftoff: Update deps
  recipes/libliftoff/all/conanfile.py
  recipes/libliftoff/all/test_package/conanfile.py
Labels: Bump dependencies

#23674 etl: add version 20.38.11
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#23675 iguana: add version 1.0.4
  recipes/iguana/all/conandata.yml
  recipes/iguana/config.yml
Labels: Bump version

#23681 octo-logger-cpp: add version 1.9.0
  recipes/octo-logger-cpp/all/conandata.yml
  recipes/octo-logger-cpp/config.yml
Labels: Bump version

#23682 rocksdb: add version 9.1.0
  recipes/rocksdb/all/conandata.yml
  recipes/rocksdb/config.yml
Labels: Bump version

#22378 capnproto: add version 1.0.2
  recipes/capnproto/all/conandata.yml
  recipes/capnproto/config.yml
Labels: Bump version

#23703 nng: add version 1.8.0
  recipes/nng/all/conandata.yml
  recipes/nng/config.yml
Labels: Bump version

#23707 glaze: add version 2.5.4
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23708 jsoncons: add version 0.174.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#23603 Add expat and libxml2 to list of allowed version ranges
  docs/adding_packages/dependencies.md
Labels: Docs

#23719 libenvpp: add version 1.4.1
  recipes/libenvpp/all/conandata.yml
  recipes/libenvpp/config.yml
Labels: Bump version

#23727 type_safe: add version 0.2.4
  recipes/type_safe/all/conandata.yml
  recipes/type_safe/config.yml
Labels: Bump version

#23792 fix abuse of Conan attributes in fftw
  recipes/fftw/all/conanfile.py
Labels: look into

#23759 c4core: add version 0.2.0
  recipes/c4core/all/conandata.yml
  recipes/c4core/config.yml
Labels: Bump version

#23597 qarchive: use maintained version of libarchive
  recipes/qarchive/all/conanfile.py
Labels: Bump dependencies

#23770 proxy: add version 2.3.2
  recipes/proxy/all/conandata.yml
  recipes/proxy/config.yml
Labels: Bump version

#23771 opentelemetry-proto: add version 1.3.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#23772 pciutils: add version 3.12.0
  recipes/pciutils/all/conandata.yml
  recipes/pciutils/config.yml
Labels: Bump version

#23773 qcbor: add version 1.3
  recipes/qcbor/all/conandata.yml
  recipes/qcbor/config.yml
Labels: Bump version

#23774 libvpx: addversion 1.14.0
  recipes/libvpx/all/conandata.yml
  recipes/libvpx/config.yml
Labels: Bump version

#23778 tree-sitter: add version 0.22.5
  recipes/tree-sitter/all/conandata.yml
  recipes/tree-sitter/config.yml
Labels: Bump version

#23793 libunwind: add version 1.8.1
  recipes/libunwind/all/conandata.yml
  recipes/libunwind/config.yml
Labels: Bump version

#23820 glaze: add version 2.6.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23807 mbedtls: Add 2.28.8
  recipes/mbedtls/all/conandata.yml
  recipes/mbedtls/config.yml
Labels: Bump version
