Repository conan-io/conan-center-index, pull requests merged in 2024-05, with the labels that each got.

#23839 behaviortree.cpp: add version 4.6.0
  recipes/behaviortree.cpp/all/conandata.yml
  recipes/behaviortree.cpp/config.yml
Labels: Bump version

#23841 Upgrading DataFrame to version 3.1.0
  recipes/dataframe/all/conandata.yml
  recipes/dataframe/config.yml
Labels: Bump version

#23506 pango: fix conflicts with cairo, bump deps
  recipes/pango/all/conanfile.py
Labels: Bump dependencies

#23842 spdlog: add version 1.14.1
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#23849 simde: add version 0.8.2
  recipes/simde/all/conandata.yml
  recipes/simde/config.yml
Labels: Bump version

#23858 simfil: Add version 0.1.3
  recipes/simfil/all/conandata.yml
  recipes/simfil/config.yml
Labels: Bump version

#23860 jsoncons: add version 0.175.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#23868 cli11: add version 2.4.2
  recipes/cli11/all/conandata.yml
  recipes/cli11/config.yml
Labels: Bump version

#23874 daw_header_libraries: add version 2.106.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#23878 catch2: add version 3.6.0
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#23621 opencolorio: use version range for expat, bump openexr
  recipes/opencolorio/all/conanfile.py
Labels: Bump dependencies

#23672 tixi3: use version range for libxml2
  recipes/tixi3/all/conandata.yml
  recipes/tixi3/all/conanfile.py
  recipes/tixi3/all/patches/0001-missing-stdlib-include.patch
Labels: blocked

#23838 eudev: Bump libxslt to avoid conflicts
  recipes/eudev/all/conanfile.py
Labels: Bump dependencies

#23843 sdl: add version 2.30.3
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#23886 glaze: add version 2.6.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23912 librdkafka: add version 2.4.0
  recipes/librdkafka/all/conandata.yml
  recipes/librdkafka/config.yml
Labels: Bump version

#23900 sbepp: add version 1.3.0
  recipes/sbepp/all/conandata.yml
  recipes/sbepp/config.yml
Labels: Bump version

#23914 mongo-c-driver: add version 1.27.1
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#22613 s2n: add version 1.4.13
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#23918 libcurl: use version range for c-ares
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#23915 simdjson: add version 3.9.2
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#23928 libjpeg-turbo: add version 3.0.3
  recipes/libjpeg-turbo/all/conandata.yml
  recipes/libjpeg-turbo/config.yml
Labels: Bump version

#23228 libdeflate: add version 1.20
  recipes/libdeflate/all/conandata.yml
  recipes/libdeflate/config.yml
Labels: Bump version

#23932 arrow: add version 16.0.0
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#23919 Add new lmdb version, fix 0.9.31 checksum
  recipes/lmdb/all/conandata.yml
  recipes/lmdb/config.yml
Labels: Bump version

#23938 proxy: add version 2.4.0
  recipes/proxy/all/conandata.yml
  recipes/proxy/config.yml
Labels: Bump version

#23890 gegles-spdlog_setup: bump 3p to `spdlog/1.14.1`
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#23956 luau: add version 0.625
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#23958 perfetto: add version 45.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#23959 ninja: add version 1.12.1
  recipes/ninja/all/conandata.yml
  recipes/ninja/config.yml
Labels: Bump version

#23962 hwdata: add version 0.382
  recipes/hwdata/all/conandata.yml
  recipes/hwdata/config.yml
Labels: Bump version

#23980 glaze: add version 2.6.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#23982 roaring: add version 4.0.0
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#23990 [soplex] bump version to 7.0.1
  recipes/soplex/all/conandata.yml
  recipes/soplex/config.yml
Labels: Bump version

#23993 [yoga] bump version to 3.0.4
  recipes/yoga/all/conandata.yml
  recipes/yoga/config.yml
Labels: Bump version

#23995 libqasm: add version 0.6.6
  recipes/libqasm/all/conandata.yml
  recipes/libqasm/config.yml
Labels: Bump version

#24012 mp-units 2.1.1 added
  recipes/mp-units/2.0.0/conandata.yml
  recipes/mp-units/config.yml
Labels: Bump version

#24015 ctre: add version 3.9.0
  recipes/ctre/all/conandata.yml
  recipes/ctre/config.yml
Labels: Bump version

#24017 etl: add version 20.38.15
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#24022 glaze: add version 2.6.4
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24025 quill: add version 3.9.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#24026 simdutf: add version 5.2.8
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#24030 scnlib: add version 2.0.3
  recipes/scnlib/all/conandata.yml
  recipes/scnlib/config.yml
Labels: Bump version

#24064 [config] Update Conan versions 2.3.1 and 1.64.1
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#24063 flatbush: add release v1.2.1
  recipes/flatbush/all/conandata.yml
  recipes/flatbush/config.yml
Labels: Bump version

#24076 glaze: add version 2.6.6
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24077 snappy: add version 1.2.1
  recipes/snappy/all/conandata.yml
  recipes/snappy/config.yml
Labels: Bump version

#24091 onnx: add version 1.16.1
  recipes/onnx/all/conandata.yml
  recipes/onnx/config.yml
Labels: Bump version

#24066 [docs] Add changelog 2024-05-22
  docs/changelog.md
Labels: Docs

#24109 thorvg: add version 0.13.5
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24114 Add cppcheck 2.14.1
  recipes/cppcheck/all/conandata.yml
  recipes/cppcheck/config.yml
Labels: Bump version

#24108 sqlcipher: add version 4.6.0
  recipes/sqlcipher/all/conandata.yml
  recipes/sqlcipher/config.yml
Labels: Bump version

#24117 vincentlaucsb-csv-parser: add version 2.2.3
  recipes/vincentlaucsb-csv-parser/all/conandata.yml
  recipes/vincentlaucsb-csv-parser/config.yml
Labels: Bump version

#24105 dfp: add version 1.0.3
  recipes/dfp/all/conandata.yml
  recipes/dfp/config.yml
Labels: Bump version

#24120 watcher: add version 0.10.1
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#24126 [whisper-cpp] Bump version 1.6.2
  recipes/whisper-cpp/all/conandata.yml
  recipes/whisper-cpp/config.yml
Labels: Bump version

#24132 [symengine] Add version 0.12.0.
  recipes/symengine/all/conandata.yml
  recipes/symengine/config.yml
Labels: Bump version

#22584 xtr: bump to 2.1.1
  recipes/xtr/all/conandata.yml
  recipes/xtr/config.yml
Labels: Bump version

#24152 arcus: update protobuf to 3.21.12
  recipes/arcus/all/conanfile.py
Labels: Bump dependencies

#24167 Add perseo as part of the review team
  .c3i/reviewers.yml
Labels: C3I config

#24165 remove myself from the repository
  .c3i/authorized_users.yml
  .c3i/reviewers.yml
  docs/community_resources.md
Labels: User-approval pending

#24060 elfutils: Bump gettext to version 0.22.5 to support GCC 14
  recipes/elfutils/all/conanfile.py
Labels: Bump dependencies

#24174 meson: add version 1.4.1
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#24175 ada: add version 2.8.0
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#24057 add extra-cmake-modules 6.2.0
  recipes/extra-cmake-modules/all/conandata.yml
  recipes/extra-cmake-modules/config.yml
Labels: Bump version
