Repository conan-io/conan-center-index, pull requests merged in 2024-08, with the labels that each got.

#24783 mongo-c-driver: add version 1.27.4
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#24761 foxglove-websocket: Add version 1.3.0
  recipes/foxglove-websocket/all/conandata.yml
  recipes/foxglove-websocket/config.yml
Labels: Bump version

#24779 libdivide: add version 5.1
  recipes/libdivide/all/conandata.yml
  recipes/libdivide/config.yml
Labels: Bump version

#24786 glaze: add version 3.1.9
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24792 libpqxx: add version 7.9.2
  recipes/libpqxx/all/conandata.yml
  recipes/libpqxx/config.yml
Labels: Bump version

#24816 libcoro: add version 0.12.1
  recipes/libcoro/all/conandata.yml
  recipes/libcoro/config.yml
Labels: Bump version

#24820 sfl: add version 1.8.0
  recipes/sfl/all/conandata.yml
  recipes/sfl/config.yml
Labels: Bump version

#24821 daw_header_libraries: add version 2.106.2
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#21956 libxshmfence: add v1.3.2
  recipes/libxshmfence/all/conandata.yml
  recipes/libxshmfence/config.yml
Labels: Bump version

#24791 simdjson: add version 3.10.0
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#24822 libdeflate: add version 1.21
  recipes/libdeflate/all/conandata.yml
  recipes/libdeflate/config.yml
Labels: Bump version

#24833 [aws refactor] aws-c-common: Add 0.6.11 version
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#24838 stringzilla: add version 3.9.0
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#24790 Fix copy/paste mistake in linter-yaml.yml for 'Run linter (config.yml)'
  .github/workflows/linter-yaml.yml
Labels: User-approval pending

#24850 simdutf: add version 5.3.2
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#24855 uwebsockets: add version 20.65.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#24873 perfetto: add version 47.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#24881 thorvg: add version 0.14.5
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24888 s2n: add version 1.5.0, fix url of 1.4.16
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#24898 [fixes #24897] fix bad sha256 for dataframe/3.2.0
  recipes/dataframe/all/conandata.yml
Labels: checksum_mismatch

#24887 quill: add version 6.1.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#24891 daw_header_libraries: add version 2.107.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#24900 [docs] Keep only patch version compatible for zstd
  docs/adding_packages/dependencies.md
Labels: Docs

#24892 cpp-channel: add version 0.8.3
  recipes/cpp-channel/all/conandata.yml
  recipes/cpp-channel/config.yml
Labels: Bump version

#24896 simdutf: add version 5.3.5
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#24904 functionplus: add version 0.2.25
  recipes/functionalplus/all/conandata.yml
  recipes/functionalplus/config.yml
Labels: Bump version

#24863 asio: add version 1.31.0
  recipes/asio/all/conandata.yml
  recipes/asio/config.yml
Labels: Bump version

#24906 samurai: add version 0.16.0
  recipes/samurai/all/conandata.yml
  recipes/samurai/config.yml
Labels: Bump version

#24912 hwdata: add version 0.385
  recipes/hwdata/all/conandata.yml
  recipes/hwdata/config.yml
Labels: Bump version

#24925 sqlite3: add version 3.46.1
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#24926 pybind11: add version 2.13.2
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#24869 opentelemetry-cpp: Bump boost to fix old opentelemetry-cpp versions
  recipes/opentelemetry-cpp/all/conanfile.py
Labels: Bump dependencies

#24458 Set boost required version to 1.85.0 to be inline with thrift/0.17.0 …
  recipes/arrow/all/conanfile.py
Labels: Bump dependencies

#24931 fast-dds: add version 2.14.3
  recipes/fast-dds/all/conandata.yml
  recipes/fast-dds/config.yml
Labels: Bump version

#24938 libsystemd: add v255.10
  recipes/libsystemd/all/conandata.yml
  recipes/libsystemd/config.yml
Labels: Bump version

#24941 fast-cdr: add version 2.2.3
  recipes/fast-cdr/all/conandata.yml
  recipes/fast-cdr/config.yml
Labels: Bump version

#24942 catch2: add version 3.7.0
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#24945 simdutf: add version 5.3.7
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#24947 mini: add version 0.9.16
  recipes/mini/all/conandata.yml
  recipes/mini/config.yml
Labels: Bump version

#24956 pybind11: add version 2.13.4
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#24839 glaze: add new version 3.3.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#24957 dice-template-library: add version 1.8.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#24972 jsoncons: add version 0.177.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#24973 sqlitecpp: add version 3.3.2
  recipes/sqlitecpp/all/conandata.yml
  recipes/sqlitecpp/config.yml
Labels: Bump version

#24975 libheif: add version 0.18.2
  recipes/libheif/all/conandata.yml
  recipes/libheif/config.yml
Labels: Bump version

#24980 thorvg: add version 0.14.6
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24611 directx-headers: Add version 1.614.0
  recipes/directx-headers/all/conandata.yml
  recipes/directx-headers/config.yml
Labels: Bump version

#25023 assimp: add v5.4.2
  recipes/assimp/5.x/conandata.yml
  recipes/assimp/config.yml
Labels: Bump version

#25019 itlib: add version 1.11.2
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#25043 mgclient: add version 1.4.3
  recipes/mgclient/all/conandata.yml
  recipes/mgclient/config.yml
Labels: Bump version

#25036 nghttp3: add version 1.5.0
  recipes/nghttp3/all/conandata.yml
  recipes/nghttp3/config.yml
Labels: Bump version

#25010 simdutf: add version 5.4.15
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#25033 luau: add version 0.640
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#25034 pybind11: add version 2.13.5
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#25047 openmesh: add v11.0
  recipes/openmesh/all/conandata.yml
  recipes/openmesh/config.yml
Labels: Bump version

#25006 stringzilla: add version 3.9.3
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#25042 ada: add version 2.9.1
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#25052 dice-template-library: add version 1.9.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#25066 valijson: add version 1.0.3
  recipes/valijson/all/conandata.yml
  recipes/valijson/config.yml
Labels: Bump version
