Repository conan-io/conan-center-index, pull requests merged in 2024-10, with the labels that each got.

#25465 lielab: add version 0.4.1
  recipes/lielab/all/conandata.yml
  recipes/lielab/config.yml
Labels: Bump version

#25477 cnats: add version 3.8.3
  recipes/cnats/all/conandata.yml
  recipes/cnats/config.yml
Labels: Bump version

#25489 cpython: add v3.12.7
  recipes/cpython/all/conandata.yml
  recipes/cpython/config.yml
Labels: Bump version

#25490 [sentry-native] Add version 0.7.10
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#24934 xtensor: bump xsimd
  recipes/xtensor/all/conanfile.py
Labels: Bump dependencies

#24936 samurai: bump xsimd
  recipes/samurai/all/conanfile.py
Labels: Bump dependencies

#25476 sail: Add 0.9.6
  recipes/sail/all/conandata.yml
  recipes/sail/config.yml
Labels: Bump version

#25496 cnats: add version 3.9.1
  recipes/cnats/all/conandata.yml
  recipes/cnats/config.yml
Labels: Bump version

#25525 nghttp3: add version 1.6.0
  recipes/nghttp3/all/conandata.yml
  recipes/nghttp3/config.yml
Labels: Bump version

#25529 libdeflate: add version 1.22
  recipes/libdeflate/all/conandata.yml
  recipes/libdeflate/config.yml
Labels: Bump version

#25537 fakeit: add version 2.4.1
  recipes/fakeit/all/conandata.yml
  recipes/fakeit/config.yml
Labels: Bump version

#25538 xbyak: add version 7.08
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#25534 cpptrace: Add v0.7.2
  recipes/cpptrace/all/conandata.yml
  recipes/cpptrace/config.yml
Labels: Bump version

#25560 watcher: add version 0.12.0
  recipes/watcher/all/conandata.yml
  recipes/watcher/config.yml
Labels: Bump version

#25573 openexr: Add version 3.3.1
  recipes/openexr/3.x/conandata.yml
  recipes/openexr/config.yml
Labels: Bump version

#25571 plutovg: add version 0.0.7
  recipes/plutovg/all/conandata.yml
  recipes/plutovg/config.yml
Labels: Bump version

#25572 safe: add version 2.0.0
  recipes/safe/all/conandata.yml
  recipes/safe/config.yml
Labels: Bump version

#25586 zpp_bits: add version 4.4.24
  recipes/zpp_bits/all/conandata.yml
  recipes/zpp_bits/config.yml
Labels: Bump version

#25595 libuv: add version 1.49.1
  recipes/libuv/all/conandata.yml
  recipes/libuv/config.yml
Labels: Bump version

#25610 xbyak: add version 7.10
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#25612 librdkafka: add version 2.6.0
  recipes/librdkafka/all/conandata.yml
  recipes/librdkafka/config.yml
Labels: Bump version

#25524 c-blosc2: bump zlib-ng
  recipes/c-blosc2/all/conanfile.py
Labels: Bump dependencies

#25523 gdcm: bump zlib-ng
  recipes/gdcm/all/conanfile.py
Labels: Bump dependencies

#25183 rocksdb: add version 9.7.2
  recipes/rocksdb/all/conandata.yml
  recipes/rocksdb/config.yml
Labels: Bump version

#25621 duckdb: add version 1.1.2
  recipes/duckdb/all/conandata.yml
  recipes/duckdb/config.yml
Labels: Bump version

#25624 commata: add version 1.0.1
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#25627 xbyak: add version 7.20
  recipes/xbyak/all/conandata.yml
  recipes/xbyak/config.yml
Labels: Bump version

#25629 roaring: add version 4.2.1
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#25632 stringzilla: add version 3.10.3
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#25643 Deprecate legacy yaml linter
  .github/workflows/linter-yaml.yml
Labels: GitHub config

#25645 plutovg: add version 0.0.8
  recipes/plutovg/all/conandata.yml
  recipes/plutovg/config.yml
Labels: Bump version

#25657 simdjson: add version 3.10.1
  recipes/simdjson/all/conandata.yml
  recipes/simdjson/config.yml
Labels: Bump version

#25659 update emio to 0.8.0
  recipes/emio/all/conandata.yml
  recipes/emio/config.yml
Labels: Bump version

#25670 libgit2: add version 1.8.2
  recipes/libgit2/all/conandata.yml
  recipes/libgit2/config.yml
Labels: Bump version

#25667 [bump] add rotor v0.31
  recipes/rotor/all/conandata.yml
  recipes/rotor/config.yml
Labels: Bump version

#25674 meson: add version 1.6.0
  recipes/meson/all/conandata.yml
  recipes/meson/config.yml
Labels: Bump version

#25675 date: add version 3.0.3
  recipes/date/all/conandata.yml
  recipes/date/config.yml
Labels: Bump version

#25676 rocksdb: add version 9.7.3
  recipes/rocksdb/all/conandata.yml
  recipes/rocksdb/config.yml
Labels: Bump version

#25679 uwebsockets: add version 20.68.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#25684 Botan: add version 3.6.0
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#25686 Botan: add version 2.19.5
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#25697 foxglove-websocket: add version 1.3.1
  recipes/foxglove-websocket/all/conandata.yml
  recipes/foxglove-websocket/config.yml
Labels: Bump version

#25689 sqlite3: add version 3.47.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#25701 Update to SQLite3 Multiple Ciphers 1.9.0
  recipes/sqlite3mc/all/conandata.yml
  recipes/sqlite3mc/config.yml
Labels: Bump version

#25710 Add `.conanrunner` & `.conanrc` to gitignored ignored, alongside `conan_home`
  .gitignore
Labels: GitHub config

#25731 entt: add version 3.14.0
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#25732 libgit2: add version 1.8.3
  recipes/libgit2/all/conandata.yml
  recipes/libgit2/config.yml
Labels: Bump version

#25724 quill: add version 7.4.0
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#25725 rapidfuzz: add version 3.1.1
  recipes/rapidfuzz/all/conandata.yml
  recipes/rapidfuzz/config.yml
Labels: Bump version

#25733 trantor: add version 1.5.22
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#25722 daw_header_libraries: add version 2.114.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#25736 vulkan-headers: Add version 1.3.296.0
  recipes/vulkan-headers/all/conandata.yml
  recipes/vulkan-headers/config.yml
Labels: Bump version

#25749 [sentry-native] Add version 0.7.11
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#25751 add cgal/6.0.1, cgal/5.6.2, and cgal/5.5.5
  recipes/cgal/all/conandata.yml
  recipes/cgal/config.yml
Labels: Bump version

#25321 libsodium: add version 1.0.20
  recipes/libsodium/all/conandata.yml
  recipes/libsodium/config.yml
Labels: Bump version

#25752 Add src folder to .gitignore
  .gitignore
Labels: GitHub config

#25768 Revert "Add src folder to .gitignore"
  .gitignore
Labels: GitHub config

#25769 GENie: add version 1181
  recipes/genie/all/conandata.yml
  recipes/genie/config.yml
Labels: Bump version

#25767 zserio: Add new Zserio release 2.15.0
  recipes/zserio/all/conandata.yml
  recipes/zserio/config.yml
Labels: Bump version

#25774 jsoncons: add version 0.178.0
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#25773 Botan: add version 3.6.1
  recipes/botan/all/conandata.yml
  recipes/botan/config.yml
Labels: Bump version

#25777 [maintenance] Dummy change for hello-conan recipe
  recipes/hello-conan/all/conanfile.py
Labels: Failed
