Repository conan-io/conan-center-index, pull requests merged in 2024-09, with the labels that each got.

#25008 rocksdb: Add version 9.5.2
  recipes/rocksdb/all/conandata.yml
  recipes/rocksdb/config.yml
Labels: Bump version

#25080 simfil: Bump 0.3.2
  recipes/simfil/all/conandata.yml
  recipes/simfil/config.yml
Labels: Bump version

#25100 etl: add version 20.39.4
  recipes/etl/all/conandata.yml
  recipes/etl/config.yml
Labels: Bump version

#25108 popt: Updated libiconv dependency to version 1.17
  recipes/popt/1.19/conanfile.py
Labels: Bump dependencies

#25101 cpp-httplib: add version 0.17.1
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#25103 wiringpi: add version 3.8
  recipes/wiringpi/all/conandata.yml
  recipes/wiringpi/config.yml
Labels: Bump version

#25113 fast_float: add version 6.1.5
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#25116 ada: add version 2.9.2
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#25117 librdkafka: add version 2.5.3
  recipes/librdkafka/all/conandata.yml
  recipes/librdkafka/config.yml
Labels: Bump version

#25118 itlib: add version 1.11.3
  recipes/itlib/all/conandata.yml
  recipes/itlib/config.yml
Labels: Bump version

#25127 glaze: add version 3.3.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#25138 [frozen] add 1.2.0
  recipes/frozen/all/conandata.yml
  recipes/frozen/config.yml
Labels: Bump version

#25124 mongo-c-driver: add version 1.27.6
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#25128 cpp-peglib: add version 1.9.0
  recipes/cpp-peglib/1.x.x/conandata.yml
  recipes/cpp-peglib/config.yml
Labels: Bump version

#25129 intx: add version 0.12.0
  recipes/intx/all/conandata.yml
  recipes/intx/config.yml
Labels: Bump version

#25130 roaring: add version 4.1.2
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#25154 c-ares: add version 1.33.1
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#25163 hwloc: add v2.11.1
  recipes/hwloc/all/conandata.yml
  recipes/hwloc/config.yml
Labels: Bump version

#25167 gobject-introspection: add v2.78.1
  recipes/gobject-introspection/all/conandata.yml
  recipes/gobject-introspection/config.yml
Labels: Bump version

#25142 [expxat] Add expat version 2.6.3
  recipes/expat/all/conandata.yml
  recipes/expat/config.yml
Labels: Bump version

#25146 simdutf: add version 5.5.0
  recipes/simdutf/all/conandata.yml
  recipes/simdutf/config.yml
Labels: Bump version

#25149 plutovg: add version 0.0.4
  recipes/plutovg/all/conandata.yml
  recipes/plutovg/config.yml
Labels: Bump version

#25174 s2n: add version 1.5.2
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#25160 cpp-httplib: add version 0.17.3
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#25088 libcap/2.70: Bump version
  recipes/libcap/all/conandata.yml
  recipes/libcap/config.yml
Labels: Bump version

#25192 glaze: add version 3.3.4
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#25200 Add gc/8.2.8 recipe
  recipes/bdwgc/all/conandata.yml
  recipes/bdwgc/config.yml
Labels: Bump version

#25205 wxwidgets: add version 3.2.6
  recipes/wxwidgets/all/conandata.yml
  recipes/wxwidgets/config.yml
Labels: Bump version

#25227 [config] Update Conan client version to 2.7.1 and 1.65.0
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#25218 docs: use version range for meson & pkgconf in package templates
  docs/package_templates/autotools_package/all/conanfile.py
  docs/package_templates/meson_package/all/conanfile.py
  docs/package_templates/meson_package/all/test_package/conanfile.py
Labels: Docs

#25194 imath: Add version 3.1.12
  recipes/imath/all/conandata.yml
  recipes/imath/config.yml
Labels: Bump version

#25199 wiringpi: add version 3.10
  recipes/wiringpi/all/conandata.yml
  recipes/wiringpi/config.yml
Labels: Bump version

#25222 aravis: add version 0.8.33
  recipes/aravis/all/conandata.yml
  recipes/aravis/config.yml
Labels: Bump version

#25207 cnats: add version 3.8.2
  recipes/cnats/all/conandata.yml
  recipes/cnats/config.yml
Labels: Bump version

#25240 [docs] Add changelog entry for update done on 12-SEP-2024
  docs/changelog.md
Labels: Docs

#25204 trantor: add version 1.5.21
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#25238 uwebsockets: add version 20.66.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#25249 cpp-httplib: add version 0.18.0
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version

#25265 pybind11: add version 2.13.6
  recipes/pybind11/all/conandata.yml
  recipes/pybind11/config.yml
Labels: Bump version

#25268 debug-assert: add version 1.3.4
  recipes/debug_assert/all/conandata.yml
  recipes/debug_assert/config.yml
Labels: Bump version

#25271 stringzilla: add version 3.9.6
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#25278 [soplex] update to version 7.1.1
  recipes/soplex/all/conandata.yml
  recipes/soplex/config.yml
Labels: Bump version

#25277 md4qt: add version 3.0.0
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#25289 glaze: add version 3.4.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#25318 libjpeg-turbo: add version 3.0.4
  recipes/libjpeg-turbo/all/conandata.yml
  recipes/libjpeg-turbo/config.yml
Labels: Bump version

#25323 [linter] Simplify Conan V2 migration linter
  .github/workflows/linter-conan-v2.yml
  docs/linters.md
  docs/v2_migration.md
  linter/check_import_conanfile.py
  linter/check_import_errors.py
  linter/check_package_name.py
  linter/conanv2_transition.py
Labels: Docs, GitHub config

#25314 [libtiff/4.7.0] Add version 4.7.0 to libtiff
  recipes/libtiff/all/conandata.yml
  recipes/libtiff/config.yml
Labels: Bump version

#25329 Remove Linter v2 migration
  .github/workflows/linter-conan-v2.yml
  docs/linters.md
  docs/v2_migration.md
  linter/check_import_tools.py
  linter/check_layout_src_folder.py
  linter/check_package_name.py
  linter/check_version_attribute.py
  linter/conanv2_transition.py
Labels: Docs, GitHub config

#25312 libraw: Version bump to 0.21.3
  recipes/libraw/all/conandata.yml
  recipes/libraw/config.yml
Labels: Bump version

#25315 mongo-c-driver: add version 1.28.0
  recipes/mongo-c-driver/all/conandata.yml
  recipes/mongo-c-driver/config.yml
Labels: Bump version

#25330 vir-simd: add versions 0.3.0, 0.3.1
  recipes/vir-simd/all/conandata.yml
  recipes/vir-simd/config.yml
Labels: Bump version

#25346 [parallel-hashmap] Bump version to 1.4.0
  recipes/parallel-hashmap/all/conandata.yml
  recipes/parallel-hashmap/config.yml
Labels: Bump version

#25347 [greg7mdp-gtl] Bump version to 1.2.0
  recipes/greg7mdp-gtl/all/conandata.yml
  recipes/greg7mdp-gtl/config.yml
Labels: Bump version

#25326 roaring: add version 4.1.7
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#25351 plutovg: add version 0.0.5
  recipes/plutovg/all/conandata.yml
  recipes/plutovg/config.yml
Labels: Bump version

#25359 sbepp: add version 1.4.1
  recipes/sbepp/all/conandata.yml
  recipes/sbepp/config.yml
Labels: Bump version

#25349 s2n: add version 1.5.3
  recipes/s2n/all/conandata.yml
  recipes/s2n/config.yml
Labels: Bump version

#25341 mbedtls: Add 2.28.9
  recipes/mbedtls/all/conandata.yml
  recipes/mbedtls/config.yml
Labels: Bump version

#25398 docs: fix version range of pkgconf in autotools package template
  docs/package_templates/autotools_package/all/conanfile.py
Labels: Docs

#25411 libmagic: use version ranges
  recipes/libmagic/all/conanfile.py
Labels: Bump dependencies

#25413 tixi3: Bump lixslt for libxml2 support
  recipes/tixi3/all/conanfile.py
Labels: Bump dependencies

#25414 eudev: Bump lixslt for libxml2 support
  recipes/eudev/all/conanfile.py
Labels: Bump dependencies

#25415 xmlsec: Avoid conflicts with the rest of libxslt
  recipes/xmlsec/all/conanfile.py
Labels: Bump dependencies

#21238 brunsli: allow shared brotli dependency
  recipes/brunsli/all/conanfile.py
Labels: blocked

#25424 [qwt] Use version range for Qt
  recipes/qwt/all/conanfile.py
Labels: Bump dependencies

#25368 quill: add version 7.2.2
  recipes/quill/all/conandata.yml
  recipes/quill/config.yml
Labels: Bump version

#25416 mcap: add version 1.4.1
  recipes/mcap/all/conandata.yml
  recipes/mcap/config.yml
Labels: Bump version

#25450 luau: add version 0.645
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#25451 thorvg: add version 0.14.10
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#25452 rapidcsv: add version 8.84
  recipes/rapidcsv/all/conandata.yml
  recipes/rapidcsv/config.yml
Labels: Bump version
