Repository conan-io/conan-center-index, pull requests merged in 2024-01, with the labels that each got.

#22086 jsoncons: add version 0.173.2
  recipes/jsoncons/all/conandata.yml
  recipes/jsoncons/config.yml
Labels: Bump version

#22087 proj: add version 9.3.1
  recipes/proj/all/conandata.yml
  recipes/proj/config.yml
Labels: Bump version

#22089 xmlsec: bump deps
  recipes/xmlsec/all/conanfile.py
Labels: Bump dependencies

#22090 tmx: bump deps
  recipes/tmx/all/conanfile.py
Labels: Bump dependencies

#22091 opentdf-client: bump deps
  recipes/opentdf-client/all/conanfile.py
Labels: Bump dependencies

#22092 tixi3: bump deps
  recipes/tixi3/all/conanfile.py
Labels: Bump dependencies

#22093 gperftools: add version 2.14.0
  recipes/gperftools/all/conandata.yml
  recipes/gperftools/config.yml
Labels: Bump version

#22088 libxmlpp: bump deps
  recipes/libxmlpp/all/conanfile.py
Labels: Bump dependencies

#21686 rapidcheck: add version cci.20230815
  recipes/rapidcheck/all/conandata.yml
  recipes/rapidcheck/config.yml
Labels: Bump version

#22111 libenvpp: update fmt/10.2.0
  recipes/libenvpp/all/conanfile.py
Labels: Bump dependencies

#22109 quill: update fmt/10.2.0
  recipes/quill/all/conanfile.py
Labels: Bump dependencies

#22110 jinja2cpp: update fmt/10.2.0
  recipes/jinja2cpp/all/conanfile.py
Labels: Bump dependencies

#22119 mbits-diags: update fmt/10.2.0
  recipes/mbits-diags/all/conanfile.py
Labels: Bump dependencies

#22122 glaze: add version 2.0.0
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22125 fmtlog: update fmt/10.2.0
  recipes/fmtlog/all/conanfile.py
Labels: Bump dependencies

#22065 zug: add v0.1.1, drop custom version
  recipes/zug/all/conandata.yml
  recipes/zug/config.yml
Labels: Bump version

#22128 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22129 cpp-validator: update fmt/10.2.0
  recipes/cpp-validator/all/conanfile.py
Labels: Bump dependencies

#22130 svgwrite: update fmt/10.2.0
  recipes/svgwrite/all/conanfile.py
Labels: Bump dependencies

#22137 glaze: add version 2.0.1
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22141 gegles-spdlog_setup: update fmt/10.2.0
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#22139 sbepp: update dependencies
  recipes/sbepp/all/conanfile.py
Labels: Bump dependencies

#22140 mppp: update fmt/10.2.0
  recipes/mppp/all/conanfile.py
Labels: Bump dependencies

#22143 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22154 roaring: add version 2.1.1
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#22160 glaze: add version 2.0.2
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22161 fmt: add version 10.2.1
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#22163 daw_header_libraries: add version 2.97.0
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#22162 uwebsockets: add version 20.55.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#22168 uwebsockets: update libdeflate/1.19
  recipes/uwebsockets/all/conanfile.py
Labels: Bump dependencies

#22175 luau: add version 0.607
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#22176 kuba-zip: add version 0.3.1
  recipes/kuba-zip/all/conandata.yml
  recipes/kuba-zip/config.yml
Labels: Bump version

#22177 toml11: add version 3.8.0
  recipes/toml11/all/conandata.yml
  recipes/toml11/config.yml
Labels: Bump version

#21679 hwdata: add version 0.377-2
  recipes/hwdata/all/conandata.yml
  recipes/hwdata/config.yml
Labels: Bump version

#22178 mold: add version 2.4.0
  recipes/mold/all/conandata.yml
  recipes/mold/config.yml
Labels: Bump version

#22181 stringzilla: add version 2.0.4
  recipes/stringzilla/all/conandata.yml
  recipes/stringzilla/config.yml
Labels: Bump version

#22182 Bump/cyclonedds/all
  recipes/cyclonedds/all/conanfile.py
Labels: Bump dependencies

#22123 cppcommon: update fmt/10.2.0
  recipes/cppcommon/all/conanfile.py
Labels: Unexpected Error, Bump dependencies

#22223 Add cppstd 23 for gcc
  .c3i/config_v2.yml
Labels: C3I config

#21881 onnxruntime: bump wil
  recipes/onnxruntime/all/conanfile.py
Labels: Bump dependencies

#22211 (#22210) bazel: add version 5.4.1
  recipes/bazel/all/conandata.yml
  recipes/bazel/config.yml
Labels: Bump version

#22226 toml11: add version 3.8.1
  recipes/toml11/all/conandata.yml
  recipes/toml11/config.yml
Labels: Bump version

#22202 at-spi2-core 2.51.0
  recipes/at-spi2-core/config.yml
  recipes/at-spi2-core/new/conandata.yml
Labels: Bump version

#22188 wolfssl: add version 5.6.6
  recipes/wolfssl/all/conandata.yml
  recipes/wolfssl/config.yml
Labels: Bump version

#22192 openblas: add v0.3.26
  recipes/openblas/all/conandata.yml
  recipes/openblas/config.yml
Labels: Bump version

#22194 libsass: add v3.6.6
  recipes/libsass/all/conandata.yml
  recipes/libsass/config.yml
Labels: Bump version

#22239 thrift: bump deps
  recipes/thrift/all/conanfile.py
  recipes/thrift/all/patches/cmake-0.13.0.patch
Labels: Bump dependencies

#22243 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22245 vulkan-validationlayers/all: bump deps
  recipes/vulkan-validationlayers/all/conanfile.py
  recipes/vulkan-validationlayers/all/patches/1.2.182-0001-fix-cmake.patch
  recipes/vulkan-validationlayers/all/patches/1.2.189.2-0001-fix-cmake.patch
  recipes/vulkan-validationlayers/all/patches/1.2.198.0-0001-fix-cmake.patch
Labels: Bump dependencies

#22247 libmaxmind: add version 1.9.1
  recipes/libmaxminddb/all/conandata.yml
  recipes/libmaxminddb/config.yml
Labels: Bump version

#22251 glaze: add version 2.0.5
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22250 base64: add version 0.5.2
  recipes/base64/all/conandata.yml
  recipes/base64/config.yml
Labels: Bump version

#22261 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22254 sfml/all: bump deps
  recipes/sfml/all/conanfile.py
Labels: Bump dependencies

#22264 perfetto: Bump version: 41.0
  recipes/perfetto/all/conandata.yml
  recipes/perfetto/config.yml
Labels: Bump version

#22253 thrift: bump boost
  recipes/thrift/all/conanfile.py
Labels: Bump dependencies

#22268 restinio: bump to `fmt/10.2.0`
  recipes/restinio/v0.7/conanfile.py
Labels: Bump dependencies

#22270 zlig-nb: add version 2.1.6
  recipes/zlib-ng/all/conandata.yml
  recipes/zlib-ng/config.yml
Labels: Bump version

#22186 roaring: add version 2.1.2
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version

#22277 libva/all: bump deps
  recipes/libva/all/conanfile.py
Labels: Bump dependencies

#22280 libvdpau/all: bump deps
  recipes/libvdpau/all/conanfile.py
Labels: Bump dependencies

#22283 opentelemetry-proto: add version 1.1.0
  recipes/opentelemetry-proto/all/conandata.yml
  recipes/opentelemetry-proto/config.yml
Labels: Bump version

#22282 spdlog: add version 1.13.0
  recipes/spdlog/all/conandata.yml
  recipes/spdlog/config.yml
Labels: Bump version

#22248 uwebsockets: add version 20.56.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#22199 redis-plus-plus: add version 1.3.11
  recipes/redis-plus-plus/all/conandata.yml
  recipes/redis-plus-plus/config.yml
Labels: Bump version

#22215 opencl-headers: v2023.12.14
  recipes/opencl-headers/all/conandata.yml
  recipes/opencl-headers/config.yml
Labels: Bump version

#22287 opencl-clhpp-headers: v2023.12.14
  recipes/opencl-clhpp-headers/all/conandata.yml
  recipes/opencl-clhpp-headers/config.yml
Labels: Bump version

#22288 opencl-icd-loader: v2023.12.14
  recipes/opencl-icd-loader/all/conandata.yml
  recipes/opencl-icd-loader/config.yml
Labels: Bump version

#22292 glaze: add version 2.0.6
  recipes/glaze/all/conandata.yml
  recipes/glaze/config.yml
Labels: Bump version

#22296 lely-core: add v2.3.3
  recipes/lely-core/all/conandata.yml
  recipes/lely-core/config.yml
Labels: Bump version

#22298 libnuma: add v2.0.16
  recipes/libnuma/all/conandata.yml
  recipes/libnuma/config.yml
Labels: Bump version

#22304 quill: update fmt/10.2.1
  recipes/quill/all/conanfile.py
Labels: Bump dependencies

#22301 mppp: update fmt/10.2.1
  recipes/mppp/all/conanfile.py
Labels: Bump dependencies

#22305 ecos: add v2.0.10
  recipes/ecos/all/conandata.yml
  recipes/ecos/config.yml
Labels: Bump version

#22310 tgbot: add v1.7.2
  recipes/tgbot/all/conandata.yml
  recipes/tgbot/config.yml
Labels: Bump version

#22317 hdrhistogram-c: add v0.11.8
  recipes/hdrhistogram-c/all/conandata.yml
  recipes/hdrhistogram-c/config.yml
Labels: Bump version

#22321 godot_headers: add v3.5.3
  recipes/godot_headers/all/conandata.yml
  recipes/godot_headers/config.yml
Labels: Bump version

#22328 libbigwig: update zlib-ng/2.1.6
  recipes/libbigwig/all/conanfile.py
Labels: Bump dependencies

#22326 pdf-writer: add version 4.6.3
  recipes/pdf-writer/all/conandata.yml
  recipes/pdf-writer/config.yml
Labels: Bump version

#22225 usockets: add version 0.8.7
  recipes/usockets/all/conandata.yml
  recipes/usockets/config.yml
Labels: Bump version

#22330 daw_header_libraries: add version 2.98.5
  recipes/daw_header_libraries/all/conandata.yml
  recipes/daw_header_libraries/config.yml
Labels: Bump version

#22331 libenvpp: update fmt/10.2.1
  recipes/libenvpp/all/conanfile.py
Labels: Bump dependencies

#22332 mbits-diags: update fmt/10.2.1
  recipes/mbits-diags/all/conanfile.py
Labels: Bump dependencies

#22333 cargs: add version 1.1.0
  recipes/cargs/all/conandata.yml
  recipes/cargs/config.yml
Labels: Bump version

#22327 c-blosc2: update zlib-ng/2.1.6
  recipes/c-blosc2/all/conanfile.py
Labels: Bump dependencies

#22335 fmtlog: update fmtlog/10.2.1
  recipes/fmtlog/all/conanfile.py
Labels: Bump dependencies

#22183 gperftools: add version 2.15
  recipes/gperftools/all/conandata.yml
  recipes/gperftools/config.yml
Labels: Bump version

#22185 nng: add version 1.7.1
  recipes/nng/all/conandata.yml
  recipes/nng/config.yml
Labels: Bump version

#22339 dice-template-library: add version 1.2.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#22344 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22372 bacnet-stack: add v1.3.2
  recipes/bacnet-stack/all/conandata.yml
  recipes/bacnet-stack/config.yml
Labels: Bump version

#22352 xmlsec: update libxslt/1.1.39
  recipes/xmlsec/all/conanfile.py
Labels: Bump dependencies

#22376 sqlite3: add version 3.45.0
  recipes/sqlite3/all/conandata.yml
  recipes/sqlite3/config.yml
Labels: Bump version

#22377 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22285 Bump/pulseaudio/all
  recipes/pulseaudio/all/conanfile.py
Labels: Bump dependencies

#22383 aws-c-common: add version 0.9.12
  recipes/aws-c-common/all/conandata.yml
  recipes/aws-c-common/config.yml
Labels: Bump version

#22386 gegles-spdlog_setup: bump to `spdlog/1.13.0`
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#22385 libxml2: add version 2.12.4
  recipes/libxml2/all/conandata.yml
  recipes/libxml2/config.yml
Labels: Bump version

#22388 nuklear: add version 4.12.0
  recipes/nuklear/all/conandata.yml
  recipes/nuklear/config.yml
Labels: Bump version

#22390 logr: bump deps
  recipes/logr/0.1.0/conanfile.py
Labels: Bump dependencies

#22394 vulkan-loader/all: bump deps
  recipes/vulkan-loader/all/conanfile.py
Labels: Bump dependencies

#22392 Bump/libepoxy/all
  recipes/libepoxy/all/conanfile.py
Labels: Bump dependencies

#22395 Bump/libxft/all
  recipes/libxft/all/conanfile.py
Labels: Bump dependencies

#22397 Bump/glfw/all
  recipes/glfw/all/conanfile.py
Labels: Bump dependencies

#22399 Bump/pdcurses/all
  recipes/pdcurses/all/conanfile.py
Labels: Bump dependencies

#22400 Bump/fltk/all
  recipes/fltk/all/conanfile.py
Labels: Bump dependencies

#22402 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22407 xmlsec: update dependencies
  recipes/xmlsec/all/conanfile.py
Labels: Bump dependencies

#22375 catch2: add version 3.5.2
  recipes/catch2/3.x.x/conandata.yml
  recipes/catch2/config.yml
Labels: Bump version

#22411 qt6: bump deps
  recipes/qt/6.x.x/conanfile.py
Labels: Bump dependencies

#22417 [sentry-native] bump to 0.7.0
  recipes/sentry-native/all/conandata.yml
  recipes/sentry-native/config.yml
Labels: Bump version

#22423 xmlsec: add version 1.3.3
  recipes/xmlsec/all/conandata.yml
  recipes/xmlsec/config.yml
Labels: Bump version

#22424 entt: add version 3.13.0
  recipes/entt/3.x.x/conandata.yml
  recipes/entt/config.yml
Labels: Bump version

#22425 jasper: add version 4.1.2
  recipes/jasper/all/conandata.yml
  recipes/jasper/config.yml
Labels: Bump version

#22429 Update CI Conan 1.x configurations
  .c3i/config_v1.yml
Labels: C3I config

#22438 trantor: add version 1.5.16
  recipes/trantor/all/conandata.yml
  recipes/trantor/config.yml
Labels: Bump version

#22445 libcoro: update c-ares
  recipes/libcoro/all/conanfile.py
Labels: Bump dependencies

#22443 osmanip: update arsenalgear
  recipes/osmanip/all/conanfile.py
Labels: Bump dependencies

#22442 drogon: update dependencies
  recipes/drogon/all/conanfile.py
Labels: Bump dependencies

#22444 libnghttp2: update dependencices
  recipes/libnghttp2/all/conanfile.py
Labels: Bump dependencies

#22452 fakeit: update dependencies
  recipes/fakeit/all/conanfile.py
Labels: Bump dependencies

#22454 serdepp: update dependencies
  recipes/serdepp/all/conanfile.py
Labels: Bump dependencies

#22450 trantor: update dependencies
  recipes/trantor/all/conanfile.py
Labels: Bump dependencies

#22457 cpp-validator: update fmt
  recipes/cpp-validator/all/conanfile.py
Labels: Bump dependencies

#22458 jsonnet: update nlohmann_json
  recipes/jsonnet/all/conanfile.py
Labels: Bump dependencies

#22460 sqlitecpp: update sqlite3/3.45.0
  recipes/sqlitecpp/all/conanfile.py
Labels: Bump dependencies

#22459 poco: update sqlite3/3.45.0
  recipes/poco/all/conanfile.py
Labels: Bump dependencies

#22465 sqlite_orm: update sqlite3/3.45.0
  recipes/sqlite_orm/all/conanfile.py
Labels: Bump dependencies

#22463 dlib: update dependencies
  recipes/dlib/all/conanfile.py
Labels: Bump dependencies

#22474 daw utf range header libraries 2.97.0
  recipes/daw_utf_range/all/conanfile.py
Labels: Bump dependencies

#22475 daw_json_link: update daw_header_libraries/2.97.0
  recipes/daw_json_link/all/conanfile.py
Labels: Bump dependencies

#22476 libnghttp2: add version 1.59.0
  recipes/libnghttp2/all/conandata.yml
  recipes/libnghttp2/config.yml
Labels: Bump version

#22487 libcurl: update dependencies
  recipes/libcurl/all/conanfile.py
Labels: Bump dependencies

#22495 [config] Update conan version to 1.62.0 and 2.0.16
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#22503 ada: add verison 2.7.5
  recipes/ada/all/conandata.yml
  recipes/ada/config.yml
Labels: Bump version

#22509 wil: add version 1.0.240122.1
  recipes/wil/all/conandata.yml
  recipes/wil/config.yml
Labels: Bump version

#20183 gstreamer: Add version 1.22.6
  recipes/gstreamer/all/conandata.yml
  recipes/gstreamer/config.yml
Labels: Bump version

#22498 gegles-spdlog_setup: bump to `fmt/10.2.1`
  recipes/gegles-spdlog_setup/all/conanfile.py
Labels: Bump dependencies

#22499 restinio: bump to `fmt/10.2.1`
  recipes/restinio/v0.7/conanfile.py
Labels: Bump dependencies

#22497 uwebsockets: add version 20.57.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#21747 boost: add version 1.84.0
  recipes/boost/all/conandata.yml
  recipes/boost/all/conanfile.py
  recipes/boost/all/dependencies/dependencies-1.84.0.yml
  recipes/boost/all/rebuild-dependencies.py
  recipes/boost/config.yml
Labels: Unexpected Error, Failed

#22521 [docs] Update changelog 24 January 2024
  docs/changelog.md
Labels: Docs

#22520 md4qt: bump version
  recipes/md4qt/all/conandata.yml
  recipes/md4qt/config.yml
Labels: Bump version

#22528 libdrm: Add version 2.4.120
  recipes/libdrm/all/conandata.yml
  recipes/libdrm/config.yml
Labels: Bump version

#22507 [docs] Update bump PR review rule
  docs/review_process.md
Labels: Docs

#22505 [config] Add reviews required bump entry in config.yml
  .c3i/config_v1.yml
  .c3i/config_v2.yml
Labels: C3I config

#22536 c-blosc2: add version 2.13.0
  recipes/c-blosc2/all/conandata.yml
  recipes/c-blosc2/config.yml
Labels: Bump version

#22496 wayland-protocols: Add version 1.33
  recipes/wayland-protocols/all/conandata.yml
  recipes/wayland-protocols/config.yml
Labels: Bump version

#22576 fast_float: add version 6.1.0
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#22570 cpp-httplib: add version 0.15.1
  recipes/cpp-httplib/all/conandata.yml
  recipes/cpp-httplib/config.yml
Labels: Bump version
