Repository conan-io/conan-center-index, pull requests merged in 2024-07, with the labels that each got.

#24488 nsync: add version 1.29.2
  recipes/nsync/all/conandata.yml
  recipes/nsync/config.yml
Labels: Bump version

#24496 bump highs version 1.7.2
  recipes/highs/all/conandata.yml
  recipes/highs/config.yml
Labels: Bump version

#24502 tinygltf: add version 2.9.0
  recipes/tinygltf/all/conandata.yml
  recipes/tinygltf/config.yml
Labels: Bump version

#24517 lunasvg: add version 2.4.0
  recipes/lunasvg/all/conandata.yml
  recipes/lunasvg/config.yml
Labels: Bump version

#24530 [yoga] bump version to 3.1.0
  recipes/yoga/all/conandata.yml
  recipes/yoga/config.yml
Labels: Bump version

#24531 [soplex] bump version to 7.1.0
  recipes/soplex/all/conandata.yml
  recipes/soplex/config.yml
Labels: Bump version

#24533 thorvg: add new version 0.14.1
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24535 sdl: add version 2.30.5
  recipes/sdl/all/conandata.yml
  recipes/sdl/config.yml
Labels: Bump version

#24537 fmt: add version 11.0.1
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#24539 toml11: add version 4.0.3
  recipes/toml11/all/conandata.yml
  recipes/toml11/config.yml
Labels: Bump version

#24542 uwebsockets: add version 20.64.0
  recipes/uwebsockets/all/conandata.yml
  recipes/uwebsockets/config.yml
Labels: Bump version

#24543 commata: add version 1.0.0
  recipes/commata/all/conandata.yml
  recipes/commata/config.yml
Labels: Bump version

#24557 blend2d: add version 0.11.3
  recipes/blend2d/all/conandata.yml
  recipes/blend2d/config.yml
Labels: Bump version

#24567 libjxl: add version 0.10.3
  recipes/libjxl/all/conandata.yml
  recipes/libjxl/config.yml
Labels: Bump version

#24573 config: Update Conan client version to 2.5.0
  .c3i/config_v2.yml
Labels: C3I config

#24570 meshoptimizer: add version 0.21
  recipes/meshoptimizer/all/conandata.yml
  recipes/meshoptimizer/config.yml
Labels: Bump version

#24572 yyjson: add version 0.10.0
  recipes/yyjson/all/conandata.yml
  recipes/yyjson/config.yml
Labels: Bump version

#24579 sbepp: add version 1.4.0
  recipes/sbepp/all/conandata.yml
  recipes/sbepp/config.yml
Labels: Bump version

#24616 thorvg: add version 0.14.2
  recipes/thorvg/all/conandata.yml
  recipes/thorvg/config.yml
Labels: Bump version

#24596 dav1d: add 1.4.3
  recipes/dav1d/all/conandata.yml
  recipes/dav1d/config.yml
Labels: Bump version

#24613 Upgrading C++ DataFrame to version 3.2.0
  recipes/dataframe/all/conandata.yml
  recipes/dataframe/config.yml
Labels: Bump version

#24614 ouster_sdk: add version 0.12.0
  recipes/ouster_sdk/all/conandata.yml
  recipes/ouster_sdk/config.yml
Labels: Bump version

#24641 Use version range for libpng in sdl_image recipe
  recipes/sdl_image/all/conanfile.py
Labels: Bump dependencies

#24659 gtest: add 1.15.0
  recipes/gtest/all/conandata.yml
  recipes/gtest/config.yml
Labels: Bump version

#24660 c-ares: add version 1.32.2
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#24675 fmt: add version 11.0.2
  recipes/fmt/all/conandata.yml
  recipes/fmt/config.yml
Labels: Bump version

#24643 arrow: add version 17.0.0
  recipes/arrow/all/conandata.yml
  recipes/arrow/config.yml
Labels: Bump version

#24691 fast_float: add version 6.1.3
  recipes/fast_float/all/conandata.yml
  recipes/fast_float/config.yml
Labels: Bump version

#24697 yaml linter: patch description is optional - reduce noise in pull requests
  linter/conandata_yaml_linter.py
Labels: GitHub config

#24540 modern-cpp-kafka: add version 2024.07.03
  recipes/modern-cpp-kafka/all/conandata.yml
  recipes/modern-cpp-kafka/config.yml
Labels: Bump version

#24603 glib: Bump libselinux from 3.5 to 3.6 to avoid conflicts
  recipes/glib/all/conanfile.py
Labels: Bump dependencies

#24673 luau: add version 0.635
  recipes/luau/all/conandata.yml
  recipes/luau/config.yml
Labels: Bump version

#24690 blend2d: add version 0.11.4
  recipes/blend2d/all/conandata.yml
  recipes/blend2d/config.yml
Labels: Bump version

#24699 simfil: Bump 0.3.0
  recipes/simfil/all/conandata.yml
  recipes/simfil/config.yml
Labels: Bump version

#24715 dice-template-library: add version 1.6.0
  recipes/dice-template-library/all/conandata.yml
  recipes/dice-template-library/config.yml
Labels: Bump version

#24741 c-ares: add version 1.32.3
  recipes/c-ares/all/conandata.yml
  recipes/c-ares/config.yml
Labels: Bump version

#24743 octo-logger-cpp: add version 2.0.0
  recipes/octo-logger-cpp/all/conandata.yml
  recipes/octo-logger-cpp/config.yml
Labels: Bump version

#24746 libftp: add version 1.1.0
  recipes/libftp/all/conandata.yml
  recipes/libftp/config.yml
Labels: Bump version

#24723 [docs] Add zstd and ninja to version ranges supported
  docs/adding_packages/dependencies.md
Labels: Docs

#24708 qt: make "conan test" using the console for stdout
  recipes/qt/5.x.x/test_package/CMakeLists.txt
  recipes/qt/5.x.x/test_v1_package/CMakeLists.txt
  recipes/qt/6.x.x/test_package/CMakeLists.txt
Labels: Failed

#24763 [docs] Add xz_utils in version ranges
  docs/adding_packages/dependencies.md
Labels: Docs

#23653 boost: bump deps
  recipes/boost/all/conanfile.py
Labels: Bump dependencies

#24767 roaring: add version 4.1.1
  recipes/roaring/all/conandata.yml
  recipes/roaring/config.yml
Labels: Bump version
