Repository conan-io/conan-center-index, pull requests merged in 2025-01, with the labels that each got.

#25254 libjxl: add version 0.11.1
  recipes/libjxl/all/conandata.yml
  recipes/libjxl/all/conanfile.py
  recipes/libjxl/config.yml
Labels: Failed, Bump version

#25382 innoextract: add package_type, bump deps
  recipes/innoextract/all/conandata.yml
  recipes/innoextract/all/conanfile.py
  recipes/innoextract/all/patches/0003-fix-boost-1_85-usage.patch
  recipes/innoextract/all/test_v1_package/conanfile.py
Labels: Failed

#25850 botan: Fix conanfile.py android misdetection.
  recipes/botan/all/conandata.yml
  recipes/botan/all/conanfile.py
  recipes/botan/all/test_v1_package/CMakeLists.txt
  recipes/botan/all/test_v1_package/conanfile.py
  recipes/botan/all/test_v1_package/test_package.cpp
  recipes/botan/config.yml
Labels: waiting on contributor
