Repository conan-io/conan-center-index, pull requests merged in 2025-03, with the labels that each got.

#25873 sdl3: Add new major version support
  recipes/sdl/3.x/conandata.yml
  recipes/sdl/3.x/conanfile.py
  recipes/sdl/3.x/test_package/CMakeLists.txt
  recipes/sdl/3.x/test_package/conanfile.py
  recipes/sdl/3.x/test_package/test_package.cpp
  recipes/sdl/config.yml
Labels: look into

#24874 New recipe: `imgui-sfml`
  recipes/imgui-sfml/all/conandata.yml
  recipes/imgui-sfml/all/conanfile.py
  recipes/imgui-sfml/all/patches/0001-2.6-fix-imgui-linking.patch
  recipes/imgui-sfml/all/test_package/CMakeLists.txt
  recipes/imgui-sfml/all/test_package/conanfile.py
  recipes/imgui-sfml/all/test_package/test_package.cpp
  recipes/imgui-sfml/config.yml
Labels: Failed

#21456 erikzenker-hsm: add package_type + bump boost
  recipes/erikzenker-hsm/all/conanfile.py
  recipes/erikzenker-hsm/all/test_package/CMakeLists.txt
  recipes/erikzenker-hsm/all/test_package/conanfile.py
  recipes/erikzenker-hsm/all/test_v1_package/CMakeLists.txt
  recipes/erikzenker-hsm/all/test_v1_package/conanfile.py
Labels: Failed

#20836 Bump version for vulkan-validationlayers/1.3.243.0
  recipes/vulkan-validationlayers/all/conandata.yml
  recipes/vulkan-validationlayers/all/conanfile.py
  recipes/vulkan-validationlayers/all/dependencies/dependencies-1.3.243.0.yml
  recipes/vulkan-validationlayers/all/patches/1.3.243.0-0001-fix-cmake.patch
  recipes/vulkan-validationlayers/config.yml
Labels: Failed, stale
